import Foundation

/**
 Тексты сообщений кабинета — этап 45 (владелец 26.09.2026). Русские — дословно со страницы и из js_i18n-cabinet-ru.js
 сайта (chat_*, dm_*, lcm_*, req_*, of_*, sup_*, dreq_*, blk_*), а там, где сайт пишет текст прямо в коде (жалоба,
 блокировка, «Сделка состоялась?», reqTimeAgo), — оттуда. Казахские, английские и арабские — перевод тех же фраз.
 Своих слов немного, и все они — для VoiceOver и пустых мест: «Очистить», «закреплён», «Печатает…», «Видео», «Осталось».
 */
enum ИнбоксText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    private static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    /// Даты «d мес» — на языке текстов.
    static var локаль: Locale {
        switch язык {
        case "kk": return Locale(identifier: "kk_KZ")
        case "en": return Locale(identifier: "en_US")
        case "ar": return Locale(identifier: "ar_EG")
        default: return Locale(identifier: "ru_RU")
        }
    }

    /// reqTimeAgo: «1 день назад», «2 дня назад», «5 дней назад» (до недели).
    static func дней(_ n: Int) -> String {
        switch язык {
        case "kk": return String(n) + " күн бұрын"
        case "en": return n == 1 ? "1 day ago" : String(n) + " days ago"
        case "ar": return "منذ " + String(n) + (n == 1 ? " يوم" : " أيام")
        default:
            if n == 1 { return "1 день назад" }
            if n >= 2 && n <= 4 { return String(n) + " дня назад" }
            return String(n) + " дней назад"
        }
    }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    private static let ru: [String: String] = [
        // Инбокс «Чат»
        "title": "Чат", "nav_chat": "Чат", "sub": "Переписка, аренда и обмен — в одном месте",
        "search_ph": "Поиск: имя, товар, сообщение", "clear": "Очистить", "trash": "Корзина",
        "f_all": "Все", "f_lead": "Покупатели", "f_rental": "Аренда", "f_exchange": "Обмен",
        "retention": "Удалённые переписки хранятся у поддержки 12 месяцев.",
        "request_data": "Запросить данные у поддержки",
        "empty": "Пока нет диалогов.\nКогда покупатель напишет или предложит сделку — появится здесь.",
        "trash_empty": "Корзина пуста",
        "pin": "Закрепить", "unpin": "Открепить", "pinned": "Закреплено ✓", "unpinned": "Откреплено",
        "pin_max": "Можно закрепить максимум 5 чатов", "pinned_a11y": "закреплён",
        "trash_to": "Убрать в корзину", "trash_done": "Убрано в корзину", "restore": "Вернуть",
        "restored": "Возвращено ✓", "purge": "Удалить навсегда",
        "purge_q": "Удалить переписку навсегда? У вас она исчезнет безвозвратно. Для разбора споров данные хранятся у поддержки 12 месяцев.",
        "purge_done": "Удалено навсегда", "more": "Действия",
        "trash_clear": "Очистить корзину", "trash_clear_q": "Удалить навсегда %ld переписок?",
        "trash_cleared": "Корзина очищена", "trash_clear_part": "Удалено %ld из %ld",
        "you": "Вы: ", "user": "Пользователь", "user_deleted": "Удалённый пользователь", "buyer": "Покупатель",
        "rental_req": "Запрос аренды", "exchange_offer": "Предложение обмена",
        "tag_rent": "Аренда", "tag_exch": "Обмен", "tag_lead": "Лид", "tag_buyer": "Покупатель", "tag_buy": "Покупка",
        "lead_ai": "Kliko AI-ассистент отвечает", "lead_hot": "Горячий лид — подключитесь",
        "lead_active": "Вы в диалоге", "lead_closed": "Завершён",
        "it_sold": "Продано", "it_reserved": "В сделке", "it_inactive": "Снято", "it_off": "Не в выдаче",
        "it_gone": "Удалено",
        "lbl_pick": "Метка", "label_title": "Метка диалога", "label_saved": "Метка сохранена ✓",
        "lbl_maybe": "Возможно купит", "lbl_thinking": "Думает", "lbl_bought": "Купил", "lbl_regular": "Постоянный",
        "lbl_declined": "Отказ",
        // Общее
        "err_generic": "Ошибка", "err_no_conn": "Нет соединения", "err_net": "Ошибка сети", "no_conn": "Нет соединения",
        "err_load": "Ошибка загрузки", "loading": "Загрузка…", "cancel": "Отмена", "ok_btn": "Понятно",
        "close": "Закрыть", "fail": "Не удалось", "send_err": "Ошибка отправки",
        "read": "✓✓ Прочитано", "sent": "✓ Отправлено",
        // Чат по лиду
        "lcm_st_ai": "Kliko AI-ассистент ведёт диалог", "lcm_st_hot": "Горячий лид", "lcm_st_active": "Вы в диалоге",
        "lcm_st_closed": "Завершён", "lcm_presence": " · покупатель %@",
        "lcm_offline": "Нет соединения — переподключение…",
        "lcm_join_t": "Подключитесь, чтобы ответить лично", "lcm_join_b": "Подключиться",
        "lcm_joined": "Вы подключились к чату ✓",
        "lcm_deal_live": "Покупатель оформил сделку", "co_goto": "Перейти к сделке",
        "lcm_hot": "Горячий лид — свяжитесь сразу", "call": "Позвонить",
        "vbar_t": "Покупатель хочет купить безопасно", "vbar_d": "Гарант-сделка — только для проверенных продавцов",
        "verify_go": "Пройти верификацию", "listing": "Объявление", "reply_ph": "Ответить…",
        "lcm_no_msgs": "Нет сообщений", "typing": "Печатает…", "who_ai": "Kliko AI-ассистент",
        "via_tg": "из Telegram", "video": "Видео",
        "dm_direct": "Прямой чат", "dm_no_msgs": "Сообщений пока нет.\nНапишите первым",
        "dm_blocked_msg": "Общение недоступно — один из вас заблокировал другого.",
        "dm_tag_exch": "Обмен", "dm_tag_rent": "Аренда", "negotiable": "Договорная", "torg": "Торг",
        "dm_dates": "Даты", "dm_cost": "Стоимость", "dm_deposit": "Залог", "unit_day": "сут", "unit_month": "мес",
        "dm_r_requested": "Ожидает ответа", "dm_r_confirmed": "Подтверждено — товар не передан",
        "dm_r_active": "Активна", "dm_r_returned": "Завершена · залог возвращён",
        "dm_r_cancelled": "Отклонено / отменено", "dm_r_disputed": "Открыт спор",
        "dm_ex_accepted": "Обмен принят", "dm_ex_declined": "Отклонён",
        "dm_they_offer": "Вам предлагают", "dm_for_yours": "За ваш", "dm_sur": "Доплата ",
        "dm_sur_to_you": "Доплата вам ", "dm_sur_asks": "Просит вашу доплату ",
        "dm_confirm": "Подтвердить", "dm_decline": "Отклонить", "dm_handed_item": "Передал товар",
        "dm_accepted_return": "Принял возврат", "dm_accept": "Принять", "dm_done_ok": "Готово ✓",
        "dmq_confirm": "Подтвердить аренду?", "dmq_decline": "Отклонить запрос аренды?",
        "dmq_activate": "Товар передан арендатору?", "dmq_return": "Товар вернули?",
        "dmq_accept": "Принять обмен?", "dmq_xdecline": "Отклонить обмен?",
        "dmq_note": "Собеседник увидит ответ в переписке.",
        "lcm_block": "Заблокировать покупателя", "lcm_report": "Пожаловаться",
        "blk_t": "Заблокировать покупателя?", "blk_m": "Он больше не сможет вам писать. История переписки сохранится.",
        "blk_ok": "Заблокировать",
        "lcm_blocked_me": "Вы заблокировали покупателя — общение недоступно. История сохранена.",
        "lcm_unblock": "Разблокировать",
        "lcm_blocked_by": "Покупатель ограничил общение. Запрос на разблокировку — раз в 72 часа.",
        "lcm_req_unblock": "Запросить разблокировку", "lcm_unblocked": "Покупатель разблокирован",
        "lcm_unblock_sent": "Запрос на разблокировку отправлен", "lcm_blocked_done": "Покупатель заблокирован",
        "lcm_blocked_send": "Общение недоступно — блокировка",
        "rep_sub": "Выберите причину — модератор рассмотрит жалобу.", "rep_fraud": "Мошенничество",
        "rep_abuse": "Оскорбления или угрозы", "rep_spam": "Спам или реклама", "rep_prohibited": "Запрещённый товар",
        "rep_other": "Другое", "rep_comment": "Комментарий (необязательно)", "rep_send": "Отправить",
        "rep_sending": "Отправляем…", "rep_done": "Жалоба отправлена — спасибо",
        "rep_exists": "Жалоба уже отправлена ранее", "rep_auth": "Войдите, чтобы пожаловаться",
        // Предложение цены
        "of_head": "Предложение по цене", "of_m_cash": "Наличными", "of_m_inst": "В рассрочку", "of_m_cred": "В кредит",
        "of_mon": "мес", "arg_pickup": "Заберу сам", "arg_ship": "Оплачу доставку",
        "of_funded": "Деньги зарезервированы", "of_gone": "Отозвано", "of_replaced": "Заменено новым предложением",
        "of_used": "Договорённость использована", "of_done": "Принято",
        "of_next": "Дальше оформляет покупатель: он нажимает «Купить безопасно» в объявлении, и спишется согласованная цена.",
        "of_nudge": "Напомнить покупателю",
        "of_nudge_msg": "Цена согласована — {sum}. Оформляйте безопасную сделку в объявлении: спишется именно эта цена.",
        "of_ctr_sent": "Встречная цена отправлена · {sum} — ждём ответа покупателя",
        "of_accept_n": "Принять · {sum}", "of_decline": "Отказаться", "of_ctr_h": "Встречная цена",
        "of_final": "Цена окончательная", "of_ctr_mine": "Ваша встречная цена", "of_ctr_wait": "Ждём ответа покупателя",
        "of_ctr_ok_s": "Покупатель принял", "of_ctr_no_s": "Покупатель не согласился",
        "of_ctr_gone_s": "Покупатель предложил новую цену", "of_ctr_done": "Встречная цена отправлена",
        "of_ok": "Цена согласована", "of_final_done": "Покупатель увидит: цена окончательная",
        "of_no": "Отказ отправлен", "of_no_refund": "Отказ отправлен, обеспечение вернулось покупателю",
        // Заявки рядом
        "req_title": "Заявки рядом", "req_sub": "Запросы клиентов по вашей специальности поблизости — откликайтесь первыми",
        "req_filter_new": "Новые",
        "req_empty_new": "Новых заявок пока нет.\nЗдесь появятся запросы клиентов рядом по вашей специальности.",
        "req_empty_all": "Заявок пока нет.", "req_taxi": "Такси", "req_route": "Маршрут", "req_find_addr": "Найти адрес",
        "req_new": "новый", "req_verified": "Проверенный", "req_master": "Мастер", "req_client": "Клиент",
        "req_by_your_ad": "По вашему объявлению", "req_you_responded": "Вы откликнулись", "req_open_chat": "Открыть чат",
        "req_waiting_client": "Ждём, кого выберет клиент · откликов: ", "req_respond": "Откликнуться",
        "req_report_hide": "Пожаловаться / скрыть", "req_hide": "Скрыть", "req_order_yours": "Заказ ваш",
        "req_you_chosen": "Вас выбрали", "req_confirmed": "Подтверждено", "req_assigned": "Закреплено",
        "req_accept_order": "Принять заказ", "req_call": "Позвонить", "req_taken": "Заказ занят",
        "req_expired": "Время вышло", "req_toast_responded": "Отклик отправлен — общайтесь в «Чате»",
        "req_toast_pinned": "Закреплено! Ждём подтверждения мастера",
        "req_toast_accepted": "Заказ принят — сделка подтверждена", "req_deal_confirmed": "Сделка подтверждена",
        "req_err_closed": "Заявка уже закрыта", "req_err_cap": "Достаточно откликов",
        "req_err_expired": "Время заявки вышло", "req_err_notyou": "Заявка не вам",
        "req_err_notclient": "Закрепить может только клиент", "req_err_nomaster": "Мастер не найден",
        "req_pin_title": "Закрепить заказ за мастером?",
        "req_pin_text": "Заказ закрепится за этим мастером, остальные мастера потеряют доступ к заявке.",
        "req_pin_btn": "Закрепить", "req_closed_title": "Заявка уже неактивна",
        "req_closed_text": "Время заявки истекло (5 минут) или её уже закрепили за другим мастером.",
        "req_accept_title": "Принять заказ?", "req_accept_text": "Подтвердите, что берёте этот заказ в работу.",
        "req_accept_ok": "Принять", "req_svc_done": "Выполнил {d} из {t}", "req_deals_n": "%ld сделок",
        "req_left_a11y": "Осталось %@",
        "dm_deal_confirmed": "Сделка подтверждена", "dm_accept_order": "Принять заказ",
        "dm_wait_master": "Ждём подтверждения мастера…", "dm_client_chose": "Клиент выбрал этого мастера",
        "dm_master_selected": "Исполнитель выбран", "dm_pin_master": "Закрепить за мастером",
        "ago_now": "только что", "ago_min": "%ld мин назад", "ago_h": "%ld ч назад",
        // «Сделка состоялась?»
        "fb_title": "Сделка состоялась?", "fb_text": "Заявка «%@» · с %@", "fb_master": "мастером",
        "fb_comment": "Комментарий (необязательно) — увидит администрация", "fb_no": "Нет", "fb_yes": "Да, всё ок",
        "fb_thanks": "Спасибо за отзыв!", "fb_passed": "Спасибо, передали администрации",
        // Колокольчик, справка, поддержка
        "notif_title": "Уведомления", "cab_help": "Справочный центр",
        "sup_title": "Обращение в поддержку", "sup_ph": "Ваш ответ…", "sup_staff": "Поддержка", "sup_you": "Вы",
        "sup_empty": "Пока нет сообщений", "sup_notfound": "Обращение не найдено", "sup_st_new": "Новое",
        "sup_st_answered": "Есть ответ", "sup_st_waiting": "Ждём вас", "sup_st_closed": "Закрыто",
        "sup_auth": "Войдите в кабинет",
        "dreq_title": "Запросить данные",
        "dreq_subtitle": "Удалённые переписки хранятся у поддержки 12 месяцев.\nВаш аккаунт определим автоматически — логин/ID вводить не нужно.",
        "dreq_prefill": "Прошу выслать данные моей переписки.\nЧто нужно: ", "dreq_submit": "Отправить обращение",
        "dreq_sending": "Отправка…", "dreq_min_length": "Опишите подробнее — минимум 10 символов",
        "dreq_success_msg": "Обращение принято. Номер: {id}. Ответ придёт в поддержке.",
        "dreq_success_toast": "Обращение отправлено", "dreq_error": "Ошибка, попробуйте позже"
    ]

    private static let kk: [String: String] = [
        "title": "Чат", "nav_chat": "Чат", "sub": "Хат алмасу, жалға беру және айырбас — бір жерде",
        "search_ph": "Іздеу: аты, тауар, хабарлама", "clear": "Тазалау", "trash": "Себет",
        "f_all": "Барлығы", "f_lead": "Сатып алушылар", "f_rental": "Жалға", "f_exchange": "Айырбас",
        "retention": "Жойылған хат алмасулар қолдау қызметінде 12 ай сақталады.",
        "request_data": "Қолдау қызметінен деректерді сұрау",
        "empty": "Әзірге диалог жоқ.\nСатып алушы жазса немесе мәміле ұсынса — осында пайда болады.",
        "trash_empty": "Себет бос",
        "pin": "Бекіту", "unpin": "Босату", "pinned": "Бекітілді ✓", "unpinned": "Босатылды",
        "pin_max": "Ең көбі 5 чатты бекітуге болады", "pinned_a11y": "бекітілген",
        "trash_to": "Себетке жіберу", "trash_done": "Себетке жіберілді", "restore": "Қайтару",
        "restored": "Қайтарылды ✓", "purge": "Біржола жою",
        "purge_q": "Хат алмасуды біржола жою керек пе? Ол сізде қайтарусыз жоғалады. Дауларды қарау үшін деректер қолдау қызметінде 12 ай сақталады.",
        "purge_done": "Біржола жойылды", "more": "Әрекеттер",
        "trash_clear": "Себетті тазалау", "trash_clear_q": "%ld хат алмасуды біржола жою керек пе?",
        "trash_cleared": "Себет тазаланды", "trash_clear_part": "%ld / %ld жойылды",
        "you": "Сіз: ", "user": "Пайдаланушы", "user_deleted": "Жойылған пайдаланушы", "buyer": "Сатып алушы",
        "rental_req": "Жалға алу сұрауы", "exchange_offer": "Айырбас ұсынысы",
        "tag_rent": "Жалға", "tag_exch": "Айырбас", "tag_lead": "Лид", "tag_buyer": "Сатып алушы", "tag_buy": "Сатып алу",
        "lead_ai": "Kliko AI-көмекшісі жауап береді", "lead_hot": "Ыстық лид — қосылыңыз",
        "lead_active": "Сіз диалогтасыз", "lead_closed": "Аяқталды",
        "it_sold": "Сатылды", "it_reserved": "Мәміледе", "it_inactive": "Алынды", "it_off": "Шығарылымда жоқ",
        "it_gone": "Жойылды",
        "lbl_pick": "Белгі", "label_title": "Диалог белгісі", "label_saved": "Белгі сақталды ✓",
        "lbl_maybe": "Сатып алуы мүмкін", "lbl_thinking": "Ойланып жүр", "lbl_bought": "Сатып алды",
        "lbl_regular": "Тұрақты", "lbl_declined": "Бас тартты",
        "err_generic": "Қате", "err_no_conn": "Байланыс жоқ", "err_net": "Желі қатесі", "no_conn": "Байланыс жоқ",
        "err_load": "Жүктеу қатесі", "loading": "Жүктелуде…", "cancel": "Бас тарту", "ok_btn": "Түсінікті",
        "close": "Жабу", "fail": "Болмады", "send_err": "Жіберу қатесі",
        "read": "✓✓ Оқылды", "sent": "✓ Жіберілді",
        "lcm_st_ai": "Kliko AI-көмекшісі диалог жүргізуде", "lcm_st_hot": "Ыстық лид", "lcm_st_active": "Сіз диалогтасыз",
        "lcm_st_closed": "Аяқталды", "lcm_presence": " · сатып алушы %@",
        "lcm_offline": "Байланыс жоқ — қайта қосылуда…",
        "lcm_join_t": "Өзіңіз жауап беру үшін қосылыңыз", "lcm_join_b": "Қосылу",
        "lcm_joined": "Сіз чатқа қосылдыңыз ✓",
        "lcm_deal_live": "Сатып алушы мәміле рәсімдеді", "co_goto": "Мәмілеге өту",
        "lcm_hot": "Ыстық лид — бірден хабарласыңыз", "call": "Қоңырау шалу",
        "vbar_t": "Сатып алушы қауіпсіз сатып алғысы келеді", "vbar_d": "Кепіл-мәміле — тек тексерілген сатушыларға",
        "verify_go": "Верификациядан өту", "listing": "Хабарландыру", "reply_ph": "Жауап беру…",
        "lcm_no_msgs": "Хабарлама жоқ", "typing": "Жазып жатыр…", "who_ai": "Kliko AI-көмекшісі",
        "via_tg": "Telegram-нан", "video": "Бейне",
        "dm_direct": "Тікелей чат", "dm_no_msgs": "Әзірге хабарлама жоқ.\nБірінші болып жазыңыз",
        "dm_blocked_msg": "Хат алмасу мүмкін емес — біреуіңіз екіншісін бұғаттадыңыз.",
        "dm_tag_exch": "Айырбас", "dm_tag_rent": "Жалға беру", "negotiable": "Келісімді", "torg": "Саудаласу",
        "dm_dates": "Күндер", "dm_cost": "Құны", "dm_deposit": "Кепілақы", "unit_day": "тәул", "unit_month": "ай",
        "dm_r_requested": "Жауап күтуде", "dm_r_confirmed": "Расталды — тауар берілмеген",
        "dm_r_active": "Белсенді", "dm_r_returned": "Аяқталды · кепілақы қайтарылды",
        "dm_r_cancelled": "Қабылданбады / бас тартылды", "dm_r_disputed": "Дау ашылды",
        "dm_ex_accepted": "Айырбас қабылданды", "dm_ex_declined": "Қабылданбады",
        "dm_they_offer": "Сізге ұсынады", "dm_for_yours": "Сіздікіне", "dm_sur": "Қосымша төлем ",
        "dm_sur_to_you": "Сізге қосымша төлем ", "dm_sur_asks": "Сізден қосымша төлем сұрайды ",
        "dm_confirm": "Растау", "dm_decline": "Қабылдамау", "dm_handed_item": "Тауарды бердім",
        "dm_accepted_return": "Қайтаруды қабылдадым", "dm_accept": "Қабылдау", "dm_done_ok": "Дайын ✓",
        "dmq_confirm": "Жалға беруді растайсыз ба?", "dmq_decline": "Жалға алу сұрауын қабылдамайсыз ба?",
        "dmq_activate": "Тауар жалға алушыға берілді ме?", "dmq_return": "Тауар қайтарылды ма?",
        "dmq_accept": "Айырбасты қабылдайсыз ба?", "dmq_xdecline": "Айырбасты қабылдамайсыз ба?",
        "dmq_note": "Әңгімелесуші жауапты хат алмасудан көреді.",
        "lcm_block": "Сатып алушыны бұғаттау", "lcm_report": "Шағымдану",
        "blk_t": "Сатып алушыны бұғаттау керек пе?", "blk_m": "Ол сізге енді жаза алмайды. Хат алмасу тарихы сақталады.",
        "blk_ok": "Бұғаттау",
        "lcm_blocked_me": "Сіз сатып алушыны бұғаттадыңыз — байланыс мүмкін емес. Тарих сақталды.",
        "lcm_unblock": "Бұғаттан шығару",
        "lcm_blocked_by": "Сатып алушы байланысты шектеді. Бұғаттан шығару сұрауы — 72 сағатта бір рет.",
        "lcm_req_unblock": "Бұғаттан шығаруды сұрау", "lcm_unblocked": "Сатып алушы бұғаттан шығарылды",
        "lcm_unblock_sent": "Бұғаттан шығару сұрауы жіберілді", "lcm_blocked_done": "Сатып алушы бұғатталды",
        "lcm_blocked_send": "Байланыс мүмкін емес — бұғаттау",
        "rep_sub": "Себебін таңдаңыз — модератор шағымды қарайды.", "rep_fraud": "Алаяқтық",
        "rep_abuse": "Қорлау немесе қорқыту", "rep_spam": "Спам немесе жарнама", "rep_prohibited": "Тыйым салынған тауар",
        "rep_other": "Басқа", "rep_comment": "Түсініктеме (міндетті емес)", "rep_send": "Жіберу",
        "rep_sending": "Жіберілуде…", "rep_done": "Шағым жіберілді — рақмет",
        "rep_exists": "Шағым бұрын жіберілген", "rep_auth": "Шағымдану үшін кіріңіз",
        "of_head": "Баға ұсынысы", "of_m_cash": "Қолма-қол", "of_m_inst": "Бөліп төлеу", "of_m_cred": "Несиеге",
        "of_mon": "ай", "arg_pickup": "Өзім алып кетемін", "arg_ship": "Жеткізуді өзім төлеймін",
        "of_funded": "Ақша резервтелді", "of_gone": "Кері алынды", "of_replaced": "Жаңа ұсыныспен ауыстырылды",
        "of_used": "Келісім пайдаланылды", "of_done": "Қабылданды",
        "of_next": "Әрі қарай сатып алушы рәсімдейді: ол хабарландырудағы «Қауіпсіз сатып алу» түймесін басады, келісілген баға есептен шығарылады.",
        "of_nudge": "Сатып алушыға еске салу",
        "of_nudge_msg": "Баға келісілді — {sum}. Хабарландыруда қауіпсіз мәміле рәсімдеңіз: дәл осы баға есептен шығарылады.",
        "of_ctr_sent": "Қарсы баға жіберілді · {sum} — сатып алушының жауабын күтудеміз",
        "of_accept_n": "Қабылдау · {sum}", "of_decline": "Бас тарту", "of_ctr_h": "Қарсы баға",
        "of_final": "Баға түпкілікті", "of_ctr_mine": "Сіздің қарсы бағаңыз", "of_ctr_wait": "Сатып алушының жауабын күтудеміз",
        "of_ctr_ok_s": "Сатып алушы қабылдады", "of_ctr_no_s": "Сатып алушы келіспеді",
        "of_ctr_gone_s": "Сатып алушы жаңа баға ұсынды", "of_ctr_done": "Қарсы баға жіберілді",
        "of_ok": "Баға келісілді", "of_final_done": "Сатып алушы көреді: баға түпкілікті",
        "of_no": "Бас тарту жіберілді", "of_no_refund": "Бас тарту жіберілді, кепілақы сатып алушыға қайтарылды",
        "req_title": "Жақын маңдағы өтінімдер",
        "req_sub": "Сіздің мамандығыңыз бойынша жақын маңдағы клиенттердің сұраулары — бірінші болып жауап беріңіз",
        "req_filter_new": "Жаңалары",
        "req_empty_new": "Әзірге жаңа өтінім жоқ.\nМұнда мамандығыңыз бойынша жақын маңдағы клиенттердің сұраулары пайда болады.",
        "req_empty_all": "Әзірге өтінім жоқ.", "req_taxi": "Такси", "req_route": "Бағыт", "req_find_addr": "Мекенжайды табу",
        "req_new": "жаңа", "req_verified": "Тексерілген", "req_master": "Шебер", "req_client": "Клиент",
        "req_by_your_ad": "Сіздің хабарландыруыңыз бойынша", "req_you_responded": "Сіз жауап бердіңіз",
        "req_open_chat": "Чатты ашу",
        "req_waiting_client": "Клиент кімді таңдайтынын күтудеміз · жауаптар: ", "req_respond": "Жауап беру",
        "req_report_hide": "Шағымдану / жасыру", "req_hide": "Жасыру", "req_order_yours": "Тапсырыс сіздікі",
        "req_you_chosen": "Сізді таңдады", "req_confirmed": "Расталды", "req_assigned": "Бекітілді",
        "req_accept_order": "Тапсырысты қабылдау", "req_call": "Қоңырау шалу", "req_taken": "Тапсырыс бос емес",
        "req_expired": "Уақыт бітті", "req_toast_responded": "Жауап жіберілді — «Чатта» сөйлесіңіз",
        "req_toast_pinned": "Бекітілді! Шебердің растауын күтудеміз",
        "req_toast_accepted": "Тапсырыс қабылданды — мәміле расталды", "req_deal_confirmed": "Мәміле расталды",
        "req_err_closed": "Өтінім жабылған", "req_err_cap": "Жауаптар жеткілікті",
        "req_err_expired": "Өтінім уақыты бітті", "req_err_notyou": "Өтінім сізге емес",
        "req_err_notclient": "Тек клиент бекіте алады", "req_err_nomaster": "Шебер табылмады",
        "req_pin_title": "Тапсырысты шеберге бекіту керек пе?",
        "req_pin_text": "Тапсырыс осы шеберге бекітіледі, басқа шеберлер өтінімге қолжетімділігін жоғалтады.",
        "req_pin_btn": "Бекіту", "req_closed_title": "Өтінім енді белсенді емес",
        "req_closed_text": "Өтінім уақыты бітті (5 минут) немесе ол басқа шеберге бекітілген.",
        "req_accept_title": "Тапсырысты қабылдау керек пе?", "req_accept_text": "Бұл тапсырысты жұмысқа алатыныңызды растаңыз.",
        "req_accept_ok": "Қабылдау", "req_svc_done": "{t} ішінен {d} орындады", "req_deals_n": "%ld мәміле",
        "req_left_a11y": "Қалды %@",
        "dm_deal_confirmed": "Мәміле расталды", "dm_accept_order": "Тапсырысты қабылдау",
        "dm_wait_master": "Шебердің растауын күтудеміз…", "dm_client_chose": "Клиент осы шеберді таңдады",
        "dm_master_selected": "Орындаушы таңдалды", "dm_pin_master": "Шеберге бекіту",
        "ago_now": "жаңа ғана", "ago_min": "%ld мин бұрын", "ago_h": "%ld сағ бұрын",
        "fb_title": "Мәміле болды ма?", "fb_text": "Өтінім «%@» · %@", "fb_master": "шебермен",
        "fb_comment": "Түсініктеме (міндетті емес) — әкімшілік көреді", "fb_no": "Жоқ", "fb_yes": "Иә, бәрі жақсы",
        "fb_thanks": "Пікіріңізге рақмет!", "fb_passed": "Рақмет, әкімшілікке жеткіздік",
        "notif_title": "Хабарландырулар", "cab_help": "Анықтама орталығы",
        "sup_title": "Қолдау қызметіне өтініш", "sup_ph": "Сіздің жауабыңыз…", "sup_staff": "Қолдау", "sup_you": "Сіз",
        "sup_empty": "Әзірге хабарлама жоқ", "sup_notfound": "Өтініш табылмады", "sup_st_new": "Жаңа",
        "sup_st_answered": "Жауап бар", "sup_st_waiting": "Сізді күтудеміз", "sup_st_closed": "Жабық",
        "sup_auth": "Кабинетке кіріңіз",
        "dreq_title": "Деректерді сұрау",
        "dreq_subtitle": "Жойылған хат алмасулар қолдау қызметінде 12 ай сақталады.\nАккаунтыңызды өзіміз анықтаймыз — логин/ID енгізудің қажеті жоқ.",
        "dreq_prefill": "Хат алмасуымның деректерін жіберуіңізді сұраймын.\nНе керек: ", "dreq_submit": "Өтініш жіберу",
        "dreq_sending": "Жіберілуде…", "dreq_min_length": "Толығырақ сипаттаңыз — кемінде 10 таңба",
        "dreq_success_msg": "Өтініш қабылданды. Нөмірі: {id}. Жауап қолдау қызметіне келеді.",
        "dreq_success_toast": "Өтініш жіберілді", "dreq_error": "Қате, кейінірек қайталаңыз"
    ]

    private static let en: [String: String] = [
        "title": "Chat", "nav_chat": "Chat", "sub": "Messages, rentals and swaps — all in one place",
        "search_ph": "Search: name, item, message", "clear": "Clear", "trash": "Trash",
        "f_all": "All", "f_lead": "Buyers", "f_rental": "Rentals", "f_exchange": "Swaps",
        "retention": "Deleted chats are kept by support for 12 months.",
        "request_data": "Request data from support",
        "empty": "No conversations yet.\nWhen a buyer writes or offers a deal, it will appear here.",
        "trash_empty": "Trash is empty",
        "pin": "Pin", "unpin": "Unpin", "pinned": "Pinned ✓", "unpinned": "Unpinned",
        "pin_max": "You can pin up to 5 chats", "pinned_a11y": "pinned",
        "trash_to": "Move to trash", "trash_done": "Moved to trash", "restore": "Restore",
        "restored": "Restored ✓", "purge": "Delete forever",
        "purge_q": "Delete this conversation forever? It will disappear for you permanently. For dispute resolution, support keeps the data for 12 months.",
        "purge_done": "Deleted forever", "more": "Actions",
        "trash_clear": "Empty trash", "trash_clear_q": "Delete %ld conversations forever?",
        "trash_cleared": "Trash emptied", "trash_clear_part": "Deleted %ld of %ld",
        "you": "You: ", "user": "User", "user_deleted": "Deleted user", "buyer": "Buyer",
        "rental_req": "Rental request", "exchange_offer": "Swap offer",
        "tag_rent": "Rental", "tag_exch": "Swap", "tag_lead": "Lead", "tag_buyer": "Buyer", "tag_buy": "Purchase",
        "lead_ai": "Kliko AI assistant is replying", "lead_hot": "Hot lead — join in",
        "lead_active": "You're in the chat", "lead_closed": "Closed",
        "it_sold": "Sold", "it_reserved": "In a deal", "it_inactive": "Unpublished", "it_off": "Not listed",
        "it_gone": "Deleted",
        "lbl_pick": "Label", "label_title": "Chat label", "label_saved": "Label saved ✓",
        "lbl_maybe": "May buy", "lbl_thinking": "Thinking", "lbl_bought": "Bought", "lbl_regular": "Regular",
        "lbl_declined": "Declined",
        "err_generic": "Error", "err_no_conn": "No connection", "err_net": "Network error", "no_conn": "No connection",
        "err_load": "Loading error", "loading": "Loading…", "cancel": "Cancel", "ok_btn": "Got it",
        "close": "Close", "fail": "Failed", "send_err": "Sending failed",
        "read": "✓✓ Read", "sent": "✓ Sent",
        "lcm_st_ai": "Kliko AI assistant is handling the chat", "lcm_st_hot": "Hot lead", "lcm_st_active": "You're in the chat",
        "lcm_st_closed": "Closed", "lcm_presence": " · buyer %@",
        "lcm_offline": "No connection — reconnecting…",
        "lcm_join_t": "Join to reply personally", "lcm_join_b": "Join",
        "lcm_joined": "You've joined the chat ✓",
        "lcm_deal_live": "The buyer has placed a deal", "co_goto": "Go to deal",
        "lcm_hot": "Hot lead — get in touch now", "call": "Call",
        "vbar_t": "The buyer wants to buy safely", "vbar_d": "Escrow deals are for verified sellers only",
        "verify_go": "Get verified", "listing": "Listing", "reply_ph": "Reply…",
        "lcm_no_msgs": "No messages", "typing": "Typing…", "who_ai": "Kliko AI assistant",
        "via_tg": "from Telegram", "video": "Video",
        "dm_direct": "Direct chat", "dm_no_msgs": "No messages yet.\nBe the first to write",
        "dm_blocked_msg": "Messaging is unavailable — one of you has blocked the other.",
        "dm_tag_exch": "Swap", "dm_tag_rent": "Rent", "negotiable": "Negotiable", "torg": "Negotiable",
        "dm_dates": "Dates", "dm_cost": "Cost", "dm_deposit": "Deposit", "unit_day": "day", "unit_month": "mo",
        "dm_r_requested": "Awaiting reply", "dm_r_confirmed": "Confirmed — item not handed over",
        "dm_r_active": "Active", "dm_r_returned": "Completed · deposit returned",
        "dm_r_cancelled": "Declined / cancelled", "dm_r_disputed": "Dispute opened",
        "dm_ex_accepted": "Swap accepted", "dm_ex_declined": "Declined",
        "dm_they_offer": "You are offered", "dm_for_yours": "For your", "dm_sur": "Extra payment ",
        "dm_sur_to_you": "Extra payment to you ", "dm_sur_asks": "Asks you to pay extra ",
        "dm_confirm": "Confirm", "dm_decline": "Decline", "dm_handed_item": "Item handed over",
        "dm_accepted_return": "Return accepted", "dm_accept": "Accept", "dm_done_ok": "Done ✓",
        "dmq_confirm": "Confirm the rental?", "dmq_decline": "Decline the rental request?",
        "dmq_activate": "Handed the item to the renter?", "dmq_return": "Has the item been returned?",
        "dmq_accept": "Accept the swap?", "dmq_xdecline": "Decline the swap?",
        "dmq_note": "The other person will see your answer in the chat.",
        "lcm_block": "Block buyer", "lcm_report": "Report",
        "blk_t": "Block this buyer?", "blk_m": "They won't be able to message you anymore. The chat history will be kept.",
        "blk_ok": "Block",
        "lcm_blocked_me": "You blocked the buyer — messaging is unavailable. The history is kept.",
        "lcm_unblock": "Unblock",
        "lcm_blocked_by": "The buyer restricted messaging. You can request unblocking once every 72 hours.",
        "lcm_req_unblock": "Request unblocking", "lcm_unblocked": "Buyer unblocked",
        "lcm_unblock_sent": "Unblock request sent", "lcm_blocked_done": "Buyer blocked",
        "lcm_blocked_send": "Messaging unavailable — blocked",
        "rep_sub": "Choose a reason — a moderator will review the report.", "rep_fraud": "Fraud",
        "rep_abuse": "Insults or threats", "rep_spam": "Spam or advertising", "rep_prohibited": "Prohibited item",
        "rep_other": "Other", "rep_comment": "Comment (optional)", "rep_send": "Send",
        "rep_sending": "Sending…", "rep_done": "Report sent — thank you",
        "rep_exists": "You've already reported this", "rep_auth": "Sign in to report",
        "of_head": "Price offer", "of_m_cash": "Cash", "of_m_inst": "Installments", "of_m_cred": "On credit",
        "of_mon": "mo", "arg_pickup": "I'll pick it up", "arg_ship": "I'll pay for delivery",
        "of_funded": "Money reserved", "of_gone": "Withdrawn", "of_replaced": "Replaced by a new offer",
        "of_used": "Agreement already used", "of_done": "Accepted",
        "of_next": "The buyer completes it next: they tap “Buy safely” in the listing and the agreed price is charged.",
        "of_nudge": "Remind the buyer",
        "of_nudge_msg": "Price agreed — {sum}. Place a safe deal in the listing: exactly this price will be charged.",
        "of_ctr_sent": "Counteroffer sent · {sum} — waiting for the buyer",
        "of_accept_n": "Accept · {sum}", "of_decline": "Decline", "of_ctr_h": "Counteroffer",
        "of_final": "Price is final", "of_ctr_mine": "Your counteroffer", "of_ctr_wait": "Waiting for the buyer",
        "of_ctr_ok_s": "The buyer accepted", "of_ctr_no_s": "The buyer declined",
        "of_ctr_gone_s": "The buyer offered a new price", "of_ctr_done": "Counteroffer sent",
        "of_ok": "Price agreed", "of_final_done": "The buyer will see: the price is final",
        "of_no": "Declined", "of_no_refund": "Declined, the deposit was returned to the buyer",
        "req_title": "Requests nearby", "req_sub": "Nearby client requests in your field — respond first",
        "req_filter_new": "New",
        "req_empty_new": "No new requests yet.\nClient requests nearby in your field will appear here.",
        "req_empty_all": "No requests yet.", "req_taxi": "Taxi", "req_route": "Route", "req_find_addr": "Find address",
        "req_new": "new", "req_verified": "Verified", "req_master": "Pro", "req_client": "Client",
        "req_by_your_ad": "About your listing", "req_you_responded": "You responded", "req_open_chat": "Open chat",
        "req_waiting_client": "Waiting for the client to choose · responses: ", "req_respond": "Respond",
        "req_report_hide": "Report / hide", "req_hide": "Hide", "req_order_yours": "The job is yours",
        "req_you_chosen": "You were chosen", "req_confirmed": "Confirmed", "req_assigned": "Assigned",
        "req_accept_order": "Accept job", "req_call": "Call", "req_taken": "Job taken",
        "req_expired": "Time's up", "req_toast_responded": "Response sent — talk in “Chat”",
        "req_toast_pinned": "Assigned! Waiting for the pro to confirm",
        "req_toast_accepted": "Job accepted — deal confirmed", "req_deal_confirmed": "Deal confirmed",
        "req_err_closed": "The request is already closed", "req_err_cap": "Enough responses",
        "req_err_expired": "The request has expired", "req_err_notyou": "This request isn't for you",
        "req_err_notclient": "Only the client can assign", "req_err_nomaster": "Pro not found",
        "req_pin_title": "Assign the job to this pro?",
        "req_pin_text": "The job will be assigned to this pro, other pros will lose access to the request.",
        "req_pin_btn": "Assign", "req_closed_title": "The request is no longer active",
        "req_closed_text": "The request time ran out (5 minutes) or it was already assigned to another pro.",
        "req_accept_title": "Accept the job?", "req_accept_text": "Confirm that you're taking this job.",
        "req_accept_ok": "Accept", "req_svc_done": "Completed {d} of {t}", "req_deals_n": "%ld deals",
        "req_left_a11y": "%@ left",
        "dm_deal_confirmed": "Deal confirmed", "dm_accept_order": "Accept job",
        "dm_wait_master": "Waiting for the pro to confirm…", "dm_client_chose": "The client chose this pro",
        "dm_master_selected": "Pro selected", "dm_pin_master": "Assign to this pro",
        "ago_now": "just now", "ago_min": "%ld min ago", "ago_h": "%ld h ago",
        "fb_title": "Did the deal happen?", "fb_text": "Request “%@” · with %@", "fb_master": "the pro",
        "fb_comment": "Comment (optional) — seen by the administration", "fb_no": "No", "fb_yes": "Yes, all good",
        "fb_thanks": "Thanks for your feedback!", "fb_passed": "Thanks, we've passed it to the administration",
        "notif_title": "Notifications", "cab_help": "Help center",
        "sup_title": "Support request", "sup_ph": "Your reply…", "sup_staff": "Support", "sup_you": "You",
        "sup_empty": "No messages yet", "sup_notfound": "Request not found", "sup_st_new": "New",
        "sup_st_answered": "Answered", "sup_st_waiting": "Waiting for you", "sup_st_closed": "Closed",
        "sup_auth": "Sign in to your account",
        "dreq_title": "Request data",
        "dreq_subtitle": "Deleted chats are kept by support for 12 months.\nWe'll identify your account automatically — no need to enter a login or ID.",
        "dreq_prefill": "Please send me the data of my conversations.\nWhat I need: ", "dreq_submit": "Send request",
        "dreq_sending": "Sending…", "dreq_min_length": "Please describe in more detail — at least 10 characters",
        "dreq_success_msg": "Request received. Number: {id}. The reply will come in support.",
        "dreq_success_toast": "Request sent", "dreq_error": "Error, please try again later"
    ]

    private static let ar: [String: String] = [
        "title": "الدردشة", "nav_chat": "الدردشة", "sub": "المراسلات والإيجار والمقايضة — في مكان واحد",
        "search_ph": "بحث: الاسم، السلعة، الرسالة", "clear": "مسح", "trash": "المهملات",
        "f_all": "الكل", "f_lead": "المشترون", "f_rental": "الإيجار", "f_exchange": "المقايضة",
        "retention": "تحتفظ خدمة الدعم بالمحادثات المحذوفة لمدة 12 شهرًا.",
        "request_data": "طلب البيانات من الدعم",
        "empty": "لا توجد محادثات بعد.\nعندما يكتب مشترٍ أو يقترح صفقة — ستظهر هنا.",
        "trash_empty": "المهملات فارغة",
        "pin": "تثبيت", "unpin": "إلغاء التثبيت", "pinned": "تم التثبيت ✓", "unpinned": "تم إلغاء التثبيت",
        "pin_max": "يمكن تثبيت 5 محادثات كحد أقصى", "pinned_a11y": "مثبتة",
        "trash_to": "نقل إلى المهملات", "trash_done": "تم النقل إلى المهملات", "restore": "استعادة",
        "restored": "تمت الاستعادة ✓", "purge": "حذف نهائي",
        "purge_q": "حذف المحادثة نهائيًا؟ ستختفي لديك بلا رجعة. لمعالجة النزاعات تحتفظ خدمة الدعم بالبيانات لمدة 12 شهرًا.",
        "purge_done": "تم الحذف نهائيًا", "more": "إجراءات",
        "trash_clear": "إفراغ سلة المحذوفات", "trash_clear_q": "حذف %ld من المحادثات نهائيًا؟",
        "trash_cleared": "تم إفراغ السلة", "trash_clear_part": "تم حذف %ld من %ld",
        "you": "أنت: ", "user": "مستخدم", "user_deleted": "مستخدم محذوف", "buyer": "المشتري",
        "rental_req": "طلب إيجار", "exchange_offer": "عرض مقايضة",
        "tag_rent": "إيجار", "tag_exch": "مقايضة", "tag_lead": "عميل محتمل", "tag_buyer": "المشتري", "tag_buy": "شراء",
        "lead_ai": "مساعد Kliko AI يرد", "lead_hot": "عميل ساخن — انضم",
        "lead_active": "أنت في المحادثة", "lead_closed": "منتهية",
        "it_sold": "مُباع", "it_reserved": "في صفقة", "it_inactive": "موقوف", "it_off": "خارج العرض",
        "it_gone": "محذوف",
        "lbl_pick": "تصنيف", "label_title": "تصنيف المحادثة", "label_saved": "تم حفظ التصنيف ✓",
        "lbl_maybe": "قد يشتري", "lbl_thinking": "يفكر", "lbl_bought": "اشترى", "lbl_regular": "دائم",
        "lbl_declined": "رفض",
        "err_generic": "خطأ", "err_no_conn": "لا يوجد اتصال", "err_net": "خطأ في الشبكة", "no_conn": "لا يوجد اتصال",
        "err_load": "خطأ في التحميل", "loading": "جارٍ التحميل…", "cancel": "إلغاء", "ok_btn": "حسنًا",
        "close": "إغلاق", "fail": "تعذّر ذلك", "send_err": "خطأ في الإرسال",
        "read": "✓✓ مقروءة", "sent": "✓ مُرسلة",
        "lcm_st_ai": "مساعد Kliko AI يدير المحادثة", "lcm_st_hot": "عميل ساخن", "lcm_st_active": "أنت في المحادثة",
        "lcm_st_closed": "منتهية", "lcm_presence": " · المشتري %@",
        "lcm_offline": "لا يوجد اتصال — جارٍ إعادة الاتصال…",
        "lcm_join_t": "انضم لترد بنفسك", "lcm_join_b": "انضمام",
        "lcm_joined": "انضممت إلى المحادثة ✓",
        "lcm_deal_live": "أنشأ المشتري صفقة", "co_goto": "الانتقال إلى الصفقة",
        "lcm_hot": "عميل ساخن — تواصل فورًا", "call": "اتصال",
        "vbar_t": "المشتري يريد الشراء بأمان", "vbar_d": "صفقة الضمان — للبائعين الموثّقين فقط",
        "verify_go": "إتمام التوثيق", "listing": "الإعلان", "reply_ph": "رد…",
        "lcm_no_msgs": "لا توجد رسائل", "typing": "يكتب…", "who_ai": "مساعد Kliko AI",
        "via_tg": "من Telegram", "video": "فيديو",
        "dm_direct": "محادثة مباشرة", "dm_no_msgs": "لا توجد رسائل بعد.\nكن أول من يكتب",
        "dm_blocked_msg": "المراسلة غير متاحة — أحدكما حظر الآخر.",
        "dm_tag_exch": "مقايضة", "dm_tag_rent": "إيجار", "negotiable": "قابل للتفاوض", "torg": "قابل للتفاوض",
        "dm_dates": "التواريخ", "dm_cost": "التكلفة", "dm_deposit": "التأمين", "unit_day": "يوم", "unit_month": "شهر",
        "dm_r_requested": "بانتظار الرد", "dm_r_confirmed": "تم التأكيد — لم يُسلَّم الغرض",
        "dm_r_active": "نشط", "dm_r_returned": "مكتمل · أُعيد التأمين",
        "dm_r_cancelled": "مرفوض / ملغى", "dm_r_disputed": "نزاع مفتوح",
        "dm_ex_accepted": "تم قبول المقايضة", "dm_ex_declined": "مرفوض",
        "dm_they_offer": "يُعرض عليك", "dm_for_yours": "مقابل", "dm_sur": "مبلغ إضافي ",
        "dm_sur_to_you": "مبلغ إضافي لك ", "dm_sur_asks": "يطلب منك مبلغًا إضافيًا ",
        "dm_confirm": "تأكيد", "dm_decline": "رفض", "dm_handed_item": "سلّمت الغرض",
        "dm_accepted_return": "استلمت الإرجاع", "dm_accept": "قبول", "dm_done_ok": "تم ✓",
        "dmq_confirm": "تأكيد الإيجار؟", "dmq_decline": "رفض طلب الإيجار؟",
        "dmq_activate": "هل سلّمت الغرض للمستأجر؟", "dmq_return": "هل أُعيد الغرض؟",
        "dmq_accept": "قبول المقايضة؟", "dmq_xdecline": "رفض المقايضة؟",
        "dmq_note": "سيرى الطرف الآخر ردك في المحادثة.",
        "lcm_block": "حظر المشتري", "lcm_report": "إبلاغ",
        "blk_t": "حظر المشتري؟", "blk_m": "لن يتمكن من مراسلتك بعد الآن. سيُحفظ سجل المحادثة.",
        "blk_ok": "حظر",
        "lcm_blocked_me": "لقد حظرت المشتري — التواصل غير متاح. السجل محفوظ.",
        "lcm_unblock": "إلغاء الحظر",
        "lcm_blocked_by": "قيّد المشتري التواصل. طلب إلغاء الحظر — مرة كل 72 ساعة.",
        "lcm_req_unblock": "طلب إلغاء الحظر", "lcm_unblocked": "تم إلغاء حظر المشتري",
        "lcm_unblock_sent": "تم إرسال طلب إلغاء الحظر", "lcm_blocked_done": "تم حظر المشتري",
        "lcm_blocked_send": "التواصل غير متاح — حظر",
        "rep_sub": "اختر السبب — سيراجع المشرف البلاغ.", "rep_fraud": "احتيال",
        "rep_abuse": "إهانات أو تهديدات", "rep_spam": "رسائل مزعجة أو إعلانات", "rep_prohibited": "سلعة محظورة",
        "rep_other": "أخرى", "rep_comment": "تعليق (اختياري)", "rep_send": "إرسال",
        "rep_sending": "جارٍ الإرسال…", "rep_done": "تم إرسال البلاغ — شكرًا",
        "rep_exists": "تم إرسال البلاغ سابقًا", "rep_auth": "سجّل الدخول للإبلاغ",
        "of_head": "عرض سعر", "of_m_cash": "نقدًا", "of_m_inst": "بالتقسيط", "of_m_cred": "بالائتمان",
        "of_mon": "شهر", "arg_pickup": "سأستلمها بنفسي", "arg_ship": "سأدفع التوصيل",
        "of_funded": "المبلغ محجوز", "of_gone": "تم السحب", "of_replaced": "استُبدل بعرض جديد",
        "of_used": "تم استخدام الاتفاق", "of_done": "مقبول",
        "of_next": "بعد ذلك يُتم المشتري الشراء: يضغط «شراء آمن» في الإعلان ويُخصم السعر المتفق عليه.",
        "of_nudge": "تذكير المشتري",
        "of_nudge_msg": "تم الاتفاق على السعر — {sum}. أنشئ صفقة آمنة في الإعلان: سيُخصم هذا السعر بالتحديد.",
        "of_ctr_sent": "تم إرسال سعر مقابل · {sum} — بانتظار رد المشتري",
        "of_accept_n": "قبول · {sum}", "of_decline": "رفض", "of_ctr_h": "سعر مقابل",
        "of_final": "السعر نهائي", "of_ctr_mine": "سعرك المقابل", "of_ctr_wait": "بانتظار رد المشتري",
        "of_ctr_ok_s": "قبل المشتري", "of_ctr_no_s": "لم يوافق المشتري",
        "of_ctr_gone_s": "اقترح المشتري سعرًا جديدًا", "of_ctr_done": "تم إرسال السعر المقابل",
        "of_ok": "تم الاتفاق على السعر", "of_final_done": "سيرى المشتري: السعر نهائي",
        "of_no": "تم إرسال الرفض", "of_no_refund": "تم إرسال الرفض، وأُعيد التأمين إلى المشتري",
        "req_title": "طلبات قريبة", "req_sub": "طلبات العملاء القريبة في تخصصك — كن أول من يرد",
        "req_filter_new": "جديدة",
        "req_empty_new": "لا توجد طلبات جديدة بعد.\nستظهر هنا طلبات العملاء القريبة في تخصصك.",
        "req_empty_all": "لا توجد طلبات بعد.", "req_taxi": "تاكسي", "req_route": "المسار", "req_find_addr": "إيجاد العنوان",
        "req_new": "جديد", "req_verified": "موثّق", "req_master": "الحِرَفي", "req_client": "العميل",
        "req_by_your_ad": "بخصوص إعلانك", "req_you_responded": "لقد رددت", "req_open_chat": "فتح المحادثة",
        "req_waiting_client": "بانتظار اختيار العميل · الردود: ", "req_respond": "رد",
        "req_report_hide": "إبلاغ / إخفاء", "req_hide": "إخفاء", "req_order_yours": "الطلب لك",
        "req_you_chosen": "تم اختيارك", "req_confirmed": "مؤكَّد", "req_assigned": "مُسنَد",
        "req_accept_order": "قبول الطلب", "req_call": "اتصال", "req_taken": "الطلب مأخوذ",
        "req_expired": "انتهى الوقت", "req_toast_responded": "تم إرسال الرد — تواصل في «الدردشة»",
        "req_toast_pinned": "تم الإسناد! بانتظار تأكيد الحِرَفي",
        "req_toast_accepted": "تم قبول الطلب — الصفقة مؤكدة", "req_deal_confirmed": "الصفقة مؤكدة",
        "req_err_closed": "الطلب مغلق بالفعل", "req_err_cap": "الردود كافية",
        "req_err_expired": "انتهى وقت الطلب", "req_err_notyou": "الطلب ليس لك",
        "req_err_notclient": "الإسناد متاح للعميل فقط", "req_err_nomaster": "الحِرَفي غير موجود",
        "req_pin_title": "إسناد الطلب إلى هذا الحِرَفي؟",
        "req_pin_text": "سيُسند الطلب إلى هذا الحِرَفي، وسيفقد الحِرَفيون الآخرون الوصول إليه.",
        "req_pin_btn": "إسناد", "req_closed_title": "الطلب لم يعد نشطًا",
        "req_closed_text": "انتهى وقت الطلب (5 دقائق) أو تم إسناده إلى حِرَفي آخر.",
        "req_accept_title": "قبول الطلب؟", "req_accept_text": "أكّد أنك تتولى هذا الطلب.",
        "req_accept_ok": "قبول", "req_svc_done": "أنجز {d} من {t}", "req_deals_n": "%ld صفقات",
        "req_left_a11y": "المتبقي %@",
        "dm_deal_confirmed": "الصفقة مؤكدة", "dm_accept_order": "قبول الطلب",
        "dm_wait_master": "بانتظار تأكيد الحِرَفي…", "dm_client_chose": "اختار العميل هذا الحِرَفي",
        "dm_master_selected": "تم اختيار المنفّذ", "dm_pin_master": "إسناد إلى الحِرَفي",
        "ago_now": "الآن", "ago_min": "منذ %ld دقيقة", "ago_h": "منذ %ld ساعة",
        "fb_title": "هل تمت الصفقة؟", "fb_text": "الطلب «%@» · مع %@", "fb_master": "الحِرَفي",
        "fb_comment": "تعليق (اختياري) — تراه الإدارة", "fb_no": "لا", "fb_yes": "نعم، كل شيء جيد",
        "fb_thanks": "شكرًا على تقييمك!", "fb_passed": "شكرًا، أبلغنا الإدارة",
        "notif_title": "الإشعارات", "cab_help": "مركز المساعدة",
        "sup_title": "طلب إلى الدعم", "sup_ph": "ردك…", "sup_staff": "الدعم", "sup_you": "أنت",
        "sup_empty": "لا توجد رسائل بعد", "sup_notfound": "الطلب غير موجود", "sup_st_new": "جديد",
        "sup_st_answered": "يوجد رد", "sup_st_waiting": "بانتظارك", "sup_st_closed": "مغلق",
        "sup_auth": "سجّل الدخول إلى حسابك",
        "dreq_title": "طلب البيانات",
        "dreq_subtitle": "تحتفظ خدمة الدعم بالمحادثات المحذوفة لمدة 12 شهرًا.\nسنحدد حسابك تلقائيًا — لا حاجة لإدخال اسم الدخول أو المعرّف.",
        "dreq_prefill": "أرجو إرسال بيانات محادثاتي.\nما أحتاجه: ", "dreq_submit": "إرسال الطلب",
        "dreq_sending": "جارٍ الإرسال…", "dreq_min_length": "صِف بتفصيل أكثر — 10 أحرف على الأقل",
        "dreq_success_msg": "تم استلام الطلب. الرقم: {id}. سيصل الرد في الدعم.",
        "dreq_success_toast": "تم إرسال الطلب", "dreq_error": "خطأ، حاول لاحقًا"
    ]
}
