import Foundation

/// Тексты «Что нового» (этап 16) на языке телефона (kk/ru/en/ar) — тем же способом, что лента (FeedText). Ключ пункта
/// списка — его id (ПунктНового), подпись под ним — id + "_sub". У просьбы оценить своих текстов нет: окно системное.
enum WhatsNewText {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь = тексты[язык] ?? тексты["ru"]!
        return словарь[ключ] ?? тексты["ru"]![ключ] ?? ключ
    }

    private static let тексты: [String: [String: String]] = [
        "ru": ["title": "Что нового", "version": "Версия %@", "ok": "Понятно", "row": "Что нового",
               "subtitle": "Лента, объявления и сообщения теперь открываются прямо в приложении — быстрее и без загрузки страниц сайта.",
               "feed": "Быстрая лента",
               "feed_sub": "Поиск, разделы и подгрузка без загрузки страниц. Без сети — последняя лента с телефона.",
               "card": "Карточка объявления",
               "card_sub": "Фото на весь экран, характеристики, продавец и похожие объявления из того же раздела.",
               "chat": "Сообщения",
               "chat_sub": "Переписка с продавцами — во вкладке «Сообщения», непрочитанные видно сразу.",
               "favorites": "Избранное",
               "favorites_sub": "Сердечко на карточке сохраняет объявление — все сохранённые в одном месте.",
               "recent": "Вы смотрели",
               "recent_sub": "Недавно открытые объявления — над лентой, прошлые запросы — под полем поиска.",
               "saved": "Сохранённые поиски",
               "saved_sub": "Нажмите колокольчик в ленте — и мы сообщим, когда по запросу появятся новые объявления.",
               "offline": "Без интернета",
               "offline_sub": "Избранное и недавно открытые объявления открываются и без связи.",
               "ipad": "Две колонки на iPad",
               "ipad_sub": "В широком окне лента и объявление — рядом.",
               "system": "Поиск iPhone и быстрые действия",
               "system_sub": "Открытые объявления находятся в поиске iPhone, а долгое нажатие на иконку ведёт к поиску, сообщениям и избранному.",
               "theme": "Тёмная тема",
               "theme_sub": "Светлая, тёмная или как в iPhone — в кабинете, раздел «Оформление».",
               "cabinet": "Кабинет",
               "cabinet_sub": "Вход по Face ID, уведомления и данные на телефоне — в одном месте."],
        "kk": ["title": "Не жаңалық", "version": "Нұсқа %@", "ok": "Түсінікті", "row": "Не жаңалық",
               "subtitle": "Лента, хабарландырулар мен хабарламалар енді тікелей қосымшада ашылады — жылдамырақ және сайт беттерін жүктемей.",
               "feed": "Жылдам лента",
               "feed_sub": "Іздеу, бөлімдер және жүктеу беттерді жүктемей. Желі болмаса — телефондағы соңғы лента.",
               "card": "Хабарландыру карточкасы",
               "card_sub": "Толық экранды фото, сипаттамалар, сатушы және сол бөлімдегі ұқсас хабарландырулар.",
               "chat": "Хабарламалар",
               "chat_sub": "Сатушылармен хат алмасу — «Хабарламалар» қойындысында, оқылмағандары бірден көрінеді.",
               "favorites": "Таңдаулылар",
               "favorites_sub": "Карточкадағы жүрекше хабарландыруды сақтайды — сақталғандардың бәрі бір жерде.",
               "recent": "Сіз қарағандар",
               "recent_sub": "Жақында ашылған хабарландырулар — лента үстінде, бұрынғы сұраулар — іздеу өрісінің астында.",
               "saved": "Сақталған іздеулер",
               "saved_sub": "Лентадағы қоңыраушаны басыңыз — сұрау бойынша жаңа хабарландырулар шыққанда хабарлаймыз.",
               "offline": "Интернетсіз",
               "offline_sub": "Таңдаулылар мен жақында ашылған хабарландырулар байланыссыз да ашылады.",
               "ipad": "iPad-та екі баған",
               "ipad_sub": "Кең терезеде лента мен хабарландыру қатар тұрады.",
               "system": "iPhone іздеуі және жылдам әрекеттер",
               "system_sub": "Ашылған хабарландырулар iPhone іздеуінде табылады, ал белгішені басып ұстасаңыз — іздеу, хабарламалар және таңдаулылар.",
               "theme": "Қараңғы тақырып",
               "theme_sub": "Ашық, қараңғы немесе iPhone-дағыдай — кабинеттегі «Сыртқы түрі» бөлімінде.",
               "cabinet": "Кабинет",
               "cabinet_sub": "Face ID арқылы кіру, push-хабарландырулар және телефондағы деректер — бір жерде."],
        "en": ["title": "What's new", "version": "Version %@", "ok": "Got it", "row": "What's new",
               "subtitle": "The feed, listings and messages now open right in the app — faster, without loading website pages.",
               "feed": "Faster feed",
               "feed_sub": "Search, categories and scrolling without page loads. Offline, you see the last feed saved on your phone.",
               "card": "Listing details",
               "card_sub": "Full-screen photos, specifications, the seller and similar listings from the same category.",
               "chat": "Messages",
               "chat_sub": "Chat with sellers in the Messages tab and see unread messages at a glance.",
               "favorites": "Favorites",
               "favorites_sub": "Tap the heart on a listing to save it — everything you saved in one place.",
               "recent": "Recently viewed",
               "recent_sub": "Listings you opened appear above the feed, and past searches below the search field.",
               "saved": "Saved searches",
               "saved_sub": "Tap the bell in the feed and we'll notify you when new listings match your search.",
               "offline": "Works offline",
               "offline_sub": "Favorites and recently opened listings open even without a connection.",
               "ipad": "Two columns on iPad",
               "ipad_sub": "In a wide window, the feed and the listing sit side by side.",
               "system": "iPhone Search and quick actions",
               "system_sub": "Listings you opened show up in iPhone Search, and touching and holding the app icon takes you to search, messages or favorites.",
               "theme": "Dark mode",
               "theme_sub": "Light, dark or matching your iPhone — in Account, under Appearance.",
               "cabinet": "Account",
               "cabinet_sub": "Face ID sign-in, notifications and data on this phone — all in one place."],
        "ar": ["title": "ما الجديد", "version": "الإصدار %@", "ok": "حسنًا", "row": "ما الجديد",
               "subtitle": "الإعلانات والرسائل تُفتح الآن داخل التطبيق مباشرة — أسرع ومن دون تحميل صفحات الموقع.",
               "feed": "إعلانات أسرع",
               "feed_sub": "البحث والأقسام والتحميل المتواصل من دون تحميل الصفحات. ومن دون اتصال — آخر إعلانات محفوظة على الهاتف.",
               "card": "صفحة الإعلان",
               "card_sub": "صور بملء الشاشة والمواصفات والبائع وإعلانات مشابهة من القسم نفسه.",
               "chat": "الرسائل",
               "chat_sub": "راسل البائعين في تبويب «الرسائل» وشاهد الرسائل غير المقروءة فورًا.",
               "favorites": "المفضلة",
               "favorites_sub": "اضغط على القلب في الإعلان لحفظه — كل ما حفظته في مكان واحد.",
               "recent": "شوهدت مؤخرًا",
               "recent_sub": "الإعلانات التي فتحتها مؤخرًا فوق الإعلانات، وعمليات البحث السابقة تحت حقل البحث.",
               "saved": "عمليات البحث المحفوظة",
               "saved_sub": "اضغط على الجرس في الإعلانات وسنُعلمك عند ظهور إعلانات جديدة تطابق بحثك.",
               "offline": "من دون إنترنت",
               "offline_sub": "تُفتح المفضلة والإعلانات التي فتحتها مؤخرًا حتى من دون اتصال.",
               "ipad": "عمودان على iPad",
               "ipad_sub": "في النافذة العريضة تظهر الإعلانات والإعلان المختار جنبًا إلى جنب.",
               "system": "بحث iPhone والإجراءات السريعة",
               "system_sub": "تظهر الإعلانات التي فتحتها في بحث iPhone، والضغط المطوّل على أيقونة التطبيق يأخذك إلى البحث أو الرسائل أو المفضلة.",
               "theme": "الوضع الداكن",
               "theme_sub": "فاتح أو داكن أو حسب iPhone — في الحساب، قسم «المظهر».",
               "cabinet": "الحساب",
               "cabinet_sub": "الدخول باستخدام Face ID والإشعارات والبيانات على هذا الهاتف — في مكان واحد."]
    ]
}
