import Foundation

/// Тексты «Что нового» (этап 16) на языке телефона (kk/ru/en/ar) — тем же способом, что лента (FeedText). Ключ пункта
/// списка — его id (ПунктНового), подпись под ним — id + "_sub". У просьбы оценить своих текстов нет: окно системное.
enum WhatsNewText {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь = тексты[язык] ?? тексты["ru"]!
        return словарь[ключ] ?? версии[язык]?[ключ] ?? тексты["ru"]![ключ] ?? версии["ru"]?[ключ] ?? ключ
    }

    /// Пункты по версиям (ПунктНового.новоеВерсии) и подписи разделов листа. Отдельно от общего словаря — чтобы
    /// новая версия добавляла свои строки, не трогая прежние.
    private static let версии: [String: [String: String]] = [
        "ru": ["new_head": "В версии %@", "also_head": "Также в приложении",
               "v111_filters": "Фильтры как на сайте",
               "v111_filters_sub": "У каждого раздела свои фильтры, вверху — выбор раздела и подразделов, внизу — «Показать N».",
               "v111_qr": "QR-код объявления",
               "v111_qr_sub": "«Поделиться» → «QR-код»: покажите с экрана или распечатайте — камера сразу откроет объявление.",
               "v111_speed": "Быстрая лента",
               "v111_speed_sub": "Стартовые данные встроены в приложение: лента и кабинет открываются сразу, длинная лента не тормозит.",
               "v111_delivery": "«Доставка из города»",
               "v111_delivery_sub": "Только когда товар в другом городе. СДЭК не посчитал доставку — сразу «Заберу сам» или «Написать продавцу».",
               "v111_guarantee": "Гарант-ссылки партнёров",
               "v111_guarantee_sub": "Ссылка на безопасную сделку от партнёра открывается окном в приложении.",
               "v111_city": "Город в ссылках",
               "v111_city_sub": "Ссылки каталога и вакансий с городом открываются сразу с объявлениями этого места."],
        "kk": ["new_head": "%@ нұсқасында", "also_head": "Қосымшада тағы",
               "v111_filters": "Сайттағыдай сүзгілер",
               "v111_filters_sub": "Әр бөлімнің өз сүзгілері, жоғарыда — бөлім мен ішкі бөлімдерді таңдау, төменде — «N көрсету».",
               "v111_qr": "Хабарландырудың QR-коды",
               "v111_qr_sub": "«Бөлісу» → «QR-код»: экраннан көрсетіңіз не басып шығарыңыз — камера хабарландыруды бірден ашады.",
               "v111_speed": "Жылдам лента",
               "v111_speed_sub": "Бастапқы деректер қосымшаға енгізілген: лента мен кабинет бірден ашылады, ұзын лента баяуламайды.",
               "v111_delivery": "«Қаладан жеткізу»",
               "v111_delivery_sub": "Тек тауар басқа қалада болса. СДЭК есептей алмаса — бірден «Өзім аламын» не «Сатушыға жазу».",
               "v111_guarantee": "Серіктестердің кепіл-сілтемелері",
               "v111_guarantee_sub": "Серіктестің қауіпсіз мәміле сілтемесі қосымшада терезе болып ашылады.",
               "v111_city": "Сілтемелердегі қала",
               "v111_city_sub": "Қаласы бар каталог пен вакансия сілтемелері бірден сол жердің хабарландыруларымен ашылады."],
        "en": ["new_head": "In version %@", "also_head": "Also in the app",
               "v111_filters": "Filters like on the website",
               "v111_filters_sub": "Each section has its own filters, with section and subsection choice on top and “Show N” at the bottom.",
               "v111_qr": "Listing QR code",
               "v111_qr_sub": "Share → QR code: show it on screen or print it — a camera opens the listing right away.",
               "v111_speed": "Faster feed",
               "v111_speed_sub": "Starter data is built into the app: the feed and profile open instantly, long feeds stay smooth.",
               "v111_delivery": "“Delivery from the city”",
               "v111_delivery_sub": "Only when the item is in another city. If CDEK can’t quote — “I’ll pick it up” or “Message the seller”.",
               "v111_guarantee": "Partner guarantee links",
               "v111_guarantee_sub": "A partner’s safe-deal link opens in a window inside the app.",
               "v111_city": "City in links",
               "v111_city_sub": "Catalog and job links with a city open straight to listings from that place."],
        "ar": ["new_head": "في الإصدار %@", "also_head": "وأيضًا في التطبيق",
               "v111_filters": "فلاتر كما في الموقع",
               "v111_filters_sub": "لكل قسم فلاتره، وفي الأعلى اختيار القسم والأقسام الفرعية، وفي الأسفل «عرض N».",
               "v111_qr": "رمز QR للإعلان",
               "v111_qr_sub": "«مشاركة» ← «رمز QR»: اعرضه على الشاشة أو اطبعه — تفتح الكاميرا الإعلان فورًا.",
               "v111_speed": "خلاصة أسرع",
               "v111_speed_sub": "البيانات الأولية مدمجة في التطبيق: تُفتح الخلاصة والملف الشخصي فورًا، والخلاصة الطويلة لا تتباطأ.",
               "v111_delivery": "«التوصيل من المدينة»",
               "v111_delivery_sub": "فقط عندما تكون السلعة في مدينة أخرى. إن لم يحسب CDEK التوصيل — «سأستلمه بنفسي» أو «راسل البائع».",
               "v111_guarantee": "روابط الضمان من الشركاء",
               "v111_guarantee_sub": "يُفتح رابط الصفقة الآمنة من الشريك في نافذة داخل التطبيق.",
               "v111_city": "المدينة في الروابط",
               "v111_city_sub": "روابط الكتالوج والوظائف مع المدينة تفتح مباشرة على إعلانات ذلك المكان."]
    ]

    /// Подпись шапки (subtitle) — без названий возможностей (исправление после ревью, владелец 25.09.2026): шапку видно
    /// всегда, а пункты под ней — только по рубильникам (ПунктНового.список). Назови она карточку или сообщения, при
    /// выключенном рубильнике лист обещал бы то, чего нет.
    private static let тексты: [String: [String: String]] = [
        "ru": ["title": "Что нового", "version": "Версия %@", "ok": "Понятно", "row": "Что нового",
               "subtitle": "Приложение теперь многое умеет само — быстрее и без загрузки страниц сайта.",
               "feed": "Быстрая лента",
               "feed_sub": "Поиск, разделы и подгрузка без загрузки страниц. Без сети — последняя лента с телефона.",
               "card": "Карточка объявления",
               "card_sub": "Фото на весь экран, характеристики, продавец и похожие объявления из того же раздела.",
               "chat": "Сообщения",
               "chat_sub": "Переписка с продавцами — во вкладке «Сообщения», непрочитанные видно сразу.",
               "favorites": "Избранное",
               "favorites_sub": "Сердечко на карточке сохраняет объявление — все сохранённые в одном месте.",
               "recent": "Вы смотрели",
               "recent_sub": "Недавно открытые объявления — над лентой, прошлые запросы — под полем поиска.",
               "saved": "Сохранённые поиски",
               "saved_sub": "Нажмите колокольчик в ленте — и мы сообщим, когда по запросу появятся новые объявления.",
               "offline": "Без интернета",
               "offline_sub": "Избранное и недавно открытые объявления открываются и без связи.",
               "ipad": "Две колонки на iPad",
               "ipad_sub": "В широком окне лента и объявление — рядом.",
               "system": "Поиск iPhone и быстрые действия",
               "system_sub": "Открытые объявления находятся в поиске iPhone, а долгое нажатие на иконку ведёт к поиску, сообщениям и избранному.",
               "theme": "Тёмная тема",
               "theme_sub": "Светлая, тёмная или как в iPhone — в профиле, раздел «Оформление».",
               "cabinet": "Профиль",
               "cabinet_sub": "Вход по Face ID, уведомления и данные на телефоне — в одном месте."],
        "kk": ["title": "Не жаңалық", "version": "Нұсқа %@", "ok": "Түсінікті", "row": "Не жаңалық",
               "subtitle": "Қосымша енді көп нәрсені өзі істейді — жылдамырақ және сайт беттерін жүктемей.",
               "feed": "Жылдам лента",
               "feed_sub": "Іздеу, бөлімдер және жүктеу беттерді жүктемей. Желі болмаса — телефондағы соңғы лента.",
               "card": "Хабарландыру карточкасы",
               "card_sub": "Толық экранды фото, сипаттамалар, сатушы және сол бөлімдегі ұқсас хабарландырулар.",
               "chat": "Хабарламалар",
               "chat_sub": "Сатушылармен хат алмасу — «Хабарламалар» қойындысында, оқылмағандары бірден көрінеді.",
               "favorites": "Таңдаулылар",
               "favorites_sub": "Карточкадағы жүрекше хабарландыруды сақтайды — сақталғандардың бәрі бір жерде.",
               "recent": "Сіз қарағандар",
               "recent_sub": "Жақында ашылған хабарландырулар — лента үстінде, бұрынғы сұраулар — іздеу өрісінің астында.",
               "saved": "Сақталған іздеулер",
               "saved_sub": "Лентадағы қоңыраушаны басыңыз — сұрау бойынша жаңа хабарландырулар шыққанда хабарлаймыз.",
               "offline": "Интернетсіз",
               "offline_sub": "Таңдаулылар мен жақында ашылған хабарландырулар байланыссыз да ашылады.",
               "ipad": "iPad-та екі баған",
               "ipad_sub": "Кең терезеде лента мен хабарландыру қатар тұрады.",
               "system": "iPhone іздеуі және жылдам әрекеттер",
               "system_sub": "Ашылған хабарландырулар iPhone іздеуінде табылады, ал белгішені басып ұстасаңыз — іздеу, хабарламалар және таңдаулылар.",
               "theme": "Қараңғы тақырып",
               "theme_sub": "Ашық, қараңғы немесе iPhone-дағыдай — профильдегі «Сыртқы түрі» бөлімінде.",
               "cabinet": "Профиль",
               "cabinet_sub": "Face ID арқылы кіру, push-хабарландырулар және телефондағы деректер — бір жерде."],
        "en": ["title": "What's new", "version": "Version %@", "ok": "Got it", "row": "What's new",
               "subtitle": "The app now does a lot more on its own — faster, without loading website pages.",
               "feed": "Faster feed",
               "feed_sub": "Search, categories and scrolling without page loads. Offline, you see the last feed saved on your phone.",
               "card": "Listing details",
               "card_sub": "Full-screen photos, specifications, the seller and similar listings from the same category.",
               "chat": "Messages",
               "chat_sub": "Chat with sellers in the Messages tab and see unread messages at a glance.",
               "favorites": "Favorites",
               "favorites_sub": "Tap the heart on a listing to save it — everything you saved in one place.",
               "recent": "Recently viewed",
               "recent_sub": "Listings you opened appear above the feed, and past searches below the search field.",
               "saved": "Saved searches",
               "saved_sub": "Tap the bell in the feed and we'll notify you when new listings match your search.",
               "offline": "Works offline",
               "offline_sub": "Favorites and recently opened listings open even without a connection.",
               "ipad": "Two columns on iPad",
               "ipad_sub": "In a wide window, the feed and the listing sit side by side.",
               "system": "iPhone Search and quick actions",
               "system_sub": "Listings you opened show up in iPhone Search, and touching and holding the app icon takes you to search, messages or favorites.",
               "theme": "Dark mode",
               "theme_sub": "Light, dark or matching your iPhone — in Profile, under Appearance.",
               "cabinet": "Profile",
               "cabinet_sub": "Face ID sign-in, notifications and data on this phone — all in one place."],
        "ar": ["title": "ما الجديد", "version": "الإصدار %@", "ok": "حسنًا", "row": "ما الجديد",
               "subtitle": "أصبح التطبيق يؤدي الكثير بنفسه الآن — أسرع ومن دون تحميل صفحات الموقع.",
               "feed": "إعلانات أسرع",
               "feed_sub": "البحث والأقسام والتحميل المتواصل من دون تحميل الصفحات. ومن دون اتصال — آخر إعلانات محفوظة على الهاتف.",
               "card": "صفحة الإعلان",
               "card_sub": "صور بملء الشاشة والمواصفات والبائع وإعلانات مشابهة من القسم نفسه.",
               "chat": "الرسائل",
               "chat_sub": "راسل البائعين في تبويب «الرسائل» وشاهد الرسائل غير المقروءة فورًا.",
               "favorites": "المفضلة",
               "favorites_sub": "اضغط على القلب في الإعلان لحفظه — كل ما حفظته في مكان واحد.",
               "recent": "شوهدت مؤخرًا",
               "recent_sub": "الإعلانات التي فتحتها مؤخرًا فوق الإعلانات، وعمليات البحث السابقة تحت حقل البحث.",
               "saved": "عمليات البحث المحفوظة",
               "saved_sub": "اضغط على الجرس في الإعلانات وسنُعلمك عند ظهور إعلانات جديدة تطابق بحثك.",
               "offline": "من دون إنترنت",
               "offline_sub": "تُفتح المفضلة والإعلانات التي فتحتها مؤخرًا حتى من دون اتصال.",
               "ipad": "عمودان على iPad",
               "ipad_sub": "في النافذة العريضة تظهر الإعلانات والإعلان المختار جنبًا إلى جنب.",
               "system": "بحث iPhone والإجراءات السريعة",
               "system_sub": "تظهر الإعلانات التي فتحتها في بحث iPhone، والضغط المطوّل على أيقونة التطبيق يأخذك إلى البحث أو الرسائل أو المفضلة.",
               "theme": "الوضع الداكن",
               "theme_sub": "فاتح أو داكن أو حسب iPhone — في الملف الشخصي، قسم «المظهر».",
               "cabinet": "الملف الشخصي",
               "cabinet_sub": "الدخول باستخدام Face ID والإشعارات والبيانات على هذا الهاتف — في مكان واحد."]
    ]
}
