import Foundation

/**
 Тексты бизнес-разделов (этап 50): аналитика, журнал счетов, счета и заказы B2B, коммерческие предложения, разделы
 магазина — на языке телефона (kk/ru/en/ar).

 Русские — слово в слово с сайта: словарь js/i18n-cabinet-ru.js (an_…, jrn_…, b2b_…, kp_…, inv_…, sec_… и shopsec_…) и
 фразы, зашитые в js/cabinet-business.min.js (_jrnEv, docs: «Акт», «Накладная», «Договор», «Доверенность»), периоды
 журнала — как в разметке #jrn-period страницы кабинета («Год 2026», «I полугодие 2026», «Квартал 1 2026»). Свои слова
 приложения — подписи графиков, «Поделиться», «Нужен тариф PRO» и VoiceOver. Нет ключа здесь — берётся из БизнесText.
 */
enum БизнесРазделыText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[БизнесText.язык] ?? ru
        if let текст = словарь[ключ] ?? ru[ключ] { return текст }
        return БизнесText.т(ключ)
    }

    static func т(_ ключ: String, _ замены: [String: String]) -> String {
        var итог = т(ключ)
        for (имя, значение) in замены {
            итог = итог.replacingOccurrences(of: "{" + имя + "}", with: значение)
        }
        return итог
    }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    // MARK: - Русский (сайт)

    private static let ru: [String: String] = [
        // Аналитика (renderAnalytics)
        "an_title": "Аналитика магазина",
        "an_sub": "Просмотры, сделки, выручка и топ-товары",
        "an_views": "Просмотры",
        "an_active_listings": "{n} активных объявлений",
        "an_deals": "Сделки",
        "an_in_progress": "{n} в процессе",
        "an_total": "всего {n}",
        "an_revenue": "Выручка",
        "an_revenue_sub": "по завершённым сделкам",
        "an_conversion": "Конверсия",
        "an_conv_sub": "сделок к просмотрам",
        "an_rating": "Рейтинг",
        "an_reviews": "{n} отзывов",
        "an_top_views": "Топ по просмотрам",
        "an_no_data": "Пока нет данных по просмотрам",
        "an_opt": "ОПТ",
        "an_deals_chart": "Сделки по статусу",
        "an_done": "Завершены",
        "an_progress": "В процессе",
        "an_other": "Остальные",
        "err_load": "Ошибка загрузки",
        "pro_need": "Доступно в тарифе PRO",
        "pro_need_s": "Расширенная аналитика, разделы магазина и коммерческие предложения — инструменты тарифа PRO.",
        // Журнал (jrnRender, jrnLogRender, _jrnEv)
        "jrn_title": "Журнал счетов",
        "jrn_sub": "Все счета за период по порядку номеров — для сверки с банком и для отчёта. Отменённые остаются в списке, но в доход не идут.",
        "jrn_v_inv": "Счета",
        "jrn_v_stock": "Склад",
        "jrn_v_log": "Действия",
        "jrn_period": "Период",
        "jrn_year": "Год {y}",
        "jrn_h1": "I полугодие {y}",
        "jrn_h2": "II полугодие {y}",
        "jrn_q": "Квартал {q} {y}",
        "jrn_issued": "Выписано",
        "jrn_paid": "Проведено (доход)",
        "jrn_vat": "НДС с продаж",
        "jrn_cancelled": "Отменено",
        "jrn_empty": "За этот период счетов не было",
        "jrn_log_empty": "За этот период записей нет",
        "jrn_paid_at": "оплата ",
        "jrn_incl_vat": "НДС ",
        "jrn_chart": "Счета по месяцам",
        "jrn_e_reserve": "отложено под счёт",
        "jrn_e_release": "возвращено на склад",
        "jrn_e_manual": "правка остатка",
        "jrn_e_issued": "счёт выписан",
        "jrn_e_opened": "документ открыт получателем",
        "share_doc": "Поделиться счётом",
        // Счета и заказы B2B (_b2bRow, b2bStatus, invLoad)
        "inv_title": "Счета и заказы",
        "b2b_orders_in": "Заказы от покупателей",
        "b2b_orders_out": "Мои заказы у поставщиков",
        "b2b_no_incoming": "Входящих заказов пока нет",
        "b2b_no_mine": "Вы ещё не оформляли заказов",
        "b2b_buyer_word": "Покупатель",
        "b2b_supplier": "Поставщик",
        "b2b_guest_tag": "Без регистрации",
        "b2b_until": "до",
        "b2b_confirm": "Подтвердить",
        "b2b_mark_paid": "Оплата пришла",
        "b2b_ship": "Отгрузить",
        "b2b_finish": "Завершить",
        "b2b_cancel": "Отменить",
        "b2b_cancel_q": "Отменить счёт",
        "b2b_cancel_yes": "Да, отменить",
        "b2b_cancel_no": "Не надо",
        "b2b_cancel_h": "Вторая сторона увидит, что счёт отменён. Зарезервированный под него товар вернётся на склад. Вернуть отмену нельзя — выпишите новый счёт.",
        "b2b_status_updated": "Статус обновлён",
        "b2b_st_new": "новый",
        "b2b_st_confirmed": "ждём оплату",
        "b2b_st_paid": "оплачен",
        "b2b_st_shipped": "отгружен",
        "b2b_st_done": "завершён",
        "b2b_st_cancelled": "отменён",
        "inv_received_lbl": "Полученные счета",
        "doc_t_invoice": "Счёт",
        "doc_t_act": "Акт",
        "doc_t_waybill": "Накладная",
        "doc_t_contract": "Договор",
        "doc_t_poa": "Доверенность",
        "doc_t_pricelist": "Прайс-лист",
        "docs_on_site": "Печать счёта, накладной, акта и счёт-фактуры — в кабинете на сайте.",
        "open_site_docs": "Документы на сайте",
        // КП (kpLoad, kpCardIncoming, kpOpenGen, kpGen, kpSend, kpDecline)
        "kp_title": "Предложения покупателям",
        "kp_sub": "Покупатель просит расчёт — вы отправляете предложение с ценами",
        "kp_incoming": "Входящие запросы",
        "kp_sent_lbl": "Отправленные",
        "kp_received_lbl": "Полученные КП",
        "kp_none_incoming": "Пока нет запросов",
        "kp_generate_btn": "Сформировать КП",
        "kp_decline": "Отклонить",
        "kp_decline_confirm": "Отклонить запрос КП?",
        "kp_decline_ok": "Отклонить",
        "kp_status_sent": "Отправлено",
        "kp_status_declined": "Отклонено",
        "kp_from_seller": "Продавец",
        "kp_gen_title": "Коммерческое предложение",
        "kp_for": "Для",
        "kp_tpl_formal": "Шаблон: формальный",
        "kp_tpl_short": "Шаблон: краткий",
        "kp_ai_btn": "Kliko AI-генерация",
        "kp_ai_left": "Kliko AI-генераций сегодня",
        "kp_gen_ph": "Выберите шаблон или Kliko AI — текст появится здесь, его можно отредактировать.",
        "kp_send_btn": "Отправить покупателю",
        "kp_ai_wait": "Kliko AI пишет предложение…",
        "kp_empty": "Сначала сформируйте текст КП",
        "kp_sent_ok": "КП отправлено покупателю",
        "kp_need_company": "Чтобы сформировать КП, заполните реквизиты компании — название и БИН.",
        "kp_need_pro": "Формирование КП доступно только PRO-магазинам.",
        "cmp_items_total": "Итого:",
        "kp_share": "Поделиться текстом",
        // Разделы магазина (shopSecOpen, shopSecSave)
        "sec_title": "Разделы магазина",
        "sec_help": "Создайте свои разделы каталога — покупатель фильтрует товары по ним прямо на витрине магазина.",
        "sec_add": "Добавить раздел",
        "sec_name_ph": "Название раздела",
        "sec_empty": "Пока нет разделов — добавьте первый.",
        "sec_max": "Максимум 40 разделов",
        "sec_saved": "Разделы сохранены",
        "save": "Сохранить",
        "delete": "Удалить",
        "a11y_up": "Выше",
        "a11y_down": "Ниже",
    ]

    // MARK: - Қазақша

    private static let kk: [String: String] = [
        "an_title": "Дүкен аналитикасы",
        "an_sub": "Қаралымдар, мәмілелер, түсім және үздік тауарлар",
        "an_views": "Қаралымдар",
        "an_active_listings": "{n} белсенді хабарландыру",
        "an_deals": "Мәмілелер",
        "an_in_progress": "{n} орындалуда",
        "an_total": "барлығы {n}",
        "an_revenue": "Түсім",
        "an_revenue_sub": "аяқталған мәмілелер бойынша",
        "an_conversion": "Конверсия",
        "an_conv_sub": "мәмілелердің қаралымдарға қатынасы",
        "an_rating": "Рейтинг",
        "an_reviews": "{n} пікір",
        "an_top_views": "Қаралым бойынша үздіктер",
        "an_no_data": "Қаралымдар туралы дерек әзірге жоқ",
        "an_opt": "КӨТЕРМЕ",
        "an_deals_chart": "Мәмілелер мәртебе бойынша",
        "an_done": "Аяқталды",
        "an_progress": "Орындалуда",
        "an_other": "Қалғандары",
        "err_load": "Жүктеу қатесі",
        "pro_need": "PRO тарифінде қолжетімді",
        "pro_need_s": "Кеңейтілген аналитика, дүкен бөлімдері және коммерциялық ұсыныстар — PRO тарифінің құралдары.",
        "jrn_title": "Шоттар журналы",
        "jrn_sub": "Кезеңдегі барлық шот нөмір ретімен — банкпен салыстыру мен есеп үшін. Жойылғандары тізімде қалады, бірақ табысқа кірмейді.",
        "jrn_v_inv": "Шоттар",
        "jrn_v_stock": "Қойма",
        "jrn_v_log": "Әрекеттер",
        "jrn_period": "Кезең",
        "jrn_year": "{y} жыл",
        "jrn_h1": "{y}, I жартыжылдық",
        "jrn_h2": "{y}, II жартыжылдық",
        "jrn_q": "{y}, {q}-тоқсан",
        "jrn_issued": "Жазылды",
        "jrn_paid": "Өткізілді (табыс)",
        "jrn_vat": "Сатудан ҚҚС",
        "jrn_cancelled": "Жойылды",
        "jrn_empty": "Бұл кезеңде шот болмады",
        "jrn_log_empty": "Бұл кезеңде жазба жоқ",
        "jrn_paid_at": "төлем ",
        "jrn_incl_vat": "ҚҚС ",
        "jrn_chart": "Айлар бойынша шоттар",
        "jrn_e_reserve": "шотқа сақталды",
        "jrn_e_release": "қоймаға қайтарылды",
        "jrn_e_manual": "қалдық түзетілді",
        "jrn_e_issued": "шот жазылды",
        "jrn_e_opened": "құжатты алушы ашты",
        "share_doc": "Шотпен бөлісу",
        "inv_title": "Шоттар мен тапсырыстар",
        "b2b_orders_in": "Сатып алушылардың тапсырыстары",
        "b2b_orders_out": "Жеткізушілердегі тапсырыстарым",
        "b2b_no_incoming": "Кіріс тапсырыстар әзірге жоқ",
        "b2b_no_mine": "Сіз әлі тапсырыс бермедіңіз",
        "b2b_buyer_word": "Сатып алушы",
        "b2b_supplier": "Жеткізуші",
        "b2b_guest_tag": "Тіркелусіз",
        "b2b_until": "дейін",
        "b2b_confirm": "Растау",
        "b2b_mark_paid": "Төлем түсті",
        "b2b_ship": "Жөнелту",
        "b2b_finish": "Аяқтау",
        "b2b_cancel": "Жою",
        "b2b_cancel_q": "Шотты жою",
        "b2b_cancel_yes": "Иә, жою",
        "b2b_cancel_no": "Керек емес",
        "b2b_cancel_h": "Екінші тарап шоттың жойылғанын көреді. Оған сақталған тауар қоймаға қайтады. Жоюды қайтару мүмкін емес — жаңа шот жазыңыз.",
        "b2b_status_updated": "Мәртебе жаңартылды",
        "b2b_st_new": "жаңа",
        "b2b_st_confirmed": "төлем күтілуде",
        "b2b_st_paid": "төленді",
        "b2b_st_shipped": "жөнелтілді",
        "b2b_st_done": "аяқталды",
        "b2b_st_cancelled": "жойылды",
        "inv_received_lbl": "Алынған шоттар",
        "doc_t_invoice": "Шот",
        "doc_t_act": "Акт",
        "doc_t_waybill": "Жүкқұжат",
        "doc_t_contract": "Шарт",
        "doc_t_poa": "Сенімхат",
        "doc_t_pricelist": "Баға парағы",
        "docs_on_site": "Шотты, жүкқұжатты, актіні және шот-фактураны басып шығару — сайттағы кабинетте.",
        "open_site_docs": "Сайттағы құжаттар",
        "kp_title": "Сатып алушыларға ұсыныстар",
        "kp_sub": "Сатып алушы есеп сұрайды — сіз бағалары бар ұсыныс жібересіз",
        "kp_incoming": "Кіріс сұраулар",
        "kp_sent_lbl": "Жіберілгендер",
        "kp_received_lbl": "Алынған КҰ",
        "kp_none_incoming": "Сұраулар әзірге жоқ",
        "kp_generate_btn": "КҰ жасау",
        "kp_decline": "Бас тарту",
        "kp_decline_confirm": "КҰ сұрауынан бас тарту керек пе?",
        "kp_decline_ok": "Бас тарту",
        "kp_status_sent": "Жіберілді",
        "kp_status_declined": "Қабылданбады",
        "kp_from_seller": "Сатушы",
        "kp_gen_title": "Коммерциялық ұсыныс",
        "kp_for": "Кімге",
        "kp_tpl_formal": "Үлгі: ресми",
        "kp_tpl_short": "Үлгі: қысқа",
        "kp_ai_btn": "Kliko AI арқылы жасау",
        "kp_ai_left": "Бүгінгі Kliko AI генерациялары",
        "kp_gen_ph": "Үлгіні немесе Kliko AI-ды таңдаңыз — мәтін осында шығады, оны өзгертуге болады.",
        "kp_send_btn": "Сатып алушыға жіберу",
        "kp_ai_wait": "Kliko AI ұсыныс жазып жатыр…",
        "kp_empty": "Алдымен КҰ мәтінін жасаңыз",
        "kp_sent_ok": "КҰ сатып алушыға жіберілді",
        "kp_need_company": "КҰ жасау үшін компания деректемелерін — атауы мен БСН толтырыңыз.",
        "kp_need_pro": "КҰ жасау тек PRO дүкендерге қолжетімді.",
        "cmp_items_total": "Барлығы:",
        "kp_share": "Мәтінмен бөлісу",
        "sec_title": "Дүкен бөлімдері",
        "sec_help": "Каталогтың өз бөлімдерін жасаңыз — сатып алушы тауарларды дүкен витринасында солар бойынша сүзеді.",
        "sec_add": "Бөлім қосу",
        "sec_name_ph": "Бөлім атауы",
        "sec_empty": "Бөлімдер әзірге жоқ — біріншісін қосыңыз.",
        "sec_max": "Ең көбі 40 бөлім",
        "sec_saved": "Бөлімдер сақталды",
        "save": "Сақтау",
        "delete": "Жою",
        "a11y_up": "Жоғары",
        "a11y_down": "Төмен",
    ]

    // MARK: - English

    private static let en: [String: String] = [
        "an_title": "Store analytics",
        "an_sub": "Views, deals, revenue and top products",
        "an_views": "Views",
        "an_active_listings": "{n} active listings",
        "an_deals": "Deals",
        "an_in_progress": "{n} in progress",
        "an_total": "{n} in total",
        "an_revenue": "Revenue",
        "an_revenue_sub": "from completed deals",
        "an_conversion": "Conversion",
        "an_conv_sub": "deals to views",
        "an_rating": "Rating",
        "an_reviews": "{n} reviews",
        "an_top_views": "Top by views",
        "an_no_data": "No view data yet",
        "an_opt": "WHOLESALE",
        "an_deals_chart": "Deals by status",
        "an_done": "Completed",
        "an_progress": "In progress",
        "an_other": "Other",
        "err_load": "Loading error",
        "pro_need": "Available on the PRO plan",
        "pro_need_s": "Advanced analytics, store sections and commercial offers are PRO plan tools.",
        "jrn_title": "Invoice journal",
        "jrn_sub": "All invoices for the period in number order — for bank reconciliation and reporting. Cancelled ones stay in the list but don't count as income.",
        "jrn_v_inv": "Invoices",
        "jrn_v_stock": "Stock",
        "jrn_v_log": "Actions",
        "jrn_period": "Period",
        "jrn_year": "Year {y}",
        "jrn_h1": "H1 {y}",
        "jrn_h2": "H2 {y}",
        "jrn_q": "Q{q} {y}",
        "jrn_issued": "Issued",
        "jrn_paid": "Posted (income)",
        "jrn_vat": "Sales VAT",
        "jrn_cancelled": "Cancelled",
        "jrn_empty": "No invoices in this period",
        "jrn_log_empty": "No records in this period",
        "jrn_paid_at": "paid ",
        "jrn_incl_vat": "VAT ",
        "jrn_chart": "Invoices by month",
        "jrn_e_reserve": "reserved for an invoice",
        "jrn_e_release": "returned to stock",
        "jrn_e_manual": "stock adjusted",
        "jrn_e_issued": "invoice issued",
        "jrn_e_opened": "document opened by recipient",
        "share_doc": "Share invoice",
        "inv_title": "Invoices and orders",
        "b2b_orders_in": "Orders from buyers",
        "b2b_orders_out": "My orders from suppliers",
        "b2b_no_incoming": "No incoming orders yet",
        "b2b_no_mine": "You haven't placed any orders yet",
        "b2b_buyer_word": "Buyer",
        "b2b_supplier": "Supplier",
        "b2b_guest_tag": "No account",
        "b2b_until": "until",
        "b2b_confirm": "Confirm",
        "b2b_mark_paid": "Payment received",
        "b2b_ship": "Ship",
        "b2b_finish": "Complete",
        "b2b_cancel": "Cancel",
        "b2b_cancel_q": "Cancel the invoice",
        "b2b_cancel_yes": "Yes, cancel",
        "b2b_cancel_no": "Don't cancel",
        "b2b_cancel_h": "The other party will see the invoice was cancelled. Goods reserved for it return to stock. A cancellation can't be undone — issue a new invoice.",
        "b2b_status_updated": "Status updated",
        "b2b_st_new": "new",
        "b2b_st_confirmed": "awaiting payment",
        "b2b_st_paid": "paid",
        "b2b_st_shipped": "shipped",
        "b2b_st_done": "completed",
        "b2b_st_cancelled": "cancelled",
        "inv_received_lbl": "Received invoices",
        "doc_t_invoice": "Invoice",
        "doc_t_act": "Act",
        "doc_t_waybill": "Waybill",
        "doc_t_contract": "Contract",
        "doc_t_poa": "Power of attorney",
        "doc_t_pricelist": "Price list",
        "docs_on_site": "Printing invoices, waybills, acts and VAT invoices is in the cabinet on the website.",
        "open_site_docs": "Documents on the website",
        "kp_title": "Offers to buyers",
        "kp_sub": "A buyer asks for a quote — you send an offer with prices",
        "kp_incoming": "Incoming requests",
        "kp_sent_lbl": "Sent",
        "kp_received_lbl": "Received offers",
        "kp_none_incoming": "No requests yet",
        "kp_generate_btn": "Create offer",
        "kp_decline": "Decline",
        "kp_decline_confirm": "Decline the offer request?",
        "kp_decline_ok": "Decline",
        "kp_status_sent": "Sent",
        "kp_status_declined": "Declined",
        "kp_from_seller": "Seller",
        "kp_gen_title": "Commercial offer",
        "kp_for": "For",
        "kp_tpl_formal": "Template: formal",
        "kp_tpl_short": "Template: short",
        "kp_ai_btn": "Kliko AI generation",
        "kp_ai_left": "Kliko AI generations today",
        "kp_gen_ph": "Pick a template or Kliko AI — the text appears here and you can edit it.",
        "kp_send_btn": "Send to buyer",
        "kp_ai_wait": "Kliko AI is writing the offer…",
        "kp_empty": "Create the offer text first",
        "kp_sent_ok": "Offer sent to the buyer",
        "kp_need_company": "To create an offer, fill in your company details — name and BIN.",
        "kp_need_pro": "Creating offers is available only to PRO stores.",
        "cmp_items_total": "Total:",
        "kp_share": "Share text",
        "sec_title": "Store sections",
        "sec_help": "Create your own catalog sections — buyers filter products by them right in your storefront.",
        "sec_add": "Add section",
        "sec_name_ph": "Section name",
        "sec_empty": "No sections yet — add the first one.",
        "sec_max": "Up to 40 sections",
        "sec_saved": "Sections saved",
        "save": "Save",
        "delete": "Delete",
        "a11y_up": "Move up",
        "a11y_down": "Move down",
    ]

    // MARK: - العربية

    private static let ar: [String: String] = [
        "an_title": "تحليلات المتجر",
        "an_sub": "المشاهدات والصفقات والإيرادات وأفضل المنتجات",
        "an_views": "المشاهدات",
        "an_active_listings": "{n} إعلانات نشطة",
        "an_deals": "الصفقات",
        "an_in_progress": "{n} قيد التنفيذ",
        "an_total": "الإجمالي {n}",
        "an_revenue": "الإيرادات",
        "an_revenue_sub": "من الصفقات المكتملة",
        "an_conversion": "التحويل",
        "an_conv_sub": "الصفقات إلى المشاهدات",
        "an_rating": "التقييم",
        "an_reviews": "{n} مراجعات",
        "an_top_views": "الأكثر مشاهدة",
        "an_no_data": "لا توجد بيانات مشاهدات بعد",
        "an_opt": "جملة",
        "an_deals_chart": "الصفقات حسب الحالة",
        "an_done": "مكتملة",
        "an_progress": "قيد التنفيذ",
        "an_other": "أخرى",
        "err_load": "خطأ في التحميل",
        "pro_need": "متاح في باقة PRO",
        "pro_need_s": "التحليلات المتقدمة وأقسام المتجر والعروض التجارية من أدوات باقة PRO.",
        "jrn_title": "سجل الفواتير",
        "jrn_sub": "جميع فواتير الفترة بترتيب الأرقام — للمطابقة مع البنك وللتقارير. تبقى الملغاة في القائمة لكنها لا تُحتسب دخلاً.",
        "jrn_v_inv": "الفواتير",
        "jrn_v_stock": "المخزون",
        "jrn_v_log": "الإجراءات",
        "jrn_period": "الفترة",
        "jrn_year": "سنة {y}",
        "jrn_h1": "النصف الأول {y}",
        "jrn_h2": "النصف الثاني {y}",
        "jrn_q": "الربع {q} {y}",
        "jrn_issued": "صادرة",
        "jrn_paid": "مُرحّلة (دخل)",
        "jrn_vat": "ضريبة المبيعات",
        "jrn_cancelled": "ملغاة",
        "jrn_empty": "لا فواتير في هذه الفترة",
        "jrn_log_empty": "لا سجلات في هذه الفترة",
        "jrn_paid_at": "الدفع ",
        "jrn_incl_vat": "الضريبة ",
        "jrn_chart": "الفواتير حسب الشهر",
        "jrn_e_reserve": "محجوز لفاتورة",
        "jrn_e_release": "أُعيد إلى المخزون",
        "jrn_e_manual": "تعديل الرصيد",
        "jrn_e_issued": "صدرت الفاتورة",
        "jrn_e_opened": "فتح المستلم المستند",
        "share_doc": "مشاركة الفاتورة",
        "inv_title": "الفواتير والطلبات",
        "b2b_orders_in": "طلبات المشترين",
        "b2b_orders_out": "طلباتي لدى الموردين",
        "b2b_no_incoming": "لا طلبات واردة بعد",
        "b2b_no_mine": "لم تقدّم أي طلبات بعد",
        "b2b_buyer_word": "المشتري",
        "b2b_supplier": "المورد",
        "b2b_guest_tag": "بدون حساب",
        "b2b_until": "حتى",
        "b2b_confirm": "تأكيد",
        "b2b_mark_paid": "وصل الدفع",
        "b2b_ship": "شحن",
        "b2b_finish": "إنهاء",
        "b2b_cancel": "إلغاء",
        "b2b_cancel_q": "إلغاء الفاتورة",
        "b2b_cancel_yes": "نعم، إلغاء",
        "b2b_cancel_no": "لا",
        "b2b_cancel_h": "سيرى الطرف الآخر أن الفاتورة أُلغيت. ستعود البضاعة المحجوزة لها إلى المخزون. لا يمكن التراجع عن الإلغاء — أصدر فاتورة جديدة.",
        "b2b_status_updated": "تم تحديث الحالة",
        "b2b_st_new": "جديد",
        "b2b_st_confirmed": "بانتظار الدفع",
        "b2b_st_paid": "مدفوع",
        "b2b_st_shipped": "مشحون",
        "b2b_st_done": "مكتمل",
        "b2b_st_cancelled": "ملغى",
        "inv_received_lbl": "الفواتير المستلمة",
        "doc_t_invoice": "فاتورة",
        "doc_t_act": "محضر",
        "doc_t_waybill": "بوليصة شحن",
        "doc_t_contract": "عقد",
        "doc_t_poa": "توكيل",
        "doc_t_pricelist": "قائمة الأسعار",
        "docs_on_site": "طباعة الفواتير وبوالص الشحن والمحاضر والفواتير الضريبية من الحساب على الموقع.",
        "open_site_docs": "المستندات على الموقع",
        "kp_title": "عروض للمشترين",
        "kp_sub": "يطلب المشتري تسعيرة — وترسل عرضًا بالأسعار",
        "kp_incoming": "الطلبات الواردة",
        "kp_sent_lbl": "المرسلة",
        "kp_received_lbl": "العروض المستلمة",
        "kp_none_incoming": "لا طلبات بعد",
        "kp_generate_btn": "إنشاء عرض",
        "kp_decline": "رفض",
        "kp_decline_confirm": "رفض طلب العرض؟",
        "kp_decline_ok": "رفض",
        "kp_status_sent": "أُرسل",
        "kp_status_declined": "مرفوض",
        "kp_from_seller": "البائع",
        "kp_gen_title": "عرض تجاري",
        "kp_for": "إلى",
        "kp_tpl_formal": "قالب: رسمي",
        "kp_tpl_short": "قالب: مختصر",
        "kp_ai_btn": "إنشاء عبر Kliko AI",
        "kp_ai_left": "عمليات Kliko AI اليوم",
        "kp_gen_ph": "اختر قالبًا أو Kliko AI — سيظهر النص هنا ويمكنك تعديله.",
        "kp_send_btn": "إرسال إلى المشتري",
        "kp_ai_wait": "Kliko AI يكتب العرض…",
        "kp_empty": "أنشئ نص العرض أولاً",
        "kp_sent_ok": "أُرسل العرض إلى المشتري",
        "kp_need_company": "لإنشاء عرض، أكمل بيانات الشركة — الاسم ورقم BIN.",
        "kp_need_pro": "إنشاء العروض متاح لمتاجر PRO فقط.",
        "cmp_items_total": "الإجمالي:",
        "kp_share": "مشاركة النص",
        "sec_title": "أقسام المتجر",
        "sec_help": "أنشئ أقسام الكتالوج الخاصة بك — يصفّي المشتري المنتجات بها مباشرة في واجهة متجرك.",
        "sec_add": "إضافة قسم",
        "sec_name_ph": "اسم القسم",
        "sec_empty": "لا أقسام بعد — أضف الأول.",
        "sec_max": "حتى 40 قسمًا",
        "sec_saved": "تم حفظ الأقسام",
        "save": "حفظ",
        "delete": "حذف",
        "a11y_up": "إلى الأعلى",
        "a11y_down": "إلى الأسفل",
    ]
}
