import Foundation

/**
 Тексты платных услуг, клуба основателей и компании — этап 48 (владелец 26.09.2026: «всё одно и то же, просто код
 разный»), на языке телефона (kk/ru/en/ar).

 Русские — слово в слово с сайта: словарь js/i18n-cabinet-ru.js (pxd_*, pro_*, promo_*, upg_*, combo_*, bc_*, club_*,
 split_*, cmp_*, rw_*, b2b_*, ai_over) и фразы, зашитые в код без ключа: js/cabinet.min.js (publishTopPick — «На балансе…
 не хватает…», «Не удалось проверить баланс…»; showPhotoUpsell — «Поднять в ТОП · от N ₸/день»; showFounder —
 «Партнёрская программа», «Друзей активировано», «потолок»; cabRefCopy — «Ссылка недоступна»; CMP_BANKS; CAB_HELP —
 «Компания и витрина»), разметка экрана компании страницы кабинета («Реквизиты компании», «Изменить», «Документы»,
 «Инструменты магазина», «Печать и подпись») и пункты меню «Для бизнеса» / «Акции». В rw_hint_bin убран хвост «Или
 нажмите «По фото» вверху.» — кнопки распознавания по фото (company_ocr) в приложении нет. <b>, &minus; и <br> сайта —
 обычным текстом, «−» и переносом строки.

 Свои слова приложения — заголовок «Платные услуги» (у сайта это окна, а не экран), «Открыть в кабинете на сайте»,
 «Глубокий разбор Kliko AI · осталось запусков: {n}» (сайт пишет «осталось запусков» только тостом после разбора),
 «Повторить» и подписи VoiceOver (a11y_*). Остальные языки — перевод тех же фраз.
 */
enum БизнесText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    /// Текст с подстановками по имени: ["n": "5", "b": "700"] → {n}, {b}.
    static func т(_ ключ: String, _ замены: [String: String]) -> String {
        var итог = т(ключ)
        for (имя, значение) in замены {
            итог = итог.replacingOccurrences(of: "{" + имя + "}", with: значение)
        }
        return итог
    }

    static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    // MARK: - Русский (сайт)

    private static let ru: [String: String] = [
        // Общее
        "paid_title": "Платные услуги",
        "club_title": "Клуб основателей",
        "cmp_title": "Компания и витрина",
        "biz_group": "Для бизнеса",
        "row_club": "Акции",
        "no_digital": "Эта возможность недоступна в приложении.",
        "on_site": "Открыть в кабинете на сайте",
        "loading": "Загрузка…",
        "retry": "Повторить",
        "close": "Закрыть",
        "cancel": "Отмена",
        "err_generic": "Ошибка",
        "no_conn": "Нет соединения",
        "copied_excl": "Скопировано!",
        // PRO (showProOffer, pxdRender)
        "pxd_eyebrow": "Kliko PRO · Магазин",
        "pxd_h1a": "Продавайте как",
        "pxd_h1b": "профессионал",
        "pxd_sub": "Витрина, инструменты роста и Kliko AI — всё, чтобы выделяться и продавать больше.",
        "pro_h2": "Всё для тех, кто продаёт много и товарами",
        "pro_free": "Бесплатно",
        "pro_per_month": "/ мес",
        "pro_your_tier": "Ваш тариф",
        "pxd_owned": "У вас PRO",
        "pxd_active_left": "Активен ещё {n} дн.",
        "pxd_until": "до",
        "pro_lifetime": "бессрочно",
        "pxd_slots_upto": "До {n} активных объявлений",
        "pxd_slots_unlim": "Безлимит объявлений",
        "pxd_ai_days": "Все Kliko AI-функции — {n} дн.",
        "pro_t1_sub": "Приоритет в выдаче|Масс-редактор и склад|Kliko AI-импорт пачкой|Прайс-лист|Публикация по расписанию|Опт/B2B-счета (НДС, акты, накладные)|Налоговый модуль (ФНО)|Интеграции: CRM и 1С|Расширенная аналитика",
        "pro_note": "Оплата с кошелька кабинета · 30 дней · продление в один клик",
        "cab_get_pro": "Оформить PRO",
        "pro_activate_free": "Активировать бесплатно",
        // Продвижение (openPromote, publishTopPick, showPhotoUpsell)
        "promo_title": "Продвижение",
        "promo_free_bumps": "Бесплатные авто-поднятия (день 7·14·21) — включены",
        "promo_your_disc": "Ваша скидка на продвижение:",
        "promo_packages": "Готовые пакеты",
        "promo_max_rib": "Максимум",
        "promo_wallet_bal": "Баланс кошелька: ",
        "promo_boost_v": "Продвинуть",
        "top_from": "Поднять в ТОП · от {n} ₸/день",
        "q_short": "На балансе {b} ₸, для «{l}» нужно {p} ₸ — не хватает {n} ₸",
        "q_fail": "Не удалось проверить баланс — попробуйте ещё раз",
        // Слоты (upgSlotsPaneHTML)
        "upg_slots_title": "Слоты объявлений",
        "upg_now_active": "Сейчас активно: ",
        "slot_of": "из",
        "upg_slots_free_lbl": "Активных объявлений бесплатно",
        "upg_slots_note_hint": "Сколько держать в выдаче одновременно · тариф на 30 дней",
        "upg_your_tariff_disc": "Ваша скидка на тарифы:",
        "upg_listings_word": "объявлений",
        "upg_current": "текущий",
        "upg_base_limit": "базовый лимит",
        "upg_per_month": "/ месяц",
        "upg_included": "включено",
        "upg_choose": "Выбрать",
        "upg_verify_bonus": "Пройти верификацию — +5 бесплатных слотов",
        "upg_slots_in_section": "Слоты доступны в разделе «Мои объявления».",
        // Комбо (upgComboPaneHTML)
        "upg_combo_t": "Комбо-пакеты",
        "upg_combo_sub": "Слоты + безлимитный Kliko AI — выгоднее вместе",
        "upg_combo_intro": "Больше активных объявлений (слоты) + безлимитные Kliko AI-разборы одним пакетом — выгоднее, чем по отдельности. Слоты и Kliko AI действуют 30 дней (Kliko AI — по сроку пакета).",
        "upg_combo_name": "Комбо «{n}»",
        "combo_start": "Старт",
        "combo_active": "Актив",
        "combo_max": "Макс",
        "upg_combo_feat": "{n} слотов · безлимитный Kliko AI {d} дн",
        "upg_disc_note": "Скидка −{n}% уже применена",
        "bc_order": "Оформить",
        // Kliko AI (upgAiPaneHTML, renderSlotBanner)
        "upg_ai_packs": "Пакеты Kliko AI",
        "upg_ai_intro2": "Пакет снимает лимит Kliko AI на выбранный срок. Если пакет уже действует, дни добавятся к нему.",
        "upg_ai_intro_free": "Kliko AI-разборы бесплатны — активируйте любой срок и пользуйтесь без лимита.",
        "upg_ai_free_note": "Kliko AI сейчас бесплатно — активируйте любой срок без оплаты",
        "upg_ai_disc_note": "Скидка −{n}% на пакеты Kliko AI уже применена",
        "upg_ai_pack": "Kliko AI на {d} дней",
        "upg_ai_perday": "≈ {n} ₸ в день",
        "upg_ai_best": "Выгоднее всего",
        "upg_free_word": "Бесплатно",
        "upg_unlimited_ai": "Безлимитные Kliko AI-разборы",
        "ai_over": "Закончились",
        "bc_ai_pack": "Пакет Kliko AI",
        "credits_left": "Глубокий разбор Kliko AI · осталось запусков: {n}",
        // Клуб основателей (_clubRender, showFounder, clubPromoResult)
        "club_share_text": "Заходи на Kliko.kz — маркетплейс, где не кинут на предоплате. По моей ссылке ты в Клубе основателей со скидкой на услуги.",
        "club_load_failed": "Не удалось загрузить",
        "club_no_promos_title": "Акций пока нет",
        "club_no_promos_sub": "На данный момент активных акций нет.\nСледите за обновлениями — скоро появятся новые.",
        "club_lifetime_discount_sub": "пожизненная скидка на платные услуги",
        "club_growth_per_friend": "за друзей +{step}%/друг · до {cap}%",
        "club_growth_fixed": "фикс. скидка {cap}%",
        "club_base_hint": "База −{base}% · {growth}",
        "club_locked_title": "Скидка до −90% ждёт",
        "club_locked_sub": "Пройдите верификацию — активируется номер участника\nи пожизненная скидка на услуги.",
        "club_friends": "Друзей активировано: {n} · +{b}%",
        "club_cap": "потолок −{n}%",
        "club_your_link_label": "Твоя ссылка — приглашай друзей",
        "club_copy": "Копировать",
        "club_share": "Поделиться",
        "club_no_link": "Ссылка недоступна",
        "club_promo_label": "Есть промокод?",
        "club_promo_placeholder": "ПРОМОКОД",
        "club_promo_apply": "Применить",
        "club_note": "Скидки — на продвижение и слоты. PRO и комиссия гаранта без скидки.\nДруг засчитывается после его верификации (в течение 7 дней).",
        "club_promo_empty": "Введите промокод",
        "club_promo_apply_failed": "Не удалось применить",
        "club_promo_ok_title": "Промокод активирован!",
        "club_promo_ok_scope": "на продвижение и слоты",
        "club_promo_ok_until": "Действует до {date} · {days} дн.",
        "club_promo_err_title": "К сожалению, не получилось",
        "club_promo_used_title": "Промокод уже использован",
        "club_promo_used_sub": "Этот код можно применить только один раз.",
        "club_promo_expired_title": "Акция завершилась",
        "club_promo_expired_sub": "Срок действия промокода истёк.",
        "club_promo_limit_title": "Промокод недоступен",
        "club_promo_limit_sub": "Лимит применений исчерпан.",
        "club_promo_notfound_title": "Промокод не найден",
        "club_promo_notfound_sub": "Проверьте код и попробуйте снова.",
        "pt_title": "Партнёрская программа",
        "pt_month": "начислено в этом месяце · предварительно",
        "pt_invited": "Приглашённых",
        "pt_pending": "Ждёт выплаты",
        "pt_paid": "Выплачено всего",
        "pt_note": "Доля от чистого дохода площадки с ваших приглашённых — после комиссии банка. Раз в месяц закрываем прошедший месяц и переводим на кошелёк. Меньше {n} ₸ — копится до следующего раза.",
        // Магазин (splitCard, splitSubmit)
        "split_active_t": "Статус: Магазин",
        "split_active_s": "Выплаты на расчётный счёт и корп-карту доступны",
        "split_active_note": "Реквизиты юр. лица зарегистрированы у эквайера. Средства выводятся на счёт компании (KYC) — покупатели видят проверенный магазин.",
        "split_pend_t": "Заявка на проверке",
        "split_pend_s": "Эквайер обрабатывает регистрацию — обычно 1–3 рабочих дня",
        "split_pend_note": "Как только реквизиты подтвердят, статус «Магазин» включится автоматически и откроются выплаты на счёт. Уведомим.",
        "split_none_t": "Станьте магазином",
        "split_none_s": "Приём на счёт компании и знак «Проверенный магазин» — покупатели доверяют больше",
        "split_none_note": "Всего пара минут — поможем на каждом шаге. Останется дождаться проверки реквизитов (1–3 рабочих дня).",
        "split_s1_t": "Верификация продавца",
        "split_s1_done": "Пройдена",
        "split_s1_d": "Подтвердите личность — основа доверия",
        "split_s2_t": "Реквизиты юр. лица",
        "split_s2_done": "Заполнены",
        "split_s2_d": "Название, БИН и IBAN компании",
        "split_s3_t": "Выплаты на счёт компании",
        "split_s3_d": "Платёжная система проверит реквизиты (1–3 дня) → статус «Магазин»",
        "split_cta_verify": "Пройти верификацию",
        "split_cta_reqs": "Заполнить реквизиты",
        "split_cta_go": "Стать магазином",
        "split_rej": "Заявка отклонена",
        "split_rej2": "Проверьте реквизиты и подайте снова.",
        "split_submitted": "Заявка отправлена — проверка 1–3 рабочих дня",
        "split_need_verify": "Сначала верификация",
        "split_need_reqs": "Заполните реквизиты",
        // Реквизиты (разметка экрана компании, openReqWizard)
        "cmp_card_t": "Реквизиты компании",
        "cmp_edit": "Изменить",
        "cmp_f_name": "Наименование (ТОО/ИП)",
        "cmp_f_bin": "БИН",
        "cmp_f_director": "Руководитель",
        "cmp_f_addr": "Юридический адрес",
        "cmp_f_bank": "Банк",
        "cmp_f_bik": "БИК",
        "cmp_f_iik": "ИИК (IBAN)",
        "cmp_f_kbe": "Кбе",
        "cmp_f_acctype": "Тип счёта",
        "cmp_f_phone": "Телефон компании",
        "cmp_bank_pick": "— выберите банк —",
        "cmp_saved": "Реквизиты и шаблон сохранены",
        "cmp_bin_none": "Компания с таким БИН не найдена — введите вручную",
        "cmp_err_bin": "БИН должен содержать 12 цифр",
        "cmp_err_iik": "ИИК: KZ + 13–18 символов",
        "rw_title": "Реквизиты юр. лица",
        "rw_sub": "Для выплат на счёт компании",
        "rw_s1": "Шаг 1 · Компания",
        "rw_s2": "Шаг 2 · Банк и счёт",
        "rw_s3": "Шаг 3 · Проверка",
        "rw_find": "Найти",
        "rw_finding": "Ищу…",
        "rw_bin_ph": "12 цифр",
        "rw_hint_bin": "Введите БИН — наименование, руководитель и адрес подтянутся из гос-реестра автоматически.",
        "rw_hint_iik": "IBAN есть только у вас — реестр его не отдаёт. Банк выберите из списка, БИК подставится сам.",
        "rw_hint_save": "Данные передаются платёжной системе, чтобы подключить выплаты на счёт вашей компании.",
        "rw_next": "Далее",
        "rw_back": "Назад",
        "rw_save": "Сохранить реквизиты",
        "rw_saving": "Сохраняю…",
        "rw_empty": "Данные не заполнены",
        "rw_need_name": "Укажите наименование (или найдите по БИН)",
        "rw_need_bank": "Выберите банк",
        "rw_manual": "Реестр недоступен — заполните вручную",
        "rw_found_ok": "Данные подтянуты из реестра",
        // Документы и B2B (разметка экрана компании, модуль business)
        "docs_t": "Документы",
        "docs_s": "Счета, акты и предложения — что прислали вам и что отправили вы",
        "b2b_orders_in": "Заказы от покупателей",
        "b2b_orders_out": "Мои заказы у поставщиков",
        "b2b_no_incoming": "Входящих заказов пока нет",
        "b2b_no_mine": "Вы ещё не оформляли заказов",
        "b2b_buyer_word": "Покупатель",
        "b2b_supplier": "Поставщик",
        "b2b_guest_tag": "Без регистрации",
        "b2b_until": "до",
        "b2b_st_new": "новый",
        "b2b_st_confirmed": "ждём оплату",
        "b2b_st_paid": "оплачен",
        "b2b_st_shipped": "отгружен",
        "b2b_st_done": "завершён",
        "b2b_st_cancelled": "отменён",
        "biz_title": "Инструменты магазина",
        "biz_invoices": "Счета",
        "biz_seal": "Печать и подпись",
        "biz_pricelist": "Прайс-лист",
        "biz_sections": "Разделы магазина",
        "biz_kp": "Коммерческие предложения",
        "biz_analytics": "Аналитика",
        "biz_integrations": "Интеграции",
        // VoiceOver
        "a11y_site": "Открывает сайт",
        "a11y_done": "выполнено",
        "a11y_step": "Шаг {n} из 3"
    ]

    // MARK: - Қазақша

    private static let kk: [String: String] = [
        "paid_title": "Ақылы қызметтер",
        "club_title": "Негізін қалаушылар клубы",
        "cmp_title": "Компания және витрина",
        "biz_group": "Бизнес үшін",
        "row_club": "Акциялар",
        "no_digital": "Бұл мүмкіндік қосымшада қолжетімсіз.",
        "on_site": "Сайттағы кабинетте ашу",
        "loading": "Жүктелуде…",
        "retry": "Қайталау",
        "close": "Жабу",
        "cancel": "Болдырмау",
        "err_generic": "Қате",
        "no_conn": "Байланыс жоқ",
        "copied_excl": "Көшірілді!",
        "pxd_eyebrow": "Kliko PRO · Дүкен",
        "pxd_h1a": "Сатыңыз",
        "pxd_h1b": "кәсіпқой сияқты",
        "pxd_sub": "Витрина, өсу құралдары және Kliko AI — ерекшеленіп, көбірек сату үшін бәрі.",
        "pro_h2": "Көп және тауармен сататындарға арналған бәрі",
        "pro_free": "Тегін",
        "pro_per_month": "/ ай",
        "pro_your_tier": "Сіздің тарифіңіз",
        "pxd_owned": "Сізде PRO бар",
        "pxd_active_left": "Тағы {n} күн белсенді",
        "pxd_until": "дейін",
        "pro_lifetime": "мерзімсіз",
        "pxd_slots_upto": "{n} белсенді хабарландыруға дейін",
        "pxd_slots_unlim": "Хабарландырулар шектеусіз",
        "pxd_ai_days": "Барлық Kliko AI мүмкіндіктері — {n} күн",
        "pro_t1_sub": "Іздеуде басымдық|Жаппай редактор және қойма|Kliko AI топтап импорттау|Баға парағы|Кесте бойынша жариялау|Көтерме/B2B шоттары (ҚҚС, актілер, жүкқұжаттар)|Салық модулі (ФНО)|Интеграциялар: CRM және 1С|Кеңейтілген аналитика",
        "pro_note": "Кабинет әмиянынан төлем · 30 күн · бір рет басып ұзарту",
        "cab_get_pro": "PRO рәсімдеу",
        "pro_activate_free": "Тегін белсендіру",
        "promo_title": "Жарнамалау",
        "promo_free_bumps": "Тегін авто-көтерулер (7·14·21-күн) — қосулы",
        "promo_your_disc": "Жарнамалауға жеңілдігіңіз:",
        "promo_packages": "Дайын пакеттер",
        "promo_max_rib": "Максимум",
        "promo_wallet_bal": "Әмиян балансы: ",
        "promo_boost_v": "Жарнамалау",
        "top_from": "ТОП-қа көтеру · күніне {n} ₸-ден",
        "q_short": "Балансыңызда {b} ₸, «{l}» үшін {p} ₸ керек — {n} ₸ жетпейді",
        "q_fail": "Балансты тексеру мүмкін болмады — қайталап көріңіз",
        "upg_slots_title": "Хабарландыру слоттары",
        "upg_now_active": "Қазір белсенді: ",
        "slot_of": "/",
        "upg_slots_free_lbl": "Тегін белсенді хабарландырулар",
        "upg_slots_note_hint": "Бір уақытта қанша ұстау · тариф 30 күнге",
        "upg_your_tariff_disc": "Тарифтерге жеңілдігіңіз:",
        "upg_listings_word": "хабарландыру",
        "upg_current": "ағымдағы",
        "upg_base_limit": "негізгі лимит",
        "upg_per_month": "/ ай",
        "upg_included": "қосылған",
        "upg_choose": "Таңдау",
        "upg_verify_bonus": "Верификациядан өту — +5 тегін слот",
        "upg_slots_in_section": "Слоттар «Менің хабарландыруларым» бөлімінде қолжетімді.",
        "upg_combo_t": "Комбо-пакеттер",
        "upg_combo_sub": "Слоттар + шектеусіз Kliko AI — бірге тиімдірек",
        "upg_combo_intro": "Көбірек белсенді хабарландыру (слоттар) + шектеусіз Kliko AI талдаулары бір пакетте — бөлек алғаннан тиімдірек. Слоттар мен Kliko AI 30 күн әрекет етеді (Kliko AI — пакет мерзімі бойынша).",
        "upg_combo_name": "«{n}» комбосы",
        "combo_start": "Старт",
        "combo_active": "Актив",
        "combo_max": "Макс",
        "upg_combo_feat": "{n} слот · шектеусіз Kliko AI {d} күн",
        "upg_disc_note": "−{n}% жеңілдік қолданылды",
        "bc_order": "Рәсімдеу",
        "upg_ai_packs": "Kliko AI пакеттері",
        "upg_ai_intro2": "Пакет таңдалған мерзімге Kliko AI лимитін алып тастайды. Пакет әрекет етіп тұрса, күндер оған қосылады.",
        "upg_ai_intro_free": "Kliko AI талдаулары тегін — кез келген мерзімді белсендіріп, лимитсіз пайдаланыңыз.",
        "upg_ai_free_note": "Kliko AI қазір тегін — кез келген мерзімді төлемсіз белсендіріңіз",
        "upg_ai_disc_note": "Kliko AI пакеттеріне −{n}% жеңілдік қолданылды",
        "upg_ai_pack": "Kliko AI {d} күнге",
        "upg_ai_perday": "≈ күніне {n} ₸",
        "upg_ai_best": "Ең тиімдісі",
        "upg_free_word": "Тегін",
        "upg_unlimited_ai": "Шектеусіз Kliko AI талдаулары",
        "ai_over": "Бітті",
        "bc_ai_pack": "Kliko AI пакеті",
        "credits_left": "Kliko AI терең талдауы · қалған іске қосу: {n}",
        "club_share_text": "Kliko.kz-ке кір — алдын ала төлемде алдамайтын маркетплейс. Менің сілтемем бойынша сен қызметтерге жеңілдігі бар Негізін қалаушылар клубындасың.",
        "club_load_failed": "Жүктеу мүмкін болмады",
        "club_no_promos_title": "Әзірге акция жоқ",
        "club_no_promos_sub": "Қазіргі уақытта белсенді акциялар жоқ.\nЖаңалықтарды қадағалаңыз — жақында жаңалары шығады.",
        "club_lifetime_discount_sub": "ақылы қызметтерге өмірлік жеңілдік",
        "club_growth_per_friend": "достар үшін +{step}%/дос · {cap}%-ке дейін",
        "club_growth_fixed": "тұрақты жеңілдік {cap}%",
        "club_base_hint": "Негіз −{base}% · {growth}",
        "club_locked_title": "−90%-ке дейін жеңілдік күтіп тұр",
        "club_locked_sub": "Верификациядан өтіңіз — қатысушы нөмірі\nжәне қызметтерге өмірлік жеңілдік белсендіріледі.",
        "club_friends": "Белсендірілген достар: {n} · +{b}%",
        "club_cap": "шегі −{n}%",
        "club_your_link_label": "Сенің сілтемең — достарыңды шақыр",
        "club_copy": "Көшіру",
        "club_share": "Бөлісу",
        "club_no_link": "Сілтеме қолжетімсіз",
        "club_promo_label": "Промокод бар ма?",
        "club_promo_placeholder": "ПРОМОКОД",
        "club_promo_apply": "Қолдану",
        "club_note": "Жеңілдіктер — жарнамалау мен слоттарға. PRO және кепіл комиссиясы жеңілдіксіз.\nДос верификациядан кейін есептеледі (7 күн ішінде).",
        "club_promo_empty": "Промокодты енгізіңіз",
        "club_promo_apply_failed": "Қолдану мүмкін болмады",
        "club_promo_ok_title": "Промокод белсендірілді!",
        "club_promo_ok_scope": "жарнамалау мен слоттарға",
        "club_promo_ok_until": "{date} дейін жарамды · {days} күн",
        "club_promo_err_title": "Өкінішке қарай, болмады",
        "club_promo_used_title": "Промокод бұрын пайдаланылған",
        "club_promo_used_sub": "Бұл кодты тек бір рет қолдануға болады.",
        "club_promo_expired_title": "Акция аяқталды",
        "club_promo_expired_sub": "Промокодтың мерзімі өтті.",
        "club_promo_limit_title": "Промокод қолжетімсіз",
        "club_promo_limit_sub": "Қолдану лимиті таусылды.",
        "club_promo_notfound_title": "Промокод табылмады",
        "club_promo_notfound_sub": "Кодты тексеріп, қайталап көріңіз.",
        "pt_title": "Серіктестік бағдарлама",
        "pt_month": "осы айда есептелді · алдын ала",
        "pt_invited": "Шақырылғандар",
        "pt_pending": "Төлемді күтуде",
        "pt_paid": "Барлығы төленді",
        "pt_note": "Шақырғандарыңыздан алаңның таза табысындағы үлес — банк комиссиясынан кейін. Айына бір рет өткен айды жауып, әмиянға аударамыз. {n} ₸-ден аз болса — келесі ретке дейін жиналады.",
        "split_active_t": "Мәртебе: Дүкен",
        "split_active_s": "Есеп шотқа және корп-картаға төлемдер қолжетімді",
        "split_active_note": "Заңды тұлға деректемелері эквайерде тіркелген. Қаражат компания шотына шығарылады (KYC) — сатып алушылар тексерілген дүкенді көреді.",
        "split_pend_t": "Өтінім тексеруде",
        "split_pend_s": "Эквайер тіркеуді өңдеуде — әдетте 1–3 жұмыс күні",
        "split_pend_note": "Деректемелер расталған бойда «Дүкен» мәртебесі өздігінен қосылып, шотқа төлемдер ашылады. Хабарлаймыз.",
        "split_none_t": "Дүкен болыңыз",
        "split_none_s": "Компания шотына қабылдау және «Тексерілген дүкен» белгісі — сатып алушылар көбірек сенеді",
        "split_none_note": "Бар-жоғы бірнеше минут — әр қадамда көмектесеміз. Деректемелер тексерілуін күту ғана қалады (1–3 жұмыс күні).",
        "split_s1_t": "Сатушы верификациясы",
        "split_s1_done": "Өтті",
        "split_s1_d": "Жеке басыңызды растаңыз — сенімнің негізі",
        "split_s2_t": "Заңды тұлға деректемелері",
        "split_s2_done": "Толтырылды",
        "split_s2_d": "Компания атауы, БСН және IBAN",
        "split_s3_t": "Компания шотына төлемдер",
        "split_s3_d": "Төлем жүйесі деректемелерді тексереді (1–3 күн) → «Дүкен» мәртебесі",
        "split_cta_verify": "Верификациядан өту",
        "split_cta_reqs": "Деректемелерді толтыру",
        "split_cta_go": "Дүкен болу",
        "split_rej": "Өтінім қабылданбады",
        "split_rej2": "Деректемелерді тексеріп, қайта беріңіз.",
        "split_submitted": "Өтінім жіберілді — тексеру 1–3 жұмыс күні",
        "split_need_verify": "Алдымен верификация",
        "split_need_reqs": "Деректемелерді толтырыңыз",
        "cmp_card_t": "Компания деректемелері",
        "cmp_edit": "Өзгерту",
        "cmp_f_name": "Атауы (ЖШС/ЖК)",
        "cmp_f_bin": "БСН",
        "cmp_f_director": "Басшы",
        "cmp_f_addr": "Заңды мекенжай",
        "cmp_f_bank": "Банк",
        "cmp_f_bik": "БСК",
        "cmp_f_iik": "ЖСК (IBAN)",
        "cmp_f_kbe": "Кбе",
        "cmp_f_acctype": "Шот түрі",
        "cmp_f_phone": "Компания телефоны",
        "cmp_bank_pick": "— банкті таңдаңыз —",
        "cmp_saved": "Деректемелер мен үлгі сақталды",
        "cmp_bin_none": "Мұндай БСН бар компания табылмады — қолмен енгізіңіз",
        "cmp_err_bin": "БСН 12 цифрдан тұруы керек",
        "cmp_err_iik": "ЖСК: KZ + 13–18 таңба",
        "rw_title": "Заңды тұлға деректемелері",
        "rw_sub": "Компания шотына төлемдер үшін",
        "rw_s1": "1-қадам · Компания",
        "rw_s2": "2-қадам · Банк және шот",
        "rw_s3": "3-қадам · Тексеру",
        "rw_find": "Табу",
        "rw_finding": "Іздеуде…",
        "rw_bin_ph": "12 цифр",
        "rw_hint_bin": "БСН енгізіңіз — атауы, басшысы мен мекенжайы мемлекеттік тізілімнен өздігінен толтырылады.",
        "rw_hint_iik": "IBAN тек сізде бар — тізілім оны бермейді. Банкті тізімнен таңдаңыз, БСК өздігінен қойылады.",
        "rw_hint_save": "Деректер компанияңыздың шотына төлемдерді қосу үшін төлем жүйесіне беріледі.",
        "rw_next": "Әрі қарай",
        "rw_back": "Артқа",
        "rw_save": "Деректемелерді сақтау",
        "rw_saving": "Сақталуда…",
        "rw_empty": "Деректер толтырылмаған",
        "rw_need_name": "Атауын көрсетіңіз (немесе БСН бойынша табыңыз)",
        "rw_need_bank": "Банкті таңдаңыз",
        "rw_manual": "Тізілім қолжетімсіз — қолмен толтырыңыз",
        "rw_found_ok": "Деректер тізілімнен алынды",
        "docs_t": "Құжаттар",
        "docs_s": "Шоттар, актілер және ұсыныстар — сізге жібергендері және сіз жібергендер",
        "b2b_orders_in": "Сатып алушылардан тапсырыстар",
        "b2b_orders_out": "Жеткізушілердегі тапсырыстарым",
        "b2b_no_incoming": "Кіріс тапсырыстар әзірге жоқ",
        "b2b_no_mine": "Сіз әлі тапсырыс рәсімдемегенсіз",
        "b2b_buyer_word": "Сатып алушы",
        "b2b_supplier": "Жеткізуші",
        "b2b_guest_tag": "Тіркелусіз",
        "b2b_until": "дейін",
        "b2b_st_new": "жаңа",
        "b2b_st_confirmed": "төлемді күтудеміз",
        "b2b_st_paid": "төленді",
        "b2b_st_shipped": "жөнелтілді",
        "b2b_st_done": "аяқталды",
        "b2b_st_cancelled": "бас тартылды",
        "biz_title": "Дүкен құралдары",
        "biz_invoices": "Шоттар",
        "biz_seal": "Мөр және қолтаңба",
        "biz_pricelist": "Баға парағы",
        "biz_sections": "Дүкен бөлімдері",
        "biz_kp": "Коммерциялық ұсыныстар",
        "biz_analytics": "Аналитика",
        "biz_integrations": "Интеграциялар",
        "a11y_site": "Сайтты ашады",
        "a11y_done": "орындалды",
        "a11y_step": "{n}-қадам, барлығы 3"
    ]

    // MARK: - English

    private static let en: [String: String] = [
        "paid_title": "Paid services",
        "club_title": "Founders Club",
        "cmp_title": "Company and storefront",
        "biz_group": "For business",
        "row_club": "Promotions",
        "no_digital": "This feature is not available in the app.",
        "on_site": "Open in the cabinet on the website",
        "loading": "Loading…",
        "retry": "Retry",
        "close": "Close",
        "cancel": "Cancel",
        "err_generic": "Error",
        "no_conn": "No connection",
        "copied_excl": "Copied!",
        "pxd_eyebrow": "Kliko PRO · Store",
        "pxd_h1a": "Sell like a",
        "pxd_h1b": "professional",
        "pxd_sub": "Storefront, growth tools and Kliko AI — everything to stand out and sell more.",
        "pro_h2": "Everything for those who sell a lot and sell goods",
        "pro_free": "Free",
        "pro_per_month": "/ mo",
        "pro_your_tier": "Your plan",
        "pxd_owned": "You have PRO",
        "pxd_active_left": "Active for {n} more days",
        "pxd_until": "until",
        "pro_lifetime": "no expiry",
        "pxd_slots_upto": "Up to {n} active listings",
        "pxd_slots_unlim": "Unlimited listings",
        "pxd_ai_days": "All Kliko AI features — {n} days",
        "pro_t1_sub": "Priority in search|Bulk editor and stock|Kliko AI batch import|Price list|Scheduled publishing|Wholesale/B2B invoices (VAT, acts, waybills)|Tax module (tax forms)|Integrations: CRM and 1C|Advanced analytics",
        "pro_note": "Paid from the cabinet wallet · 30 days · renew in one tap",
        "cab_get_pro": "Get PRO",
        "pro_activate_free": "Activate for free",
        "promo_title": "Promotion",
        "promo_free_bumps": "Free auto-bumps (day 7·14·21) — on",
        "promo_your_disc": "Your promotion discount:",
        "promo_packages": "Ready-made packages",
        "promo_max_rib": "Maximum",
        "promo_wallet_bal": "Wallet balance: ",
        "promo_boost_v": "Promote",
        "top_from": "Bump to TOP · from {n} ₸/day",
        "q_short": "Your balance is {b} ₸, «{l}» needs {p} ₸ — {n} ₸ short",
        "q_fail": "Could not check the balance — please try again",
        "upg_slots_title": "Listing slots",
        "upg_now_active": "Active now: ",
        "slot_of": "of",
        "upg_slots_free_lbl": "Free active listings",
        "upg_slots_note_hint": "How many to keep live at once · 30-day plan",
        "upg_your_tariff_disc": "Your plan discount:",
        "upg_listings_word": "listings",
        "upg_current": "current",
        "upg_base_limit": "base limit",
        "upg_per_month": "/ month",
        "upg_included": "included",
        "upg_choose": "Choose",
        "upg_verify_bonus": "Get verified — +5 free slots",
        "upg_slots_in_section": "Slots are available in «My listings».",
        "upg_combo_t": "Combo packages",
        "upg_combo_sub": "Slots + unlimited Kliko AI — better together",
        "upg_combo_intro": "More active listings (slots) + unlimited Kliko AI analyses in one package — cheaper than separately. Slots and Kliko AI last 30 days (Kliko AI — for the package term).",
        "upg_combo_name": "Combo «{n}»",
        "combo_start": "Start",
        "combo_active": "Active",
        "combo_max": "Max",
        "upg_combo_feat": "{n} slots · unlimited Kliko AI {d} days",
        "upg_disc_note": "−{n}% discount already applied",
        "bc_order": "Order",
        "upg_ai_packs": "Kliko AI packages",
        "upg_ai_intro2": "A package removes the Kliko AI limit for the chosen term. If a package is already active, the days are added to it.",
        "upg_ai_intro_free": "Kliko AI analyses are free — activate any term and use them without a limit.",
        "upg_ai_free_note": "Kliko AI is free right now — activate any term without paying",
        "upg_ai_disc_note": "−{n}% discount on Kliko AI packages already applied",
        "upg_ai_pack": "Kliko AI for {d} days",
        "upg_ai_perday": "≈ {n} ₸ per day",
        "upg_ai_best": "Best value",
        "upg_free_word": "Free",
        "upg_unlimited_ai": "Unlimited Kliko AI analyses",
        "ai_over": "Used up",
        "bc_ai_pack": "Kliko AI package",
        "credits_left": "Kliko AI deep analysis · runs left: {n}",
        "club_share_text": "Come to Kliko.kz — a marketplace where nobody cheats you on prepayment. With my link you are in the Founders Club with a discount on services.",
        "club_load_failed": "Could not load",
        "club_no_promos_title": "No promotions yet",
        "club_no_promos_sub": "There are no active promotions right now.\nStay tuned — new ones are coming soon.",
        "club_lifetime_discount_sub": "lifetime discount on paid services",
        "club_growth_per_friend": "for friends +{step}%/friend · up to {cap}%",
        "club_growth_fixed": "fixed discount {cap}%",
        "club_base_hint": "Base −{base}% · {growth}",
        "club_locked_title": "A discount of up to −90% is waiting",
        "club_locked_sub": "Get verified — your member number\nand a lifetime discount on services will be activated.",
        "club_friends": "Friends activated: {n} · +{b}%",
        "club_cap": "cap −{n}%",
        "club_your_link_label": "Your link — invite friends",
        "club_copy": "Copy",
        "club_share": "Share",
        "club_no_link": "Link unavailable",
        "club_promo_label": "Have a promo code?",
        "club_promo_placeholder": "PROMO CODE",
        "club_promo_apply": "Apply",
        "club_note": "Discounts apply to promotion and slots. PRO and the escrow fee are not discounted.\nA friend counts after their verification (within 7 days).",
        "club_promo_empty": "Enter a promo code",
        "club_promo_apply_failed": "Could not apply",
        "club_promo_ok_title": "Promo code activated!",
        "club_promo_ok_scope": "on promotion and slots",
        "club_promo_ok_until": "Valid until {date} · {days} days",
        "club_promo_err_title": "Sorry, it did not work",
        "club_promo_used_title": "Promo code already used",
        "club_promo_used_sub": "This code can be applied only once.",
        "club_promo_expired_title": "The promotion has ended",
        "club_promo_expired_sub": "The promo code has expired.",
        "club_promo_limit_title": "Promo code unavailable",
        "club_promo_limit_sub": "The usage limit has been reached.",
        "club_promo_notfound_title": "Promo code not found",
        "club_promo_notfound_sub": "Check the code and try again.",
        "pt_title": "Partner programme",
        "pt_month": "accrued this month · preliminary",
        "pt_invited": "Invited",
        "pt_pending": "Awaiting payout",
        "pt_paid": "Paid out in total",
        "pt_note": "A share of the platform's net income from the people you invited — after the bank fee. Once a month we close the previous month and transfer it to your wallet. Less than {n} ₸ — it accumulates until next time.",
        "split_active_t": "Status: Store",
        "split_active_s": "Payouts to a current account and corporate card are available",
        "split_active_note": "The legal entity details are registered with the acquirer. Funds are paid out to the company account (KYC) — buyers see a verified store.",
        "split_pend_t": "Application under review",
        "split_pend_s": "The acquirer is processing the registration — usually 1–3 business days",
        "split_pend_note": "As soon as the details are confirmed, the «Store» status turns on automatically and payouts to the account open. We will notify you.",
        "split_none_t": "Become a store",
        "split_none_s": "Payments to the company account and the «Verified store» badge — buyers trust you more",
        "split_none_note": "Just a couple of minutes — we will help at every step. Then you only wait for the details check (1–3 business days).",
        "split_s1_t": "Seller verification",
        "split_s1_done": "Done",
        "split_s1_d": "Confirm your identity — the basis of trust",
        "split_s2_t": "Legal entity details",
        "split_s2_done": "Filled in",
        "split_s2_d": "Company name, BIN and IBAN",
        "split_s3_t": "Payouts to the company account",
        "split_s3_d": "The payment system will check the details (1–3 days) → «Store» status",
        "split_cta_verify": "Get verified",
        "split_cta_reqs": "Fill in the details",
        "split_cta_go": "Become a store",
        "split_rej": "Application rejected",
        "split_rej2": "Check the details and apply again.",
        "split_submitted": "Application sent — review takes 1–3 business days",
        "split_need_verify": "Verification first",
        "split_need_reqs": "Fill in the details",
        "cmp_card_t": "Company details",
        "cmp_edit": "Edit",
        "cmp_f_name": "Name (LLP/IE)",
        "cmp_f_bin": "BIN",
        "cmp_f_director": "Director",
        "cmp_f_addr": "Legal address",
        "cmp_f_bank": "Bank",
        "cmp_f_bik": "BIC",
        "cmp_f_iik": "IIC (IBAN)",
        "cmp_f_kbe": "Kbe",
        "cmp_f_acctype": "Account type",
        "cmp_f_phone": "Company phone",
        "cmp_bank_pick": "— choose a bank —",
        "cmp_saved": "Details and template saved",
        "cmp_bin_none": "No company with this BIN was found — enter the data manually",
        "cmp_err_bin": "The BIN must have 12 digits",
        "cmp_err_iik": "IIC: KZ + 13–18 characters",
        "rw_title": "Legal entity details",
        "rw_sub": "For payouts to the company account",
        "rw_s1": "Step 1 · Company",
        "rw_s2": "Step 2 · Bank and account",
        "rw_s3": "Step 3 · Review",
        "rw_find": "Find",
        "rw_finding": "Searching…",
        "rw_bin_ph": "12 digits",
        "rw_hint_bin": "Enter the BIN — the name, director and address are filled in from the state register automatically.",
        "rw_hint_iik": "Only you have the IBAN — the register does not provide it. Choose the bank from the list, the BIC is filled in automatically.",
        "rw_hint_save": "The data is passed to the payment system to enable payouts to your company account.",
        "rw_next": "Next",
        "rw_back": "Back",
        "rw_save": "Save details",
        "rw_saving": "Saving…",
        "rw_empty": "No data filled in",
        "rw_need_name": "Enter the name (or find it by BIN)",
        "rw_need_bank": "Choose a bank",
        "rw_manual": "The register is unavailable — fill in manually",
        "rw_found_ok": "Data loaded from the register",
        "docs_t": "Documents",
        "docs_s": "Invoices, acts and offers — what you received and what you sent",
        "b2b_orders_in": "Orders from buyers",
        "b2b_orders_out": "My orders from suppliers",
        "b2b_no_incoming": "No incoming orders yet",
        "b2b_no_mine": "You have not placed any orders yet",
        "b2b_buyer_word": "Buyer",
        "b2b_supplier": "Supplier",
        "b2b_guest_tag": "Without registration",
        "b2b_until": "until",
        "b2b_st_new": "new",
        "b2b_st_confirmed": "awaiting payment",
        "b2b_st_paid": "paid",
        "b2b_st_shipped": "shipped",
        "b2b_st_done": "completed",
        "b2b_st_cancelled": "cancelled",
        "biz_title": "Store tools",
        "biz_invoices": "Invoices",
        "biz_seal": "Stamp and signature",
        "biz_pricelist": "Price list",
        "biz_sections": "Store sections",
        "biz_kp": "Commercial offers",
        "biz_analytics": "Analytics",
        "biz_integrations": "Integrations",
        "a11y_site": "Opens the website",
        "a11y_done": "done",
        "a11y_step": "Step {n} of 3"
    ]

    // MARK: - العربية

    private static let ar: [String: String] = [
        "paid_title": "الخدمات المدفوعة",
        "club_title": "نادي المؤسسين",
        "cmp_title": "الشركة والواجهة",
        "biz_group": "للأعمال",
        "row_club": "العروض",
        "no_digital": "هذه الميزة غير متاحة في التطبيق.",
        "on_site": "فتح في الحساب على الموقع",
        "loading": "جارٍ التحميل…",
        "retry": "إعادة المحاولة",
        "close": "إغلاق",
        "cancel": "إلغاء",
        "err_generic": "خطأ",
        "no_conn": "لا يوجد اتصال",
        "copied_excl": "تم النسخ!",
        "pxd_eyebrow": "Kliko PRO · متجر",
        "pxd_h1a": "بِع مثل",
        "pxd_h1b": "المحترفين",
        "pxd_sub": "واجهة وأدوات نمو وKliko AI — كل ما يلزم للتميّز وبيع المزيد.",
        "pro_h2": "كل ما يحتاجه من يبيع كثيرًا ويبيع سلعًا",
        "pro_free": "مجانًا",
        "pro_per_month": "/ شهر",
        "pro_your_tier": "باقتك",
        "pxd_owned": "لديك PRO",
        "pxd_active_left": "نشِط لمدة {n} يومًا أخرى",
        "pxd_until": "حتى",
        "pro_lifetime": "بلا مدة",
        "pxd_slots_upto": "حتى {n} إعلانًا نشطًا",
        "pxd_slots_unlim": "إعلانات بلا حدود",
        "pxd_ai_days": "كل ميزات Kliko AI — {n} يومًا",
        "pro_t1_sub": "أولوية في نتائج البحث|محرّر جماعي ومخزون|استيراد دفعي بـKliko AI|قائمة أسعار|نشر مجدول|فواتير الجملة/B2B (ضريبة، محاضر، بوالص)|وحدة الضرائب|تكاملات: CRM و1C|تحليلات موسّعة",
        "pro_note": "الدفع من محفظة الحساب · 30 يومًا · تجديد بنقرة واحدة",
        "cab_get_pro": "اشترك في PRO",
        "pro_activate_free": "فعّل مجانًا",
        "promo_title": "الترويج",
        "promo_free_bumps": "الرفع التلقائي المجاني (اليوم 7·14·21) — مفعّل",
        "promo_your_disc": "خصمك على الترويج:",
        "promo_packages": "باقات جاهزة",
        "promo_max_rib": "الأقصى",
        "promo_wallet_bal": "رصيد المحفظة: ",
        "promo_boost_v": "روّج",
        "top_from": "رفع إلى TOP · من {n} ₸/يوم",
        "q_short": "رصيدك {b} ₸، و«{l}» يحتاج {p} ₸ — ينقص {n} ₸",
        "q_fail": "تعذّر التحقق من الرصيد — حاول مرة أخرى",
        "upg_slots_title": "خانات الإعلانات",
        "upg_now_active": "النشطة الآن: ",
        "slot_of": "من",
        "upg_slots_free_lbl": "إعلانات نشطة مجانًا",
        "upg_slots_note_hint": "كم تُبقي معروضًا في وقت واحد · باقة لمدة 30 يومًا",
        "upg_your_tariff_disc": "خصمك على الباقات:",
        "upg_listings_word": "إعلانًا",
        "upg_current": "الحالية",
        "upg_base_limit": "الحد الأساسي",
        "upg_per_month": "/ شهر",
        "upg_included": "مشمول",
        "upg_choose": "اختيار",
        "upg_verify_bonus": "أكمل التحقق — +5 خانات مجانية",
        "upg_slots_in_section": "الخانات متاحة في قسم «إعلاناتي».",
        "upg_combo_t": "باقات كومبو",
        "upg_combo_sub": "خانات + Kliko AI بلا حدود — أوفر معًا",
        "upg_combo_intro": "مزيد من الإعلانات النشطة (خانات) + تحليلات Kliko AI بلا حدود في باقة واحدة — أوفر من شرائها منفصلة. الخانات وKliko AI صالحة 30 يومًا (Kliko AI — حسب مدة الباقة).",
        "upg_combo_name": "كومبو «{n}»",
        "combo_start": "البداية",
        "combo_active": "النشِط",
        "combo_max": "الأقصى",
        "upg_combo_feat": "{n} خانة · Kliko AI بلا حدود {d} يومًا",
        "upg_disc_note": "تم تطبيق خصم −{n}%",
        "bc_order": "اطلب",
        "upg_ai_packs": "باقات Kliko AI",
        "upg_ai_intro2": "تزيل الباقة حد Kliko AI للمدة المختارة. إن كانت الباقة سارية تُضاف الأيام إليها.",
        "upg_ai_intro_free": "تحليلات Kliko AI مجانية — فعّل أي مدة واستخدمها بلا حدود.",
        "upg_ai_free_note": "Kliko AI مجاني الآن — فعّل أي مدة دون دفع",
        "upg_ai_disc_note": "تم تطبيق خصم −{n}% على باقات Kliko AI",
        "upg_ai_pack": "Kliko AI لمدة {d} يومًا",
        "upg_ai_perday": "≈ {n} ₸ يوميًا",
        "upg_ai_best": "الأوفر",
        "upg_free_word": "مجانًا",
        "upg_unlimited_ai": "تحليلات Kliko AI بلا حدود",
        "ai_over": "نفدت",
        "bc_ai_pack": "باقة Kliko AI",
        "credits_left": "التحليل العميق بـKliko AI · المتبقي من التشغيلات: {n}",
        "club_share_text": "ادخل إلى Kliko.kz — سوق لا يخدعك في الدفع المسبق. عبر رابطي تصبح في نادي المؤسسين مع خصم على الخدمات.",
        "club_load_failed": "تعذّر التحميل",
        "club_no_promos_title": "لا توجد عروض بعد",
        "club_no_promos_sub": "لا توجد عروض نشطة حاليًا.\nتابع التحديثات — ستظهر عروض جديدة قريبًا.",
        "club_lifetime_discount_sub": "خصم مدى الحياة على الخدمات المدفوعة",
        "club_growth_per_friend": "مقابل الأصدقاء +{step}%/صديق · حتى {cap}%",
        "club_growth_fixed": "خصم ثابت {cap}%",
        "club_base_hint": "الأساس −{base}% · {growth}",
        "club_locked_title": "خصم حتى −90% بانتظارك",
        "club_locked_sub": "أكمل التحقق — يُفعَّل رقم العضوية\nوخصم مدى الحياة على الخدمات.",
        "club_friends": "الأصدقاء المفعّلون: {n} · +{b}%",
        "club_cap": "الحد الأقصى −{n}%",
        "club_your_link_label": "رابطك — ادعُ أصدقاءك",
        "club_copy": "نسخ",
        "club_share": "مشاركة",
        "club_no_link": "الرابط غير متاح",
        "club_promo_label": "لديك رمز ترويجي؟",
        "club_promo_placeholder": "الرمز الترويجي",
        "club_promo_apply": "تطبيق",
        "club_note": "الخصومات على الترويج والخانات. PRO وعمولة الضمان بلا خصم.\nيُحتسب الصديق بعد التحقق منه (خلال 7 أيام).",
        "club_promo_empty": "أدخل الرمز الترويجي",
        "club_promo_apply_failed": "تعذّر التطبيق",
        "club_promo_ok_title": "تم تفعيل الرمز الترويجي!",
        "club_promo_ok_scope": "على الترويج والخانات",
        "club_promo_ok_until": "صالح حتى {date} · {days} يومًا",
        "club_promo_err_title": "للأسف، لم ينجح ذلك",
        "club_promo_used_title": "الرمز الترويجي مستخدم مسبقًا",
        "club_promo_used_sub": "يمكن تطبيق هذا الرمز مرة واحدة فقط.",
        "club_promo_expired_title": "انتهى العرض",
        "club_promo_expired_sub": "انتهت صلاحية الرمز الترويجي.",
        "club_promo_limit_title": "الرمز الترويجي غير متاح",
        "club_promo_limit_sub": "استُنفد حد الاستخدام.",
        "club_promo_notfound_title": "الرمز الترويجي غير موجود",
        "club_promo_notfound_sub": "تحقق من الرمز وحاول مرة أخرى.",
        "pt_title": "برنامج الشراكة",
        "pt_month": "مستحق هذا الشهر · مبدئيًا",
        "pt_invited": "المدعوون",
        "pt_pending": "بانتظار الدفع",
        "pt_paid": "المدفوع إجمالًا",
        "pt_note": "حصة من صافي دخل المنصة من المدعوين — بعد عمولة البنك. مرة في الشهر نغلق الشهر الماضي ونحوّل المبلغ إلى المحفظة. أقل من {n} ₸ — يتراكم حتى المرة القادمة.",
        "split_active_t": "الحالة: متجر",
        "split_active_s": "الدفعات إلى الحساب الجاري وبطاقة الشركة متاحة",
        "split_active_note": "بيانات الكيان القانوني مسجلة لدى المُحصِّل. تُسحب الأموال إلى حساب الشركة (KYC) — ويرى المشترون متجرًا موثَّقًا.",
        "split_pend_t": "الطلب قيد المراجعة",
        "split_pend_s": "يعالج المُحصِّل التسجيل — عادةً 1–3 أيام عمل",
        "split_pend_note": "بمجرد تأكيد البيانات تُفعَّل حالة «متجر» تلقائيًا وتُفتح الدفعات إلى الحساب. سنُعلمك.",
        "split_none_t": "كن متجرًا",
        "split_none_s": "استلام على حساب الشركة وشارة «متجر موثَّق» — يثق المشترون أكثر",
        "split_none_note": "دقيقتان فقط — سنساعدك في كل خطوة. يبقى انتظار التحقق من البيانات (1–3 أيام عمل).",
        "split_s1_t": "التحقق من البائع",
        "split_s1_done": "مكتمل",
        "split_s1_d": "أكّد هويتك — أساس الثقة",
        "split_s2_t": "بيانات الكيان القانوني",
        "split_s2_done": "مُعبّأة",
        "split_s2_d": "اسم الشركة وBIN وIBAN",
        "split_s3_t": "الدفعات إلى حساب الشركة",
        "split_s3_d": "سيتحقق نظام الدفع من البيانات (1–3 أيام) ← حالة «متجر»",
        "split_cta_verify": "أكمل التحقق",
        "split_cta_reqs": "عبّئ البيانات",
        "split_cta_go": "كن متجرًا",
        "split_rej": "رُفض الطلب",
        "split_rej2": "تحقق من البيانات وقدّم الطلب مجددًا.",
        "split_submitted": "أُرسل الطلب — المراجعة 1–3 أيام عمل",
        "split_need_verify": "التحقق أولًا",
        "split_need_reqs": "عبّئ البيانات",
        "cmp_card_t": "بيانات الشركة",
        "cmp_edit": "تعديل",
        "cmp_f_name": "الاسم (شركة/مقاول فردي)",
        "cmp_f_bin": "BIN",
        "cmp_f_director": "المدير",
        "cmp_f_addr": "العنوان القانوني",
        "cmp_f_bank": "البنك",
        "cmp_f_bik": "BIC",
        "cmp_f_iik": "IIC (IBAN)",
        "cmp_f_kbe": "Kbe",
        "cmp_f_acctype": "نوع الحساب",
        "cmp_f_phone": "هاتف الشركة",
        "cmp_bank_pick": "— اختر البنك —",
        "cmp_saved": "حُفظت البيانات والقالب",
        "cmp_bin_none": "لم يُعثر على شركة بهذا الرقم BIN — أدخل البيانات يدويًا",
        "cmp_err_bin": "يجب أن يتكوّن BIN من 12 رقمًا",
        "cmp_err_iik": "IIC: ‏KZ + 13–18 رمزًا",
        "rw_title": "بيانات الكيان القانوني",
        "rw_sub": "للدفعات إلى حساب الشركة",
        "rw_s1": "الخطوة 1 · الشركة",
        "rw_s2": "الخطوة 2 · البنك والحساب",
        "rw_s3": "الخطوة 3 · المراجعة",
        "rw_find": "بحث",
        "rw_finding": "جارٍ البحث…",
        "rw_bin_ph": "12 رقمًا",
        "rw_hint_bin": "أدخل BIN — تُملأ التسمية والمدير والعنوان من السجل الحكومي تلقائيًا.",
        "rw_hint_iik": "رقم IBAN لديك فقط — السجل لا يوفّره. اختر البنك من القائمة وسيُملأ BIC تلقائيًا.",
        "rw_hint_save": "تُنقل البيانات إلى نظام الدفع لتفعيل الدفعات إلى حساب شركتك.",
        "rw_next": "التالي",
        "rw_back": "رجوع",
        "rw_save": "حفظ البيانات",
        "rw_saving": "جارٍ الحفظ…",
        "rw_empty": "لم تُعبّأ البيانات",
        "rw_need_name": "أدخل الاسم (أو ابحث عنه بـBIN)",
        "rw_need_bank": "اختر البنك",
        "rw_manual": "السجل غير متاح — عبّئ يدويًا",
        "rw_found_ok": "جُلبت البيانات من السجل",
        "docs_t": "المستندات",
        "docs_s": "الفواتير والمحاضر والعروض — ما أُرسل إليك وما أرسلته",
        "b2b_orders_in": "طلبات من المشترين",
        "b2b_orders_out": "طلباتي لدى الموردين",
        "b2b_no_incoming": "لا توجد طلبات واردة بعد",
        "b2b_no_mine": "لم تُنشئ أي طلبات بعد",
        "b2b_buyer_word": "المشتري",
        "b2b_supplier": "المورد",
        "b2b_guest_tag": "دون تسجيل",
        "b2b_until": "حتى",
        "b2b_st_new": "جديد",
        "b2b_st_confirmed": "بانتظار الدفع",
        "b2b_st_paid": "مدفوع",
        "b2b_st_shipped": "مشحون",
        "b2b_st_done": "مكتمل",
        "b2b_st_cancelled": "ملغى",
        "biz_title": "أدوات المتجر",
        "biz_invoices": "الفواتير",
        "biz_seal": "الختم والتوقيع",
        "biz_pricelist": "قائمة الأسعار",
        "biz_sections": "أقسام المتجر",
        "biz_kp": "العروض التجارية",
        "biz_analytics": "التحليلات",
        "biz_integrations": "التكاملات",
        "a11y_site": "يفتح الموقع",
        "a11y_done": "مكتمل",
        "a11y_step": "الخطوة {n} من 3"
    ]
}
