import Foundation

/// Тексты студии роликов (строки #reel-ov и js/cabinet-reel.min.js сайта) — ru/kk/en/ar. Русские надписи кадра («площадка
/// сделок», «Безопасная сделка: оплата через гарант Kliko», «Скачайте приложение Kliko»…) — слово в слово как у сайта.
enum ReelStudioText {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь = тексты[язык] ?? тексты["ru"] ?? [:]
        return словарь[ключ] ?? тексты["ru"]?[ключ] ?? ключ
    }

    private static let тексты: [String: [String: String]] = [
        "ru": [
            "title": "Видео для Reels / TikTok", "close": "Закрыть", "loading": "Готовим студию…",
            "hint": "Стиль подбирается автоматически — жмите «Стиль» для другого.",
            "style": "Стиль", "style_other": "Другой стиль",
            "st_emerald": "Изумруд", "st_noir": "Нуар · золото", "st_violet": "Ультрафиолет", "st_minimal": "Минимал",
            "st_sunset": "Закат",
            "sound": "Фирменный звук Kliko", "volume": "Громкость",
            "photos": "Фото в ролике", "photos_hint": "Нажмите на фото, чтобы убрать или вернуть его. Стрелки меняют порядок.",
            "photos_max": "В ролике не больше 5 фото", "photos_min": "Оставьте хотя бы одно фото",
            "photos_none": "Фото не загрузились — проверьте связь и откройте студию ещё раз.",
            "move_left": "Раньше", "move_right": "Позже", "photo_n": "Фото %d", "on": "в ролике", "off": "убрано",
            "texts": "Тексты", "f_title": "Название", "f_price": "Цена", "f_cta": "Призыв в конце",
            "make_image": "Картинка", "tag_now": "сразу", "make_video": "Видео",
            "prep": "Готовим кадры…", "render": "Рендер %d%%", "mux": "Собираем MP4…", "cancel": "Отменить",
            "cancelled": "Создание видео отменено",
            "ready": "Готово! Жмите «Поделиться» → выберите Reels / TikTok (видео подставится само).",
            "ready_snd": "Со звуком.", "ready_nosnd": "Звук на этом устройстве не записался — видео без звука.",
            "fail": "Не удалось создать видео на этом устройстве. Нажмите «Видео» ещё раз.",
            "save": "В галерею", "saved": "Ролик сохранён в галерею",
            "save_fail": "Нет доступа к галерее — разрешите добавление фото в Настройках",
            "share": "Поделиться", "remake": "↻ Пересоздать заново",
            "reels": "Instagram Reels", "stories": "Instagram Stories", "tiktok": "TikTok",
            "caption_copied": "Подпись со ссылкой скопирована — вставьте её под роликом",
            "image_making": "Готовим картинку…", "image_fail": "Не удалось сделать картинку",
            "autopost": "Автопостинг в бизнес-аккаунт", "ap_loading": "Загрузка…",
            "post_to": "Опубликовать в %@", "connect": "Подключить %@",
            "connect_sub": "один раз — потом постинг в 1 клик", "soon": "скоро — подключается администратором",
            "posting": "Публикуем…", "posted": "Опубликовано ✓", "posted_to": "Опубликовано в %@ ✓",
            "post_fail": "Не удалось опубликовать", "connecting": "Переходим к подключению %@…",
            "no_conn": "Нет подключения к интернету", "pro_need": "Автопостинг — в тарифе PRO",
            "negotiable": "Договорная", "cond_new": "Новое", "cond_used": "Б/у",
            "v_tagline": "площадка сделок", "v_trust": "Безопасная сделка: оплата через гарант Kliko",
            "v_cta": "Скачайте приложение Kliko", "v_store": "Загрузите в",
            "v_qr": "Наведите камеру на QR — откроется объявление", "v_poster_qr": "наведи камеру",
            "c_safe": "🛡 Безопасная сделка через гарант на Kliko.kz", "c_app": "📲 Приложение Kliko в App Store:",
            "default_title": "Объявление"
        ],
        "kk": [
            "title": "Reels / TikTok үшін бейне", "close": "Жабу", "loading": "Студия дайындалуда…",
            "hint": "Стиль автоматты түрде таңдалады — басқасы үшін «Стиль» басыңыз.",
            "style": "Стиль", "style_other": "Басқа стиль",
            "st_emerald": "Зүмірет", "st_noir": "Нуар · алтын", "st_violet": "Ультракүлгін", "st_minimal": "Минимал",
            "st_sunset": "Шапақ",
            "sound": "Kliko фирмалық дыбысы", "volume": "Дыбыс деңгейі",
            "photos": "Роликтегі фото", "photos_hint": "Фотоны алып тастау не қайтару үшін басыңыз. Жебелер ретін өзгертеді.",
            "photos_max": "Роликте 5 фотодан артық болмайды", "photos_min": "Кемінде бір фото қалдырыңыз",
            "photos_none": "Фото жүктелмеді — байланысты тексеріп, студияны қайта ашыңыз.",
            "move_left": "Ертерек", "move_right": "Кейінірек", "photo_n": "%d-фото", "on": "роликте", "off": "алынды",
            "texts": "Мәтіндер", "f_title": "Атауы", "f_price": "Бағасы", "f_cta": "Соңындағы үндеу",
            "make_image": "Сурет", "tag_now": "бірден", "make_video": "Бейне",
            "prep": "Кадрлар дайындалуда…", "render": "Рендер %d%%", "mux": "MP4 жиналуда…", "cancel": "Болдырмау",
            "cancelled": "Бейне жасау тоқтатылды",
            "ready": "Дайын! «Бөлісу» басып → Reels / TikTok таңдаңыз (бейне өзі қойылады).",
            "ready_snd": "Дыбыспен.", "ready_nosnd": "Бұл құрылғыда дыбыс жазылмады — бейне дыбыссыз.",
            "fail": "Бұл құрылғыда бейне жасау мүмкін болмады. «Бейне» түймесін қайта басыңыз.",
            "save": "Галереяға", "saved": "Ролик галереяға сақталды",
            "save_fail": "Галереяға рұқсат жоқ — Баптауларда фото қосуға рұқсат беріңіз",
            "share": "Бөлісу", "remake": "↻ Қайта жасау",
            "reels": "Instagram Reels", "stories": "Instagram Stories", "tiktok": "TikTok",
            "caption_copied": "Сілтемесі бар жазба көшірілді — оны ролик астына қойыңыз",
            "image_making": "Сурет дайындалуда…", "image_fail": "Сурет жасау мүмкін болмады",
            "autopost": "Бизнес-аккаунтқа автожариялау", "ap_loading": "Жүктелуде…",
            "post_to": "%@ желісіне жариялау", "connect": "%@ қосу",
            "connect_sub": "бір рет — кейін 1 басумен жариялау", "soon": "жақында — әкімші қосады",
            "posting": "Жариялануда…", "posted": "Жарияланды ✓", "posted_to": "%@ желісінде жарияланды ✓",
            "post_fail": "Жариялау мүмкін болмады", "connecting": "%@ қосуға өтудеміз…",
            "no_conn": "Интернет байланысы жоқ", "pro_need": "Автожариялау — PRO тарифінде",
            "negotiable": "Келісімді", "cond_new": "Жаңа", "cond_used": "Қолданылған",
            "v_tagline": "мәмілелер алаңы", "v_trust": "Қауіпсіз мәміле: Kliko кепілі арқылы төлем",
            "v_cta": "Kliko қосымшасын жүктеңіз", "v_store": "Жүктеп алыңыз",
            "v_qr": "Камераны QR-ға бағыттаңыз — хабарландыру ашылады", "v_poster_qr": "камераны бағытта",
            "c_safe": "🛡 Kliko.kz кепілі арқылы қауіпсіз мәміле", "c_app": "📲 Kliko қосымшасы App Store-да:",
            "default_title": "Хабарландыру"
        ],
        "en": [
            "title": "Video for Reels / TikTok", "close": "Close", "loading": "Preparing the studio…",
            "hint": "The style is picked automatically — tap “Style” for another one.",
            "style": "Style", "style_other": "Another style",
            "st_emerald": "Emerald", "st_noir": "Noir · gold", "st_violet": "Ultraviolet", "st_minimal": "Minimal",
            "st_sunset": "Sunset",
            "sound": "Kliko signature sound", "volume": "Volume",
            "photos": "Photos in the video", "photos_hint": "Tap a photo to remove or return it. Arrows change the order.",
            "photos_max": "A video holds up to 5 photos", "photos_min": "Keep at least one photo",
            "photos_none": "Photos didn't load — check your connection and open the studio again.",
            "move_left": "Earlier", "move_right": "Later", "photo_n": "Photo %d", "on": "in the video", "off": "removed",
            "texts": "Texts", "f_title": "Title", "f_price": "Price", "f_cta": "Call to action at the end",
            "make_image": "Image", "tag_now": "instant", "make_video": "Video",
            "prep": "Preparing frames…", "render": "Rendering %d%%", "mux": "Building MP4…", "cancel": "Cancel",
            "cancelled": "Video creation cancelled",
            "ready": "Done! Tap “Share” → choose Reels / TikTok (the video is attached automatically).",
            "ready_snd": "With sound.", "ready_nosnd": "Sound couldn't be recorded on this device — the video is silent.",
            "fail": "Couldn't create the video on this device. Tap “Video” again.",
            "save": "Save to Photos", "saved": "Video saved to Photos",
            "save_fail": "No access to Photos — allow adding photos in Settings",
            "share": "Share", "remake": "↻ Make again",
            "reels": "Instagram Reels", "stories": "Instagram Stories", "tiktok": "TikTok",
            "caption_copied": "Caption with the link copied — paste it under the video",
            "image_making": "Preparing the image…", "image_fail": "Couldn't create the image",
            "autopost": "Autopost to business account", "ap_loading": "Loading…",
            "post_to": "Post to %@", "connect": "Connect %@",
            "connect_sub": "once — then post in 1 tap", "soon": "soon — connected by the administrator",
            "posting": "Posting…", "posted": "Posted ✓", "posted_to": "Posted to %@ ✓",
            "post_fail": "Couldn't post", "connecting": "Opening %@ connection…",
            "no_conn": "No internet connection", "pro_need": "Autopost is part of the PRO plan",
            "negotiable": "Negotiable", "cond_new": "New", "cond_used": "Used",
            "v_tagline": "deals marketplace", "v_trust": "Safe deal: payment via Kliko escrow",
            "v_cta": "Get the Kliko app", "v_store": "Download on the",
            "v_qr": "Point your camera at the QR — the listing opens", "v_poster_qr": "scan with camera",
            "c_safe": "🛡 Safe deal via escrow on Kliko.kz", "c_app": "📲 Kliko app on the App Store:",
            "default_title": "Listing"
        ],
        "ar": [
            "title": "فيديو لـ Reels / TikTok", "close": "إغلاق", "loading": "جارٍ تجهيز الاستوديو…",
            "hint": "يُختار النمط تلقائيًا — اضغط «النمط» لنمط آخر.",
            "style": "النمط", "style_other": "نمط آخر",
            "st_emerald": "زمرد", "st_noir": "نوار · ذهبي", "st_violet": "بنفسجي", "st_minimal": "بسيط",
            "st_sunset": "غروب",
            "sound": "صوت Kliko المميز", "volume": "مستوى الصوت",
            "photos": "الصور في الفيديو", "photos_hint": "اضغط على صورة لإزالتها أو إعادتها. الأسهم تغيّر الترتيب.",
            "photos_max": "يتسع الفيديو لـ 5 صور كحد أقصى", "photos_min": "اترك صورة واحدة على الأقل",
            "photos_none": "لم تُحمَّل الصور — تحقق من الاتصال وافتح الاستوديو مرة أخرى.",
            "move_left": "أبكر", "move_right": "لاحقًا", "photo_n": "الصورة %d", "on": "في الفيديو", "off": "أُزيلت",
            "texts": "النصوص", "f_title": "العنوان", "f_price": "السعر", "f_cta": "دعوة في النهاية",
            "make_image": "صورة", "tag_now": "فورًا", "make_video": "فيديو",
            "prep": "جارٍ تجهيز اللقطات…", "render": "المعالجة %d%%", "mux": "جارٍ تجميع MP4…", "cancel": "إلغاء",
            "cancelled": "أُلغي إنشاء الفيديو",
            "ready": "تم! اضغط «مشاركة» ← اختر Reels / TikTok (يُرفق الفيديو تلقائيًا).",
            "ready_snd": "مع الصوت.", "ready_nosnd": "تعذّر تسجيل الصوت على هذا الجهاز — الفيديو بلا صوت.",
            "fail": "تعذّر إنشاء الفيديو على هذا الجهاز. اضغط «فيديو» مرة أخرى.",
            "save": "حفظ في الصور", "saved": "تم حفظ الفيديو في الصور",
            "save_fail": "لا يوجد وصول إلى الصور — اسمح بإضافة الصور من الإعدادات",
            "share": "مشاركة", "remake": "↻ إنشاء من جديد",
            "reels": "Instagram Reels", "stories": "Instagram Stories", "tiktok": "TikTok",
            "caption_copied": "تم نسخ النص مع الرابط — ألصقه تحت الفيديو",
            "image_making": "جارٍ تجهيز الصورة…", "image_fail": "تعذّر إنشاء الصورة",
            "autopost": "النشر التلقائي في حساب الأعمال", "ap_loading": "جارٍ التحميل…",
            "post_to": "انشر في %@", "connect": "اربط %@",
            "connect_sub": "مرة واحدة — ثم النشر بلمسة", "soon": "قريبًا — يربطه المسؤول",
            "posting": "جارٍ النشر…", "posted": "تم النشر ✓", "posted_to": "تم النشر في %@ ✓",
            "post_fail": "تعذّر النشر", "connecting": "جارٍ الانتقال لربط %@…",
            "no_conn": "لا يوجد اتصال بالإنترنت", "pro_need": "النشر التلقائي متاح في باقة PRO",
            "negotiable": "قابل للتفاوض", "cond_new": "جديد", "cond_used": "مستعمل",
            "v_tagline": "منصة الصفقات", "v_trust": "صفقة آمنة: الدفع عبر ضمان Kliko",
            "v_cta": "حمّل تطبيق Kliko", "v_store": "حمّله من",
            "v_qr": "وجّه الكاميرا إلى رمز QR — سيفتح الإعلان", "v_poster_qr": "وجّه الكاميرا",
            "c_safe": "🛡 صفقة آمنة عبر الضمان على Kliko.kz", "c_app": "📲 تطبيق Kliko على App Store:",
            "default_title": "إعلان"
        ]
    ]
}
