import Foundation

/**
 Тексты витрины, которые добавил этап «расстояние, аренда, подсказки, истории» (владелец 26.09.2026: «витрина как
 мобильная версия сайта»). Русские — со словаря сайта js/i18n-marketplace-ru.js, ключи в скобках: vit_near_h, vit_near_s,
 vit_near_n, vit_trust_*, vit_sub_*, near_on, near_me, geo_denied, unit_m, unit_km, vert_rent, badge_rent, negotiable,
 escrow_title, escrow_hero_sub, escrow_s1…s4, escrow_ok, escrow_cta_register, escrow_cta_verify, st_news, st_more,
 st_go_*, st_hide7, st_prev, st_next; окно запрета геопозиции — из js/geo.min.js (ulxPermHint). Словарей kk/en/ar сайта в
 снимке нет — переведено тем же тоном, что прежние тексты приложения.
 */
enum ВитринаТекст {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь = тексты[язык] ?? тексты["ru"] ?? [:]
        return словарь[ключ] ?? тексты["ru"]?[ключ] ?? ключ
    }

    /// Строка с одним числом: «12 в радиусе 2 км», «следим за 3».
    static func т(_ ключ: String, число: Int) -> String {
        String(format: т(ключ), число)
    }

    private static let тексты: [String: [String: String]] = [
        "ru": [
            "near_h": "Рядом с вами", "near_s": "Включите геолокацию — покажем ближайшие",
            "near_n": "%d в радиусе 2 км", "near_on": "Показываю ближайшие к вам", "near_me": "Рядом со мной",
            "geo_denied": "Не удалось определить местоположение", "near_word": "рядом",
            "trust_h": "Гарант-сделка",
            "trust_s": "Продавец получит деньги только после того, как вы подтвердите, что вещь у вас.",
            "trust_go": "Как это работает",
            "sub_h": "Ваш поиск", "sub_s": "Сохраните поиск — пришлём, когда появится", "sub_go": "Сохранить поиск",
            "sub_n": "следим за %d", "saved": "Поиск сохранён — уведомим, когда появится", "sub_open": "Смотреть подписки",
            "close": "Закрыть", "close_near": "Закрыть — Рядом с вами", "close_trust": "Закрыть — Гарант-сделка",
            "unit_m": "м", "unit_km": "км",
            "rent": "Аренда", "negotiable": "Договорная", "cats": "Категории",
            "escrow_title": "Как работает Гарант-сделка",
            "escrow_hero": "Безопасно для обеих сторон: покупатель не потеряет деньги, а продавец гарантированно получит оплату.",
            "escrow_s1_t": "Вы оформляете сделку",
            "escrow_s1_d": "Оплата замораживается на платформе Kliko.kz. Деньги не уходят продавцу сразу — они под защитой.",
            "escrow_s2_t": "Продавец отправляет товар",
            "escrow_s2_d": "Он видит, что оплата уже заморожена, и спокойно передаёт или отправляет товар.",
            "escrow_s3_t": "Вы получаете и проверяете",
            "escrow_s3_d": "Осматриваете товар — всё ли соответствует объявлению.",
            "escrow_s4_t": "Деньги уходят продавцу",
            "escrow_s4_d": "Всё хорошо — подтверждаете, и только тогда продавец получает оплату. Не подошло — деньги возвращаются вам.",
            "escrow_ok": "Я понял", "escrow_register": "Зарегистрироваться", "escrow_verify": "Пройти верификацию",
            "perm_t": "Доступ к геопозиции запрещён",
            "perm_s": "Без него не работают «Рядом», расстояние до товара и подстановка вашего города.",
            "perm_off_t": "Геолокация выключена на устройстве",
            "perm_off_s": "Она выключена целиком, а не только для Kliko: включите её в настройках устройства, и «Рядом» с расстояниями заработают.",
            "perm_path": "Настройки  →  Конфиденциальность  →  Службы геолокации",
            "perm_settings": "Открыть настройки", "perm_ok": "Понятно",
            "st_news": "Новости и акции", "st_more": "Подробнее", "st_hide7": "Не показывать 7 дней",
            "st_prev": "Предыдущая", "st_next": "Следующая",
            "st_go_transport": "Перейти к Авто", "st_go_realty": "Перейти к Недвижимости",
            "st_go_electronics": "Перейти к Электронике", "st_go_services": "Перейти к Услугам",
            "st_go_goods": "Перейти к Товарам", "st_go_animals": "Перейти к Животным", "st_go_jobs": "Перейти к Работе"
        ],
        "kk": [
            "near_h": "Жаныңызда", "near_s": "Геолокацияны қосыңыз — ең жақындарын көрсетеміз",
            "near_n": "2 км радиуста %d", "near_on": "Сізге ең жақындарын көрсетіп тұрмын", "near_me": "Маған жақын",
            "geo_denied": "Орналасқан жерді анықтау мүмкін болмады", "near_word": "жақын",
            "trust_h": "Кепіл-мәміле",
            "trust_s": "Сатушы ақшаны зат сізде екенін растағаныңыздан кейін ғана алады.",
            "trust_go": "Бұл қалай жұмыс істейді",
            "sub_h": "Сіздің іздеуіңіз", "sub_s": "Іздеуді сақтаңыз — пайда болғанда хабарлаймыз", "sub_go": "Іздеуді сақтау",
            "sub_n": "%d іздеуді бақылап отырмыз", "saved": "Іздеу сақталды — пайда болғанда хабарлаймыз", "sub_open": "Жазылымдарды көру",
            "close": "Жабу", "close_near": "Жабу — Жаныңызда", "close_trust": "Жабу — Кепіл-мәміле",
            "unit_m": "м", "unit_km": "км",
            "rent": "Жалға", "negotiable": "Келісімді", "cats": "Санаттар",
            "escrow_title": "Кепіл-мәміле қалай жұмыс істейді",
            "escrow_hero": "Екі тарапқа да қауіпсіз: сатып алушы ақшасын жоғалтпайды, ал сатушы төлемді міндетті түрде алады.",
            "escrow_s1_t": "Сіз мәміле жасайсыз",
            "escrow_s1_d": "Төлем Kliko.kz платформасында қатырылады. Ақша сатушыға бірден кетпейді — ол қорғауда.",
            "escrow_s2_t": "Сатушы тауарды жібереді",
            "escrow_s2_d": "Ол төлемнің қатырылғанын көріп, тауарды алаңсыз береді немесе жібереді.",
            "escrow_s3_t": "Сіз алып, тексересіз",
            "escrow_s3_d": "Тауарды қарайсыз — бәрі хабарландыруға сай ма.",
            "escrow_s4_t": "Ақша сатушыға кетеді",
            "escrow_s4_d": "Бәрі жақсы болса — растайсыз, сонда ғана сатушы төлемді алады. Сәйкес келмесе — ақша өзіңізге қайтады.",
            "escrow_ok": "Түсіндім", "escrow_register": "Тіркелу", "escrow_verify": "Верификациядан өту",
            "perm_t": "Геопозицияға рұқсат жоқ",
            "perm_s": "Онсыз «Жақын», тауарға дейінгі қашықтық және қалаңызды қою жұмыс істемейді.",
            "perm_off_t": "Құрылғыда геолокация өшірулі",
            "perm_off_s": "Ол тек Kliko үшін емес, толық өшірулі: құрылғы баптауларында қосыңыз, сонда «Жақын» мен қашықтықтар жұмыс істейді.",
            "perm_path": "Баптаулар  →  Құпиялылық  →  Геолокация қызметтері",
            "perm_settings": "Баптауларды ашу", "perm_ok": "Түсінікті",
            "st_news": "Жаңалықтар мен акциялар", "st_more": "Толығырақ", "st_hide7": "7 күн көрсетпеу",
            "st_prev": "Алдыңғы", "st_next": "Келесі",
            "st_go_transport": "Авто бөліміне өту", "st_go_realty": "Жылжымайтын мүлікке өту",
            "st_go_electronics": "Электроникаға өту", "st_go_services": "Қызметтерге өту",
            "st_go_goods": "Тауарларға өту", "st_go_animals": "Жануарларға өту", "st_go_jobs": "Жұмысқа өту"
        ],
        "en": [
            "near_h": "Near you", "near_s": "Turn on location — we'll show the nearest",
            "near_n": "%d within 2 km", "near_on": "Showing the nearest to you", "near_me": "Near me",
            "geo_denied": "Couldn't determine your location", "near_word": "nearby",
            "trust_h": "Safe deal",
            "trust_s": "The seller gets the money only after you confirm the item is with you.",
            "trust_go": "How it works",
            "sub_h": "Your search", "sub_s": "Save the search — we'll tell you when it appears", "sub_go": "Save search",
            "sub_n": "watching %d", "saved": "Search saved — we'll let you know when it appears", "sub_open": "View subscriptions",
            "close": "Close", "close_near": "Close — Near you", "close_trust": "Close — Safe deal",
            "unit_m": "m", "unit_km": "km",
            "rent": "Rent", "negotiable": "Negotiable", "cats": "Categories",
            "escrow_title": "How the Safe deal works",
            "escrow_hero": "Safe for both sides: the buyer won't lose money, and the seller is guaranteed to get paid.",
            "escrow_s1_t": "You make the deal",
            "escrow_s1_d": "The payment is frozen on Kliko.kz. The money doesn't go to the seller right away — it's protected.",
            "escrow_s2_t": "The seller ships the item",
            "escrow_s2_d": "They see the payment is already frozen and hand over or ship the item with peace of mind.",
            "escrow_s3_t": "You receive and check it",
            "escrow_s3_d": "Inspect the item — does everything match the listing.",
            "escrow_s4_t": "The money goes to the seller",
            "escrow_s4_d": "All good — you confirm, and only then the seller gets paid. Not right — the money comes back to you.",
            "escrow_ok": "Got it", "escrow_register": "Sign up", "escrow_verify": "Get verified",
            "perm_t": "Location access is denied",
            "perm_s": "Without it, “Nearby”, distance to items and filling in your city don't work.",
            "perm_off_t": "Location is off on the device",
            "perm_off_s": "It's off entirely, not just for Kliko: turn it on in the device settings, and “Nearby” with distances will work.",
            "perm_path": "Settings  →  Privacy  →  Location Services",
            "perm_settings": "Open Settings", "perm_ok": "OK",
            "st_news": "News and offers", "st_more": "Learn more", "st_hide7": "Don't show for 7 days",
            "st_prev": "Previous", "st_next": "Next",
            "st_go_transport": "Go to Cars", "st_go_realty": "Go to Real estate",
            "st_go_electronics": "Go to Electronics", "st_go_services": "Go to Services",
            "st_go_goods": "Go to Goods", "st_go_animals": "Go to Animals", "st_go_jobs": "Go to Jobs"
        ],
        "ar": [
            "near_h": "بالقرب منك", "near_s": "شغّل تحديد الموقع — وسنعرض الأقرب",
            "near_n": "%d ضمن 2 كم", "near_on": "نعرض الأقرب إليك", "near_me": "بالقرب مني",
            "geo_denied": "تعذّر تحديد موقعك", "near_word": "قريب",
            "trust_h": "الصفقة المضمونة",
            "trust_s": "يحصل البائع على المال فقط بعد أن تؤكد أن الغرض لديك.",
            "trust_go": "كيف تعمل",
            "sub_h": "بحثك", "sub_s": "احفظ البحث — سنخبرك عندما يظهر", "sub_go": "حفظ البحث",
            "sub_n": "نتابع %d", "saved": "تم حفظ البحث — سنخبرك عندما يظهر", "sub_open": "عرض الاشتراكات",
            "close": "إغلاق", "close_near": "إغلاق — بالقرب منك", "close_trust": "إغلاق — الصفقة المضمونة",
            "unit_m": "م", "unit_km": "كم",
            "rent": "إيجار", "negotiable": "قابل للتفاوض", "cats": "الفئات",
            "escrow_title": "كيف تعمل الصفقة المضمونة",
            "escrow_hero": "آمنة للطرفين: المشتري لن يخسر ماله، والبائع سيحصل على الدفعة بالتأكيد.",
            "escrow_s1_t": "تُنشئ الصفقة",
            "escrow_s1_d": "يُجمَّد المبلغ على منصة Kliko.kz. لا يذهب المال إلى البائع فورًا — إنه محمي.",
            "escrow_s2_t": "البائع يرسل الغرض",
            "escrow_s2_d": "يرى أن الدفعة مجمّدة بالفعل، فيسلّم الغرض أو يرسله بطمأنينة.",
            "escrow_s3_t": "تستلم وتتحقق",
            "escrow_s3_d": "تفحص الغرض — هل كل شيء مطابق للإعلان.",
            "escrow_s4_t": "المال يذهب إلى البائع",
            "escrow_s4_d": "كل شيء جيد — تؤكد، وعندها فقط يحصل البائع على الدفعة. لم يناسبك — يعود المال إليك.",
            "escrow_ok": "فهمت", "escrow_register": "التسجيل", "escrow_verify": "إتمام التحقق",
            "perm_t": "الوصول إلى الموقع مرفوض",
            "perm_s": "بدونه لا تعمل «بالقرب» والمسافة إلى الغرض وتعبئة مدينتك.",
            "perm_off_t": "تحديد الموقع متوقف على الجهاز",
            "perm_off_s": "إنه متوقف كليًا وليس لـ Kliko فقط: شغّله في إعدادات الجهاز، وستعمل «بالقرب» والمسافات.",
            "perm_path": "الإعدادات  →  الخصوصية  →  خدمات الموقع",
            "perm_settings": "فتح الإعدادات", "perm_ok": "حسنًا",
            "st_news": "الأخبار والعروض", "st_more": "المزيد", "st_hide7": "لا تعرض لمدة 7 أيام",
            "st_prev": "السابق", "st_next": "التالي",
            "st_go_transport": "الانتقال إلى السيارات", "st_go_realty": "الانتقال إلى العقارات",
            "st_go_electronics": "الانتقال إلى الإلكترونيات", "st_go_services": "الانتقال إلى الخدمات",
            "st_go_goods": "الانتقال إلى البضائع", "st_go_animals": "الانتقال إلى الحيوانات", "st_go_jobs": "الانتقال إلى الوظائف"
        ]
    ]
}
