import Foundation

/**
 Тексты вида «как на сайте» (этапы 24–27, 49) на языке приложения (kk/ru/en/ar) — тем же способом, что лента (FeedText).

 Русские слова — с сайта, а не придуманные: словарь витрины js/i18n-marketplace-ru.js («По всей стране» — all_kz,
 «Рекомендуем» — mh_reco_h, «Все» — mh_row_all, «Смотреть все» — mh_see_all, «предложение/-ия/-ий» — mh_offers_*,
 «Предложения от проверенных продавцов» — feed_reco, «Поиск по фото» — ps_search, «Не удалось загрузить подборки» —
 mh_fail), подписи нижней панели и поле поиска — из разметки главной («Категории», «Избранное», «Чат», «Кабинет»,
 «Разместить», «Что искали?»), названия разделов — MK_HOME_V, баннер — .mh-bn главной.

 Этап 49 (владелец 26.09.2026: «всё одно и то же, просто код разный»): подсказки поля поиска — те, что сервер сайта
 подставляет в #mk-q по очереди (снимки 25–26.09), подписи плиток — vsub_*, «вакансия/-и/-й» — mh_vac_*, листы баннера —
 .hp-p главной, карточки — mh_* и vit_t_* («Проверен по VIN», «Гарант»…), подгрузка — fl_*, пустая выдача — empty_*,
 баннер «Продавай на Kliko.kz» — .mk-banner, подвал — .ulxsf. Словарей kk/en/ar сайта в снимке нет — переведено тем же
 тоном, что прежние тексты приложения.
 */
enum DesignText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? тексты["ru"]!
        return словарь[ключ] ?? тексты["ru"]![ключ] ?? ключ
    }

    /// Язык текстов — как у всего приложения: первый предпочитаемый (его ставит и переключатель языка в шапке, этап 49).
    static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    /// «26 предложений»: число с неразрывными пробелами тысяч и слово в нужной форме (_mhCount сайта).
    static func предложений(_ n: Int) -> String {
        число(n) + "\u{00A0}" + т("offers" + форма(n))
    }

    /// «3 вакансии» — _mhCount(n, true) у плитки и ряда «Работа».
    static func вакансий(_ n: Int) -> String {
        число(n) + "\u{00A0}" + т("vac" + форма(n))
    }

    /// Окончание слова после числа: noun() сайта — «_1», «_2» или «_5»; в казахском слово после числа не меняется.
    static func форма(_ n: Int) -> String {
        switch язык {
        case "ru":
            let д = n % 10, с = n % 100
            if (11...14).contains(с) { return "_5" }
            if д == 1 { return "_1" }
            if (2...4).contains(д) { return "_2" }
            return "_5"
        case "en", "ar":
            return n == 1 ? "_1" : "_5"
        default:
            return "_1"
        }
    }

    /// «1 234» — как fmt() сайта: разряды неразрывным пробелом.
    static func число(_ n: Int) -> String {
        формат.string(from: NSNumber(value: n)) ?? String(n)
    }

    /// Подсказки поля поиска: сервер сайта ставит в #mk-q одну из них при каждой отрисовке страницы.
    static var подсказкиПоиска: [String] {
        (1...6).map { т("ph_\($0)") }
    }

    private static let формат: NumberFormatter = {
        let ф = NumberFormatter()
        ф.numberStyle = .decimal
        ф.groupingSeparator = "\u{00A0}"
        ф.maximumFractionDigits = 0
        return ф
    }()

    private static let тексты: [String: [String: String]] = [
        "ru": [
            "all_kz": "По всей стране", "search": "Что искали?", "photo": "Поиск по фото", "on_site": "Откроется в приложении",
            "city": "Город", "theme": "Тема оформления", "clear": "Очистить", "lang": "Язык",
            "ph_1": "Что искали?", "ph_2": "Что ищете?", "ph_3": "Поиск…", "ph_4": "Поиск по объявлениям",
            "ph_5": "Введите ключевое слово", "ph_6": "Найти объявление…",
            "reco": "Рекомендуем", "row_all": "Все", "see_all": "Смотреть все",
            "feed": "Предложения от проверенных продавцов", "feed_query": "По запросу «%@»",
            "offers_1": "предложение", "offers_2": "предложения", "offers_5": "предложений",
            "vac_1": "вакансия", "vac_2": "вакансии", "vac_5": "вакансий",
            "fail": "Не удалось загрузить подборки", "retry": "Повторить",
            "v_transport": "Авто", "v_realty": "Недвижимость", "v_electronics": "Электроника",
            "v_services": "Услуги", "v_goods": "Товары", "v_animals": "Животные", "v_jobs": "Работа", "v_all": "Все",
            "sub_transport": "Легковые, мото, запчасти", "sub_realty": "Квартиры, дома, участки",
            "sub_electronics": "Телефоны, ноутбуки, ТВ", "sub_services": "Мастера и специалисты",
            "sub_goods": "Одежда, дом, дети, спорт", "sub_animals": "Собаки, кошки, птицы, корм",
            "sub_jobs": "Вакансии и резюме",
            "banner": "Баннер Kliko",
            "bn_import_t": "Перенесём ваши объявления", "bn_import_s": "Пришлите прайс или фото — Kliko AI соберёт карточки сам",
            "bn_import_b": "Перенести",
            "bn_sell_t": "Продавайте на Kliko", "bn_sell_s": "Разместить объявление — бесплатно", "bn_sell_b": "Разместить",
            "bn_bid_t": "Торгуйтесь по-настоящему", "bn_bid_s": "Предложите свою цену — ответ придёт в чат",
            "bn_bid_b": "Подробнее",
            "bn_escrow_t": "Безопасная сделка", "bn_escrow_s": "Деньги у Kliko, пока вы не получите товар",
            "bn_escrow_b": "Как это работает",
            "hp_import_t": "Перенесём ваши объявления", "hp_import_s": "Три шага — и ваш товар на витрине",
            "hp_import_1": "Пришлите прайс или фото", "hp_import_1s": "Таблица, список, снимки ценников — подойдёт то, что уже есть",
            "hp_import_2": "Kliko AI соберёт карточки", "hp_import_2s": "Сам разберёт названия, цены и характеристики и разложит по разделам",
            "hp_import_3": "Проверьте и опубликуйте", "hp_import_3s": "Всё открыто для правки до публикации — пачкой или по одному",
            "hp_import_go": "Начать перенос",
            "hp_sell_t": "Продавайте на Kliko", "hp_sell_s": "Площадка, где безопасность сделки — не обещание, а порядок работы",
            "hp_sell_1": "Безопасная сделка", "hp_sell_1s": "Деньги у Kliko, пока покупатель не получит товар, — потом сразу вам",
            "hp_sell_2": "Продавцы подтверждены через eGov",
            "hp_sell_2s": "Вход и регистрация — по ИИН и биометрии. За объявлением стоит человек, а не одноразовый номер",
            "hp_sell_3": "Переписка и торг на площадке", "hp_sell_3s": "Цена, условия и договорённости остаются в чате — их видно обеим сторонам",
            "hp_sell_4": "Разместить — бесплатно", "hp_sell_4s": "Объявление выходит в ленту без оплаты; платите только за продвижение, если захотите",
            "hp_sell_go": "Регистрация продавца через eGov",
            "hp_sell_go_verify": "Пройти верификацию через eGov", "hp_sell_go_post": "Разместить объявление",
            "hp_bid_t": "Торгуйтесь по-настоящему", "hp_bid_s": "Не «уточните цену», а предложение, на которое отвечают",
            "hp_bid_1": "Предложите свою цену", "hp_bid_1s": "Ответ придёт в чат карточкой: продавец принимает или называет свою",
            "hp_bid_2": "Продавец проверен", "hp_bid_2s": "Личность подтверждена через eGov — видно ещё до того, как вы написали",
            "hp_bid_3": "Предложение можно подкрепить деньгами",
            "hp_bid_3s": "Предоплата через Безопасную сделку показывает серьёзность намерения и возвращается, если не сошлись",
            "hp_bid_card_h": "Ваше предложение", "hp_bid_card_b": "Подкрепить деньгами?", "hp_bid_go": "Понятно",
            "hp_ai_t": "Kliko AI соберёт объявление за вас", "hp_ai_s": "Сфотографируйте вещь — название, раздел и характеристики заполнятся сами",
            "close": "Закрыть",
            "mln": "млн", "y": "г.", "km": "км", "l": "л", "gb": "ГБ", "tb": "ТБ", "gb_ram": "ГБ ОЗУ",
            "rooms": "%@-комн.", "studio": "Студия", "m2": "м²", "fl": "эт.", "sot": "сот.", "rooms_chip": "комн.",
            "sal_from": "от %@", "sal_to": "до %@", "sal_none": "Зарплата не указана", "respond": "Откликнуться",
            "emp_full": "Полная занятость", "emp_part": "Частичная занятость", "emp_shift": "Вахта", "emp_remote": "Удалённо",
            "emp_internship": "Стажировка",
            "reserved": "Резерв", "t_vin": "Проверен по VIN", "t_cad": "Кадастр проверен", "t_imei": "IMEI проверен",
            "t_warranty": "Гарантия %@", "t_master": "Мастер проверен", "t_escrow": "Безопасно", "t_eds": "Подпись eGov",
            "r_studio": "Студия", "r_none": "Без ремонта", "r_cosmetic": "Косметический", "r_euro": "Евроремонт",
            "r_design": "Дизайнерский", "r_brick": "Кирпичный", "r_panel": "Панельный", "r_monolith": "Монолитный",
            "r_block": "Блочный", "r_separate": "Раздельный", "r_combined": "Совмещённый", "r_two": "Два и более",
            "r_private": "Частная собственность", "r_share": "Долевая", "r_mortgage": "В ипотеке", "r_other": "Другое",
            "r_long": "Долгосрочно", "r_daily": "Посуточно", "r_owner": "Собственник", "r_agent": "Риелтор", "r_ijs": "ИЖС",
            "r_garden": "Садовый", "r_farm": "КХ", "r_commercial": "Коммерческое",
            "rl_mortgage_ok": "Ипотека", "rl_utilities": "Коммунальные включены", "rl_furniture": "Мебель и техника",
            "rl_kids": "Можно с детьми", "rl_pets": "Можно с животными", "rl_parking": "Есть парковка",
            "fl_loading": "Загружаем объявления", "fl_more": "Подгружаем ещё объявления",
            "fl_slow": "Сеть медленная — пожалуйста, подождите",
            "empty_sub": "Попробуйте другой запрос или сбросьте фильтры",
            "sell_h": "Продавай на Kliko.kz", "sell_p": "Бесплатно · Безопасная сделка · Аудитория по всему Казахстану", "sell_p_np": "Бесплатно · Аудитория по всему Казахстану",
            "sell_b": "Разместить объявление →",
            "f_about": "Маркетплейс с безопасными сделками: деньги у Kliko, пока вы не получите товар.", "f_about_np": "Маркетплейс Казахстана: покупайте и продавайте удобно.",
            "f_buyers": "Покупателям", "f_help": "Справочный центр", "f_safe": "Как работает Безопасная сделка", "f_pay": "Оплата и возврат",
            "f_sellers": "Продавцам", "f_pro": "Возможности PRO", "f_tariffs": "Услуги и цены", "f_cabinet": "Профиль",
            "f_rules": "Что запрещено", "f_docs": "Документы", "f_agreement": "Соглашение", "f_offer": "Оферта",
            "f_privacy": "Конфиденциальность", "f_company": "ТОО «КЛИКО»", "f_bin": "БИН 260840012679",
            "f_address": "Казахстан, г. Астана, проспект Абай, дом 30", "f_hours": "Пн–Пт 10:00–18:00",
            "f_copy": "© 2026 Kliko.kz · Казахстан. Все права защищены. Использование сайта означает согласие с",
            "f_copy_link": "условиями площадки",
            "f_tm": "Названия и логотипы марок принадлежат их правообладателям и показаны для опознавания товаров.",
            "f_more": "Подробнее",
            "f_reg": "Внесён в государственный реестр прав на объекты, охраняемые авторским правом, № 77232",
            "f_pay_cards": "Оплата картой: Visa, Mastercard", "f_pay_secure": "Оплата защищена 3-D Secure",
            "f_pay_psp": "ТОО «Freedom Pay»", "f_pay_nostore": "данные карты не хранятся",
            "f_pay_open": "Откроет сайт платёжной организации", "f_app": "Kliko.kz для iOS · версия %@ (сборка %@)",
            "f_mail": "Написать в поддержку", "f_call": "Позвонить в поддержку",
            "nav": "Основная навигация", "categories": "Категории", "home": "Главная", "favorites": "Избранное",
            "chat": "Чат", "cabinet": "Профиль", "post": "Разместить", "sell": "Продать", "unread": "Непрочитанных: %d"
        ],
        "kk": [
            "all_kz": "Бүкіл Қазақстан", "search": "Не іздедіңіз?", "photo": "Фото бойынша іздеу", "on_site": "Қолданбада ашылады",
            "city": "Қала", "theme": "Безендіру тақырыбы", "clear": "Тазалау", "lang": "Тіл",
            "ph_1": "Не іздедіңіз?", "ph_2": "Не іздеп жүрсіз?", "ph_3": "Іздеу…", "ph_4": "Хабарландырулардан іздеу",
            "ph_5": "Кілт сөзді енгізіңіз", "ph_6": "Хабарландыру табу…",
            "reco": "Ұсынамыз", "row_all": "Барлығы", "see_all": "Барлығын көру",
            "feed": "Тексерілген сатушылардың ұсыныстары", "feed_query": "«%@» сұрауы бойынша",
            "offers_1": "ұсыныс", "offers_2": "ұсыныс", "offers_5": "ұсыныс",
            "vac_1": "бос орын", "vac_2": "бос орын", "vac_5": "бос орын",
            "fail": "Топтамалар жүктелмеді", "retry": "Қайталау",
            "v_transport": "Көлік", "v_realty": "Жылжымайтын мүлік", "v_electronics": "Электроника",
            "v_services": "Қызметтер", "v_goods": "Тауарлар", "v_animals": "Жануарлар", "v_jobs": "Жұмыс", "v_all": "Барлығы",
            "sub_transport": "Жеңіл көліктер, мото, бөлшектер", "sub_realty": "Пәтерлер, үйлер, жер телімдері",
            "sub_electronics": "Телефондар, ноутбуктер, ТВ", "sub_services": "Шеберлер мен мамандар",
            "sub_goods": "Киім, үй, балалар, спорт", "sub_animals": "Иттер, мысықтар, құстар, жем",
            "sub_jobs": "Бос орындар мен түйіндемелер",
            "banner": "Kliko баннері",
            "bn_import_t": "Хабарландыруларыңызды көшіреміз", "bn_import_s": "Прайс немесе фото жіберіңіз — Kliko AI карточкаларды өзі жинайды",
            "bn_import_b": "Көшіру",
            "bn_sell_t": "Kliko-да сатыңыз", "bn_sell_s": "Хабарландыру беру — тегін", "bn_sell_b": "Жариялау",
            "bn_bid_t": "Шынымен саудаласыңыз", "bn_bid_s": "Өз бағаңызды ұсыныңыз — жауап чатқа келеді",
            "bn_bid_b": "Толығырақ",
            "bn_escrow_t": "Қауіпсіз мәміле", "bn_escrow_s": "Тауарды алғанша ақша Kliko-да тұрады",
            "bn_escrow_b": "Бұл қалай жұмыс істейді",
            "hp_import_t": "Хабарландыруларыңызды көшіреміз", "hp_import_s": "Үш қадам — және тауарыңыз витринада",
            "hp_import_1": "Прайс немесе фото жіберіңіз", "hp_import_1s": "Кесте, тізім, баға белгілерінің суреттері — барын жіберсеңіз болды",
            "hp_import_2": "Kliko AI карточкаларды жинайды", "hp_import_2s": "Атауларды, бағаларды және сипаттамаларды өзі талдап, бөлімдерге орналастырады",
            "hp_import_3": "Тексеріп, жариялаңыз", "hp_import_3s": "Жарияланғанға дейін бәрін түзетуге болады — топтап немесе бір-бірден",
            "hp_import_go": "Көшіруді бастау",
            "hp_sell_t": "Kliko-да сатыңыз", "hp_sell_s": "Мәміле қауіпсіздігі уәде емес, жұмыс тәртібі болатын алаң",
            "hp_sell_1": "Қауіпсіз мәміле", "hp_sell_1s": "Сатып алушы тауарды алғанша ақша Kliko-да, содан кейін бірден сізге",
            "hp_sell_2": "Сатушылар eGov арқылы расталған",
            "hp_sell_2s": "Кіру және тіркелу — ЖСН мен биометрия арқылы. Хабарландырудың артында бір реттік нөмір емес, адам тұр",
            "hp_sell_3": "Хат алмасу мен сауда алаңда", "hp_sell_3s": "Баға, шарттар мен келісімдер чатта қалады — оны екі тарап та көреді",
            "hp_sell_4": "Жариялау — тегін", "hp_sell_4s": "Хабарландыру лентаға ақысыз шығады; қаласаңыз, тек жарнамалау үшін төлейсіз",
            "hp_sell_go": "eGov арқылы сатушы ретінде тіркелу",
            "hp_sell_go_verify": "eGov арқылы верификациядан өту", "hp_sell_go_post": "Хабарландыру беру",
            "hp_bid_t": "Шынымен саудаласыңыз", "hp_bid_s": "«Бағаны нақтылаңыз» емес, жауап берілетін ұсыныс",
            "hp_bid_1": "Өз бағаңызды ұсыныңыз", "hp_bid_1s": "Жауап чатқа карточка болып келеді: сатушы қабылдайды немесе өз бағасын айтады",
            "hp_bid_2": "Сатушы тексерілген", "hp_bid_2s": "Тұлғасы eGov арқылы расталған — мұны жазбас бұрын-ақ көресіз",
            "hp_bid_3": "Ұсынысты ақшамен бекітуге болады",
            "hp_bid_3s": "Қауіпсіз мәміле арқылы алдын ала төлем ниетіңіздің байыптылығын көрсетеді, келіспесеңіз — қайтарылады",
            "hp_bid_card_h": "Сіздің ұсынысыңыз", "hp_bid_card_b": "Ақшамен бекіту керек пе?", "hp_bid_go": "Түсінікті",
            "hp_ai_t": "Kliko AI хабарландыруды сіз үшін жинайды", "hp_ai_s": "Затты суретке түсіріңіз — атауы, бөлімі мен сипаттамалары өздігінен толтырылады",
            "close": "Жабу",
            "mln": "млн", "y": "ж.", "km": "км", "l": "л", "gb": "ГБ", "tb": "ТБ", "gb_ram": "ГБ ЖЖҚ",
            "rooms": "%@ бөлмелі", "studio": "Студия", "m2": "м²", "fl": "қабат", "sot": "сот.", "rooms_chip": "бөлме",
            "sal_from": "%@ бастап", "sal_to": "%@ дейін", "sal_none": "Жалақы көрсетілмеген", "respond": "Өтініш беру",
            "emp_full": "Толық жұмыс күні", "emp_part": "Толық емес жұмыс күні", "emp_shift": "Вахта", "emp_remote": "Қашықтан",
            "emp_internship": "Тағылымдама",
            "reserved": "Брондалған", "t_vin": "VIN бойынша тексерілген", "t_cad": "Кадастр тексерілген", "t_imei": "IMEI тексерілген",
            "t_warranty": "Кепілдік %@", "t_master": "Шебер тексерілген", "t_escrow": "Қауіпсіз", "t_eds": "eGov қолтаңбасы",
            "r_studio": "Студия", "r_none": "Жөндеусіз", "r_cosmetic": "Косметикалық", "r_euro": "Еурожөндеу",
            "r_design": "Дизайнерлік", "r_brick": "Кірпіш", "r_panel": "Панельді", "r_monolith": "Монолитті",
            "r_block": "Блокты", "r_separate": "Бөлек", "r_combined": "Біріктірілген", "r_two": "Екі және одан көп",
            "r_private": "Жеке меншік", "r_share": "Үлестік", "r_mortgage": "Ипотекада", "r_other": "Басқа",
            "r_long": "Ұзақ мерзімге", "r_daily": "Тәулігімен", "r_owner": "Иесі", "r_agent": "Риелтор", "r_ijs": "ЖТҚ",
            "r_garden": "Бау-бақша", "r_farm": "ШҚ", "r_commercial": "Коммерциялық",
            "rl_mortgage_ok": "Ипотека", "rl_utilities": "Коммуналдық төлемдер кіреді", "rl_furniture": "Жиһаз бен техника",
            "rl_kids": "Балалармен болады", "rl_pets": "Жануарлармен болады", "rl_parking": "Тұрақ бар",
            "fl_loading": "Хабарландырулар жүктелуде", "fl_more": "Тағы хабарландырулар жүктелуде",
            "fl_slow": "Желі баяу — күте тұрыңыз",
            "empty_sub": "Басқа сұрау жазып көріңіз немесе сүзгілерді тазалаңыз",
            "sell_h": "Kliko.kz-те сатыңыз", "sell_p": "Тегін · Қауіпсіз мәміле · Бүкіл Қазақстан бойынша аудитория", "sell_p_np": "Тегін · Бүкіл Қазақстан бойынша аудитория",
            "sell_b": "Хабарландыру беру →",
            "f_about": "Қауіпсіз мәмілелері бар маркетплейс: тауарды алғанша ақша Kliko-да тұрады.", "f_about_np": "Қазақстан маркетплейсі: ыңғайлы сатып алыңыз және сатыңыз.",
            "f_buyers": "Сатып алушыларға", "f_help": "Анықтама орталығы", "f_safe": "Қауіпсіз мәміле қалай жұмыс істейді",
            "f_pay": "Төлем және қайтару", "f_sellers": "Сатушыларға", "f_pro": "PRO мүмкіндіктері", "f_tariffs": "Қызметтер мен бағалар",
            "f_cabinet": "Профиль", "f_rules": "Не тыйым салынған", "f_docs": "Құжаттар", "f_agreement": "Келісім",
            "f_offer": "Оферта", "f_privacy": "Құпиялылық", "f_company": "«КЛИКО» ЖШС", "f_bin": "БСН 260840012679",
            "f_address": "Қазақстан, Астана қ., Абай даңғылы, 30-үй", "f_hours": "Дс–Жм 10:00–18:00",
            "f_copy": "© 2026 Kliko.kz · Қазақстан. Барлық құқықтар қорғалған. Сайтты пайдалану келісуді білдіреді:",
            "f_copy_link": "алаң шарттары",
            "f_tm": "Маркалардың атаулары мен логотиптері олардың құқық иеленушілеріне тиесілі және тауарды тану үшін көрсетілген.",
            "f_more": "Толығырақ",
            "f_reg": "Авторлық құқықпен қорғалатын объектілерге құқықтардың мемлекеттік тізіліміне енгізілген, № 77232",
            "f_pay_cards": "Картамен төлеу: Visa, Mastercard", "f_pay_secure": "Төлем 3-D Secure арқылы қорғалған",
            "f_pay_psp": "«Freedom Pay» ЖШС", "f_pay_nostore": "карта деректері сақталмайды",
            "f_pay_open": "Төлем ұйымының сайтын ашады", "f_app": "Kliko.kz iOS үшін · нұсқа %@ (жинақ %@)",
            "f_mail": "Қолдауға жазу", "f_call": "Қолдауға қоңырау шалу",
            "nav": "Негізгі навигация", "categories": "Санаттар", "home": "Басты бет", "favorites": "Таңдаулылар",
            "chat": "Чат", "cabinet": "Профиль", "post": "Жариялау", "sell": "Сату", "unread": "Оқылмаған: %d"
        ],
        "en": [
            "all_kz": "All of Kazakhstan", "search": "What are you looking for?", "photo": "Search by photo",
            "on_site": "Opens in the app", "city": "City", "theme": "Appearance", "clear": "Clear", "lang": "Language",
            "ph_1": "What are you looking for?", "ph_2": "Looking for something?", "ph_3": "Search…", "ph_4": "Search listings",
            "ph_5": "Enter a keyword", "ph_6": "Find a listing…",
            "reco": "Recommended", "row_all": "All", "see_all": "See all",
            "feed": "Offers from verified sellers", "feed_query": "Results for “%@”",
            "offers_1": "offer", "offers_2": "offers", "offers_5": "offers",
            "vac_1": "vacancy", "vac_2": "vacancies", "vac_5": "vacancies",
            "fail": "Couldn't load the collections", "retry": "Try again",
            "v_transport": "Vehicles", "v_realty": "Real estate", "v_electronics": "Electronics",
            "v_services": "Services", "v_goods": "Goods", "v_animals": "Animals", "v_jobs": "Jobs", "v_all": "All",
            "sub_transport": "Cars, motorcycles, parts", "sub_realty": "Apartments, houses, land",
            "sub_electronics": "Phones, laptops, TV", "sub_services": "Pros and specialists",
            "sub_goods": "Clothes, home, kids, sport", "sub_animals": "Dogs, cats, birds, pet food",
            "sub_jobs": "Vacancies and resumes",
            "banner": "Kliko banner",
            "bn_import_t": "We'll move your listings", "bn_import_s": "Send a price list or photos — Kliko AI builds the listings itself",
            "bn_import_b": "Move",
            "bn_sell_t": "Sell on Kliko", "bn_sell_s": "Posting a listing is free", "bn_sell_b": "Post",
            "bn_bid_t": "Bargain for real", "bn_bid_s": "Offer your price — the answer comes to the chat",
            "bn_bid_b": "Learn more",
            "bn_escrow_t": "Safe deal", "bn_escrow_s": "Kliko holds the money until you receive the item",
            "bn_escrow_b": "How it works",
            "hp_import_t": "We'll move your listings", "hp_import_s": "Three steps — and your goods are on the showcase",
            "hp_import_1": "Send a price list or photos", "hp_import_1s": "A spreadsheet, a list, photos of price tags — whatever you already have",
            "hp_import_2": "Kliko AI builds the listings", "hp_import_2s": "It reads names, prices and specs itself and sorts them into categories",
            "hp_import_3": "Check and publish", "hp_import_3s": "Everything can be edited before publishing — in bulk or one by one",
            "hp_import_go": "Start moving",
            "hp_sell_t": "Sell on Kliko", "hp_sell_s": "A marketplace where a safe deal is not a promise but the way things work",
            "hp_sell_1": "Safe deal", "hp_sell_1s": "Kliko holds the money until the buyer receives the item — then it goes straight to you",
            "hp_sell_2": "Sellers verified with eGov",
            "hp_sell_2s": "Sign-in and sign-up use the IIN and biometrics. Behind a listing there is a person, not a throwaway number",
            "hp_sell_3": "Messages and bargaining on the platform", "hp_sell_3s": "Price, terms and agreements stay in the chat — both sides can see them",
            "hp_sell_4": "Posting is free", "hp_sell_4s": "A listing goes to the feed at no charge; you pay only for promotion, if you want it",
            "hp_sell_go": "Register as a seller with eGov",
            "hp_sell_go_verify": "Get verified with eGov", "hp_sell_go_post": "Post a listing",
            "hp_bid_t": "Bargain for real", "hp_bid_s": "Not “ask for the price” but an offer that gets an answer",
            "hp_bid_1": "Offer your price", "hp_bid_1s": "The answer comes to the chat as a card: the seller accepts or names their own",
            "hp_bid_2": "The seller is verified", "hp_bid_2s": "Identity confirmed with eGov — you can see it before you write",
            "hp_bid_3": "An offer can be backed with money",
            "hp_bid_3s": "A prepayment through the Safe deal shows you are serious and comes back if you don't agree",
            "hp_bid_card_h": "Your offer", "hp_bid_card_b": "Back it with money?", "hp_bid_go": "Got it",
            "hp_ai_t": "Kliko AI builds the listing for you", "hp_ai_s": "Take a photo of the item — the name, category and specs fill in themselves",
            "close": "Close",
            "mln": "mln", "y": "", "km": "km", "l": "L", "gb": "GB", "tb": "TB", "gb_ram": "GB RAM",
            "rooms": "%@-room", "studio": "Studio", "m2": "m²", "fl": "fl.", "sot": "ares", "rooms_chip": "rooms",
            "sal_from": "from %@", "sal_to": "up to %@", "sal_none": "Salary not specified", "respond": "Apply",
            "emp_full": "Full-time", "emp_part": "Part-time", "emp_shift": "Rotational shifts", "emp_remote": "Remote",
            "emp_internship": "Internship",
            "reserved": "Reserved", "t_vin": "VIN checked", "t_cad": "Cadastre checked", "t_imei": "IMEI checked",
            "t_warranty": "Warranty %@", "t_master": "Verified pro", "t_escrow": "Safe", "t_eds": "eGov-signed",
            "r_studio": "Studio", "r_none": "No renovation", "r_cosmetic": "Cosmetic", "r_euro": "Euro-style renovation",
            "r_design": "Designer", "r_brick": "Brick", "r_panel": "Panel", "r_monolith": "Monolithic",
            "r_block": "Block", "r_separate": "Separate", "r_combined": "Combined", "r_two": "Two or more",
            "r_private": "Private ownership", "r_share": "Shared", "r_mortgage": "Mortgaged", "r_other": "Other",
            "r_long": "Long-term", "r_daily": "Daily", "r_owner": "Owner", "r_agent": "Agent", "r_ijs": "Private housing",
            "r_garden": "Garden", "r_farm": "Farm", "r_commercial": "Commercial",
            "rl_mortgage_ok": "Mortgage", "rl_utilities": "Utilities included", "rl_furniture": "Furniture and appliances",
            "rl_kids": "Kids welcome", "rl_pets": "Pets welcome", "rl_parking": "Parking",
            "fl_loading": "Loading listings", "fl_more": "Loading more listings",
            "fl_slow": "The network is slow — please wait",
            "empty_sub": "Try another search or reset the filters",
            "sell_h": "Sell on Kliko.kz", "sell_p": "Free · Safe deal · Buyers all over Kazakhstan", "sell_p_np": "Free · Buyers all over Kazakhstan",
            "sell_b": "Post a listing →",
            "f_about": "A marketplace with safe deals: Kliko holds the money until you receive the item.", "f_about_np": "Kazakhstan's marketplace: buy and sell with ease.",
            "f_buyers": "For buyers", "f_help": "Help center", "f_safe": "How the Safe deal works", "f_pay": "Payment and refunds",
            "f_sellers": "For sellers", "f_pro": "PRO features", "f_tariffs": "Services and prices", "f_cabinet": "Profile",
            "f_rules": "What is prohibited", "f_docs": "Documents", "f_agreement": "User agreement", "f_offer": "Public offer",
            "f_privacy": "Privacy", "f_company": "KLIKO LLP", "f_bin": "BIN 260840012679",
            "f_address": "30 Abay Avenue, Astana, Kazakhstan", "f_hours": "Mon–Fri 10:00–18:00",
            "f_copy": "© 2026 Kliko.kz · Kazakhstan. All rights reserved. Using the website means you agree to the",
            "f_copy_link": "platform terms",
            "f_tm": "Brand names and logos belong to their owners and are shown to identify the goods.",
            "f_more": "Learn more",
            "f_reg": "Entered in the state register of rights to copyright-protected works, No. 77232",
            "f_pay_cards": "Card payment: Visa, Mastercard", "f_pay_secure": "Payments protected by 3-D Secure",
            "f_pay_psp": "Freedom Pay LLP", "f_pay_nostore": "card details are not stored",
            "f_pay_open": "Opens the payment provider's website", "f_app": "Kliko.kz for iOS · version %@ (build %@)",
            "f_mail": "Email support", "f_call": "Call support",
            "nav": "Main navigation", "categories": "Categories", "home": "Home", "favorites": "Favorites",
            "chat": "Chat", "cabinet": "Profile", "post": "Post a listing", "sell": "Sell", "unread": "Unread: %d"
        ],
        "ar": [
            "all_kz": "كل كازاخستان", "search": "عمّ تبحث؟", "photo": "البحث بالصورة", "on_site": "يُفتح في التطبيق",
            "city": "المدينة", "theme": "المظهر", "clear": "مسح", "lang": "اللغة",
            "ph_1": "عمّ تبحث؟", "ph_2": "ماذا تبحث؟", "ph_3": "بحث…", "ph_4": "البحث في الإعلانات",
            "ph_5": "أدخل كلمة مفتاحية", "ph_6": "ابحث عن إعلان…",
            "reco": "نوصي به", "row_all": "الكل", "see_all": "عرض الكل",
            "feed": "عروض من بائعين موثّقين", "feed_query": "نتائج «%@»",
            "offers_1": "عرض", "offers_2": "عروض", "offers_5": "عروض",
            "vac_1": "وظيفة", "vac_2": "وظائف", "vac_5": "وظائف",
            "fail": "تعذّر تحميل المجموعات", "retry": "إعادة المحاولة",
            "v_transport": "سيارات", "v_realty": "عقارات", "v_electronics": "إلكترونيات",
            "v_services": "خدمات", "v_goods": "سلع", "v_animals": "حيوانات", "v_jobs": "وظائف", "v_all": "الكل",
            "sub_transport": "سيارات ودراجات نارية وقطع غيار", "sub_realty": "شقق ومنازل وأراضٍ",
            "sub_electronics": "هواتف وحواسيب محمولة وتلفزيونات", "sub_services": "حرفيون ومتخصصون",
            "sub_goods": "ملابس ومنزل وأطفال ورياضة", "sub_animals": "كلاب وقطط وطيور وأعلاف",
            "sub_jobs": "وظائف شاغرة وسير ذاتية",
            "banner": "لافتة Kliko",
            "bn_import_t": "سننقل إعلاناتك", "bn_import_s": "أرسل قائمة أسعار أو صورًا — وسيُنشئ Kliko AI الإعلانات بنفسه",
            "bn_import_b": "انقل",
            "bn_sell_t": "بِع على Kliko", "bn_sell_s": "نشر الإعلان مجاني", "bn_sell_b": "انشر",
            "bn_bid_t": "فاوض بجدية", "bn_bid_s": "اقترح سعرك — وسيصلك الرد في الدردشة",
            "bn_bid_b": "المزيد",
            "bn_escrow_t": "صفقة آمنة", "bn_escrow_s": "يحتفظ Kliko بالمال حتى تستلم السلعة",
            "bn_escrow_b": "كيف يعمل ذلك",
            "hp_import_t": "سننقل إعلاناتك", "hp_import_s": "ثلاث خطوات — وبضاعتك في الواجهة",
            "hp_import_1": "أرسل قائمة أسعار أو صورًا", "hp_import_1s": "جدول أو قائمة أو صور بطاقات الأسعار — يكفي ما لديك",
            "hp_import_2": "Kliko AI يُنشئ الإعلانات", "hp_import_2s": "يقرأ الأسماء والأسعار والمواصفات بنفسه ويوزّعها على الأقسام",
            "hp_import_3": "راجِع وانشر", "hp_import_3s": "كل شيء قابل للتعديل قبل النشر — دفعة واحدة أو واحدًا تلو الآخر",
            "hp_import_go": "ابدأ النقل",
            "hp_sell_t": "بِع على Kliko", "hp_sell_s": "منصة يكون فيها أمان الصفقة نظام عمل لا مجرد وعد",
            "hp_sell_1": "صفقة آمنة", "hp_sell_1s": "يحتفظ Kliko بالمال حتى يستلم المشتري السلعة — ثم يذهب إليك مباشرة",
            "hp_sell_2": "البائعون موثّقون عبر eGov",
            "hp_sell_2s": "الدخول والتسجيل برقم الهوية والقياسات الحيوية. خلف الإعلان شخص حقيقي لا رقم مؤقت",
            "hp_sell_3": "المراسلة والتفاوض على المنصة", "hp_sell_3s": "السعر والشروط والاتفاقات تبقى في الدردشة — يراها الطرفان",
            "hp_sell_4": "النشر مجاني", "hp_sell_4s": "يظهر الإعلان في الموجز دون دفع؛ تدفع فقط مقابل الترويج إن أردت",
            "hp_sell_go": "التسجيل كبائع عبر eGov",
            "hp_sell_go_verify": "التحقق عبر eGov", "hp_sell_go_post": "انشر إعلانًا",
            "hp_bid_t": "فاوض بجدية", "hp_bid_s": "ليس «استفسر عن السعر» بل عرض يُرَدّ عليه",
            "hp_bid_1": "اقترح سعرك", "hp_bid_1s": "يصلك الرد في الدردشة كبطاقة: يقبل البائع أو يقترح سعره",
            "hp_bid_2": "البائع موثّق", "hp_bid_2s": "الهوية مؤكدة عبر eGov — تراها قبل أن تكتب",
            "hp_bid_3": "يمكن دعم العرض بالمال",
            "hp_bid_3s": "الدفع المسبق عبر الصفقة الآمنة يُظهر جدية نيتك ويُعاد إن لم تتفقا",
            "hp_bid_card_h": "عرضك", "hp_bid_card_b": "هل تدعمه بالمال؟", "hp_bid_go": "مفهوم",
            "hp_ai_t": "Kliko AI يُنشئ الإعلان نيابةً عنك", "hp_ai_s": "صوّر الغرض — وسيُملأ الاسم والقسم والمواصفات تلقائيًا",
            "close": "إغلاق",
            "mln": "مليون", "y": "", "km": "كم", "l": "لتر", "gb": "GB", "tb": "TB", "gb_ram": "GB RAM",
            "rooms": "%@ غرف", "studio": "استوديو", "m2": "م²", "fl": "طابق", "sot": "آر", "rooms_chip": "غرف",
            "sal_from": "من %@", "sal_to": "حتى %@", "sal_none": "الراتب غير محدد", "respond": "تقدّم",
            "emp_full": "دوام كامل", "emp_part": "دوام جزئي", "emp_shift": "عمل بالمناوبة", "emp_remote": "عن بُعد",
            "emp_internship": "تدريب",
            "reserved": "محجوز", "t_vin": "تم التحقق من VIN", "t_cad": "السجل العقاري موثّق", "t_imei": "تم التحقق من IMEI",
            "t_warranty": "ضمان %@", "t_master": "حرفي موثّق", "t_escrow": "آمن", "t_eds": "توقيع eGov",
            "r_studio": "استوديو", "r_none": "بدون تجديد", "r_cosmetic": "تجديد تجميلي", "r_euro": "تجديد أوروبي",
            "r_design": "تصميم خاص", "r_brick": "طوب", "r_panel": "ألواح", "r_monolith": "خرسانة مصبوبة",
            "r_block": "بلوك", "r_separate": "منفصل", "r_combined": "مشترك", "r_two": "اثنان أو أكثر",
            "r_private": "ملكية خاصة", "r_share": "ملكية مشتركة", "r_mortgage": "مرهون", "r_other": "أخرى",
            "r_long": "طويل الأمد", "r_daily": "يومي", "r_owner": "المالك", "r_agent": "وسيط", "r_ijs": "سكن فردي",
            "r_garden": "حديقة", "r_farm": "مزرعة", "r_commercial": "تجاري",
            "rl_mortgage_ok": "رهن عقاري", "rl_utilities": "المرافق مشمولة", "rl_furniture": "أثاث وأجهزة",
            "rl_kids": "يُسمح بالأطفال", "rl_pets": "يُسمح بالحيوانات", "rl_parking": "موقف سيارات",
            "fl_loading": "جارٍ تحميل الإعلانات", "fl_more": "جارٍ تحميل المزيد من الإعلانات",
            "fl_slow": "الشبكة بطيئة — يرجى الانتظار",
            "empty_sub": "جرّب بحثًا آخر أو أعد ضبط عوامل التصفية",
            "sell_h": "بِع على Kliko.kz", "sell_p": "مجانًا · صفقة آمنة · جمهور في كل كازاخستان", "sell_p_np": "مجانًا · جمهور في كل كازاخستان",
            "sell_b": "انشر إعلانًا →",
            "f_about": "سوق بصفقات آمنة: يحتفظ Kliko بالمال حتى تستلم السلعة.", "f_about_np": "سوق كازاخستان: اشترِ وبِع بسهولة.",
            "f_buyers": "للمشترين", "f_help": "مركز المساعدة", "f_safe": "كيف تعمل الصفقة الآمنة", "f_pay": "الدفع والاسترداد",
            "f_sellers": "للبائعين", "f_pro": "مزايا PRO", "f_tariffs": "الخدمات والأسعار", "f_cabinet": "الملف الشخصي",
            "f_rules": "ما هو محظور", "f_docs": "المستندات", "f_agreement": "اتفاقية الاستخدام", "f_offer": "العرض العام",
            "f_privacy": "الخصوصية", "f_company": "شركة KLIKO ذ.م.م", "f_bin": "BIN 260840012679",
            "f_address": "كازاخستان، أستانا، شارع أباي، 30", "f_hours": "الاثنين–الجمعة 10:00–18:00",
            "f_copy": "© 2026 Kliko.kz · كازاخستان. جميع الحقوق محفوظة. استخدام الموقع يعني موافقتك على",
            "f_copy_link": "شروط المنصة",
            "f_tm": "أسماء العلامات التجارية وشعاراتها ملك لأصحابها وتُعرض لتعريف السلع.",
            "f_more": "المزيد",
            "f_reg": "مُدرج في السجل الحكومي لحقوق المصنفات المحمية بحق المؤلف، رقم 77232",
            "f_pay_cards": "الدفع بالبطاقة: Visa، Mastercard", "f_pay_secure": "الدفع محمي بتقنية 3-D Secure",
            "f_pay_psp": "شركة Freedom Pay", "f_pay_nostore": "لا تُخزَّن بيانات البطاقة",
            "f_pay_open": "يفتح موقع مزوّد الدفع", "f_app": "Kliko.kz لنظام iOS · الإصدار %@ (البناء %@)",
            "f_mail": "راسل الدعم", "f_call": "اتصل بالدعم",
            "nav": "التنقل الرئيسي", "categories": "الفئات", "home": "الرئيسية", "favorites": "المفضلة",
            "chat": "الدردشة", "cabinet": "الملف الشخصي", "post": "انشر إعلانًا", "sell": "بيع", "unread": "غير مقروءة: %d"
        ]
    ]
}
