import Foundation

/**
 Тексты страницы объявления «как на сайте» (этапы 28–29) на языке телефона (kk/ru/en/ar) — тем же способом, что лента.

 Русские слова — со страницы объявления сайта, а не придуманные: словарь js/i18n-marketplace-ru.js («Б/У» — cond_used,
 «С пробегом» — with_mileage, «Режим работы» — hours_work_line, «Продавец утверждает» — trust_seller_claims, «Что это
 даёт» — trust_what_gives, «Связаться» — cc_btn, «Чат, звонок или WhatsApp» — cc_sticky_sub, «Предложить цену» —
 offer_sticky_t, «Торг — ответ придёт в чат» — offer_sticky_sub, «Продавец скрыл номер» — gate_phone_title…), подписи
 «Продавец утверждает» — TRUST_LABELS, советы «… — на что смотреть» — MK_BUY_TIPS (js/mk-refs-ru.js), «Новостройка» и
 «Вторичный рынок» — mkCond в js/marketplace.min.js. Текст для WhatsApp — mkRevealWa сайта («Здравствуйте! Интересует
 «…» за … ₸. Ещё актуально?»).
 */
enum ListingPageText {
    static func т(_ ключ: String) -> String {
        let код = язык
        if let своё = тексты[код]?[ключ] ?? текстыДоверия[код]?[ключ] { return своё }
        return тексты["ru"]?[ключ] ?? текстыДоверия["ru"]?[ключ] ?? ключ
    }

    static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    /// Ключи «Продавец утверждает» в порядке справочника сайта (TRUST_LABELS в js/mk-refs-ru.js).
    static let ключиЗаявлений: [String] = [
        "receipt", "working", "complete", "vin_clean", "not_crashed", "service_book", "one_owner", "docs_ok", "no_liens",
        "lawyer_checked", "mortgage_ok", "vet_passport", "sterilized", "vet_checked", "pedigree", "trained", "original",
        "tags", "measured", "no_defects", "safety_cert", "clean", "not_recalled", "guarantor", "licensed", "portfolio",
        "deposit", "contract", "condition_act", "insured", "cleaned"
    ]

    /// Слово после числа: noun() сайта — «1 отзыв», «2 отзыва», «5 отзывов». Основа ключа — «reviews», «deals»…
    static func число(_ n: Int, _ основа: String) -> String {
        let форма: String
        switch язык {
        case "ru":
            let д = n % 10, с = n % 100
            if (11...14).contains(с) { форма = "_5" }
            else if д == 1 { форма = "_1" }
            else if (2...4).contains(д) { форма = "_2" }
            else { форма = "_5" }
        case "en", "ar":
            форма = n == 1 ? "_1" : "_5"
        default:
            форма = "_1"
        }
        return String(n) + " " + т(основа + форма)
    }

    private static let тексты: [String: [String: String]] = [
        "ru": [
            "stock_in_avail": "В наличии", "stock_pcs": "%d шт", "stock_low": "осталось мало",
            "cpu_short": "Проц.", "gpu_short": "Видео", "shop": "Магазин", "hours_accepts_lbl": "Принимает звонки",
            "cond_new": "Новое", "cond_used": "Б/У", "with_mileage": "С пробегом", "no_mileage": "Без пробега",
            "realty_new": "Новостройка", "realty_used": "Вторичный рынок", "rent": "Аренда",
            "price_from": "от", "negotiable": "Договорная", "torg": "Торг", "unit_day": "сут", "unit_month": "М",
            "hours_work": "Режим работы", "hours_247": "Круглосуточно",
            "claims": "Продавец утверждает", "what_gives": "Что это даёт", "trust_title": "Знаки доверия",
            "trust_look": "На что смотреть у этого объявления", "claimed": "заявлено", "ok": "Понятно",
            "warranty": "Гарантия продавца %@", "ship_free": "Бесплатная доставка", "ship_days": "Срок ~%@ дн.",
            "month_1": "месяц", "month_2": "месяца", "month_5": "месяцев", "day_1": "день", "day_2": "дня", "day_5": "дней",
            "t_receipt": "Чек есть", "t_working": "Рабочее / проверено", "t_complete": "Полный комплект",
            "t_vin_clean": "VIN / история чистая", "t_not_crashed": "Не битый", "t_service_book": "Сервисная книжка",
            "t_one_owner": "Один владелец", "t_docs_ok": "Документы в порядке", "t_no_liens": "Без обременений",
            "t_lawyer_checked": "Проверено юристом", "t_mortgage_ok": "Можно в ипотеку", "t_vet_passport": "Ветпаспорт / привит",
            "t_sterilized": "Стерилизован", "t_vet_checked": "Осмотр ветеринара", "t_pedigree": "Клеймо / чип / родословная",
            "t_trained": "Приучен", "t_original": "Оригинал (подлинность)", "t_tags": "С бирками / чек",
            "t_measured": "Точные замеры", "t_no_defects": "Без дефектов", "t_safety_cert": "Сертификат безопасности",
            "t_clean": "Чистое / продезинф.", "t_not_recalled": "Не отзывалось", "t_guarantor": "Безопасная сделка",
            "t_licensed": "Опыт / лицензия", "t_portfolio": "Портфолио", "t_deposit": "Залог / депозит",
            "t_contract": "Договор аренды", "t_condition_act": "Проверка состояния (акт)", "t_insured": "Страховка",
            "t_cleaned": "Чистка между арендами",
            "tip_auto": "Авто — на что смотреть",
            "tip_auto_1": "Проверьте авто по VIN и базам РК — кнопка «Проверить авто»: залог, розыск, ограничения.",
            "tip_auto_2": "Пробег и кузов: сверьте с сервисной книжкой, осмотрите днём и на подъёмнике.",
            "tip_auto_3": "Документы: техпаспорт, VIN на кузове совпадает с документами, число владельцев.",
            "tip_auto_4": "Оплата — через Безопасную сделку, при личной встрече. Не отправляйте предоплату незнакомцу.",
            "tip_tech": "Техника — на что смотреть",
            "tip_tech_1": "Проверьте IMEI/серийник — кнопка «Проверка устройства»: реестр РК, чёрный список.",
            "tip_tech_2": "Блокировка: устройство сброшено и не привязано к чужому Apple ID или Google.",
            "tip_tech_3": "Проверьте вживую: включение, экран, батарея, камеры, разъёмы.",
            "tip_tech_4": "Комплект, чек и гарантия. Оплата — через Безопасную сделку.",
            "tip_realty": "Недвижимость — на что смотреть",
            "tip_realty_1": "Проверьте объект по кадастру — кнопка «Проверить недвижимость»: обременения, арест, залог.",
            "tip_realty_2": "Документы собственности: кто владелец, основание, свежая выписка.",
            "tip_realty_3": "Осмотр лично: коммуникации, состояние, район и соседи.",
            "tip_realty_4": "Задаток и оплата — через Безопасную сделку или договор, не «на слово».",
            "tip_rent": "Аренда — на что смотреть",
            "tip_rent_1": "Договор: сроки, стоимость и ответственность сторон — зафиксируйте письменно.",
            "tip_rent_2": "Залог: сумма и условия возврата — оговорите заранее.",
            "tip_rent_3": "Состояние при получении: сфотографируйте и отметьте дефекты.",
            "tip_rent_4": "Платите через Безопасную сделку — залог под защитой Kliko.",
            "tip_service": "Услуги — на что смотреть",
            "tip_service_1": "Посмотрите отзывы и примеры работ (портфолио) исполнителя.",
            "tip_service_2": "Согласуйте объём, сроки и итоговую цену до начала.",
            "tip_service_3": "Оплата через Безопасную сделку: аванс и остаток после приёмки.",
            "tip_service_4": "Не переводите деньги напрямую до выполнения работы.",
            "desc": "Описание", "added": "Добавлено %@", "views": "Просмотров: %d", "today": "сегодня",
            "yesterday": "вчера", "ago": "%@ назад",
            "months": "янв,фев,мар,апр,мая,июн,июл,авг,сен,окт,ноя,дек",
            "new_seller": "Новый продавец", "verified": "Проверен через eGov", "since": "с %@ г.",
            "reviews_1": "отзыв", "reviews_2": "отзыва", "reviews_5": "отзывов",
            "deals_1": "сделка", "deals_2": "сделки", "deals_5": "сделок",
            "similar": "Похожие объявления", "similar_svc": "Ещё в этой категории",
            "back": "Назад", "close": "Закрыть", "photo": "Фото %d из %d",
            "offer": "Предложить цену", "offer_sub": "Торг — ответ придёт в чат",
            "contact": "Связаться", "contact_sub": "Чат, звонок или WhatsApp",
            "buy_safe": "Купить безопасно", "rent_safe": "Арендовать безопасно", "on_site": "Откроется в приложении",
            "call": "Позвонить", "wa": "WhatsApp", "chat": "Чат на площадке",
            "num_unavail": "Номер временно недоступен", "contact_unavail": "Контакт временно недоступен",
            "gate_phone_t": "Продавец скрыл номер",
            "gate_phone_b": "Чтобы его не отвлекали звонками, продавец не показывает телефон. Напишите в чат — сообщение придёт ему сразу, и он ответит здесь же. Это удобно и безопасно.",
            "gate_deal_t": "Номер — после оплаты сделки",
            "gate_deal_b": "Телефон продавца откроется после оплаты через Безопасную сделку. Пока напишите ему в чат — сообщение придёт сразу, и он ответит здесь же.",
            "gate_account_t": "Нужен аккаунт",
            "gate_account_b": "Зарегистрируйтесь, чтобы связаться с продавцом и покупать. Это быстро и бесплатно.",
            "reg": "Зарегистрироваться",
            "hours_gate_t": "Звонок — в рабочее время",
            "hours_gate_b": "Чтобы не беспокоить продавца в нерабочее время, звонок доступен по расписанию. Напишите в чат прямо сейчас — сообщение точно дойдёт, а продавец ответит, когда ему будет удобно.",
            "hours_accepts": "Принимает звонки %@",
            "write_chat": "Написать в чат", "later": "Позже",
            "root_electronics": "Электроника", "root_transport": "Транспорт", "root_realty": "Недвижимость", "root_clothing": "Одежда и обувь", "root_home-garden": "Дом и сад", "root_kids": "Детские товары", "root_sport": "Спорт и отдых", "root_animals": "Животные", "root_jobs": "Работа", "root_services": "Услуги", "root_hobby": "Хобби и творчество", "root_food-farm": "Продукты и фермерство", "root_beauty": "Красота и здоровье",
            "wa_text": "Здравствуйте! Интересует «%@» за %@. Ещё актуально?"
        ],
        "kk": [
            "stock_in_avail": "Қоймада бар", "stock_pcs": "%d дана", "stock_low": "аз қалды",
            "cpu_short": "Проц.", "gpu_short": "Бейне", "shop": "Дүкен", "hours_accepts_lbl": "Қоңырау қабылдайды",
            "cond_new": "Жаңа", "cond_used": "Қолданылған", "with_mileage": "Жүрісі бар", "no_mileage": "Жүрісі жоқ",
            "realty_new": "Жаңа үй", "realty_used": "Қайталама нарық", "rent": "Жалға",
            "price_from": "бастап", "negotiable": "Келісімді", "torg": "Сауда", "unit_day": "тәул", "unit_month": "ай",
            "hours_work": "Жұмыс уақыты", "hours_247": "Тәулік бойы",
            "claims": "Сатушы растайды", "what_gives": "Бұл не береді", "trust_title": "Сенім белгілері",
            "trust_look": "Бұл хабарландыруда неге қарау керек", "claimed": "мәлімделген", "ok": "Түсінікті",
            "warranty": "Сатушы кепілдігі %@", "ship_free": "Тегін жеткізу", "ship_days": "Мерзімі ~%@ күн",
            "month_1": "ай", "month_2": "ай", "month_5": "ай", "day_1": "күн", "day_2": "күн", "day_5": "күн",
            "t_receipt": "Чегі бар", "t_working": "Жұмыс істейді / тексерілген", "t_complete": "Толық жиынтық",
            "t_vin_clean": "VIN / тарихы таза", "t_not_crashed": "Соғылмаған", "t_service_book": "Сервистік кітапша",
            "t_one_owner": "Бір иесі", "t_docs_ok": "Құжаттары дұрыс", "t_no_liens": "Ауыртпалықсыз",
            "t_lawyer_checked": "Заңгер тексерген", "t_mortgage_ok": "Ипотекаға болады", "t_vet_passport": "Ветпаспорт / егілген",
            "t_sterilized": "Стерилизацияланған", "t_vet_checked": "Ветеринар қараған", "t_pedigree": "Таңба / чип / тегі",
            "t_trained": "Үйретілген", "t_original": "Түпнұсқа", "t_tags": "Биркасымен / чегімен",
            "t_measured": "Нақты өлшемдер", "t_no_defects": "Ақаусыз", "t_safety_cert": "Қауіпсіздік сертификаты",
            "t_clean": "Таза / залалсыздандырылған", "t_not_recalled": "Кері қайтарылмаған", "t_guarantor": "Қауіпсіз мәміле",
            "t_licensed": "Тәжірибе / лицензия", "t_portfolio": "Портфолио", "t_deposit": "Кепілақы / депозит",
            "t_contract": "Жалға алу шарты", "t_condition_act": "Жай-күйін тексеру (акт)", "t_insured": "Сақтандыру",
            "t_cleaned": "Жалдау арасында тазалау",
            "tip_auto": "Көлік — неге қарау керек",
            "tip_auto_1": "Көлікті VIN және ҚР базалары бойынша тексеріңіз — «Көлікті тексеру» батырмасы: кепіл, іздеу, шектеулер.",
            "tip_auto_2": "Жүрісі мен шанағы: сервистік кітапшамен салыстырыңыз, күндіз және көтергіште қараңыз.",
            "tip_auto_3": "Құжаттар: техпаспорт, шанақтағы VIN құжатпен сәйкес, иелер саны.",
            "tip_auto_4": "Төлем — Қауіпсіз мәміле арқылы, жеке кездесуде. Бейтаныс адамға алдын ала төлем жібермеңіз.",
            "tip_tech": "Техника — неге қарау керек",
            "tip_tech_1": "IMEI/сериялық нөмірді тексеріңіз — «Құрылғыны тексеру» батырмасы: ҚР тізілімі, қара тізім.",
            "tip_tech_2": "Бұғаттау: құрылғы тазартылған және бөтен Apple ID немесе Google-ға байланбаған.",
            "tip_tech_3": "Тікелей тексеріңіз: қосылуы, экран, батарея, камералар, ұяшықтар.",
            "tip_tech_4": "Жиынтық, чек және кепілдік. Төлем — Қауіпсіз мәміле арқылы.",
            "tip_realty": "Жылжымайтын мүлік — неге қарау керек",
            "tip_realty_1": "Нысанды кадастр бойынша тексеріңіз — «Мүлікті тексеру» батырмасы: ауыртпалық, тыйым, кепіл.",
            "tip_realty_2": "Меншік құжаттары: иесі кім, негізі, жаңа үзінді.",
            "tip_realty_3": "Жеке қарау: коммуникациялар, жай-күйі, аудан және көршілер.",
            "tip_realty_4": "Кепілақы мен төлем — Қауіпсіз мәміле немесе шарт арқылы, «сөзбен» емес.",
            "tip_rent": "Жалға алу — неге қарау керек",
            "tip_rent_1": "Шарт: мерзім, құн және тараптардың жауапкершілігі — жазбаша бекітіңіз.",
            "tip_rent_2": "Кепілақы: сомасы мен қайтару шарттары — алдын ала келісіңіз.",
            "tip_rent_3": "Алған кездегі жай-күйі: суретке түсіріп, ақауларды белгілеңіз.",
            "tip_rent_4": "Қауіпсіз мәміле арқылы төлеңіз — кепілақы Kliko-ның қорғауында.",
            "tip_service": "Қызметтер — неге қарау керек",
            "tip_service_1": "Орындаушының пікірлері мен жұмыс үлгілерін (портфолио) қараңыз.",
            "tip_service_2": "Көлемін, мерзімін және түпкі бағасын басталғанға дейін келісіңіз.",
            "tip_service_3": "Қауіпсіз мәміле арқылы төлем: аванс және қабылдағаннан кейін қалдығы.",
            "tip_service_4": "Жұмыс орындалғанға дейін ақшаны тікелей аудармаңыз.",
            "desc": "Сипаттама", "added": "Қосылды %@", "views": "Қаралым: %d", "today": "бүгін",
            "yesterday": "кеше", "ago": "%@ бұрын",
            "months": "қаң,ақп,нау,сәу,мам,мау,шіл,там,қыр,қаз,қар,жел",
            "new_seller": "Жаңа сатушы", "verified": "eGov арқылы тексерілген", "since": "%@ ж. бастап",
            "reviews_1": "пікір", "reviews_2": "пікір", "reviews_5": "пікір",
            "deals_1": "мәміле", "deals_2": "мәміле", "deals_5": "мәміле",
            "similar": "Ұқсас хабарландырулар", "similar_svc": "Осы санаттағы басқалары",
            "back": "Артқа", "close": "Жабу", "photo": "%d/%d фото",
            "offer": "Баға ұсыну", "offer_sub": "Сауда — жауап чатқа келеді",
            "contact": "Байланысу", "contact_sub": "Чат, қоңырау немесе WhatsApp",
            "buy_safe": "Қауіпсіз сатып алу", "rent_safe": "Қауіпсіз жалға алу", "on_site": "Қолданбада ашылады",
            "call": "Қоңырау шалу", "wa": "WhatsApp", "chat": "Алаңдағы чат",
            "num_unavail": "Нөмір уақытша қолжетімсіз", "contact_unavail": "Байланыс уақытша қолжетімсіз",
            "gate_phone_t": "Сатушы нөмірін жасырды",
            "gate_phone_b": "Қоңыраулар алаңдатпауы үшін сатушы телефонын көрсетпейді. Чатқа жазыңыз — хабар оған бірден жетеді, ол осында жауап береді. Бұл ыңғайлы әрі қауіпсіз.",
            "gate_deal_t": "Нөмір — мәміле төленгеннен кейін",
            "gate_deal_b": "Қауіпсіз мәміле арқылы төлегеннен кейін сатушының телефоны ашылады. Әзірге чатқа жазыңыз — хабар бірден жетеді, ол осында жауап береді.",
            "gate_account_t": "Аккаунт қажет",
            "gate_account_b": "Сатушымен байланысу және сатып алу үшін тіркеліңіз. Бұл жылдам әрі тегін.",
            "reg": "Тіркелу",
            "hours_gate_t": "Қоңырау — жұмыс уақытында",
            "hours_gate_b": "Сатушыны жұмыстан тыс уақытта мазаламау үшін қоңырау кесте бойынша қолжетімді. Дәл қазір чатқа жазыңыз — хабар міндетті түрде жетеді, ал сатушы өзіне ыңғайлы кезде жауап береді.",
            "hours_accepts": "Қоңырау қабылдайды %@",
            "write_chat": "Чатқа жазу", "later": "Кейін",
            "root_electronics": "Электроника", "root_transport": "Көлік", "root_realty": "Жылжымайтын мүлік", "root_clothing": "Киім мен аяқ киім", "root_home-garden": "Үй және бақ", "root_kids": "Балалар тауарлары", "root_sport": "Спорт және демалыс", "root_animals": "Жануарлар", "root_jobs": "Жұмыс", "root_services": "Қызметтер", "root_hobby": "Хобби және шығармашылық", "root_food-farm": "Азық-түлік және фермерлік", "root_beauty": "Сұлулық және денсаулық",
            "wa_text": "Сәлеметсіз бе! «%@» %@ бағасына қызықтырады. Әлі өзекті ме?"
        ],
        "en": [
            "stock_in_avail": "In stock", "stock_pcs": "%d pcs", "stock_low": "few left",
            "cpu_short": "CPU", "gpu_short": "GPU", "shop": "Shop", "hours_accepts_lbl": "Takes calls",
            "cond_new": "New", "cond_used": "Used", "with_mileage": "Used", "no_mileage": "Brand new",
            "realty_new": "New build", "realty_used": "Resale", "rent": "For rent",
            "price_from": "from", "negotiable": "Negotiable", "torg": "Negotiable", "unit_day": "day", "unit_month": "mo",
            "hours_work": "Working hours", "hours_247": "24/7",
            "claims": "The seller states", "what_gives": "Why it matters", "trust_title": "Trust signs",
            "trust_look": "What to check for this listing", "claimed": "stated", "ok": "Got it",
            "warranty": "Seller warranty %@", "ship_free": "Free delivery", "ship_days": "About %@ days",
            "month_1": "month", "month_2": "months", "month_5": "months", "day_1": "day", "day_2": "days", "day_5": "days",
            "t_receipt": "Receipt available", "t_working": "Working / tested", "t_complete": "Complete set",
            "t_vin_clean": "Clean VIN / history", "t_not_crashed": "No accidents", "t_service_book": "Service book",
            "t_one_owner": "One owner", "t_docs_ok": "Documents in order", "t_no_liens": "No encumbrances",
            "t_lawyer_checked": "Checked by a lawyer", "t_mortgage_ok": "Mortgage possible", "t_vet_passport": "Vet passport / vaccinated",
            "t_sterilized": "Neutered", "t_vet_checked": "Vet checked", "t_pedigree": "Brand / chip / pedigree",
            "t_trained": "Trained", "t_original": "Original (authentic)", "t_tags": "With tags / receipt",
            "t_measured": "Exact measurements", "t_no_defects": "No defects", "t_safety_cert": "Safety certificate",
            "t_clean": "Clean / disinfected", "t_not_recalled": "No recalls", "t_guarantor": "Safe deal",
            "t_licensed": "Experience / licence", "t_portfolio": "Portfolio", "t_deposit": "Deposit",
            "t_contract": "Rental agreement", "t_condition_act": "Condition check (report)", "t_insured": "Insurance",
            "t_cleaned": "Cleaned between rentals",
            "tip_auto": "Cars — what to check",
            "tip_auto_1": "Check the car by VIN in Kazakhstan's databases — the “Check the car” button: liens, wanted lists, restrictions.",
            "tip_auto_2": "Mileage and body: compare with the service book, inspect in daylight and on a lift.",
            "tip_auto_3": "Documents: registration, the VIN on the body matches the papers, number of owners.",
            "tip_auto_4": "Pay through the Safe deal, in person. Never send a prepayment to a stranger.",
            "tip_tech": "Electronics — what to check",
            "tip_tech_1": "Check the IMEI/serial — the “Device check” button: Kazakhstan's register, blacklist.",
            "tip_tech_2": "Locks: the device is reset and not tied to someone else's Apple ID or Google account.",
            "tip_tech_3": "Test it in person: power, screen, battery, cameras, ports.",
            "tip_tech_4": "Box contents, receipt and warranty. Pay through the Safe deal.",
            "tip_realty": "Real estate — what to check",
            "tip_realty_1": "Check the property in the cadastre — the “Check the property” button: encumbrances, arrest, pledge.",
            "tip_realty_2": "Ownership documents: who owns it, on what basis, a fresh extract.",
            "tip_realty_3": "Visit in person: utilities, condition, the area and neighbours.",
            "tip_realty_4": "Deposit and payment — through the Safe deal or a contract, not on trust.",
            "tip_rent": "Renting — what to check",
            "tip_rent_1": "Contract: dates, price and each side's liability — put it in writing.",
            "tip_rent_2": "Deposit: the amount and how it is returned — agree in advance.",
            "tip_rent_3": "Condition on handover: take photos and note any defects.",
            "tip_rent_4": "Pay through the Safe deal — Kliko protects the deposit.",
            "tip_service": "Services — what to check",
            "tip_service_1": "Look at the provider's reviews and examples of work (portfolio).",
            "tip_service_2": "Agree on the scope, timing and final price before starting.",
            "tip_service_3": "Pay through the Safe deal: an advance, and the rest after acceptance.",
            "tip_service_4": "Don't transfer money directly before the work is done.",
            "desc": "Description", "added": "Added %@", "views": "Views: %d", "today": "today",
            "yesterday": "yesterday", "ago": "%@ ago",
            "months": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
            "new_seller": "New seller", "verified": "Verified via eGov", "since": "since %@",
            "reviews_1": "review", "reviews_2": "reviews", "reviews_5": "reviews",
            "deals_1": "deal", "deals_2": "deals", "deals_5": "deals",
            "similar": "Similar listings", "similar_svc": "More in this category",
            "back": "Back", "close": "Close", "photo": "Photo %d of %d",
            "offer": "Make an offer", "offer_sub": "Haggle — the reply comes to chat",
            "contact": "Contact", "contact_sub": "Chat, call or WhatsApp",
            "buy_safe": "Buy safely", "rent_safe": "Rent safely", "on_site": "Opens in the app",
            "call": "Call", "wa": "WhatsApp", "chat": "Chat on Kliko",
            "num_unavail": "The number is temporarily unavailable", "contact_unavail": "The contact is temporarily unavailable",
            "gate_phone_t": "The seller hid their number",
            "gate_phone_b": "So that calls don't distract them, the seller doesn't show their phone. Write in the chat — the message reaches them right away, and they'll answer here. It's convenient and safe.",
            "gate_deal_t": "The number — after the deal is paid",
            "gate_deal_b": "The seller's phone opens once you pay through the Safe deal. For now, write in the chat — the message arrives right away, and they'll answer here.",
            "gate_account_t": "You need an account",
            "gate_account_b": "Sign up to contact the seller and buy. It's quick and free.",
            "reg": "Sign up",
            "hours_gate_t": "Calls — during working hours",
            "hours_gate_b": "So as not to disturb the seller after hours, calls are available on schedule. Write in the chat right now — the message will get through, and the seller will answer when it suits them.",
            "hours_accepts": "Takes calls %@",
            "write_chat": "Write in the chat", "later": "Later",
            "root_electronics": "Electronics", "root_transport": "Vehicles", "root_realty": "Real estate", "root_clothing": "Clothing and shoes", "root_home-garden": "Home and garden", "root_kids": "Kids' goods", "root_sport": "Sports and leisure", "root_animals": "Animals", "root_jobs": "Jobs", "root_services": "Services", "root_hobby": "Hobbies and crafts", "root_food-farm": "Food and farming", "root_beauty": "Beauty and health",
            "wa_text": "Hello! I'm interested in “%@” for %@. Is it still available?"
        ],
        "ar": [
            "stock_in_avail": "متوفر", "stock_pcs": "%d قطعة", "stock_low": "الكمية قليلة",
            "cpu_short": "المعالج", "gpu_short": "الرسوميات", "shop": "متجر", "hours_accepts_lbl": "يستقبل المكالمات",
            "cond_new": "جديد", "cond_used": "مستعمل", "with_mileage": "مستعملة", "no_mileage": "بدون عداد",
            "realty_new": "بناء جديد", "realty_used": "سوق ثانوي", "rent": "للإيجار",
            "price_from": "من", "negotiable": "قابل للتفاوض", "torg": "تفاوض", "unit_day": "يوم", "unit_month": "شهر",
            "hours_work": "ساعات العمل", "hours_247": "على مدار الساعة",
            "claims": "يؤكد البائع", "what_gives": "ما الفائدة", "trust_title": "علامات الثقة",
            "trust_look": "ما الذي يجب التحقق منه في هذا الإعلان", "claimed": "مُعلن", "ok": "حسنًا",
            "warranty": "ضمان البائع %@", "ship_free": "توصيل مجاني", "ship_days": "المدة ~%@ يوم",
            "month_1": "شهر", "month_2": "أشهر", "month_5": "شهرًا", "day_1": "يوم", "day_2": "أيام", "day_5": "يومًا",
            "t_receipt": "يوجد إيصال", "t_working": "يعمل / تم فحصه", "t_complete": "مجموعة كاملة",
            "t_vin_clean": "رقم VIN / سجل نظيف", "t_not_crashed": "بدون حوادث", "t_service_book": "دفتر الصيانة",
            "t_one_owner": "مالك واحد", "t_docs_ok": "الوثائق سليمة", "t_no_liens": "بدون أعباء",
            "t_lawyer_checked": "فحصه محامٍ", "t_mortgage_ok": "يمكن بالرهن العقاري", "t_vet_passport": "جواز بيطري / ملقّح",
            "t_sterilized": "معقّم", "t_vet_checked": "فحصه طبيب بيطري", "t_pedigree": "وسم / شريحة / نسب",
            "t_trained": "مدرّب", "t_original": "أصلي", "t_tags": "بالملصقات / الإيصال",
            "t_measured": "مقاسات دقيقة", "t_no_defects": "بدون عيوب", "t_safety_cert": "شهادة سلامة",
            "t_clean": "نظيف / معقّم", "t_not_recalled": "لم يُسحب", "t_guarantor": "صفقة آمنة",
            "t_licensed": "خبرة / ترخيص", "t_portfolio": "معرض أعمال", "t_deposit": "تأمين / وديعة",
            "t_contract": "عقد إيجار", "t_condition_act": "فحص الحالة (محضر)", "t_insured": "تأمين",
            "t_cleaned": "تنظيف بين الإيجارات",
            "tip_auto": "السيارات — ما الذي يجب التحقق منه",
            "tip_auto_1": "تحقق من السيارة برقم VIN وقواعد بيانات كازاخستان — زر «فحص السيارة»: رهن، بحث، قيود.",
            "tip_auto_2": "العداد والهيكل: قارنهما بدفتر الصيانة، وافحص السيارة نهارًا وعلى رافعة.",
            "tip_auto_3": "الوثائق: شهادة التسجيل، ورقم VIN على الهيكل يطابق الوثائق، وعدد المالكين.",
            "tip_auto_4": "الدفع عبر الصفقة الآمنة وعند اللقاء. لا ترسل دفعة مقدمة لشخص غريب.",
            "tip_tech": "الأجهزة — ما الذي يجب التحقق منه",
            "tip_tech_1": "تحقق من IMEI/الرقم التسلسلي — زر «فحص الجهاز»: سجل كازاخستان والقائمة السوداء.",
            "tip_tech_2": "القفل: الجهاز مُعاد ضبطه وغير مرتبط بحساب Apple ID أو Google لشخص آخر.",
            "tip_tech_3": "افحصه بنفسك: التشغيل، الشاشة، البطارية، الكاميرات، المنافذ.",
            "tip_tech_4": "الملحقات والإيصال والضمان. الدفع عبر الصفقة الآمنة.",
            "tip_realty": "العقارات — ما الذي يجب التحقق منه",
            "tip_realty_1": "تحقق من العقار في السجل العقاري — زر «فحص العقار»: أعباء، حجز، رهن.",
            "tip_realty_2": "وثائق الملكية: من المالك، وسند الملكية، ومستخرج حديث.",
            "tip_realty_3": "المعاينة بنفسك: المرافق، الحالة، الحي والجيران.",
            "tip_realty_4": "العربون والدفع — عبر الصفقة الآمنة أو بعقد، لا «بالكلام».",
            "tip_rent": "الإيجار — ما الذي يجب التحقق منه",
            "tip_rent_1": "العقد: المدة والسعر ومسؤولية الطرفين — دوّنها كتابيًا.",
            "tip_rent_2": "التأمين: المبلغ وشروط الاسترداد — اتفقا مسبقًا.",
            "tip_rent_3": "الحالة عند الاستلام: التقط صورًا وسجّل العيوب.",
            "tip_rent_4": "ادفع عبر الصفقة الآمنة — التأمين في حماية Kliko.",
            "tip_service": "الخدمات — ما الذي يجب التحقق منه",
            "tip_service_1": "اطلع على تقييمات المنفّذ ونماذج أعماله.",
            "tip_service_2": "اتفقا على الحجم والمدة والسعر النهائي قبل البدء.",
            "tip_service_3": "الدفع عبر الصفقة الآمنة: دفعة مقدمة والباقي بعد الاستلام.",
            "tip_service_4": "لا تحوّل المال مباشرة قبل إنجاز العمل.",
            "desc": "الوصف", "added": "أُضيف %@", "views": "المشاهدات: %d", "today": "اليوم",
            "yesterday": "أمس", "ago": "قبل %@",
            "months": "يناير,فبراير,مارس,أبريل,مايو,يونيو,يوليو,أغسطس,سبتمبر,أكتوبر,نوفمبر,ديسمبر",
            "new_seller": "بائع جديد", "verified": "موثّق عبر eGov", "since": "منذ %@",
            "reviews_1": "تقييم", "reviews_2": "تقييمات", "reviews_5": "تقييمات",
            "deals_1": "صفقة", "deals_2": "صفقات", "deals_5": "صفقات",
            "similar": "إعلانات مشابهة", "similar_svc": "المزيد في هذه الفئة",
            "back": "رجوع", "close": "إغلاق", "photo": "الصورة %d من %d",
            "offer": "اقترح سعرًا", "offer_sub": "تفاوض — يصلك الرد في الدردشة",
            "contact": "تواصل", "contact_sub": "دردشة أو اتصال أو WhatsApp",
            "buy_safe": "شراء آمن", "rent_safe": "استئجار آمن", "on_site": "يُفتح في التطبيق",
            "call": "اتصال", "wa": "WhatsApp", "chat": "الدردشة في المنصة",
            "num_unavail": "الرقم غير متاح مؤقتًا", "contact_unavail": "جهة الاتصال غير متاحة مؤقتًا",
            "gate_phone_t": "أخفى البائع رقمه",
            "gate_phone_b": "حتى لا تشغله المكالمات، لا يعرض البائع هاتفه. اكتب في الدردشة — ستصله الرسالة فورًا وسيرد هنا. هذا مريح وآمن.",
            "gate_deal_t": "الرقم — بعد دفع الصفقة",
            "gate_deal_b": "سيظهر هاتف البائع بعد الدفع عبر الصفقة الآمنة. إلى ذلك الحين اكتب له في الدردشة — ستصله الرسالة فورًا وسيرد هنا.",
            "gate_account_t": "تحتاج إلى حساب",
            "gate_account_b": "سجّل لتتواصل مع البائع وتشتري. الأمر سريع ومجاني.",
            "reg": "التسجيل",
            "hours_gate_t": "الاتصال — في ساعات العمل",
            "hours_gate_b": "حتى لا يُزعج البائع خارج ساعات العمل، الاتصال متاح حسب الجدول. اكتب في الدردشة الآن — ستصل الرسالة بالتأكيد، وسيرد البائع في الوقت المناسب له.",
            "hours_accepts": "يستقبل المكالمات %@",
            "write_chat": "اكتب في الدردشة", "later": "لاحقًا",
            "root_electronics": "إلكترونيات", "root_transport": "مركبات", "root_realty": "عقارات", "root_clothing": "ملابس وأحذية", "root_home-garden": "المنزل والحديقة", "root_kids": "مستلزمات الأطفال", "root_sport": "رياضة وترفيه", "root_animals": "حيوانات", "root_jobs": "وظائف", "root_services": "خدمات", "root_hobby": "هوايات وإبداع", "root_food-farm": "أغذية وزراعة", "root_beauty": "الجمال والصحة",
            "wa_text": "مرحبًا! أنا مهتم بـ «%@» بسعر %@. هل ما زال متاحًا؟"
        ]
    ]

    /// Лист «Что это даёт» (openInfo сайта): шапка, разделы гарантии и доставки, пояснения знаков доверия (trustd_*
    /// словаря сайта). Отдельным словарём — чтобы не раздувать основной.
    private static let текстыДоверия: [String: [String: String]] = [
        "ru": [
            "info_title": "Безопасная покупка", "info_sub": "Знаки доверия, гарантия и доставка",
            "cov_warr_title": "Гарантия продавца — %@", "cov_asis_title": "Продаётся как есть",
            "cov_w1_l": "Гарантия %@", "cov_w1_d": "Откажет в этот срок — продавец обязан вернуть деньги или заменить. Срок идёт с даты получения.",
            "cov_w2_l": "Оформляйте через Безопасную сделку", "cov_w2_d": "Деньги у Kliko, пока вы не подтвердите, что товар исправен — это ваша страховка.", "cov_w2_l_np": "Договоритесь о проверке до оплаты", "cov_w2_d_np": "Осмотрите и проверьте товар до оплаты — так надёжнее.",
            "cov_w3_l": "Сохраните переписку и чек", "cov_w3_d": "Условия и срок гарантии подтверждаются вашим диалогом в чате и чеком.",
            "cov_w3_l2": "Гарантийный талон в сделке", "cov_w3_d2": "В безопасной сделке продавец может подписать гарантийный талон через eGov — талон хранится в сделке вместе с перепиской.",
            "cov_a1_l": "Без гарантии после покупки", "cov_a1_d": "Обычно так у б/у: продавец не отвечает за поломки после сделки — поэтому важно проверить заранее.",
            "cov_a2_l": "Проверяйте при получении", "cov_a2_d": "Осмотрите и протестируйте до оплаты. В Безопасной сделке деньги у Kliko, пока вы не получите товар.", "cov_a2_d_np": "Осмотрите и протестируйте до оплаты.",
            "cov_a3_l": "Спросите продавца заранее", "cov_a3_d": "Уточните в чате комплект, дефекты и причину продажи — до встречи.",
            "dlv_title": "Доставка", "dlv_free_d": "Продавец берёт доставку на себя.",
            "dlv_days_d": "Ориентировочный срок доставки от продавца.", "dlv_carrier_l": "Транспортная компания",
            "dlv_safe_l": "Курьер и Безопасная сделка", "dlv_safe_d": "Курьера можно заказать из чата; деньги у Kliko, пока вы не получите товар.",
            "t_receipt_d": "Есть чек — подтверждены магазин и дата покупки, проще гарантия и возврат.", "t_working_d": "Проверено при вас или показано в работе — не «кот в мешке».",
            "t_complete_d": "Полный комплект: коробка, зарядка, документы, аксессуары.", "t_vin_clean_d": "VIN и история чистые — не в розыске, без арестов и ограничений.",
            "t_not_crashed_d": "Не был в серьёзных ДТП — кузов и геометрия целы.", "t_service_book_d": "Есть сервисная книжка — обслуживание по регламенту, видна история.",
            "t_one_owner_d": "Один владелец — понятная история, меньше сюрпризов.", "t_docs_ok_d": "Документы в порядке — право собственности чистое, сделку можно оформить.",
            "t_no_liens_d": "Без обременений — не в залоге, не под арестом, не в споре.", "t_lawyer_checked_d": "Юрист проверил документы — риски исключены заранее.",
            "t_mortgage_ok_d": "Подходит под ипотеку — банк готов кредитовать этот объект.", "t_vet_passport_d": "Ветпаспорт и прививки — питомец здоров и привит по возрасту.",
            "t_sterilized_d": "Стерилизован/кастрирован — меньше рисков для здоровья и хлопот.", "t_vet_checked_d": "Осмотрен ветеринаром — состояние подтверждено специалистом.",
            "t_pedigree_d": "Клеймо/чип/родословная — происхождение подтверждено, питомца можно опознать.", "t_trained_d": "Приучен (к лотку/командам) — готов к дому, меньше хлопот.",
            "t_original_d": "Оригинал, не подделка — подлинность подтверждена.", "t_tags_d": "С бирками и чеком — новое, не ношеное, проверяется на месте.",
            "t_measured_d": "Точные замеры — подойдёт по размеру, без возвратов.", "t_no_defects_d": "Без дефектов — нет пятен, затяжек и дырок.",
            "t_safety_cert_d": "Сертификат безопасности — соответствует нормам для детей.", "t_clean_d": "Чистое и продезинфицировано — готово к использованию.",
            "t_not_recalled_d": "Модель не отзывалась производителем — без известных дефектов.", "t_guarantor_d": "Оплата через Безопасную сделку — деньги придут исполнителю только после приёмки.",
            "t_licensed_d": "Опыт и лицензия — работу выполняет квалифицированный специалист.", "t_portfolio_d": "Есть портфолио — видно качество прошлых работ.",
            "t_deposit_d": "Залог/депозит — фиксирует ответственность и возвращается при сдаче.", "t_contract_d": "Договор аренды — условия зафиксированы письменно, защищает обе стороны.",
            "t_condition_act_d": "Акт состояния при передаче — фиксирует, в каком виде взяли и вернули.", "t_insured_d": "Страховка — покрывает риски повреждения на время аренды.",
            "t_cleaned_d": "Чистка между арендами — вы получаете чистую вещь."
        ],
        "kk": [
            "info_title": "Қауіпсіз сатып алу", "info_sub": "Сенім белгілері, кепілдік және жеткізу",
            "cov_warr_title": "Сатушы кепілдігі — %@", "cov_asis_title": "Қалай бар, солай сатылады",
            "cov_w1_l": "Кепілдік %@", "cov_w1_d": "Осы мерзімде істен шықса — сатушы ақшаны қайтаруға немесе ауыстыруға міндетті. Мерзім алған күннен басталады.",
            "cov_w2_l": "Қауіпсіз мәміле арқылы рәсімдеңіз", "cov_w2_d": "Тауардың дұрыс екенін растағанша ақша Kliko-да тұрады — бұл сіздің сақтандыруыңыз.", "cov_w2_l_np": "Төлемге дейін тексеруге келісіңіз", "cov_w2_d_np": "Төлемге дейін тауарды қарап, тексеріңіз — осылай сенімдірек.",
            "cov_w3_l": "Хат алмасу мен чекті сақтаңыз", "cov_w3_d": "Кепілдік шарттары мен мерзімі чаттағы диалогыңызбен және чекпен расталады.",
            "cov_w3_l2": "Мәміледегі кепілдік талоны", "cov_w3_d2": "Қауіпсіз мәміледе сатушы кепілдік талонына eGov арқылы қол қоя алады — талон мәміледе хат алмасумен бірге сақталады.",
            "cov_a1_l": "Сатып алғаннан кейін кепілдік жоқ", "cov_a1_d": "Қолданылған тауарда әдетте солай: мәміледен кейінгі ақауға сатушы жауап бермейді — сондықтан алдын ала тексеріңіз.",
            "cov_a2_l": "Алған кезде тексеріңіз", "cov_a2_d": "Төлемге дейін қарап, сынап көріңіз. Қауіпсіз мәміледе тауарды алғанша ақша Kliko-да тұрады.", "cov_a2_d_np": "Төлемге дейін қарап, сынап көріңіз.",
            "cov_a3_l": "Сатушыдан алдын ала сұраңыз", "cov_a3_d": "Жиынтықты, ақауларды және сату себебін кездесуге дейін чатта нақтылаңыз.",
            "dlv_title": "Жеткізу", "dlv_free_d": "Жеткізуді сатушы өз мойнына алады.",
            "dlv_days_d": "Сатушының болжамды жеткізу мерзімі.", "dlv_carrier_l": "Көлік компаниясы",
            "dlv_safe_l": "Курьер және Қауіпсіз мәміле", "dlv_safe_d": "Курьерді чаттан шақыруға болады; тауарды алғанша ақша Kliko-да тұрады.",
            "t_receipt_d": "Чегі бар — дүкен мен сатып алу күні расталған, кепілдік пен қайтару оңай.", "t_working_d": "Көз алдыңызда тексерілген немесе жұмыста көрсетілген — «қаптағы мысық» емес.",
            "t_complete_d": "Толық жиынтық: қорап, зарядтағыш, құжаттар, керек-жарақ.", "t_vin_clean_d": "VIN мен тарихы таза — іздеуде емес, тыйым мен шектеу жоқ.",
            "t_not_crashed_d": "Ауыр жол апатында болмаған — шанағы мен геометриясы бүтін.", "t_service_book_d": "Сервистік кітапшасы бар — регламент бойынша қызмет көрсетілген, тарихы көрінеді.",
            "t_one_owner_d": "Бір иесі — тарихы түсінікті, тосын жағдай аз.", "t_docs_ok_d": "Құжаттары ретті — меншік құқығы таза, мәмілені рәсімдеуге болады.",
            "t_no_liens_d": "Ауыртпалықсыз — кепілде емес, тыйым салынбаған, дау жоқ.", "t_lawyer_checked_d": "Құжаттарды заңгер тексерген — тәуекелдер алдын ала жойылған.",
            "t_mortgage_ok_d": "Ипотекаға жарамды — банк бұл нысанға несие беруге дайын.", "t_vet_passport_d": "Ветпаспорт пен екпелер — жануар сау, жасына қарай екпе алған.",
            "t_sterilized_d": "Зарарсыздандырылған/піштірілген — денсаулыққа қатер мен әуре аз.", "t_vet_checked_d": "Ветеринар қараған — жағдайын маман растаған.",
            "t_pedigree_d": "Таңба/чип/тектік куәлік — шығу тегі расталған, жануарды тануға болады.", "t_trained_d": "Үйретілген (науаға/командаларға) — үйге дайын, әуре аз.",
            "t_original_d": "Түпнұсқа, жалған емес — шынайылығы расталған.", "t_tags_d": "Биркасы мен чегі бар — жаңа, киілмеген, орнында тексеріледі.",
            "t_measured_d": "Нақты өлшемдер — өлшеміңізге келеді, қайтарусыз.", "t_no_defects_d": "Ақаусыз — дақ, тартылған жіп пен тесік жоқ.",
            "t_safety_cert_d": "Қауіпсіздік сертификаты — балаларға арналған нормаларға сай.", "t_clean_d": "Таза және залалсыздандырылған — қолдануға дайын.",
            "t_not_recalled_d": "Модельді өндіруші кері шақырмаған — белгілі ақаулары жоқ.", "t_guarantor_d": "Қауіпсіз мәміле арқылы төлем — ақша орындаушыға тек қабылдаудан кейін түседі.",
            "t_licensed_d": "Тәжірибе мен лицензия — жұмысты білікті маман орындайды.", "t_portfolio_d": "Портфолиосы бар — бұрынғы жұмыстардың сапасы көрінеді.",
            "t_deposit_d": "Кепілақы/депозит — жауапкершілікті бекітеді және тапсырғанда қайтарылады.", "t_contract_d": "Жалға алу шарты — шарттар жазбаша бекітілген, екі тарапты да қорғайды.",
            "t_condition_act_d": "Тапсыру кезіндегі жағдай актісі — қандай күйде алып, қайтарғаныңызды бекітеді.", "t_insured_d": "Сақтандыру — жалға алу кезінде бүліну тәуекелін жабады.",
            "t_cleaned_d": "Жалға берулер арасында тазалау — сіз таза зат аласыз."
        ],
        "en": [
            "info_title": "Safe purchase", "info_sub": "Trust signs, warranty and delivery",
            "cov_warr_title": "Seller warranty — %@", "cov_asis_title": "Sold as is",
            "cov_w1_l": "Warranty %@", "cov_w1_d": "If it fails within this period, the seller must refund or replace it. The period starts on the day you receive it.",
            "cov_w2_l": "Use the Safe deal", "cov_w2_d": "Kliko holds the money until you confirm the item works — that's your insurance.", "cov_w2_l_np": "Agree on a check before paying", "cov_w2_d_np": "Inspect and check the item before paying — it's safer that way.",
            "cov_w3_l": "Keep the chat and the receipt", "cov_w3_d": "The warranty terms are confirmed by your chat and the receipt.",
            "cov_w3_l2": "Warranty card in the deal", "cov_w3_d2": "In a safe deal the seller can sign a warranty card via eGov — it is stored in the deal together with the chat.",
            "cov_a1_l": "No warranty after purchase", "cov_a1_d": "Usual for used items: the seller isn't responsible for breakdowns after the deal — so check it in advance.",
            "cov_a2_l": "Check on receipt", "cov_a2_d": "Inspect and test before paying. With the Safe deal, Kliko holds the money until you receive the item.", "cov_a2_d_np": "Inspect and test before paying.",
            "cov_a3_l": "Ask the seller in advance", "cov_a3_d": "Ask in the chat about the kit, defects and the reason for selling — before you meet.",
            "dlv_title": "Delivery", "dlv_free_d": "The seller covers delivery.",
            "dlv_days_d": "Approximate delivery time from the seller.", "dlv_carrier_l": "Transport company",
            "dlv_safe_l": "Courier and Safe deal", "dlv_safe_d": "You can order a courier from the chat; Kliko holds the money until you receive the item.",
            "t_receipt_d": "There's a receipt — the store and purchase date are confirmed, warranty and returns are easier.", "t_working_d": "Checked in front of you or shown working — no pig in a poke.",
            "t_complete_d": "Full set: box, charger, documents, accessories.", "t_vin_clean_d": "Clean VIN and history — not wanted, no arrests or restrictions.",
            "t_not_crashed_d": "No serious accidents — body and geometry are intact.", "t_service_book_d": "Service book — maintained on schedule, the history is visible.",
            "t_one_owner_d": "One owner — a clear history, fewer surprises.", "t_docs_ok_d": "Documents in order — clean ownership, the deal can be completed.",
            "t_no_liens_d": "No encumbrances — not pledged, not under arrest, not in dispute.", "t_lawyer_checked_d": "A lawyer checked the documents — risks ruled out in advance.",
            "t_mortgage_ok_d": "Mortgage-eligible — a bank is ready to lend on this property.", "t_vet_passport_d": "Vet passport and vaccinations — the pet is healthy and vaccinated for its age.",
            "t_sterilized_d": "Spayed/neutered — fewer health risks and less hassle.", "t_vet_checked_d": "Examined by a vet — the condition is confirmed by a specialist.",
            "t_pedigree_d": "Brand/chip/pedigree — origin confirmed, the pet can be identified.", "t_trained_d": "Trained (litter/commands) — ready for home, less hassle.",
            "t_original_d": "Original, not a fake — authenticity confirmed.", "t_tags_d": "With tags and receipt — new, unworn, checked on the spot.",
            "t_measured_d": "Exact measurements — it will fit, no returns.", "t_no_defects_d": "No defects — no stains, snags or holes.",
            "t_safety_cert_d": "Safety certificate — meets the standards for children.", "t_clean_d": "Clean and disinfected — ready to use.",
            "t_not_recalled_d": "The model wasn't recalled by the manufacturer — no known defects.", "t_guarantor_d": "Payment through the Safe deal — the money reaches the contractor only after acceptance.",
            "t_licensed_d": "Experience and license — the work is done by a qualified specialist.", "t_portfolio_d": "Has a portfolio — the quality of past work is visible.",
            "t_deposit_d": "Deposit — secures responsibility and is returned on hand-back.", "t_contract_d": "Rental agreement — the terms are in writing and protect both sides.",
            "t_condition_act_d": "Condition report at hand-over — records the state it was taken and returned in.", "t_insured_d": "Insurance — covers damage risks during the rental.",
            "t_cleaned_d": "Cleaning between rentals — you get a clean item."
        ],
        "ar": [
            "info_title": "شراء آمن", "info_sub": "علامات الثقة والضمان والتوصيل",
            "cov_warr_title": "ضمان البائع — %@", "cov_asis_title": "يُباع كما هو",
            "cov_w1_l": "ضمان %@", "cov_w1_d": "إذا تعطّل خلال هذه المدة فعلى البائع إعادة المال أو الاستبدال. تبدأ المدة من يوم الاستلام.",
            "cov_w2_l": "أتمّ الشراء عبر الصفقة الآمنة", "cov_w2_d": "يحتفظ Kliko بالمال حتى تؤكد أن المنتج سليم — هذا تأمينك.", "cov_w2_l_np": "اتفق على الفحص قبل الدفع", "cov_w2_d_np": "عاين السلعة وافحصها قبل الدفع — هكذا أكثر أمانًا.",
            "cov_w3_l": "احتفظ بالمحادثة والإيصال", "cov_w3_d": "شروط الضمان ومدته تثبتها محادثتك في الدردشة والإيصال.",
            "cov_w3_l2": "بطاقة الضمان في الصفقة", "cov_w3_d2": "في الصفقة الآمنة يمكن للبائع توقيع بطاقة الضمان عبر eGov — وتُحفظ في الصفقة مع المحادثة.",
            "cov_a1_l": "بلا ضمان بعد الشراء", "cov_a1_d": "هذا معتاد في المستعمل: لا يتحمل البائع الأعطال بعد الصفقة — لذا افحصه مسبقًا.",
            "cov_a2_l": "افحص عند الاستلام", "cov_a2_d": "عاين وجرّب قبل الدفع. في الصفقة الآمنة يحتفظ Kliko بالمال حتى تستلم السلعة.", "cov_a2_d_np": "عاين وجرّب قبل الدفع.",
            "cov_a3_l": "اسأل البائع مسبقًا", "cov_a3_d": "استوضح في الدردشة عن الملحقات والعيوب وسبب البيع — قبل اللقاء.",
            "dlv_title": "التوصيل", "dlv_free_d": "يتحمل البائع تكلفة التوصيل.",
            "dlv_days_d": "مدة التوصيل التقريبية من البائع.", "dlv_carrier_l": "شركة النقل",
            "dlv_safe_l": "المندوب والصفقة الآمنة", "dlv_safe_d": "يمكن طلب مندوب من الدردشة، ويحتفظ Kliko بالمال حتى تستلم السلعة.",
            "t_receipt_d": "يوجد إيصال — المتجر وتاريخ الشراء مؤكدان، والضمان والإرجاع أسهل.", "t_working_d": "فُحص أمامك أو عُرض وهو يعمل — بلا مفاجآت.",
            "t_complete_d": "طقم كامل: العلبة والشاحن والمستندات والملحقات.", "t_vin_clean_d": "رقم VIN والسجل نظيفان — غير مطلوب، بلا حجز أو قيود.",
            "t_not_crashed_d": "لم يتعرض لحوادث خطيرة — الهيكل والأبعاد سليمة.", "t_service_book_d": "يوجد دفتر صيانة — صيانة حسب الجدول والسجل واضح.",
            "t_one_owner_d": "مالك واحد — سجل واضح ومفاجآت أقل.", "t_docs_ok_d": "المستندات سليمة — الملكية نظيفة ويمكن إتمام الصفقة.",
            "t_no_liens_d": "بلا أعباء — غير مرهون ولا محجوز ولا عليه نزاع.", "t_lawyer_checked_d": "راجع محامٍ المستندات — استُبعدت المخاطر مسبقًا.",
            "t_mortgage_ok_d": "مناسب للرهن العقاري — البنك مستعد لتمويل هذا العقار.", "t_vet_passport_d": "جواز بيطري وتطعيمات — الحيوان سليم ومطعّم حسب عمره.",
            "t_sterilized_d": "معقّم/مخصي — مخاطر صحية ومتاعب أقل.", "t_vet_checked_d": "فحصه طبيب بيطري — الحالة مؤكدة من مختص.",
            "t_pedigree_d": "وسم/شريحة/نسب — الأصل مؤكد ويمكن التعرف على الحيوان.", "t_trained_d": "مدرّب (على الصندوق/الأوامر) — جاهز للمنزل ومتاعب أقل.",
            "t_original_d": "أصلي وليس مقلدًا — الأصالة مؤكدة.", "t_tags_d": "بالبطاقات والإيصال — جديد غير مستعمل ويُفحص في المكان.",
            "t_measured_d": "مقاسات دقيقة — سيناسبك دون إرجاع.", "t_no_defects_d": "بلا عيوب — لا بقع ولا خيوط مشدودة ولا ثقوب.",
            "t_safety_cert_d": "شهادة سلامة — مطابق لمعايير الأطفال.", "t_clean_d": "نظيف ومعقّم — جاهز للاستخدام.",
            "t_not_recalled_d": "لم يسحب المصنّع هذا الطراز — لا عيوب معروفة.", "t_guarantor_d": "الدفع عبر الصفقة الآمنة — يصل المال إلى المنفذ بعد القبول فقط.",
            "t_licensed_d": "خبرة وترخيص — ينفذ العمل مختص مؤهل.", "t_portfolio_d": "يوجد معرض أعمال — جودة الأعمال السابقة واضحة.",
            "t_deposit_d": "تأمين/وديعة — يثبت المسؤولية ويُعاد عند التسليم.", "t_contract_d": "عقد إيجار — الشروط مكتوبة وتحمي الطرفين.",
            "t_condition_act_d": "محضر الحالة عند التسليم — يوثّق حالة الشيء عند الاستلام والإرجاع.", "t_insured_d": "تأمين — يغطي مخاطر التلف خلال مدة الإيجار.",
            "t_cleaned_d": "تنظيف بين الإيجارات — تحصل على شيء نظيف."
        ]
    ]
}
