import Foundation

/**
 Тексты страницы объявления авто и недвижимости (владелец 26.09.2026: «авто и недвижимость чуть другое отображение
 внутри, как на сайте») на языке телефона (kk/ru/en/ar) — тем же способом, что ListingPageText.

 Русские слова — со страницы объявления сайта: словарь js/i18n-marketplace-ru.js (chk_* — кнопка и отчёт проверки,
 installment, credit, pay_methods — «Способы оплаты», rplan_t — «Схема помещения», sec_location — «Расположение»,
 open_2gis, fac_*/spec_* — подписи и значения характеристик SPEC_LBL_MAP/SPEC_VAL_MAP) и MK_REALTY_LBL в
 js/marketplace.min.js (подписи полей жилья). Тексты отчёта, которых нет в словаре, — как у сайта прямо в коде
 (_mkChkLock, _mkChkEmpty, mkCheckReport, mkPayRow).
 */
enum ListingKindsText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[ListingPageText.язык] ?? тексты["ru"]!
        return словарь[ключ] ?? тексты["ru"]![ключ] ?? ключ
    }

    private static let тексты: [String: [String: String]] = [
        "ru": [
            "chk_auto_title": "Проверка автомобиля", "chk_realty_title": "Проверка недвижимости",
            "chk_auto_clean": "Чисто по базам РК", "chk_owner_ok": "Собственник подтверждён",
            "chk_no_liens": "Без обременений и арестов", "chk_issues": "Найдены ограничения",
            "chk_vin_ok": "VIN подтверждён", "chk_cadastre_ok": "Кадастр подтверждён",
            "chk_rk_pending": "базы РК на проверке", "chk_by_rk": "Проверка по базам РК",
            "chk_open": "Открыть", "chk_check": "Проверить",
            "chk_auto_hs": "Залог · розыск · история", "chk_realty_hs": "Обременения · арест · собственник",
            "chk_vin": "VIN %@", "chk_vin_none": "VIN не указан", "chk_kad": "Кадастр %@", "chk_kad_none": "Кадастр не указан",
            "chk_lock_t": "Отчёт открыт для проверенных",
            "chk_lock_b": "Проверка по базам РК — часть защиты сделки. Доступна после верификации личности.",
            "chk_lock_btn": "Пройти верификацию →",
            "chk_empty_t": "Проверка ещё не проводилась",
            "chk_empty_b": "Запросите проверку по базам РК — результат появится здесь и в карточке.",
            "chk_request": "Запросить проверку",
            "chk_clean_short": "Чисто", "chk_limits": "Ограничения", "chk_pending": "На проверке",
            "chk_confirmed": "Подтверждён", "chk_unconfirmed": "Не подтверждён", "chk_has": "Есть", "chk_none": "Нет",
            "chk_vin_unrec": "VIN не распознан", "chk_check_num": "Проверьте номер", "chk_has_limits": "Есть ограничения",
            "chk_rk_found": "Найдены записи в базах РК — уточните",
            "chk_clean_vin_sub": "VIN подтверждён, ограничений не найдено",
            "chk_vin_pending_sub": "Залог, розыск, история — на проверке", "chk_kad_unrec": "Кадастр не распознан",
            "chk_realty_issue_rent": "Вопросы к собственнику/объекту",
            "chk_realty_issue_sale": "Найдены обременения / арест", "chk_clean_ready": "Чисто — можно оформлять",
            "chk_owner_ok_sub": "Собственник подтверждён, ограничений нет",
            "chk_kad_pending_sub": "Обременения, арест, собственник — на проверке",
            "chk_car_data": "Данные автомобиля", "chk_vin_decode": "VIN-декод", "chk_vin_valid": "VIN валиден",
            "chk_brand": "Марка", "chk_year": "Год выпуска", "chk_country": "Страна завода", "chk_rk_bases": "Базы РК",
            "chk_pledge": "Залог / обременения", "chk_wanted": "Розыск / угон", "chk_restrictions": "Ограничения / арест",
            "chk_realty_reg": "Регистр недвижимости РК", "chk_encumbrance": "Обременения / залог",
            "chk_arrest": "Арест / запрет", "chk_owner": "Собственник",
            "chk_owner_match_rent": "Совпадает с арендодателем", "chk_owner_match_sale": "Совпадает с продавцом",
            "chk_kadastr": "Кадастр", "chk_correct": "Корректен", "chk_region": "Регион", "chk_ad_type": "Тип объявления",
            "chk_rent": "Аренда", "chk_sale": "Продажа", "chk_source": "Источник: проверка платформы",
            "chk_disclaimer": "Справочная информация, не заменяет официальную выписку.",
            "chk_b_car": "ТС", "chk_b_rk": "РК", "chk_b_rn": "РН", "chk_b_k": "К",
            "rplan_t": "Схема помещения", "rplan_open": "Открыть и увеличить",
            "pay_methods": "Способы оплаты", "installment": "Рассрочка", "credit": "Кредит",
            "inst_plus": "Рассрочка · +%@%%", "inst_comm": "Комиссия рассрочки %@%%", "cred_rate": "Кредит · %@%%/год",
            "no_bank_notary": "без банка (нотариус)", "from": "от", "mon": "мес",
            "sec_location": "Расположение", "open_2gis": "Открыть в 2ГИС →",
            "re_rooms": "Комнат", "re_area": "Площадь", "re_land_area": "Участок", "re_floor": "Этаж",
            "re_floors": "Этажей", "re_year_built": "Год постройки", "re_renovation": "Ремонт", "re_building": "Тип дома",
            "re_bathroom": "Санузел", "re_docs": "Документы", "re_mortgage_ok": "Ипотека", "re_term": "Срок аренды",
            "re_utilities": "Коммунальные включены", "re_furniture": "Мебель и техника", "re_kids": "Можно с детьми",
            "re_pets": "Можно с животными", "re_owner": "Кто размещает", "re_land_use": "Назначение",
            "re_parking": "Есть парковка",
            "fac_gearbox": "Коробка", "fac_fuel": "Топливо", "spec_mileage": "Пробег", "fac_year_short": "Год",
            "spec_year": "Год выпуска", "fac_engine": "Двигатель, л", "fac_area": "Площадь, м²", "fac_rooms": "Комнат",
            "fac_size": "Размер", "fac_color": "Цвет", "fac_material": "Материал", "fac_plot": "Участок, сот",
            "fac_auto": "Автомат", "fac_manual": "Механика", "fac_robot": "Робот", "fac_cvt": "Вариатор",
            "fac_petrol": "Бензин", "fac_diesel": "Дизель", "fac_gas": "Газ", "fac_hybrid": "Гибрид",
            "fac_electric": "Электро", "gpu_integrated": "Встроенная", "gpu_discrete": "Дискретная",
            "cond_new": "Новое", "cond_used": "Б/У", "fac_studio": "Студия"
        ],
        "kk": [
            "chk_auto_title": "Көлікті тексеру", "chk_realty_title": "Жылжымайтын мүлікті тексеру",
            "chk_auto_clean": "ҚР базалары бойынша таза", "chk_owner_ok": "Меншік иесі расталды",
            "chk_no_liens": "Ауыртпалықсыз және тыйымсыз", "chk_issues": "Шектеулер табылды",
            "chk_vin_ok": "VIN расталды", "chk_cadastre_ok": "Кадастр расталды",
            "chk_rk_pending": "ҚР базалары тексерілуде", "chk_by_rk": "ҚР базалары бойынша тексеру",
            "chk_open": "Ашу", "chk_check": "Тексеру",
            "chk_auto_hs": "Кепіл · іздеу · тарих", "chk_realty_hs": "Ауыртпалық · тыйым · меншік иесі",
            "chk_vin": "VIN %@", "chk_vin_none": "VIN көрсетілмеген", "chk_kad": "Кадастр %@",
            "chk_kad_none": "Кадастр көрсетілмеген",
            "chk_lock_t": "Есеп тексерілгендерге ашық",
            "chk_lock_b": "ҚР базалары бойынша тексеру — мәміле қорғауының бөлігі. Жеке басты верификациялағаннан кейін қолжетімді.",
            "chk_lock_btn": "Верификациядан өту →",
            "chk_empty_t": "Тексеру әлі жүргізілмеген",
            "chk_empty_b": "ҚР базалары бойынша тексеруді сұраңыз — нәтиже осында және карточкада шығады.",
            "chk_request": "Тексеруді сұрау",
            "chk_clean_short": "Таза", "chk_limits": "Шектеулер", "chk_pending": "Тексерілуде",
            "chk_confirmed": "Расталды", "chk_unconfirmed": "Расталмады", "chk_has": "Бар", "chk_none": "Жоқ",
            "chk_vin_unrec": "VIN танылмады", "chk_check_num": "Нөмірді тексеріңіз", "chk_has_limits": "Шектеулер бар",
            "chk_rk_found": "ҚР базаларында жазбалар табылды — нақтылаңыз",
            "chk_clean_vin_sub": "VIN расталды, шектеулер табылмады",
            "chk_vin_pending_sub": "Кепіл, іздеу, тарих — тексерілуде", "chk_kad_unrec": "Кадастр танылмады",
            "chk_realty_issue_rent": "Меншік иесіне/нысанға сұрақтар бар",
            "chk_realty_issue_sale": "Ауыртпалық / тыйым табылды", "chk_clean_ready": "Таза — рәсімдеуге болады",
            "chk_owner_ok_sub": "Меншік иесі расталды, шектеулер жоқ",
            "chk_kad_pending_sub": "Ауыртпалық, тыйым, меншік иесі — тексерілуде",
            "chk_car_data": "Көлік деректері", "chk_vin_decode": "VIN-декод", "chk_vin_valid": "VIN жарамды",
            "chk_brand": "Маркасы", "chk_year": "Шыққан жылы", "chk_country": "Зауыт елі", "chk_rk_bases": "ҚР базалары",
            "chk_pledge": "Кепіл / ауыртпалық", "chk_wanted": "Іздеу / ұрлық", "chk_restrictions": "Шектеу / тыйым",
            "chk_realty_reg": "ҚР жылжымайтын мүлік тізілімі", "chk_encumbrance": "Ауыртпалық / кепіл",
            "chk_arrest": "Тыйым / шектеу", "chk_owner": "Меншік иесі",
            "chk_owner_match_rent": "Жалға берушімен сәйкес", "chk_owner_match_sale": "Сатушымен сәйкес",
            "chk_kadastr": "Кадастр", "chk_correct": "Дұрыс", "chk_region": "Өңір", "chk_ad_type": "Хабарландыру түрі",
            "chk_rent": "Жалға беру", "chk_sale": "Сату", "chk_source": "Дереккөз: платформа тексеруі",
            "chk_disclaimer": "Анықтамалық ақпарат, ресми үзіндіні алмастырмайды.",
            "chk_b_car": "КҚ", "chk_b_rk": "ҚР", "chk_b_rn": "ЖМ", "chk_b_k": "К",
            "rplan_t": "Бөлме сызбасы", "rplan_open": "Ашу және үлкейту",
            "pay_methods": "Төлем тәсілдері", "installment": "Бөліп төлеу", "credit": "Несие",
            "inst_plus": "Бөліп төлеу · +%@%%", "inst_comm": "Бөліп төлеу комиссиясы %@%%", "cred_rate": "Несие · жылына %@%%",
            "no_bank_notary": "банксіз (нотариус)", "from": "бастап", "mon": "ай",
            "sec_location": "Орналасуы", "open_2gis": "2ГИС-те ашу →",
            "re_rooms": "Бөлме", "re_area": "Ауданы", "re_land_area": "Учаске", "re_floor": "Қабат",
            "re_floors": "Қабат саны", "re_year_built": "Салынған жылы", "re_renovation": "Жөндеу", "re_building": "Үй түрі",
            "re_bathroom": "Санторап", "re_docs": "Құжаттар", "re_mortgage_ok": "Ипотека", "re_term": "Жалға беру мерзімі",
            "re_utilities": "Коммуналдық төлемдер кіреді", "re_furniture": "Жиһаз бен техника",
            "re_kids": "Балалармен болады", "re_pets": "Жануарлармен болады", "re_owner": "Кім орналастырады",
            "re_land_use": "Мақсаты", "re_parking": "Тұрақ бар",
            "fac_gearbox": "Беріліс қорабы", "fac_fuel": "Отын", "spec_mileage": "Жүрісі", "fac_year_short": "Жылы",
            "spec_year": "Шыққан жылы", "fac_engine": "Қозғалтқыш, л", "fac_area": "Ауданы, м²", "fac_rooms": "Бөлме",
            "fac_size": "Өлшемі", "fac_color": "Түсі", "fac_material": "Материал", "fac_plot": "Учаске, сот",
            "fac_auto": "Автомат", "fac_manual": "Механика", "fac_robot": "Робот", "fac_cvt": "Вариатор",
            "fac_petrol": "Бензин", "fac_diesel": "Дизель", "fac_gas": "Газ", "fac_hybrid": "Гибрид",
            "fac_electric": "Электр", "gpu_integrated": "Кіріктірілген", "gpu_discrete": "Дискретті",
            "cond_new": "Жаңа", "cond_used": "Қолданылған", "fac_studio": "Студия"
        ],
        "en": [
            "chk_auto_title": "Vehicle check", "chk_realty_title": "Property check",
            "chk_auto_clean": "Clean in KZ registries", "chk_owner_ok": "Owner confirmed",
            "chk_no_liens": "No encumbrances or arrests", "chk_issues": "Restrictions found",
            "chk_vin_ok": "VIN confirmed", "chk_cadastre_ok": "Cadastre confirmed",
            "chk_rk_pending": "KZ registries being checked", "chk_by_rk": "Check against KZ registries",
            "chk_open": "Open", "chk_check": "Check",
            "chk_auto_hs": "Pledge · wanted · history", "chk_realty_hs": "Encumbrances · arrest · owner",
            "chk_vin": "VIN %@", "chk_vin_none": "VIN not provided", "chk_kad": "Cadastre %@",
            "chk_kad_none": "Cadastre not provided",
            "chk_lock_t": "Report is open to verified users",
            "chk_lock_b": "The KZ registry check is part of deal protection. Available after identity verification.",
            "chk_lock_btn": "Get verified →",
            "chk_empty_t": "No check has been run yet",
            "chk_empty_b": "Request a check against KZ registries — the result will appear here and on the listing.",
            "chk_request": "Request a check",
            "chk_clean_short": "Clean", "chk_limits": "Restrictions", "chk_pending": "Checking",
            "chk_confirmed": "Confirmed", "chk_unconfirmed": "Not confirmed", "chk_has": "Yes", "chk_none": "No",
            "chk_vin_unrec": "VIN not recognised", "chk_check_num": "Check the number", "chk_has_limits": "Restrictions found",
            "chk_rk_found": "Records found in KZ registries — ask the seller",
            "chk_clean_vin_sub": "VIN confirmed, no restrictions found",
            "chk_vin_pending_sub": "Pledge, wanted, history — being checked", "chk_kad_unrec": "Cadastre not recognised",
            "chk_realty_issue_rent": "Questions about the owner/property",
            "chk_realty_issue_sale": "Encumbrances / arrest found", "chk_clean_ready": "Clean — ready to close",
            "chk_owner_ok_sub": "Owner confirmed, no restrictions",
            "chk_kad_pending_sub": "Encumbrances, arrest, owner — being checked",
            "chk_car_data": "Vehicle data", "chk_vin_decode": "VIN decode", "chk_vin_valid": "VIN valid",
            "chk_brand": "Make", "chk_year": "Year", "chk_country": "Country of manufacture", "chk_rk_bases": "KZ registries",
            "chk_pledge": "Pledge / encumbrances", "chk_wanted": "Wanted / stolen", "chk_restrictions": "Restrictions / arrest",
            "chk_realty_reg": "KZ property register", "chk_encumbrance": "Encumbrances / pledge",
            "chk_arrest": "Arrest / ban", "chk_owner": "Owner",
            "chk_owner_match_rent": "Matches the landlord", "chk_owner_match_sale": "Matches the seller",
            "chk_kadastr": "Cadastre", "chk_correct": "Valid", "chk_region": "Region", "chk_ad_type": "Listing type",
            "chk_rent": "Rent", "chk_sale": "Sale", "chk_source": "Source: platform check",
            "chk_disclaimer": "For reference only; does not replace an official extract.",
            "chk_b_car": "VEH", "chk_b_rk": "KZ", "chk_b_rn": "REG", "chk_b_k": "C",
            "rplan_t": "Floor plan", "rplan_open": "Open and zoom",
            "pay_methods": "Payment options", "installment": "Instalments", "credit": "Loan",
            "inst_plus": "Instalments · +%@%%", "inst_comm": "Instalment fee %@%%", "cred_rate": "Loan · %@%%/yr",
            "no_bank_notary": "no bank (notary)", "from": "from", "mon": "mo",
            "sec_location": "Location", "open_2gis": "Open in 2GIS →",
            "re_rooms": "Rooms", "re_area": "Area", "re_land_area": "Plot", "re_floor": "Floor",
            "re_floors": "Floors", "re_year_built": "Year built", "re_renovation": "Renovation", "re_building": "Building type",
            "re_bathroom": "Bathroom", "re_docs": "Documents", "re_mortgage_ok": "Mortgage", "re_term": "Rental term",
            "re_utilities": "Utilities included", "re_furniture": "Furniture and appliances", "re_kids": "Children welcome",
            "re_pets": "Pets allowed", "re_owner": "Listed by", "re_land_use": "Land use", "re_parking": "Parking",
            "fac_gearbox": "Gearbox", "fac_fuel": "Fuel", "spec_mileage": "Mileage", "fac_year_short": "Year",
            "spec_year": "Year", "fac_engine": "Engine, L", "fac_area": "Area, m²", "fac_rooms": "Rooms",
            "fac_size": "Size", "fac_color": "Colour", "fac_material": "Material", "fac_plot": "Plot, ares",
            "fac_auto": "Automatic", "fac_manual": "Manual", "fac_robot": "Robotic", "fac_cvt": "CVT",
            "fac_petrol": "Petrol", "fac_diesel": "Diesel", "fac_gas": "Gas", "fac_hybrid": "Hybrid",
            "fac_electric": "Electric", "gpu_integrated": "Integrated", "gpu_discrete": "Discrete",
            "cond_new": "New", "cond_used": "Used", "fac_studio": "Studio"
        ],
        "ar": [
            "chk_auto_title": "فحص السيارة", "chk_realty_title": "فحص العقار",
            "chk_auto_clean": "نظيفة في سجلات كازاخستان", "chk_owner_ok": "المالك مؤكَّد",
            "chk_no_liens": "بلا أعباء أو حجز", "chk_issues": "وُجدت قيود",
            "chk_vin_ok": "رقم VIN مؤكَّد", "chk_cadastre_ok": "السجل العقاري مؤكَّد",
            "chk_rk_pending": "سجلات كازاخستان قيد الفحص", "chk_by_rk": "الفحص في سجلات كازاخستان",
            "chk_open": "فتح", "chk_check": "فحص",
            "chk_auto_hs": "رهن · بحث · تاريخ", "chk_realty_hs": "أعباء · حجز · مالك",
            "chk_vin": "VIN %@", "chk_vin_none": "لم يُذكر VIN", "chk_kad": "الرقم العقاري %@",
            "chk_kad_none": "لم يُذكر الرقم العقاري",
            "chk_lock_t": "التقرير متاح للموثَّقين",
            "chk_lock_b": "الفحص في سجلات كازاخستان جزء من حماية الصفقة. متاح بعد توثيق الهوية.",
            "chk_lock_btn": "وثّق هويتك ←",
            "chk_empty_t": "لم يُجرَ الفحص بعد",
            "chk_empty_b": "اطلب الفحص في سجلات كازاخستان — ستظهر النتيجة هنا وفي الإعلان.",
            "chk_request": "طلب الفحص",
            "chk_clean_short": "نظيف", "chk_limits": "قيود", "chk_pending": "قيد الفحص",
            "chk_confirmed": "مؤكَّد", "chk_unconfirmed": "غير مؤكَّد", "chk_has": "يوجد", "chk_none": "لا يوجد",
            "chk_vin_unrec": "لم يُتعرَّف على VIN", "chk_check_num": "تحقق من الرقم", "chk_has_limits": "توجد قيود",
            "chk_rk_found": "وُجدت سجلات في قواعد كازاخستان — استوضح",
            "chk_clean_vin_sub": "VIN مؤكَّد، لم تُوجد قيود",
            "chk_vin_pending_sub": "الرهن والبحث والتاريخ — قيد الفحص", "chk_kad_unrec": "لم يُتعرَّف على الرقم العقاري",
            "chk_realty_issue_rent": "أسئلة حول المالك/العقار",
            "chk_realty_issue_sale": "وُجدت أعباء / حجز", "chk_clean_ready": "نظيف — يمكن الإتمام",
            "chk_owner_ok_sub": "المالك مؤكَّد، لا قيود",
            "chk_kad_pending_sub": "الأعباء والحجز والمالك — قيد الفحص",
            "chk_car_data": "بيانات السيارة", "chk_vin_decode": "فك VIN", "chk_vin_valid": "VIN صالح",
            "chk_brand": "الماركة", "chk_year": "سنة الصنع", "chk_country": "بلد المصنع", "chk_rk_bases": "سجلات كازاخستان",
            "chk_pledge": "رهن / أعباء", "chk_wanted": "بحث / سرقة", "chk_restrictions": "قيود / حجز",
            "chk_realty_reg": "سجل العقارات في كازاخستان", "chk_encumbrance": "أعباء / رهن",
            "chk_arrest": "حجز / منع", "chk_owner": "المالك",
            "chk_owner_match_rent": "يطابق المؤجِّر", "chk_owner_match_sale": "يطابق البائع",
            "chk_kadastr": "الرقم العقاري", "chk_correct": "صحيح", "chk_region": "المنطقة", "chk_ad_type": "نوع الإعلان",
            "chk_rent": "إيجار", "chk_sale": "بيع", "chk_source": "المصدر: فحص المنصة",
            "chk_disclaimer": "معلومات مرجعية لا تغني عن المستخرج الرسمي.",
            "chk_b_car": "مركبة", "chk_b_rk": "KZ", "chk_b_rn": "سجل", "chk_b_k": "ع",
            "rplan_t": "مخطط المكان", "rplan_open": "فتح وتكبير",
            "pay_methods": "طرق الدفع", "installment": "التقسيط", "credit": "قرض",
            "inst_plus": "التقسيط · +%@%%", "inst_comm": "عمولة التقسيط %@%%", "cred_rate": "قرض · %@%% سنويًا",
            "no_bank_notary": "بلا بنك (كاتب عدل)", "from": "من", "mon": "شهر",
            "sec_location": "الموقع", "open_2gis": "فتح في 2GIS ←",
            "re_rooms": "الغرف", "re_area": "المساحة", "re_land_area": "الأرض", "re_floor": "الطابق",
            "re_floors": "عدد الطوابق", "re_year_built": "سنة البناء", "re_renovation": "التشطيب", "re_building": "نوع المبنى",
            "re_bathroom": "الحمّام", "re_docs": "الوثائق", "re_mortgage_ok": "رهن عقاري", "re_term": "مدة الإيجار",
            "re_utilities": "الخدمات مشمولة", "re_furniture": "أثاث وأجهزة", "re_kids": "يُسمح بالأطفال",
            "re_pets": "يُسمح بالحيوانات", "re_owner": "المُعلِن", "re_land_use": "الاستخدام", "re_parking": "يوجد موقف",
            "fac_gearbox": "ناقل الحركة", "fac_fuel": "الوقود", "spec_mileage": "المسافة المقطوعة", "fac_year_short": "السنة",
            "spec_year": "سنة الصنع", "fac_engine": "المحرك، لتر", "fac_area": "المساحة، م²", "fac_rooms": "الغرف",
            "fac_size": "المقاس", "fac_color": "اللون", "fac_material": "الخامة", "fac_plot": "الأرض، آر",
            "fac_auto": "أوتوماتيك", "fac_manual": "يدوي", "fac_robot": "روبوتي", "fac_cvt": "CVT",
            "fac_petrol": "بنزين", "fac_diesel": "ديزل", "fac_gas": "غاز", "fac_hybrid": "هجين",
            "fac_electric": "كهربائي", "gpu_integrated": "مدمجة", "gpu_discrete": "منفصلة",
            "cond_new": "جديد", "cond_used": "مستعمل", "fac_studio": "استوديو"
        ]
    ]
}
