import Foundation

/**
 Русские названия разделов — снимок справочника сайта js/cats-ru.js (MK_CATS, 26.09.2026) для хлебных крошек страницы
 объявления (владелец 26.09.2026, TestFlight: вместо «Электроника › Ноутбуки» стояло «Категория»).

 Обычно названия даёт загруженная страница сайта (SiteSession.названияРазделов); когда она не ответила или сама их не
 знает, крошки берут отсюда. Только русский — другого снимка у сайта в приложении нет: на kk/en/ar крошки без ответа
 страницы показывают корень словами приложения, как прежде. Новый раздел, которого нет в снимке, — просто без имени.
 */
enum ИменаРазделовСайта {
    /// Названия для разделов из списка, если язык телефона русский; прочие — пусто.
    static func запасные(_ разделы: [String]) -> [String: String] {
        guard ListingPageText.язык == "ru" else { return [:] }
        var итог: [String: String] = [:]
        for раздел in разделы {
            if let имя = ru[раздел] { итог[раздел] = имя }
        }
        return итог
    }

    private static let ru: [String: String] = [
        "electronics": "Электроника", "phones-tablets": "Телефоны и планшеты", "smartphones": "Смартфоны",
        "tablets": "Планшеты", "smartwatches": "Смарт-часы и браслеты",
        "phone-accessories": "Аксессуары для телефонов", "phone-cases": "Чехлы и защита",
        "phone-chargers": "Зарядные устройства", "phone-parts": "Запчасти для телефонов", "computers": "Компьютеры",
        "laptops": "Ноутбуки", "desktops": "Настольные ПК", "all-in-one": "Моноблоки", "monitors": "Мониторы",
        "pc-components": "Комплектующие", "cpu": "Процессоры", "gpu": "Видеокарты", "ram": "Оперативная память",
        "ssd-hdd": "SSD и жёсткие диски", "motherboards": "Материнские платы", "power-supplies": "Блоки питания",
        "pc-cases": "Корпуса", "cooling": "Охлаждение", "printers": "Принтеры и МФУ",
        "keyboards-mice": "Клавиатуры и мыши", "networking": "Сетевое оборудование",
        "ups-batteries": "ИБП и аккумуляторы", "tv-audio": "ТВ и аудио", "tv": "Телевизоры", "headphones": "Наушники",
        "speakers": "Колонки и акустика", "projectors": "Проекторы", "home-theater": "Домашние кинотеатры",
        "receivers": "AV-ресиверы", "media-players": "Медиаплееры", "photo-video": "Фото и видео",
        "cameras": "Фотоаппараты", "mirrorless": "Беззеркальные камеры", "lenses": "Объективы",
        "camcorders": "Видеокамеры", "action-cameras": "Экшн-камеры", "drones": "Дроны и квадрокоптеры",
        "photo-accessories": "Аксессуары для фото", "tripods": "Штативы и стедикамы", "games": "Игры",
        "consoles": "Игровые консоли", "video-games": "Игры (диски и коды)", "gamepads": "Геймпады",
        "gaming-chairs": "Игровые кресла и столы", "vr-headsets": "VR-гарнитуры", "office-equipment": "Оргтехника",
        "scanners": "Сканеры", "cash-registers": "Кассовые аппараты", "transport": "Транспорт", "cars": "Автомобили",
        "cars-sedan": "Легковые", "cars-suv": "Внедорожники и кроссоверы", "cars-minivan": "Минивэны и микроавтобусы",
        "cars-electric": "Электромобили", "cars-hybrid": "Гибриды", "cars-sport": "Спортивные",
        "motorcycles": "Мотоциклы и мототехника", "motorcycles-road": "Дорожные мотоциклы",
        "motorcycles-off": "Кроссовые / внедорожные", "scooters": "Скутеры и мопеды", "atvs": "Квадроциклы и ATV",
        "e-scooters": "Электросамокаты", "trucks-special": "Грузовые и спецтехника", "trucks": "Грузовики",
        "buses": "Автобусы", "agricultural": "Сельхозтехника", "construction-equip": "Строительная техника",
        "forklifts": "Погрузчики", "auto-parts": "Автозапчасти", "auto-parts-items": "Запчасти",
        "tires-wheels": "Шины и диски", "auto-accessories": "Автоаксессуары", "auto-audio": "Автозвук и мультимедиа",
        "auto-oils": "Масла и жидкости", "auto-lighting": "Освещение и оптика", "water-transport": "Водный транспорт",
        "boats": "Лодки", "jet-skis": "Гидроциклы", "realty": "Недвижимость", "apartments": "Квартиры",
        "apartments-sale": "Продажа квартир", "apartments-rent": "Аренда квартир",
        "apartments-daily": "Посуточная аренда", "rooms": "Комнаты", "houses": "Дома", "houses-sale": "Продажа домов",
        "houses-rent": "Аренда домов", "cottages": "Дачи и коттеджи", "commercial-realty": "Коммерческая недвижимость",
        "offices": "Офисы", "retail": "Торговые помещения", "warehouses": "Склады", "land": "Земельные участки",
        "land-housing": "ИЖС", "land-commercial": "Коммерческое назначение", "land-farm": "С/х назначение",
        "garages-parking": "Гаражи и паркинг", "garage-sale": "Продажа гаражей", "garage-rent": "Аренда гаражей",
        "parking-space": "Паркоместа", "clothing": "Одежда и обувь", "mens-clothing": "Мужская одежда",
        "mens-tops": "Верх (рубашки, футболки)", "mens-bottoms": "Низ (брюки, джинсы)",
        "mens-outerwear": "Верхняя одежда", "mens-suits": "Костюмы и пиджаки", "mens-sportswear": "Спортивная одежда",
        "womens-clothing": "Женская одежда", "womens-dresses": "Платья и юбки", "womens-tops": "Верх (блузки, топы)",
        "womens-bottoms": "Низ (брюки, джинсы)", "womens-outerwear": "Верхняя одежда",
        "womens-sportswear": "Спортивная одежда", "kids-clothing": "Детская одежда", "kids-clothing-0-3": "0–3 года",
        "kids-clothing-3-7": "3–7 лет", "kids-clothing-7-14": "7–14 лет", "shoes": "Обувь",
        "mens-shoes": "Мужская обувь", "womens-shoes": "Женская обувь", "kids-shoes": "Детская обувь",
        "sport-shoes": "Кроссовки и спортивная обувь", "bags-accessories": "Сумки и аксессуары",
        "handbags": "Женские сумки", "backpacks": "Рюкзаки", "wallets": "Кошельки и портмоне",
        "belts-scarves": "Ремни, шарфы, перчатки", "hats": "Шапки и головные уборы", "sunglasses": "Очки",
        "jewelry": "Ювелирные украшения", "rings": "Кольца", "necklaces": "Цепочки и кулоны", "bracelets": "Браслеты",
        "earrings": "Серьги", "watches": "Часы", "home-garden": "Дом и сад", "furniture": "Мебель",
        "sofas": "Диваны и кресла", "beds": "Кровати и матрасы", "tables": "Столы и стулья",
        "wardrobes": "Шкафы и стеллажи", "kitchen-furniture": "Кухонная мебель",
        "hall-furniture": "Мебель для прихожей", "office-furniture": "Офисная мебель",
        "outdoor-furniture": "Садовая мебель", "appliances": "Бытовая техника", "fridges": "Холодильники",
        "washing-machines": "Стиральные машины", "dishwashers": "Посудомоечные машины", "stoves": "Плиты и духовки",
        "microwaves": "Микроволновые печи", "air-conditioners": "Кондиционеры", "vacuum-cleaners": "Пылесосы",
        "small-appliances": "Мелкая бытовая техника", "kettles-coffee": "Чайники и кофемашины",
        "water-heaters": "Водонагреватели", "kitchenware": "Посуда и кухня", "cookware": "Кастрюли, сковороды",
        "cutlery": "Ножи и столовые приборы", "tableware": "Тарелки и чашки", "repair": "Ремонт и стройка",
        "tools": "Инструменты", "power-tools": "Электроинструмент", "building-materials": "Стройматериалы",
        "windows-doors": "Окна и двери", "plumbing": "Сантехника", "electrical": "Электрика",
        "flooring": "Напольные покрытия", "wallpaper-paint": "Обои и краски",
        "heating-cooling": "Отопление и вентиляция", "lighting": "Освещение", "chandeliers": "Люстры и светильники",
        "lamps": "Лампы и бра", "led-strips": "LED-ленты", "plants-gardening": "Растения и садоводство",
        "plants": "Комнатные растения", "seeds": "Семена", "garden-tools": "Садовый инвентарь",
        "lawn-mowers": "Газонокосилки", "textiles-decor": "Текстиль и декор", "bedding": "Постельное бельё",
        "curtains": "Шторы и тюль", "carpets": "Ковры", "decor-items": "Декор и интерьер", "kids": "Детские товары",
        "toys": "Игрушки", "toys-0-3": "До 3 лет", "toys-3-7": "3–7 лет", "toys-7plus": "7+ лет",
        "lego-constructors": "Конструкторы и LEGO", "radio-toys": "Радиоуправляемые",
        "dolls-figures": "Куклы и фигурки", "strollers-carseats": "Коляски и автокресла", "strollers": "Коляски",
        "car-seats": "Автокресла", "baby-carriers": "Рюкзаки-кенгуру", "kids-furniture": "Детская мебель",
        "kids-beds": "Детские кровати", "cribs": "Кроватки для новорождённых", "highchairs": "Стульчики для кормления",
        "kids-clothing-0-12": "Одежда 0–12 лет", "kids-newborn": "Для новорождённых (0–1)",
        "kids-clothing-boys": "Для мальчиков", "kids-clothing-girls": "Для девочек",
        "kids-outerwear": "Верхняя одежда", "school-supplies": "Школьные принадлежности",
        "school-backpacks": "Рюкзаки и сумки", "school-stationery": "Канцелярия", "school-uniform": "Школьная форма",
        "school-books": "Учебники и пособия", "kids-sports": "Детский спорт и активный отдых",
        "kids-bikes-scooters": "Велосипеды и самокаты", "kids-playgrounds": "Игровые комплексы",
        "kids-swimming": "Плавание и бассейны", "baby-food": "Детское питание", "baby-formula": "Смеси и каши",
        "baby-puree": "Пюре и снеки", "baby-feeding": "Бутылочки и посуда", "baby-care": "Уход за ребёнком",
        "baby-diapers": "Подгузники и салфетки", "baby-hygiene": "Купание и гигиена",
        "baby-monitors": "Радионяни и мониторы", "sport": "Спорт и отдых", "bicycles": "Велосипеды",
        "mtb": "Горные велосипеды", "road-bikes": "Шоссейные велосипеды", "kids-bikes": "Детские велосипеды",
        "e-bikes": "Электровелосипеды", "bike-accessories": "Велоаксессуары", "fitness": "Тренажёры и фитнес",
        "treadmills": "Беговые дорожки", "exercise-bikes": "Велотренажёры", "weights-barbells": "Штанги и гантели",
        "yoga-mats": "Коврики и йога", "sports-nutrition": "Спортивное питание", "winter-sport": "Зимний спорт",
        "skis": "Лыжи", "snowboards": "Сноуборды", "ice-skates": "Коньки", "water-sport": "Водный спорт",
        "surfing": "Сёрфинг и вейкбординг", "diving": "Дайвинг и снорклинг", "team-sports": "Командные виды спорта",
        "football-gear": "Футбол", "basketball-gear": "Баскетбол", "volleyball-gear": "Волейбол",
        "racket-sports": "Ракетные виды спорта", "camping": "Туризм и кемпинг", "tents": "Палатки",
        "sleeping-bags": "Спальники", "backpacks-camping": "Рюкзаки туристические",
        "hiking-boots": "Трекинговая обувь", "hunting-fishing": "Охота и рыбалка", "fishing-rods": "Удочки и снасти",
        "hunting-equipment": "Охотничье снаряжение", "animals": "Животные", "dogs": "Собаки", "dogs-puppies": "Щенки",
        "dogs-adults": "Взрослые собаки", "cats": "Кошки", "cats-kittens": "Котята", "cats-adults": "Взрослые кошки",
        "birds": "Птицы", "parrots": "Попугаи", "canaries": "Канарейки и зяблики", "pigeons": "Голуби",
        "birds-exotic": "Экзотические птицы", "birds-other": "Другие птицы", "fish-aquariums": "Рыбы и аквариумы",
        "aquariums": "Аквариумы", "fish": "Рыбы", "rodents": "Грызуны", "rodents-hamsters": "Хомяки и мыши",
        "rodents-rabbits": "Кролики", "rodents-guinea": "Морские свинки", "rodents-cages": "Клетки и аксессуары",
        "reptiles": "Рептилии и амфибии", "reptiles-turtles": "Черепахи", "reptiles-lizards": "Ящерицы и гекконы",
        "reptiles-snakes": "Змеи", "reptiles-terrariums": "Террариумы и оборудование", "livestock": "Сельхозживотные",
        "cattle": "Коровы и быки", "sheep-goats": "Овцы и козы", "horses": "Лошади", "camels": "Верблюды",
        "pigs": "Свиньи", "poultry": "Домашняя птица", "poultry-chickens": "Куры и петухи",
        "poultry-ducks-geese": "Утки и гуси", "poultry-turkeys": "Индюки", "poultry-quails": "Перепела",
        "pet-food-care": "Корм и уход", "dog-food": "Корм для собак", "cat-food": "Корм для кошек",
        "vet-supplies": "Ветеринарные препараты", "pet-accessories": "Аксессуары для животных",
        "cages-carriers": "Клетки и переноски", "collars-leashes": "Ошейники и поводки", "jobs": "Работа",
        "vacancies": "Вакансии", "jobs-it": "IT и программирование", "jobs-marketing": "Маркетинг и реклама",
        "jobs-trade": "Торговля и продажи", "jobs-finance": "Финансы и бухгалтерия", "jobs-driver": "Водители",
        "jobs-builder": "Строители и ремонт", "jobs-security": "Охрана", "jobs-logistics": "Склад и логистика",
        "jobs-part-time": "Подработка и разовые", "resumes": "Резюме", "services": "Услуги",
        "tech-repair": "Ремонт техники", "phone-repair": "Ремонт телефонов", "iphone-repair": "Ремонт iPhone",
        "android-repair": "Ремонт Android", "screen-replacement": "Замена экрана",
        "battery-replacement": "Замена аккумулятора", "laptop-repair": "Ремонт ноутбуков",
        "laptop-screen-rep": "Замена матрицы ноутбука", "laptop-battery-rep": "Замена батареи ноутбука",
        "laptop-keyboard-rep": "Ремонт клавиатуры ноутбука", "pc-repair": "Ремонт компьютеров",
        "pc-upgrade": "Апгрейд ПК", "virus-removal": "Удаление вирусов", "os-install": "Установка Windows/macOS",
        "tablet-repair": "Ремонт планшетов", "tv-repair": "Ремонт телевизоров",
        "appliance-repair": "Ремонт бытовой техники", "fridge-repair": "Ремонт холодильников",
        "washer-repair": "Ремонт стиральных машин", "ac-repair": "Ремонт кондиционеров",
        "microwave-repair": "Ремонт микроволновок", "printer-repair": "Ремонт принтеров",
        "camera-repair": "Ремонт фотоаппаратов", "repair-construction": "Ремонт и строительство",
        "apartment-repair": "Ремонт квартир", "cosmetic-repair": "Косметический ремонт",
        "major-repair": "Капитальный ремонт", "plumbing-service": "Сантехнические работы",
        "electrical-service": "Электромонтаж", "window-service": "Установка и ремонт окон",
        "window-install": "Установка пластиковых окон", "window-repair-svc": "Ремонт окон и ручек",
        "window-mosquito": "Москитные сетки", "door-service": "Установка дверей",
        "flooring-service": "Укладка полов и плитки", "painting-service": "Малярные и штукатурные работы",
        "ceiling-service": "Натяжные потолки", "construction-gen": "Строительство домов",
        "welding": "Сварочные работы", "furniture-assembly": "Сборка мебели",
        "moving-service": "Перевозка мебели и переезд", "cleaning-service": "Уборка и клининг",
        "dry-cleaning": "Химчистка мебели и ковров", "auto-services": "Авто-услуги",
        "car-service": "СТО и ремонт авто", "tire-service": "Шиномонтаж", "car-wash": "Автомойка",
        "auto-painting": "Кузовной ремонт и покраска", "car-detailing": "Детейлинг и полировка",
        "auto-electrician": "Авто-электрик", "auto-glass": "Ремонт и замена стёкол авто",
        "auto-diagnostics": "Компьютерная диагностика", "evacuation": "Эвакуатор",
        "beauty-health": "Красота и здоровье", "hairdresser": "Парикмахер", "manicure": "Маникюр и педикюр",
        "eyelashes-brows": "Ресницы и брови", "massage": "Массаж", "cosmetology": "Косметология",
        "makeup": "Визаж и макияж", "tattooing": "Татуировки и пирсинг", "epilation": "Эпиляция и депиляция",
        "medical-services": "Медицинские услуги", "psychologist": "Психолог", "fitness-trainer": "Фитнес-тренер",
        "tutors-education": "Репетиторы и обучение", "math-tutor": "Математика", "english-tutor": "Английский язык",
        "russian-tutor": "Русский язык", "kazakh-tutor": "Казахский язык", "music-lessons": "Музыкальные занятия",
        "driving-lessons": "Автошкола / вождение", "courses-online": "Онлайн-курсы",
        "kids-development": "Детское развитие", "drawing-art": "Рисование и творчество",
        "it-development": "IT и разработка", "web-dev": "Создание сайтов", "mobile-dev": "Разработка приложений",
        "seo": "SEO и продвижение", "smm": "SMM и контент", "design": "Дизайн и графика", "1c-it": "1С и ERP",
        "it-support": "IT-поддержка бизнеса", "delivery-courier": "Доставка и курьеры",
        "city-courier": "Курьер по городу", "same-day-delivery": "Доставка в день заказа",
        "express-delivery": "Экспресс-доставка (1–2 ч)", "cargo-intercity": "Межгородские грузоперевозки",
        "cargo-transport": "Грузоперевозки", "movers": "Грузчики", "package-delivery": "Пересылка посылок",
        "food-delivery": "Доставка еды", "motorcycle-courier": "Мото-курьер", "photo-video-svc": "Фото и видеосъёмка",
        "photographer": "Фотограф", "videographer": "Видеограф", "wedding-photo": "Свадебная фото/видео",
        "drone-photo": "Аэрофото и видео с дрона", "reels-creation": "Reels и контент для соцсетей",
        "events": "Мероприятия и праздники", "toastmaster": "Тамада и ведущий", "dj": "DJ и музыканты",
        "animators": "Аниматоры и клоуны", "event-decoration": "Декор мероприятий", "catering": "Кейтеринг и банкеты",
        "legal-financial": "Юридические и финансовые", "lawyer": "Юрист и адвокат", "notary": "Нотариус",
        "accountant": "Бухгалтер", "business-reg": "Регистрация бизнеса", "tax-consulting": "Налоговые консультации",
        "insurance": "Страхование", "translation": "Переводы", "written-translation": "Письменный перевод",
        "oral-translation": "Устный перевод", "other-services": "Другие услуги", "handyman": "Муж на час",
        "pet-walking": "Выгул и уход за животными", "laundry": "Стирка и глажка", "tailoring": "Пошив и ремонт одежды",
        "shoe-repair": "Ремонт обуви", "key-copy": "Изготовление ключей", "printing": "Печать и полиграфия",
        "security-cameras": "Видеонаблюдение и охрана", "hobby": "Хобби и творчество", "books": "Книги и журналы",
        "fiction": "Художественная литература", "educational-books": "Учебники и образование",
        "textbooks": "Школьные учебники", "comics-manga": "Комиксы и манга",
        "musical-instruments": "Музыкальные инструменты", "guitars": "Гитары",
        "keyboards-piano": "Пианино и синтезаторы", "drums": "Ударные инструменты",
        "wind-instruments": "Духовые инструменты", "studio-gear": "Студийное оборудование",
        "collecting": "Коллекционирование", "coins": "Монеты", "stamps": "Марки", "antiques": "Антиквариат",
        "handmade": "Рукоделие", "knitting": "Вязание", "embroidery": "Вышивка", "board-games": "Настольные игры",
        "chess": "Шахматы", "puzzles": "Пазлы", "art-supplies": "Рисование и живопись", "art-paints": "Краски и кисти",
        "art-canvas": "Холсты и бумага", "art-graphics": "Графика и маркеры", "art-easels": "Мольберты и планшеты",
        "model-making": "Моделирование и 3D-печать", "models-kits": "Сборные модели", "models-rc": "Радиоуправляемые",
        "models-3d": "3D-принтеры и филамент", "models-tools": "Инструменты для моделизма",
        "food-farm": "Продукты и фермерство", "fruits-vegetables": "Фрукты и овощи",
        "local-produce": "Местные фрукты и овощи", "greens": "Зелень и специи",
        "honey-natural": "Мёд и натуральные продукты", "honey": "Мёд", "dairy": "Молоко, творог, сыр", "eggs": "Яйца",
        "meat-farm": "Мясо и птица", "dried-fruits": "Сухофрукты и орехи", "jam-preserves": "Варенье и заготовки",
        "seedlings": "Рассада и саженцы", "fruit-seedlings": "Саженцы деревьев", "veg-seedlings": "Рассада овощей",
        "farm-equipment": "Сельхозоборудование", "farm-tractors": "Мини-тракторы и мотоблоки",
        "farm-tools": "Навесное оборудование", "farm-irrigation": "Полив и теплицы", "beekeeping": "Пчеловодство",
        "bee-hives": "Ульи и рамки", "bee-tools": "Инвентарь пчеловода", "bee-families": "Пчелосемьи и матки",
        "fertilizers": "Удобрения и агрохимия", "fert-mineral": "Минеральные удобрения",
        "fert-organic": "Органика и биогумус", "fert-protection": "Защита растений",
        "grocery": "Бакалея и готовые продукты", "grocery-sauces": "Соусы, майонез, кетчуп",
        "grocery-oil": "Масло и жиры", "grocery-cereals": "Крупы, макароны, мука",
        "grocery-canned": "Консервы и соленья", "grocery-sweets": "Сладости и снеки", "grocery-drinks": "Напитки",
        "grocery-tea-coffee": "Чай и кофе", "grocery-bakery": "Хлеб и выпечка",
        "grocery-frozen": "Замороженные продукты", "grocery-other": "Прочая бакалея", "beauty": "Красота и здоровье",
        "beauty-perfume": "Парфюмерия", "perfume-women": "Женская парфюмерия", "perfume-men": "Мужская парфюмерия",
        "perfume-unisex": "Унисекс и нишевая", "perfume-sets": "Наборы и миниатюры",
        "beauty-makeup": "Декоративная косметика", "makeup-face": "Для лица (тон, пудра)",
        "makeup-eyes": "Для глаз (тушь, тени)", "makeup-lips": "Для губ", "makeup-brushes": "Кисти и спонжи",
        "makeup-sets": "Наборы косметики", "beauty-skincare": "Уход за кожей", "skincare-face": "Уход за лицом",
        "skincare-masks": "Маски и патчи", "skincare-sun": "Солнцезащита", "skincare-problem": "Проблемная кожа",
        "beauty-haircare": "Уход за волосами", "hair-shampoo": "Шампуни и бальзамы", "hair-treatment": "Маски и уход",
        "hair-color": "Краски и осветление", "hair-styling": "Стайлинг и укладка",
        "beauty-bodycare": "Уход за телом и гигиена", "body-shower": "Гели и мыло", "body-cream": "Кремы и лосьоны",
        "body-hygiene": "Личная гигиена", "body-shaving": "Бритьё и депиляция", "beauty-manicure": "Маникюр и педикюр",
        "nails-polish": "Лаки и гель-лаки", "nails-tools": "Инструменты и фрезеры", "nails-lamps": "Лампы для сушки",
        "nails-care": "Уход за ногтями", "beauty-appliances": "Приборы для красоты",
        "beauty-hairdryers": "Фены и стайлеры", "beauty-clippers": "Машинки для стрижки",
        "beauty-epilators": "Эпиляторы и лазеры", "beauty-face-devices": "Приборы для лица",
        "beauty-vitamins": "Витамины и БАДы", "vitamins-complex": "Витамины и минералы",
        "vitamins-sport": "Спортивное питание", "vitamins-herbal": "Травы и фитопрепараты",
        "beauty-medical": "Медтехника и здоровье", "med-diagnostic": "Тонометры и термометры",
        "med-rehab": "Реабилитация и ортопедия", "med-massage": "Массажёры", "med-supplies": "Расходные материалы",
        "beauty-optics": "Оптика (очки, линзы)", "optics-glasses": "Очки для зрения",
        "optics-sun": "Солнцезащитные очки", "optics-lenses": "Контактные линзы", "beauty-other": "Другое для красоты"
    ]
}
