import Foundation

/**
 Тексты мастеров подачи (TestFlight: «при подаче авто сначала бренд и модель, затем фото», «услуга не верно
 настроена») на языке телефона (ru/kk/en/ar): мастер авто (_aw2 сайта), мастер объекта недвижимости (_rw2), мастер
 услуги (#svc-wizard-panel, _SVC_DIR_Q) и заголовки плана съёмки (_rshHead). Русские — слово в слово с сайта
 (js/cabinet.min.js, js/cabinet-compose.min.js, js/i18n-cabinet-ru.js); «Популярные», «Укажите год и пробег»,
 «Заполните поля со звёздочкой» и «Услуга» у первого шага — свои, в том же тоне. Нет ключа — текст ПодачаText.
 */
enum МастерПодачиText {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь: [String: String]
        switch язык {
        case "kk": словарь = kk
        case "en": словарь = en
        case "ar": словарь = ar
        default: словарь = ru
        }
        return словарь[ключ] ?? ru[ключ] ?? ПодачаText.т(ключ)
    }

    private static let ru: [String: String] = [
        // общее
        "m_step": "Шаг %d из %d", "m_cancel": "Отмена", "m_back": "Назад", "m_next": "Далее", "m_done": "Готово",
        "m_save": "Сохранить", "m_reset": "Сбросить", "m_close": "Закрыть",
        // мастер авто
        "aw_car": "Автомобиль", "aw_brand": "Марка", "aw_model": "Модель", "aw_gen": "Поколение",
        "aw_brand_search": "Поиск марки", "aw_model_search": "Поиск модели",
        "aw_brand_other": "Другая марка — вписать", "aw_brand_other_ph": "Название марки",
        "aw_model_other": "Другая модель — вписать", "aw_model_other_ph": "Название модели",
        "aw_other_need": "Впишите название", "aw_loading": "Загружаем справочник…",
        "aw_brands_none": "Справочник марок сейчас недоступен — впишите марку сами, остальное заполним как обычно.",
        "aw_models_none": "Моделей этой марки нет в справочнике — впишите название сами.",
        "aw_models_body": "Показаны модели выбранного типа кузова — %d из %d.",
        "aw_gens_none": "Поколений этой модели нет в справочнике — шаг можно пропустить.",
        "aw_first_brand": "Сначала выберите марку.",
        "aw_popular": "Популярные", "aw_others": "Другие", "aw_nothing": "Ничего не нашли — впишите название сами",
        "aw_year": "Год выпуска", "aw_year_pick": "— выберите год —", "aw_mileage": "Пробег", "aw_engine": "Двигатель",
        "aw_km": "км", "aw_l": "л", "aw_now": "н.в.", "aw_yr": "г.",
        "aw_gen_years": "Годы — от выбранного поколения (%@): так объявление находят и по году, и по поколению.",
        "aw_nums_hint": "Пробег и объём — только числами: «85 000 км» отбор прочитает как ноль.",
        "aw_need_nums": "Укажите год и пробег",
        "aw_gear": "Коробка", "aw_fuel": "Топливо",
        "aw_words_hint": "Слова те же, что в фильтре витрины — иначе объявление не попадёт в выдачу по коробке и топливу.",
        "aw_saved": "Параметры сохранены",
        "aw_entry_t": "Параметры автомобиля", "aw_entry_new": "Указать параметры автомобиля",
        "aw_entry_s": "марка, модель, поколение, пробег",
        "aw_body_cars": "Какой кузов?", "aw_body_moto": "Что именно?", "aw_body_other": "Уточните тип",
        "aw_body_s": "%@ · так объявление попадёт в нужный фильтр покупателя.",
        "aw_body_skip": "Пропустить уточнение", "aw_body": "Кузов",
        "aw_title_lock": "Название собирается из параметров автомобиля — так машину находят по марке, модели и поколению",
        // мастер недвижимости
        "rw_title": "Недвижимость", "rw_what_q": "Что вы размещаете?",
        "rw_what_s": "От этого зависят поля: у аренды свои условия, у продажи — документы.",
        "rw_deal_l": "Тип сделки", "rw_kind_l": "Тип объекта",
        "rw_sale": "Продаю", "rw_sale_s": "продажа объекта", "rw_rent": "Сдаю", "rw_rent_s": "аренда жилья",
        "rw_params_q": "Параметры объекта",
        "rw_params_s": "Именно по ним покупатели фильтруют — без них объявление не найдут.",
        "rw_cond_rent": "Условия аренды", "rw_cond_rent_s": "Это первое, что спрашивают в переписке — ответьте заранее.",
        "rw_cond_sale": "Условия продажи", "rw_cond_sale_s": "Документы и возможность ипотеки повышают доверие.",
        "rw_sum_q": "Проверьте перед публикацией", "rw_sum_s": "Эти данные попадут в карточку и в фильтры поиска.",
        "rw_deal": "Сделка", "rw_obj": "Объект", "rw_yes": "да",
        "rw_none": "Для этого типа объекта дополнительных полей нет.",
        "rw_saved": "Параметры сохранены — название и описание заполнены",
        "rw_entry_new": "Заполнить параметры объекта", "rw_entry_new_s": "Комнаты, площадь, этаж и условия — по шагам",
        "rw_entry_saved": "параметры сохранены", "rw_req": "Заполните поля со звёздочкой",
        "rk_apartment": "Квартира", "rk_house": "Дом", "rk_commercial": "Коммерция", "rk_land": "Участок",
        "rd_sale": "Продажа", "rd_rent": "Аренда", "rd_sale_l": "продажа", "rd_rent_l": "аренда",
        // мастер услуги
        "svc_step": "Услуга", "svc_pick": "Чем хотите заняться?",
        "svc_pick_s": "Выберите направление — остальное соберёт Kliko AI. Заполнять руками не нужно.",
        "svc_change": "Изменить", "svc_q1": "Что вы делаете или что чините?",
        "svc_q1_ph": "Напр.: ремонт холодильников и стиральных машин на дому",
        "svc_q2": "Что входит, ваши плюсы?", "svc_q2_ph": "Напр.: бесплатный выезд, гарантия 6 мес, оригинальные запчасти",
        "svc_opt": "необязательно", "svc_price": "Цена от, ₸", "svc_city": "Город", "svc_city_ph": "Город / посёлок",
        "svc_go": "Собрать объявление",
        "svc_note": "Kliko AI подберёт раздел, напишет заголовок и деловое описание. Фото для услуги необязательно.",
        "svc_prog_1": "Подбираю раздел…", "svc_prog_2": "Пишу заголовок…", "svc_prog_3": "Готовлю описание…",
        "svc_done": "Готово! Проверьте и опубликуйте", "svc_need": "Опишите, что вы делаете",
        "svc_fail": "Не удалось собрать. Попробуйте ещё раз", "svc_limit_t": "Достигнут лимит",
        "svc_manual": "Заполню вручную",
        "svc_photo_opt": "необязательно для услуги", "svc_photo_add": "Добавить своё фото",
        "sq_tech-repair": "Что чините?", "sp_tech-repair": "Напр.: холодильники и стиральные машины на дому",
        "sq_repair-construction": "Какие работы делаете?",
        "sp_repair-construction": "Напр.: отделка квартир под ключ, сантехника, электрика",
        "sq_auto-services": "Какие авто-услуги оказываете?", "sp_auto-services": "Напр.: шиномонтаж, замена масла, автомойка",
        "sq_beauty-health": "Что делаете?", "sp_beauty-health": "Напр.: маникюр и педикюр, наращивание ресниц на дому",
        "sq_tutors-education": "Чему обучаете?", "sp_tutors-education": "Напр.: репетитор по математике, подготовка к ЕНТ",
        "sq_it-development": "Что разрабатываете?", "sp_it-development": "Напр.: сайты и интернет-магазины на заказ",
        "sq_delivery-courier": "Что доставляете?", "sp_delivery-courier": "Напр.: курьер по городу, доставка еды и документов",
        "sq_photo-video-svc": "Что снимаете?", "sp_photo-video-svc": "Напр.: свадебная фото- и видеосъёмка, монтаж",
        "sq_events": "Что организуете?", "sp_events": "Напр.: ведущий на праздник, аниматоры, декор",
        "sq_legal-financial": "Какие услуги оказываете?", "sp_legal-financial": "Напр.: бухгалтерское сопровождение, помощь юриста",
        "sq_translation": "Что переводите?", "sp_translation": "Напр.: письменный перевод документов, устный перевод",
        "sq_other-services": "Что вы делаете?", "sp_other-services": "Напр.: муж на час, выгул собак, мелкий ремонт",
        // план съёмки
        "rsh_h": "Снимите по плану", "rsh_rent_tail": ", аренда", "rsh_count": "Снято %d из %d",
        "gh_rent": "Аренда", "gh_phone": "Телефон", "gh_laptop": "Ноутбук", "gh_clothes": "Одежда", "gh_shoes": "Обувь",
        "gh_furniture": "Мебель", "gh_appliance": "Техника", "gh_building": "Стройматериалы", "gh_other": "Другое"
    ]

    private static let kk: [String: String] = [
        "m_step": "%d-қадам, барлығы %d", "m_cancel": "Бас тарту", "m_back": "Артқа", "m_next": "Әрі қарай",
        "m_done": "Дайын", "m_save": "Сақтау", "m_reset": "Тазалау", "m_close": "Жабу",
        "aw_car": "Автокөлік", "aw_brand": "Маркасы", "aw_model": "Моделі", "aw_gen": "Буыны",
        "aw_brand_search": "Марканы іздеу", "aw_model_search": "Модельді іздеу",
        "aw_brand_other": "Басқа марка — жазу", "aw_brand_other_ph": "Марка атауы",
        "aw_model_other": "Басқа модель — жазу", "aw_model_other_ph": "Модель атауы",
        "aw_other_need": "Атауын жазыңыз", "aw_loading": "Анықтамалық жүктелуде…",
        "aw_brands_none": "Маркалар анықтамалығы қазір қолжетімсіз — марканы өзіңіз жазыңыз, қалғанын әдеттегідей толтырамыз.",
        "aw_models_none": "Бұл марканың модельдері анықтамалықта жоқ — атауын өзіңіз жазыңыз.",
        "aw_models_body": "Таңдалған шанақ түрінің модельдері көрсетілген — %d / %d.",
        "aw_gens_none": "Бұл модельдің буындары анықтамалықта жоқ — қадамды өткізіп жіберуге болады.",
        "aw_first_brand": "Алдымен марканы таңдаңыз.",
        "aw_popular": "Танымал", "aw_others": "Басқалары", "aw_nothing": "Ештеңе табылмады — атауын өзіңіз жазыңыз",
        "aw_year": "Шығарылған жылы", "aw_year_pick": "— жылды таңдаңыз —", "aw_mileage": "Жүрісі", "aw_engine": "Қозғалтқыш",
        "aw_km": "км", "aw_l": "л", "aw_now": "қ.у.", "aw_yr": "ж.",
        "aw_gen_years": "Жылдар — таңдалған буыннан (%@): хабарландыруды жылы бойынша да, буыны бойынша да табады.",
        "aw_nums_hint": "Жүрісі мен көлемі — тек санмен: «85 000 км» сүзгі нөл деп оқиды.",
        "aw_need_nums": "Жылы мен жүрісін көрсетіңіз",
        "aw_gear": "Беріліс қорабы", "aw_fuel": "Отын",
        "aw_words_hint": "Сөздер витрина сүзгісіндегідей — әйтпесе хабарландыру қорап пен отын бойынша іздеуге түспейді.",
        "aw_saved": "Параметрлер сақталды",
        "aw_entry_t": "Автокөлік параметрлері", "aw_entry_new": "Автокөлік параметрлерін көрсету",
        "aw_entry_s": "маркасы, моделі, буыны, жүрісі",
        "aw_body_cars": "Шанақ түрі қандай?", "aw_body_moto": "Нақты не?", "aw_body_other": "Түрін нақтылаңыз",
        "aw_body_s": "%@ · хабарландыру сатып алушының керек сүзгісіне түседі.",
        "aw_body_skip": "Нақтыламай өту", "aw_body": "Шанақ",
        "aw_title_lock": "Атауы автокөлік параметрлерінен құралады — көлікті маркасы, моделі және буыны бойынша табады",
        "rw_title": "Жылжымайтын мүлік", "rw_what_q": "Не орналастырасыз?",
        "rw_what_s": "Өрістер осыған байланысты: жалдаудың өз шарттары, сатудың — құжаттары бар.",
        "rw_deal_l": "Мәміле түрі", "rw_kind_l": "Нысан түрі",
        "rw_sale": "Сатамын", "rw_sale_s": "нысанды сату", "rw_rent": "Жалға беремін", "rw_rent_s": "тұрғын үйді жалға беру",
        "rw_params_q": "Нысан параметрлері",
        "rw_params_s": "Сатып алушылар дәл осылар бойынша сүзеді — оларсыз хабарландыруды таппайды.",
        "rw_cond_rent": "Жалдау шарттары", "rw_cond_rent_s": "Хат алмасуда алдымен осыны сұрайды — алдын ала жауап беріңіз.",
        "rw_cond_sale": "Сату шарттары", "rw_cond_sale_s": "Құжаттар мен ипотека мүмкіндігі сенімді арттырады.",
        "rw_sum_q": "Жарияламас бұрын тексеріңіз", "rw_sum_s": "Бұл деректер карточкаға және іздеу сүзгілеріне түседі.",
        "rw_deal": "Мәміле", "rw_obj": "Нысан", "rw_yes": "иә",
        "rw_none": "Бұл нысан түріне қосымша өрістер жоқ.",
        "rw_saved": "Параметрлер сақталды — атауы мен сипаттамасы толтырылды",
        "rw_entry_new": "Нысан параметрлерін толтыру", "rw_entry_new_s": "Бөлмелер, аудан, қабат және шарттар — қадаммен",
        "rw_entry_saved": "параметрлер сақталды", "rw_req": "Жұлдызшасы бар өрістерді толтырыңыз",
        "rk_apartment": "Пәтер", "rk_house": "Үй", "rk_commercial": "Коммерция", "rk_land": "Жер телімі",
        "rd_sale": "Сату", "rd_rent": "Жалға беру", "rd_sale_l": "сату", "rd_rent_l": "жалға беру",
        "svc_step": "Қызмет", "svc_pick": "Немен айналысқыңыз келеді?",
        "svc_pick_s": "Бағытты таңдаңыз — қалғанын Kliko AI жинайды. Қолмен толтырудың қажеті жоқ.",
        "svc_change": "Өзгерту", "svc_q1": "Не істейсіз немесе нені жөндейсіз?",
        "svc_q1_ph": "Мысалы: тоңазытқыш пен кір жуғыш машиналарды үйде жөндеу",
        "svc_q2": "Не кіреді, артықшылықтарыңыз?", "svc_q2_ph": "Мысалы: тегін шығу, 6 ай кепілдік, түпнұсқа бөлшектер",
        "svc_opt": "міндетті емес", "svc_price": "Бағасы, ₸ бастап", "svc_city": "Қала", "svc_city_ph": "Қала / кент",
        "svc_go": "Хабарландыруды жинау",
        "svc_note": "Kliko AI бөлімді таңдап, тақырып пен іскерлік сипаттама жазады. Қызмет үшін фото міндетті емес.",
        "svc_prog_1": "Бөлімді таңдап жатырмын…", "svc_prog_2": "Тақырып жазып жатырмын…",
        "svc_prog_3": "Сипаттама дайындап жатырмын…",
        "svc_done": "Дайын! Тексеріп, жариялаңыз", "svc_need": "Не істейтініңізді сипаттаңыз",
        "svc_fail": "Жинау мүмкін болмады. Қайталап көріңіз", "svc_limit_t": "Шекке жеттіңіз",
        "svc_manual": "Қолмен толтырамын",
        "svc_photo_opt": "қызмет үшін міндетті емес", "svc_photo_add": "Өз фотоңызды қосу",
        "sq_tech-repair": "Нені жөндейсіз?", "sp_tech-repair": "Мысалы: тоңазытқыштар мен кір жуғыш машиналар үйде",
        "sq_repair-construction": "Қандай жұмыстар жасайсыз?",
        "sp_repair-construction": "Мысалы: пәтерлерді толық әрлеу, сантехника, электр",
        "sq_auto-services": "Қандай авто-қызметтер көрсетесіз?", "sp_auto-services": "Мысалы: шиномонтаж, май ауыстыру, көлік жуу",
        "sq_beauty-health": "Не істейсіз?", "sp_beauty-health": "Мысалы: маникюр мен педикюр, кірпік жапсыру үйде",
        "sq_tutors-education": "Нені үйретесіз?", "sp_tutors-education": "Мысалы: математикадан репетитор, ҰБТ-ға дайындық",
        "sq_it-development": "Не әзірлейсіз?", "sp_it-development": "Мысалы: тапсырыспен сайттар мен интернет-дүкендер",
        "sq_delivery-courier": "Не жеткізесіз?", "sp_delivery-courier": "Мысалы: қала ішінде курьер, тамақ пен құжат жеткізу",
        "sq_photo-video-svc": "Не түсіресіз?", "sp_photo-video-svc": "Мысалы: той фото- және бейнетүсірілімі, монтаж",
        "sq_events": "Не ұйымдастырасыз?", "sp_events": "Мысалы: мерекеге жүргізуші, аниматорлар, безендіру",
        "sq_legal-financial": "Қандай қызметтер көрсетесіз?", "sp_legal-financial": "Мысалы: бухгалтерлік сүйемелдеу, заңгер көмегі",
        "sq_translation": "Нені аударасыз?", "sp_translation": "Мысалы: құжаттарды жазбаша аудару, ауызша аударма",
        "sq_other-services": "Не істейсіз?", "sp_other-services": "Мысалы: бір сағатқа шебер, ит серуендету, ұсақ жөндеу",
        "rsh_h": "Жоспар бойынша түсіріңіз", "rsh_rent_tail": ", жалға беру", "rsh_count": "%d / %d түсірілді",
        "gh_rent": "Жалға беру", "gh_phone": "Телефон", "gh_laptop": "Ноутбук", "gh_clothes": "Киім", "gh_shoes": "Аяқ киім",
        "gh_furniture": "Жиһаз", "gh_appliance": "Техника", "gh_building": "Құрылыс материалдары", "gh_other": "Басқа"
    ]

    private static let en: [String: String] = [
        "m_step": "Step %d of %d", "m_cancel": "Cancel", "m_back": "Back", "m_next": "Next", "m_done": "Done",
        "m_save": "Save", "m_reset": "Reset", "m_close": "Close",
        "aw_car": "Car", "aw_brand": "Make", "aw_model": "Model", "aw_gen": "Generation",
        "aw_brand_search": "Search makes", "aw_model_search": "Search models",
        "aw_brand_other": "Other make — type it", "aw_brand_other_ph": "Make name",
        "aw_model_other": "Other model — type it", "aw_model_other_ph": "Model name",
        "aw_other_need": "Type the name", "aw_loading": "Loading the catalog…",
        "aw_brands_none": "The make catalog is unavailable right now — type the make yourself, the rest works as usual.",
        "aw_models_none": "This make's models aren't in the catalog — type the name yourself.",
        "aw_models_body": "Showing models of the chosen body type — %d of %d.",
        "aw_gens_none": "This model's generations aren't in the catalog — you can skip this step.",
        "aw_first_brand": "Choose the make first.",
        "aw_popular": "Popular", "aw_others": "Others", "aw_nothing": "Nothing found — type the name yourself",
        "aw_year": "Year", "aw_year_pick": "— choose the year —", "aw_mileage": "Mileage", "aw_engine": "Engine",
        "aw_km": "km", "aw_l": "L", "aw_now": "now", "aw_yr": "",
        "aw_gen_years": "Years come from the chosen generation (%@): buyers find the listing by year and by generation.",
        "aw_nums_hint": "Mileage and engine size — numbers only: the filter reads “85,000 km” as zero.",
        "aw_need_nums": "Enter the year and mileage",
        "aw_gear": "Gearbox", "aw_fuel": "Fuel",
        "aw_words_hint": "Same words as the storefront filter — otherwise the listing won't show up by gearbox and fuel.",
        "aw_saved": "Details saved",
        "aw_entry_t": "Car details", "aw_entry_new": "Add car details",
        "aw_entry_s": "make, model, generation, mileage",
        "aw_body_cars": "Which body type?", "aw_body_moto": "What exactly?", "aw_body_other": "Choose the type",
        "aw_body_s": "%@ · so the listing lands in the buyer's filter.",
        "aw_body_skip": "Skip this", "aw_body": "Body type",
        "aw_title_lock": "The title is built from the car details — buyers find cars by make, model and generation",
        "rw_title": "Real estate", "rw_what_q": "What are you listing?",
        "rw_what_s": "The fields depend on it: rentals have their terms, sales have documents.",
        "rw_deal_l": "Deal type", "rw_kind_l": "Property type",
        "rw_sale": "Selling", "rw_sale_s": "property sale", "rw_rent": "Renting out", "rw_rent_s": "housing rental",
        "rw_params_q": "Property details",
        "rw_params_s": "Buyers filter by exactly these — without them the listing won't be found.",
        "rw_cond_rent": "Rental terms", "rw_cond_rent_s": "This is the first thing asked in chat — answer it up front.",
        "rw_cond_sale": "Sale terms", "rw_cond_sale_s": "Documents and a mortgage option build trust.",
        "rw_sum_q": "Check before publishing", "rw_sum_s": "This goes into the card and the search filters.",
        "rw_deal": "Deal", "rw_obj": "Property", "rw_yes": "yes",
        "rw_none": "This property type has no extra fields.",
        "rw_saved": "Details saved — title and description filled in",
        "rw_entry_new": "Add property details", "rw_entry_new_s": "Rooms, area, floor and terms — step by step",
        "rw_entry_saved": "details saved", "rw_req": "Fill in the fields marked with an asterisk",
        "rk_apartment": "Apartment", "rk_house": "House", "rk_commercial": "Commercial", "rk_land": "Land",
        "rd_sale": "Sale", "rd_rent": "Rent", "rd_sale_l": "sale", "rd_rent_l": "rent",
        "svc_step": "Service", "svc_pick": "What do you do?",
        "svc_pick_s": "Choose a field — Kliko AI puts together the rest. No need to fill it in by hand.",
        "svc_change": "Change", "svc_q1": "What do you do or repair?",
        "svc_q1_ph": "E.g.: fridge and washing machine repair at home",
        "svc_q2": "What's included, your strengths?", "svc_q2_ph": "E.g.: free call-out, 6-month warranty, original parts",
        "svc_opt": "optional", "svc_price": "Price from, ₸", "svc_city": "City", "svc_city_ph": "City / town",
        "svc_go": "Build the listing",
        "svc_note": "Kliko AI picks the category, writes the title and a business-like description. A photo is optional for services.",
        "svc_prog_1": "Picking the category…", "svc_prog_2": "Writing the title…", "svc_prog_3": "Preparing the description…",
        "svc_done": "Done! Check it and publish", "svc_need": "Describe what you do",
        "svc_fail": "Couldn't build it. Please try again", "svc_limit_t": "Limit reached",
        "svc_manual": "I'll fill it in myself",
        "svc_photo_opt": "optional for services", "svc_photo_add": "Add your own photo",
        "sq_tech-repair": "What do you repair?", "sp_tech-repair": "E.g.: fridges and washing machines at home",
        "sq_repair-construction": "What work do you do?",
        "sp_repair-construction": "E.g.: turnkey apartment finishing, plumbing, electrics",
        "sq_auto-services": "Which car services do you offer?", "sp_auto-services": "E.g.: tyre fitting, oil change, car wash",
        "sq_beauty-health": "What do you do?", "sp_beauty-health": "E.g.: manicure and pedicure, lash extensions at home",
        "sq_tutors-education": "What do you teach?", "sp_tutors-education": "E.g.: maths tutor, UNT exam prep",
        "sq_it-development": "What do you build?", "sp_it-development": "E.g.: custom websites and online stores",
        "sq_delivery-courier": "What do you deliver?", "sp_delivery-courier": "E.g.: city courier, food and document delivery",
        "sq_photo-video-svc": "What do you shoot?", "sp_photo-video-svc": "E.g.: wedding photo and video, editing",
        "sq_events": "What do you organize?", "sp_events": "E.g.: party host, animators, decor",
        "sq_legal-financial": "Which services do you offer?", "sp_legal-financial": "E.g.: bookkeeping, legal help",
        "sq_translation": "What do you translate?", "sp_translation": "E.g.: written document translation, interpreting",
        "sq_other-services": "What do you do?", "sp_other-services": "E.g.: handyman, dog walking, small repairs",
        "rsh_h": "Shoot by the plan", "rsh_rent_tail": ", rental", "rsh_count": "%d of %d taken",
        "gh_rent": "Rental", "gh_phone": "Phone", "gh_laptop": "Laptop", "gh_clothes": "Clothing", "gh_shoes": "Shoes",
        "gh_furniture": "Furniture", "gh_appliance": "Appliances", "gh_building": "Building materials", "gh_other": "Other"
    ]

    private static let ar: [String: String] = [
        "m_step": "الخطوة %d من %d", "m_cancel": "إلغاء", "m_back": "رجوع", "m_next": "التالي", "m_done": "تم",
        "m_save": "حفظ", "m_reset": "إعادة تعيين", "m_close": "إغلاق",
        "aw_car": "سيارة", "aw_brand": "الماركة", "aw_model": "الطراز", "aw_gen": "الجيل",
        "aw_brand_search": "ابحث عن ماركة", "aw_model_search": "ابحث عن طراز",
        "aw_brand_other": "ماركة أخرى — اكتبها", "aw_brand_other_ph": "اسم الماركة",
        "aw_model_other": "طراز آخر — اكتبه", "aw_model_other_ph": "اسم الطراز",
        "aw_other_need": "اكتب الاسم", "aw_loading": "نحمّل الدليل…",
        "aw_brands_none": "دليل الماركات غير متاح الآن — اكتب الماركة بنفسك، والباقي كالمعتاد.",
        "aw_models_none": "طرازات هذه الماركة غير موجودة في الدليل — اكتب الاسم بنفسك.",
        "aw_models_body": "تظهر طرازات نوع الهيكل المختار — %d من %d.",
        "aw_gens_none": "أجيال هذا الطراز غير موجودة في الدليل — يمكن تخطي هذه الخطوة.",
        "aw_first_brand": "اختر الماركة أولًا.",
        "aw_popular": "الأكثر شيوعًا", "aw_others": "أخرى", "aw_nothing": "لم نجد شيئًا — اكتب الاسم بنفسك",
        "aw_year": "سنة الصنع", "aw_year_pick": "— اختر السنة —", "aw_mileage": "المسافة المقطوعة", "aw_engine": "المحرك",
        "aw_km": "كم", "aw_l": "ل", "aw_now": "حتى الآن", "aw_yr": "",
        "aw_gen_years": "السنوات من الجيل المختار (%@): هكذا يُعثر على الإعلان بالسنة وبالجيل.",
        "aw_nums_hint": "المسافة وحجم المحرك — بالأرقام فقط: الفلتر يقرأ «85 000 كم» صفرًا.",
        "aw_need_nums": "أدخل السنة والمسافة المقطوعة",
        "aw_gear": "ناقل الحركة", "aw_fuel": "الوقود",
        "aw_words_hint": "الكلمات نفسها التي في فلتر الواجهة — وإلا فلن يظهر الإعلان عند البحث بناقل الحركة والوقود.",
        "aw_saved": "حُفظت البيانات",
        "aw_entry_t": "بيانات السيارة", "aw_entry_new": "أدخل بيانات السيارة",
        "aw_entry_s": "الماركة، الطراز، الجيل، المسافة",
        "aw_body_cars": "ما نوع الهيكل؟", "aw_body_moto": "ما هو تحديدًا؟", "aw_body_other": "حدّد النوع",
        "aw_body_s": "%@ · ليظهر الإعلان في فلتر المشتري المناسب.",
        "aw_body_skip": "تخطي التحديد", "aw_body": "الهيكل",
        "aw_title_lock": "يُبنى العنوان من بيانات السيارة — هكذا يجد المشترون السيارة بالماركة والطراز والجيل",
        "rw_title": "العقارات", "rw_what_q": "ماذا تنشر؟",
        "rw_what_s": "الحقول تعتمد على ذلك: للإيجار شروطه، وللبيع مستنداته.",
        "rw_deal_l": "نوع الصفقة", "rw_kind_l": "نوع العقار",
        "rw_sale": "أبيع", "rw_sale_s": "بيع العقار", "rw_rent": "أؤجّر", "rw_rent_s": "تأجير سكن",
        "rw_params_q": "تفاصيل العقار",
        "rw_params_s": "بها بالضبط يصفّي المشترون — من دونها لن يُعثر على الإعلان.",
        "rw_cond_rent": "شروط الإيجار", "rw_cond_rent_s": "هذا أول ما يُسأل عنه في الدردشة — أجب مسبقًا.",
        "rw_cond_sale": "شروط البيع", "rw_cond_sale_s": "المستندات وإمكانية الرهن العقاري تزيد الثقة.",
        "rw_sum_q": "تحقّق قبل النشر", "rw_sum_s": "تدخل هذه البيانات في البطاقة وفلاتر البحث.",
        "rw_deal": "الصفقة", "rw_obj": "العقار", "rw_yes": "نعم",
        "rw_none": "لا توجد حقول إضافية لهذا النوع من العقارات.",
        "rw_saved": "حُفظت البيانات — مُلئ العنوان والوصف",
        "rw_entry_new": "املأ تفاصيل العقار", "rw_entry_new_s": "الغرف والمساحة والطابق والشروط — خطوة بخطوة",
        "rw_entry_saved": "حُفظت التفاصيل", "rw_req": "املأ الحقول المعلّمة بنجمة",
        "rk_apartment": "شقة", "rk_house": "منزل", "rk_commercial": "تجاري", "rk_land": "أرض",
        "rd_sale": "بيع", "rd_rent": "إيجار", "rd_sale_l": "بيع", "rd_rent_l": "إيجار",
        "svc_step": "الخدمة", "svc_pick": "بماذا تعمل؟",
        "svc_pick_s": "اختر المجال — وسيجمع Kliko AI الباقي. لا حاجة للتعبئة يدويًا.",
        "svc_change": "تغيير", "svc_q1": "ماذا تعمل أو ماذا تصلح؟",
        "svc_q1_ph": "مثلًا: إصلاح الثلاجات والغسالات في المنزل",
        "svc_q2": "ماذا يشمل، ومزاياك؟", "svc_q2_ph": "مثلًا: زيارة مجانية، ضمان 6 أشهر، قطع أصلية",
        "svc_opt": "اختياري", "svc_price": "السعر من، ₸", "svc_city": "المدينة", "svc_city_ph": "المدينة / البلدة",
        "svc_go": "اجمع الإعلان",
        "svc_note": "يختار Kliko AI القسم ويكتب العنوان ووصفًا مهنيًا. الصورة اختيارية للخدمات.",
        "svc_prog_1": "أختار القسم…", "svc_prog_2": "أكتب العنوان…", "svc_prog_3": "أُعدّ الوصف…",
        "svc_done": "تم! راجِع وانشر", "svc_need": "صف ما تعمله",
        "svc_fail": "تعذّر الجمع. حاول مرة أخرى", "svc_limit_t": "بلغت الحد",
        "svc_manual": "سأملؤه بنفسي",
        "svc_photo_opt": "اختيارية للخدمة", "svc_photo_add": "أضف صورتك",
        "sq_tech-repair": "ماذا تصلح؟", "sp_tech-repair": "مثلًا: الثلاجات والغسالات في المنزل",
        "sq_repair-construction": "ما الأعمال التي تنفذها؟",
        "sp_repair-construction": "مثلًا: تشطيب شقق متكامل، سباكة، كهرباء",
        "sq_auto-services": "ما خدمات السيارات التي تقدمها؟", "sp_auto-services": "مثلًا: تركيب إطارات، تغيير زيت، غسيل سيارات",
        "sq_beauty-health": "ماذا تعمل؟", "sp_beauty-health": "مثلًا: مانيكير وباديكير، تركيب رموش في المنزل",
        "sq_tutors-education": "ماذا تُعلّم؟", "sp_tutors-education": "مثلًا: مدرس رياضيات، التحضير لاختبار UNT",
        "sq_it-development": "ماذا تطوّر؟", "sp_it-development": "مثلًا: مواقع ومتاجر إلكترونية حسب الطلب",
        "sq_delivery-courier": "ماذا توصّل؟", "sp_delivery-courier": "مثلًا: مندوب داخل المدينة، توصيل طعام ومستندات",
        "sq_photo-video-svc": "ماذا تصوّر؟", "sp_photo-video-svc": "مثلًا: تصوير أعراس فوتوغرافي وفيديو، مونتاج",
        "sq_events": "ماذا تنظّم؟", "sp_events": "مثلًا: مقدّم حفلات، منشطون، ديكور",
        "sq_legal-financial": "ما الخدمات التي تقدمها؟", "sp_legal-financial": "مثلًا: مرافقة محاسبية، مساعدة محامٍ",
        "sq_translation": "ماذا تترجم؟", "sp_translation": "مثلًا: ترجمة مستندات كتابية، ترجمة فورية",
        "sq_other-services": "ماذا تعمل؟", "sp_other-services": "مثلًا: عامل صيانة بالساعة، تمشية الكلاب، إصلاحات صغيرة",
        "rsh_h": "صوّر حسب الخطة", "rsh_rent_tail": "، إيجار", "rsh_count": "التُقط %d من %d",
        "gh_rent": "إيجار", "gh_phone": "هاتف", "gh_laptop": "حاسوب محمول", "gh_clothes": "ملابس", "gh_shoes": "أحذية",
        "gh_furniture": "أثاث", "gh_appliance": "أجهزة", "gh_building": "مواد بناء", "gh_other": "أخرى"
    ]
}
