import Foundation

/**
 Тексты мастера резюме и вакансии (этап 50) на языке телефона (kk/ru/en/ar).

 Русские — слово в слово с сайта: подписи _jw2Render / _jw2Field / _jw2Skills / _jw2Exp / _jw2AI / _jw2Save из
 js/cabinet.min.js (ключи jw_…, запасные тексты _vT), занятость _JW_EMP и опыт _JW_EXP, шаблоны JR_TPL и разделы
 документа jrDocHTML из js/jobs-resume.min.js («Контакты», «Навыки», «Языки», «О себе», «Опыт работы», «Образование»,
 «Ожидания: от N ₸», «Резюме создано на Kliko.kz · Работа», «Другое оформление»). Свои слова приложения — окно выбора
 «Резюме / Вакансия» и VoiceOver. Значения опыта (_JW_EXP) сервер ждёт по-русски — переводится только подпись.
 */
enum РезюмеText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    static func т(_ ключ: String, _ замены: [String: String]) -> String {
        var итог = т(ключ)
        for (имя, значение) in замены {
            итог = итог.replacingOccurrences(of: "{" + имя + "}", with: значение)
        }
        return итог
    }

    static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    private static let ru: [String: String] = [
        "hov_resume": "Резюме",
        "hov_vacancy": "Вакансия",
        "pick_q": "Что размещаете?",
        "pick_resume_s": "Ищу работу — расскажу о себе",
        "pick_vacancy_s": "Ищу сотрудника — опишу работу",
        "step": "Шаг {i} из {n}",
        "next": "Далее",
        "publish": "Опубликовать",
        "save": "Сохранить",
        "back": "Назад",
        "close": "Закрыть",
        "loading": "Загрузка…",
        "not_found": "Запись не найдена",
        "retry": "Повторить",
        "jw_ai_q": "С чего начнём",
        "jw_ai_s": "Две строки — и Kliko AI соберёт черновик резюме: должность, о себе и навыки. Всё можно поправить.",
        "jw_ai_role": "Кем хотите работать",
        "jw_ai_role_ph": "Сварщик, водитель, бухгалтер…",
        "jw_ai_exp": "Коротко про опыт",
        "jw_ai_go": "Собрать с Kliko AI",
        "jw_ai_skip": "Заполню сам",
        "jw_ai_need": "Напишите, кем хотите работать",
        "jw_ai_ok": "Черновик готов — проверьте и поправьте",
        "jw_ai_fail": "Kliko AI не ответил",
        "jw_who_res": "Кто вы и кем работаете",
        "jw_who_vac": "Кого ищете",
        "jw_who_res_s": "По должности вас найдут в поиске — пишите так, как её называют.",
        "jw_who_vac_s": "Должность и компания — по ним вакансию находят.",
        "jw_photo": "Фото 3×4",
        "jw_photo_fail": "Не удалось загрузить фото",
        "jw_name": "Имя",
        "jw_name_ph": "Ерлан К.",
        "jw_title": "Должность",
        "jw_title_ph_res": "Сварщик 5 разряда",
        "jw_title_ph_vac": "Водитель категории C",
        "jw_company": "Компания",
        "jw_company_ph": "ТОО «Ромашка»",
        "jw_city": "Город",
        "jw_city_ph": "Астана",
        "jw_terms": "Условия",
        "jw_terms_res_s": "Сколько хотите получать и готовы ли к переезду.",
        "jw_terms_vac_s": "Занятость, опыт и деньги — то, на что смотрят первым.",
        "jw_emp": "Занятость",
        "jw_exp": "Опыт",
        "jw_sal_min": "Зарплата от, ₸",
        "jw_sal_max": "до, ₸",
        "jw_relocate": "Готов к переезду",
        "jw_about": "О себе",
        "jw_desc": "Описание",
        "jw_about_s": "Опыт, навыки, чем полезны. Пара абзацев — этого хватает.",
        "jw_desc_s": "Обязанности, условия, график. Пишите как есть — так откликаются охотнее.",
        "jw_skills": "Навыки",
        "jw_skill_ph": "Например: сварка аргоном",
        "jw_add": "Добавить",
        "jw_exp_work": "Опыт работы",
        "jw_exp_pos": "Должность",
        "jw_exp_co": "Где работали",
        "jw_exp_per": "2019 – 2024",
        "jw_tpl": "Оформление",
        "jw_tpl_s": "Так резюме увидит работодатель — и так же оно печатается и скачивается.",
        "jw_tpl_see": "Посмотреть резюме",
        "jw_ok_upd": "Изменения сохранены",
        "jw_ok_res": "Резюме опубликовано",
        "jw_ok_vac": "Вакансия опубликована",
        "jw_fail": "Не удалось опубликовать",
        "jw_limit": "Достигнут предел активных резюме",
        "jw_need_ver": "Подача в разделе «Работа» — после верификации",
        "verify": "Пройти верификацию",
        "no_net": "Нет связи",
        "delete": "Удалить",
        "emp_full": "Полная занятость",
        "emp_part": "Частичная",
        "emp_shift": "Вахта",
        "emp_remote": "Удалённо",
        "emp_internship": "Стажировка",
        "exp_Без опыта": "Без опыта",
        "exp_1–3 года": "1–3 года",
        "exp_3–5 лет": "3–5 лет",
        "exp_5+ лет": "5+ лет",
        "tpl_classic": "Классика",
        "tpl_ocean": "Океан",
        "tpl_berry": "Бордо",
        "tpl_slate": "Графит",
        "tpl_modern": "Модерн",
        "tpl_mono": "Минимал",
        "tpl_royal": "Роял",
        "tpl_sand": "Песок",
        "doc_seeker": "Соискатель",
        "doc_salary": "Ожидания: от {n} ₸",
        "doc_contacts": "Контакты",
        "doc_skills": "Навыки",
        "doc_langs": "Языки",
        "doc_about": "О себе",
        "doc_exp": "Опыт работы",
        "doc_edu": "Образование",
        "doc_footer": "Резюме создано на Kliko.kz · Работа",
        "doc_roll": "Другое оформление",
        "done_after": "Резюме и вакансии — в «Моих объявлениях», раздел «Работа».",
    ]

    private static let kk: [String: String] = [
        "hov_resume": "Түйіндеме",
        "hov_vacancy": "Бос орын",
        "pick_q": "Не орналастырасыз?",
        "pick_resume_s": "Жұмыс іздеймін — өзім туралы айтамын",
        "pick_vacancy_s": "Қызметкер іздеймін — жұмысты сипаттаймын",
        "step": "{n} қадамның {i}-і",
        "next": "Әрі қарай",
        "publish": "Жариялау",
        "save": "Сақтау",
        "back": "Артқа",
        "close": "Жабу",
        "loading": "Жүктелуде…",
        "not_found": "Жазба табылмады",
        "retry": "Қайталау",
        "jw_ai_q": "Неден бастаймыз",
        "jw_ai_s": "Екі жол — және Kliko AI түйіндеменің жобасын жасайды: лауазым, өзім туралы және дағдылар. Бәрін түзетуге болады.",
        "jw_ai_role": "Кім болып жұмыс істегіңіз келеді",
        "jw_ai_role_ph": "Дәнекерлеуші, жүргізуші, бухгалтер…",
        "jw_ai_exp": "Тәжірибе туралы қысқаша",
        "jw_ai_go": "Kliko AI-мен жинау",
        "jw_ai_skip": "Өзім толтырамын",
        "jw_ai_need": "Кім болып жұмыс істегіңіз келетінін жазыңыз",
        "jw_ai_ok": "Жоба дайын — тексеріп, түзетіңіз",
        "jw_ai_fail": "Kliko AI жауап бермеді",
        "jw_who_res": "Сіз кімсіз және кім болып жұмыс істейсіз",
        "jw_who_vac": "Кімді іздейсіз",
        "jw_who_res_s": "Лауазым бойынша сізді іздеуден табады — оны қалай атайды, солай жазыңыз.",
        "jw_who_vac_s": "Лауазым мен компания — бос орынды солар бойынша табады.",
        "jw_photo": "3×4 фото",
        "jw_photo_fail": "Фотоны жүктеу мүмкін болмады",
        "jw_name": "Аты",
        "jw_name_ph": "Ерлан К.",
        "jw_title": "Лауазым",
        "jw_title_ph_res": "5-разрядты дәнекерлеуші",
        "jw_title_ph_vac": "C санатты жүргізуші",
        "jw_company": "Компания",
        "jw_company_ph": "«Ромашка» ЖШС",
        "jw_city": "Қала",
        "jw_city_ph": "Астана",
        "jw_terms": "Шарттар",
        "jw_terms_res_s": "Қанша алғыңыз келеді және көшуге дайынсыз ба.",
        "jw_terms_vac_s": "Жұмыспен қамту, тәжірибе және ақша — алдымен соған қарайды.",
        "jw_emp": "Жұмыспен қамту",
        "jw_exp": "Тәжірибе",
        "jw_sal_min": "Жалақы, ₸ бастап",
        "jw_sal_max": "дейін, ₸",
        "jw_relocate": "Көшуге дайынмын",
        "jw_about": "Өзім туралы",
        "jw_desc": "Сипаттама",
        "jw_about_s": "Тәжірибе, дағдылар, қандай пайдасыз. Бірер абзац жеткілікті.",
        "jw_desc_s": "Міндеттер, шарттар, кесте. Барын жазыңыз — сонда көбірек үн қатады.",
        "jw_skills": "Дағдылар",
        "jw_skill_ph": "Мысалы: аргонмен дәнекерлеу",
        "jw_add": "Қосу",
        "jw_exp_work": "Жұмыс тәжірибесі",
        "jw_exp_pos": "Лауазым",
        "jw_exp_co": "Қайда жұмыс істедіңіз",
        "jw_exp_per": "2019 – 2024",
        "jw_tpl": "Безендіру",
        "jw_tpl_s": "Жұмыс беруші түйіндемені осылай көреді — дәл осылай басып шығарылады және жүктеледі.",
        "jw_tpl_see": "Түйіндемені көру",
        "jw_ok_upd": "Өзгерістер сақталды",
        "jw_ok_res": "Түйіндеме жарияланды",
        "jw_ok_vac": "Бос орын жарияланды",
        "jw_fail": "Жариялау мүмкін болмады",
        "jw_limit": "Белсенді түйіндемелер шегіне жеттіңіз",
        "jw_need_ver": "«Жұмыс» бөліміне орналастыру — верификациядан кейін",
        "verify": "Верификациядан өту",
        "no_net": "Байланыс жоқ",
        "delete": "Жою",
        "emp_full": "Толық жұмыспен қамту",
        "emp_part": "Жартылай",
        "emp_shift": "Вахта",
        "emp_remote": "Қашықтан",
        "emp_internship": "Тағылымдама",
        "exp_Без опыта": "Тәжірибесіз",
        "exp_1–3 года": "1–3 жыл",
        "exp_3–5 лет": "3–5 жыл",
        "exp_5+ лет": "5+ жыл",
        "tpl_classic": "Классика",
        "tpl_ocean": "Мұхит",
        "tpl_berry": "Бордо",
        "tpl_slate": "Графит",
        "tpl_modern": "Модерн",
        "tpl_mono": "Минимал",
        "tpl_royal": "Роял",
        "tpl_sand": "Құм",
        "doc_seeker": "Ізденуші",
        "doc_salary": "Күтілім: {n} ₸ бастап",
        "doc_contacts": "Байланыс",
        "doc_skills": "Дағдылар",
        "doc_langs": "Тілдер",
        "doc_about": "Өзім туралы",
        "doc_exp": "Жұмыс тәжірибесі",
        "doc_edu": "Білім",
        "doc_footer": "Түйіндеме Kliko.kz-те жасалды · Жұмыс",
        "doc_roll": "Басқа безендіру",
        "done_after": "Түйіндемелер мен бос орындар — «Менің хабарландыруларымда», «Жұмыс» бөлімінде.",
    ]

    private static let en: [String: String] = [
        "hov_resume": "Résumé",
        "hov_vacancy": "Vacancy",
        "pick_q": "What are you posting?",
        "pick_resume_s": "I'm looking for a job — about me",
        "pick_vacancy_s": "I'm hiring — about the job",
        "step": "Step {i} of {n}",
        "next": "Next",
        "publish": "Publish",
        "save": "Save",
        "back": "Back",
        "close": "Close",
        "loading": "Loading…",
        "not_found": "Record not found",
        "retry": "Retry",
        "jw_ai_q": "Let's start",
        "jw_ai_s": "Two lines — and Kliko AI drafts your résumé: position, about you and skills. You can edit everything.",
        "jw_ai_role": "What job do you want",
        "jw_ai_role_ph": "Welder, driver, accountant…",
        "jw_ai_exp": "Your experience in brief",
        "jw_ai_go": "Draft with Kliko AI",
        "jw_ai_skip": "I'll fill it in myself",
        "jw_ai_need": "Write what job you want",
        "jw_ai_ok": "Draft ready — check and edit it",
        "jw_ai_fail": "Kliko AI didn't respond",
        "jw_who_res": "Who you are and what you do",
        "jw_who_vac": "Who you're looking for",
        "jw_who_res_s": "Employers search by position — write it the way people call it.",
        "jw_who_vac_s": "Position and company — that's how the vacancy is found.",
        "jw_photo": "3×4 photo",
        "jw_photo_fail": "Couldn't upload the photo",
        "jw_name": "Name",
        "jw_name_ph": "Yerlan K.",
        "jw_title": "Position",
        "jw_title_ph_res": "Grade 5 welder",
        "jw_title_ph_vac": "Category C driver",
        "jw_company": "Company",
        "jw_company_ph": "Romashka LLP",
        "jw_city": "City",
        "jw_city_ph": "Astana",
        "jw_terms": "Terms",
        "jw_terms_res_s": "How much you want to earn and whether you'd relocate.",
        "jw_terms_vac_s": "Employment, experience and pay — what people look at first.",
        "jw_emp": "Employment",
        "jw_exp": "Experience",
        "jw_sal_min": "Salary from, ₸",
        "jw_sal_max": "to, ₸",
        "jw_relocate": "Ready to relocate",
        "jw_about": "About me",
        "jw_desc": "Description",
        "jw_about_s": "Experience, skills, how you help. A couple of paragraphs is enough.",
        "jw_desc_s": "Duties, conditions, schedule. Write it as is — people respond more.",
        "jw_skills": "Skills",
        "jw_skill_ph": "For example: argon welding",
        "jw_add": "Add",
        "jw_exp_work": "Work experience",
        "jw_exp_pos": "Position",
        "jw_exp_co": "Where you worked",
        "jw_exp_per": "2019 – 2024",
        "jw_tpl": "Design",
        "jw_tpl_s": "This is how employers will see your résumé — and how it prints and downloads.",
        "jw_tpl_see": "View résumé",
        "jw_ok_upd": "Changes saved",
        "jw_ok_res": "Résumé published",
        "jw_ok_vac": "Vacancy published",
        "jw_fail": "Couldn't publish",
        "jw_limit": "Active résumé limit reached",
        "jw_need_ver": "Posting in “Jobs” requires verification",
        "verify": "Get verified",
        "no_net": "No connection",
        "delete": "Delete",
        "emp_full": "Full-time",
        "emp_part": "Part-time",
        "emp_shift": "Rotational",
        "emp_remote": "Remote",
        "emp_internship": "Internship",
        "exp_Без опыта": "No experience",
        "exp_1–3 года": "1–3 years",
        "exp_3–5 лет": "3–5 years",
        "exp_5+ лет": "5+ years",
        "tpl_classic": "Classic",
        "tpl_ocean": "Ocean",
        "tpl_berry": "Burgundy",
        "tpl_slate": "Graphite",
        "tpl_modern": "Modern",
        "tpl_mono": "Minimal",
        "tpl_royal": "Royal",
        "tpl_sand": "Sand",
        "doc_seeker": "Job seeker",
        "doc_salary": "Expected: from {n} ₸",
        "doc_contacts": "Contacts",
        "doc_skills": "Skills",
        "doc_langs": "Languages",
        "doc_about": "About me",
        "doc_exp": "Work experience",
        "doc_edu": "Education",
        "doc_footer": "Résumé made on Kliko.kz · Jobs",
        "doc_roll": "Another design",
        "done_after": "Résumés and vacancies are in “My listings”, section “Jobs”.",
    ]

    private static let ar: [String: String] = [
        "hov_resume": "سيرة ذاتية",
        "hov_vacancy": "وظيفة شاغرة",
        "pick_q": "ماذا تنشر؟",
        "pick_resume_s": "أبحث عن عمل — عن نفسي",
        "pick_vacancy_s": "أبحث عن موظف — عن العمل",
        "step": "الخطوة {i} من {n}",
        "next": "التالي",
        "publish": "نشر",
        "save": "حفظ",
        "back": "رجوع",
        "close": "إغلاق",
        "loading": "جارٍ التحميل…",
        "not_found": "السجل غير موجود",
        "retry": "إعادة المحاولة",
        "jw_ai_q": "لنبدأ",
        "jw_ai_s": "سطران — وسيعدّ Kliko AI مسودة سيرتك: المسمّى ونبذة والمهارات. يمكن تعديل كل شيء.",
        "jw_ai_role": "ما العمل الذي تريده",
        "jw_ai_role_ph": "لحّام، سائق، محاسب…",
        "jw_ai_exp": "خبرتك باختصار",
        "jw_ai_go": "إعداد عبر Kliko AI",
        "jw_ai_skip": "سأملأها بنفسي",
        "jw_ai_need": "اكتب العمل الذي تريده",
        "jw_ai_ok": "المسودة جاهزة — راجعها وعدّلها",
        "jw_ai_fail": "لم يستجب Kliko AI",
        "jw_who_res": "من أنت وما عملك",
        "jw_who_vac": "من تبحث عنه",
        "jw_who_res_s": "يبحث أصحاب العمل بالمسمّى — اكتبه كما يُسمّى عادة.",
        "jw_who_vac_s": "المسمّى والشركة — بهما تُعثر على الوظيفة.",
        "jw_photo": "صورة 3×4",
        "jw_photo_fail": "تعذّر رفع الصورة",
        "jw_name": "الاسم",
        "jw_name_ph": "يرلان ك.",
        "jw_title": "المسمّى الوظيفي",
        "jw_title_ph_res": "لحّام من الدرجة 5",
        "jw_title_ph_vac": "سائق فئة C",
        "jw_company": "الشركة",
        "jw_company_ph": "شركة «روماشكا» المحدودة",
        "jw_city": "المدينة",
        "jw_city_ph": "أستانا",
        "jw_terms": "الشروط",
        "jw_terms_res_s": "كم تريد أن تكسب وهل أنت مستعد للانتقال.",
        "jw_terms_vac_s": "نوع التوظيف والخبرة والأجر — أول ما يُنظر إليه.",
        "jw_emp": "نوع التوظيف",
        "jw_exp": "الخبرة",
        "jw_sal_min": "الراتب من، ₸",
        "jw_sal_max": "إلى، ₸",
        "jw_relocate": "مستعد للانتقال",
        "jw_about": "نبذة عني",
        "jw_desc": "الوصف",
        "jw_about_s": "الخبرة والمهارات وما تقدّمه. فقرتان تكفيان.",
        "jw_desc_s": "المهام والشروط وجدول العمل. اكتب كما هو — فيتجاوب الناس أكثر.",
        "jw_skills": "المهارات",
        "jw_skill_ph": "مثلاً: اللحام بالأرغون",
        "jw_add": "إضافة",
        "jw_exp_work": "الخبرة العملية",
        "jw_exp_pos": "المسمّى",
        "jw_exp_co": "أين عملت",
        "jw_exp_per": "2019 – 2024",
        "jw_tpl": "التصميم",
        "jw_tpl_s": "هكذا سيرى صاحب العمل سيرتك — وهكذا تُطبع وتُنزّل.",
        "jw_tpl_see": "عرض السيرة",
        "jw_ok_upd": "تم حفظ التغييرات",
        "jw_ok_res": "نُشرت السيرة الذاتية",
        "jw_ok_vac": "نُشرت الوظيفة",
        "jw_fail": "تعذّر النشر",
        "jw_limit": "تم بلوغ حد السير الذاتية النشطة",
        "jw_need_ver": "النشر في «العمل» بعد توثيق الحساب",
        "verify": "توثيق الحساب",
        "no_net": "لا يوجد اتصال",
        "delete": "حذف",
        "emp_full": "دوام كامل",
        "emp_part": "دوام جزئي",
        "emp_shift": "عمل بالمناوبة",
        "emp_remote": "عن بُعد",
        "emp_internship": "تدريب",
        "exp_Без опыта": "بدون خبرة",
        "exp_1–3 года": "1–3 سنوات",
        "exp_3–5 лет": "3–5 سنوات",
        "exp_5+ лет": "+5 سنوات",
        "tpl_classic": "كلاسيكي",
        "tpl_ocean": "محيط",
        "tpl_berry": "عنابي",
        "tpl_slate": "غرافيت",
        "tpl_modern": "عصري",
        "tpl_mono": "بسيط",
        "tpl_royal": "ملكي",
        "tpl_sand": "رملي",
        "doc_seeker": "باحث عن عمل",
        "doc_salary": "المتوقع: من {n} ₸",
        "doc_contacts": "التواصل",
        "doc_skills": "المهارات",
        "doc_langs": "اللغات",
        "doc_about": "نبذة عني",
        "doc_exp": "الخبرة العملية",
        "doc_edu": "التعليم",
        "doc_footer": "أُنشئت السيرة على Kliko.kz · العمل",
        "doc_roll": "تصميم آخر",
        "done_after": "السير الذاتية والوظائف في «إعلاناتي»، قسم «العمل».",
    ]
}
