import Foundation

/// Тексты нативного кабинета на языке телефона (kk/ru/en/ar) — тем же способом, что лента (FeedText) и избранное.
enum CabinetText {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь = тексты[язык] ?? тексты["ru"]!
        return словарь[ключ] ?? тексты["ru"]![ключ] ?? ключ
    }

    private static let тексты: [String: [String: String]] = [
        "ru": ["title": "Профиль",
               "more": "Ещё", "favorites": "Избранное", "dlv_rent": "Доставки и аренды",
               "docs": "Счета и документы", "biz_toggle": "Я бизнес",
               "biz_footer": "Включите, если продаёте как магазин или компания: появятся счета, прайс-лист, интеграции и аналитика. Выбор запоминается для этого аккаунта.",
               "signed_in": "Вы вошли",
               "signed_in_sub": "Объявления, сделки, кошелёк и настройки — ниже.",
               "signed_out": "Вы не вошли",
               "signed_out_sub": "Войдите, чтобы писать продавцам, покупать безопасно и размещать объявления.",
               "checking": "Проверяем вход…", "checking_sub": "Это займёт пару секунд.",
               "unknown": "Не удалось проверить вход", "unknown_sub": "Потяните вниз, чтобы обновить.",
               "site": "Разделы", "open_cabinet": "Открыть кабинет", "site_messages": "Сообщения на сайте",
               "login": "Войти", "site_footer": "Эти страницы открываются сайтом внутри приложения.",
               "security": "Безопасность", "lock_toggle": "Вход по %@",
               "lock_footer": "При запуске и после минуты в фоне Kliko попросит подтвердить, что это вы. Выбор хранится на этом телефоне.",
               "lock_none": "Задайте код-пароль в Настройках iPhone, чтобы включить защиту входа.",
               "lock_failed": "Не удалось подтвердить. Попробуйте ещё раз.",
               "lock_unavailable": "На телефоне не задан код-пароль — защиту включить нельзя.",
               "notifications": "Уведомления", "notif_row": "Статус", "notif_on": "Включены", "notif_quiet": "Тихие",
               "notif_off": "Выключены", "notif_unknown": "Не настроены", "notif_ask": "Разрешить уведомления",
               "notif_settings": "Открыть настройки iPhone",
               "notif_off_footer": "Без уведомлений вы не узнаете о новых сообщениях и сделках, пока не откроете приложение.",
               "data": "Данные на телефоне", "clear": "Очистить", "cancel": "Отмена",
               "clear_cache": "Очистить кэш", "cache_q": "Очистить кэш?",
               "cache_msg": "Фото и ответы сайта загрузятся заново из сети. Вход, избранное и история останутся.",
               "clear_favorites": "Очистить избранное", "favorites_q": "Очистить избранное?",
               "favorites_msg": "Все сохранённые объявления будут удалены с этого телефона.",
               "clear_viewed": "Очистить просмотренные", "viewed_q": "Очистить просмотренные?",
               "viewed_msg": "Список просмотренных объявлений будет удалён с этого телефона.",
               "clear_search": "Очистить историю поиска", "search_q": "Очистить историю поиска?",
               "search_msg": "Прошлые запросы больше не будут появляться под полем поиска.",
               "data_footer": "Избранное и история хранятся только на этом телефоне и стираются при выходе из аккаунта.",
               "data_footer_synced": "Избранное хранится в вашем аккаунте на сайте, история — только на этом телефоне и стирается при выходе из аккаунта.",
               "about": "О приложении", "version": "Версия", "build": "Сборка",
               "logout_row": "Выйти из аккаунта",
               "logout_footer": "Выход — в кабинете на сайте: так сервер закроет сессию и перестанет присылать уведомления на этот телефон, а приложение сотрёт данные аккаунта."],
        "kk": ["title": "Профиль",
               "more": "Тағы", "favorites": "Таңдаулылар", "dlv_rent": "Жеткізулер мен жалдар",
               "docs": "Шоттар мен құжаттар", "biz_toggle": "Мен бизнеспін",
               "biz_footer": "Дүкен немесе компания ретінде сатсаңыз, қосыңыз: шоттар, прайс-парақ, интеграциялар және талдау пайда болады. Таңдау осы аккаунт үшін сақталады.",
               "signed_in": "Сіз кірдіңіз",
               "signed_in_sub": "Хабарландырулар, мәмілелер, әмиян және баптаулар — төменде.",
               "signed_out": "Сіз кірмегенсіз",
               "signed_out_sub": "Сатушыларға жазу, қауіпсіз сатып алу және хабарландыру орналастыру үшін кіріңіз.",
               "checking": "Кіруді тексеріп жатырмыз…", "checking_sub": "Бұл бірнеше секундқа созылады.",
               "unknown": "Кіруді тексеру мүмкін болмады", "unknown_sub": "Жаңарту үшін төмен тартыңыз.",
               "site": "Бөлімдер", "open_cabinet": "Кабинетті ашу", "site_messages": "Сайттағы хабарламалар",
               "login": "Кіру", "site_footer": "Бұл беттер қосымша ішінде сайт арқылы ашылады.",
               "security": "Қауіпсіздік", "lock_toggle": "%@ арқылы кіру",
               "lock_footer": "Іске қосқанда және фонда бір минуттан кейін Kliko бұл сіз екеніңізді растауды сұрайды. Таңдау осы телефонда сақталады.",
               "lock_none": "Кіру қорғанысын қосу үшін iPhone баптауларында құпия кодты орнатыңыз.",
               "lock_failed": "Растау мүмкін болмады. Қайталап көріңіз.",
               "lock_unavailable": "Телефонда құпия код орнатылмаған — қорғанысты қосу мүмкін емес.",
               "notifications": "Push-хабарландырулар", "notif_row": "Күйі", "notif_on": "Қосулы", "notif_quiet": "Үнсіз",
               "notif_off": "Өшірулі", "notif_unknown": "Бапталмаған", "notif_ask": "Push-хабарландыруларға рұқсат беру",
               "notif_settings": "iPhone баптауларын ашу",
               "notif_off_footer": "Push-хабарландыруларсыз жаңа хабарламалар мен мәмілелер туралы қосымшаны ашқанша білмейсіз.",
               "data": "Телефондағы деректер", "clear": "Тазалау", "cancel": "Бас тарту",
               "clear_cache": "Кэшті тазалау", "cache_q": "Кэшті тазалау керек пе?",
               "cache_msg": "Фотолар мен сайт жауаптары желіден қайта жүктеледі. Кіру, таңдаулылар және тарих сақталады.",
               "clear_favorites": "Таңдаулыларды тазалау", "favorites_q": "Таңдаулыларды тазалау керек пе?",
               "favorites_msg": "Барлық сақталған хабарландырулар осы телефоннан жойылады.",
               "clear_viewed": "Қаралғандарды тазалау", "viewed_q": "Қаралғандарды тазалау керек пе?",
               "viewed_msg": "Қаралған хабарландырулар тізімі осы телефоннан жойылады.",
               "clear_search": "Іздеу тарихын тазалау", "search_q": "Іздеу тарихын тазалау керек пе?",
               "search_msg": "Бұрынғы сұраулар іздеу өрісінің астында енді көрсетілмейді.",
               "data_footer": "Таңдаулылар мен тарих тек осы телефонда сақталады және аккаунттан шыққанда өшіріледі.",
               "data_footer_synced": "Таңдаулылар сайттағы аккаунтыңызда сақталады, тарих — тек осы телефонда және аккаунттан шыққанда өшіріледі.",
               "about": "Қосымша туралы", "version": "Нұсқа", "build": "Жинақ",
               "logout_row": "Аккаунттан шығу",
               "logout_footer": "Шығу — сайттағы кабинетте: сонда сервер сессияны жабады және осы телефонға хабарландыру жіберуді тоқтатады, ал қосымша аккаунт деректерін өшіреді."],
        "en": ["title": "Profile",
               "more": "More", "favorites": "Favorites", "dlv_rent": "Deliveries and rentals",
               "docs": "Invoices and documents", "biz_toggle": "I'm a business",
               "biz_footer": "Turn on if you sell as a shop or company: invoices, price list, integrations and analytics will appear. The choice is remembered for this account.",
               "signed_in": "You're signed in",
               "signed_in_sub": "Listings, deals, wallet and settings are below.",
               "signed_out": "You're not signed in",
               "signed_out_sub": "Sign in to message sellers, buy safely and post listings.",
               "checking": "Checking sign-in…", "checking_sub": "This takes a couple of seconds.",
               "unknown": "Couldn't check sign-in", "unknown_sub": "Pull down to refresh.",
               "site": "Sections", "open_cabinet": "Open account", "site_messages": "Messages on the website",
               "login": "Sign in", "site_footer": "These pages open from the website inside the app.",
               "security": "Security", "lock_toggle": "Protect with %@",
               "lock_footer": "On launch and after a minute in the background, Kliko will ask you to confirm it's you. This setting is stored on this phone.",
               "lock_none": "Set a passcode in iPhone Settings to turn on sign-in protection.",
               "lock_failed": "Couldn't confirm. Please try again.",
               "lock_unavailable": "This phone has no passcode, so protection can't be turned on.",
               "notifications": "Notifications", "notif_row": "Status", "notif_on": "On", "notif_quiet": "Deliver quietly",
               "notif_off": "Off", "notif_unknown": "Not set up", "notif_ask": "Allow notifications",
               "notif_settings": "Open iPhone Settings",
               "notif_off_footer": "Without notifications you won't know about new messages and deals until you open the app.",
               "data": "Data on this phone", "clear": "Clear", "cancel": "Cancel",
               "clear_cache": "Clear cache", "cache_q": "Clear the cache?",
               "cache_msg": "Photos and website responses will be downloaded again. Sign-in, favorites and history stay.",
               "clear_favorites": "Clear favorites", "favorites_q": "Clear favorites?",
               "favorites_msg": "All saved listings will be removed from this phone.",
               "clear_viewed": "Clear recently viewed", "viewed_q": "Clear recently viewed?",
               "viewed_msg": "The list of viewed listings will be removed from this phone.",
               "clear_search": "Clear search history", "search_q": "Clear search history?",
               "search_msg": "Past searches will no longer appear under the search field.",
               "data_footer": "Favorites and history are stored only on this phone and are erased when you sign out.",
               "data_footer_synced": "Favorites are stored in your account on the website; history stays only on this phone and is erased when you sign out.",
               "about": "About", "version": "Version", "build": "Build",
               "logout_row": "Sign out",
               "logout_footer": "Sign out in your account on the website: the server then closes the session and stops sending notifications to this phone, and the app erases the account's data."],
        "ar": ["title": "الملف الشخصي",
               "more": "المزيد", "favorites": "المفضلة", "dlv_rent": "التوصيل والتأجير",
               "docs": "الفواتير والمستندات", "biz_toggle": "أنا نشاط تجاري",
               "biz_footer": "فعّل هذا الخيار إذا كنت تبيع كمتجر أو شركة: ستظهر الفواتير وقائمة الأسعار والتكاملات والتحليلات. يُحفظ اختيارك لهذا الحساب.",
               "signed_in": "أنت مسجّل الدخول",
               "signed_in_sub": "الإعلانات والصفقات والمحفظة والإعدادات — أدناه.",
               "signed_out": "لم تسجّل الدخول",
               "signed_out_sub": "سجّل الدخول لمراسلة البائعين والشراء بأمان ونشر الإعلانات.",
               "checking": "جارٍ التحقق من تسجيل الدخول…", "checking_sub": "سيستغرق ذلك بضع ثوانٍ.",
               "unknown": "تعذّر التحقق من تسجيل الدخول", "unknown_sub": "اسحب لأسفل للتحديث.",
               "site": "الأقسام", "open_cabinet": "فتح الحساب", "site_messages": "الرسائل على الموقع",
               "login": "تسجيل الدخول", "site_footer": "تُفتح هذه الصفحات من الموقع داخل التطبيق.",
               "security": "الأمان", "lock_toggle": "الدخول باستخدام %@",
               "lock_footer": "عند التشغيل وبعد دقيقة في الخلفية سيطلب ‏Kliko تأكيد هويتك. يُحفظ هذا الإعداد على هذا الهاتف.",
               "lock_none": "عيّن رمز دخول في إعدادات iPhone لتفعيل حماية الدخول.",
               "lock_failed": "تعذّر التأكيد. حاول مرة أخرى.",
               "lock_unavailable": "لا يوجد رمز دخول على هذا الهاتف، لذا لا يمكن تفعيل الحماية.",
               "notifications": "الإشعارات", "notif_row": "الحالة", "notif_on": "مفعّلة", "notif_quiet": "تُسلَّم بهدوء",
               "notif_off": "متوقفة", "notif_unknown": "غير مُعدّة", "notif_ask": "السماح بالإشعارات",
               "notif_settings": "فتح إعدادات iPhone",
               "notif_off_footer": "بدون الإشعارات لن تعرف بالرسائل والصفقات الجديدة حتى تفتح التطبيق.",
               "data": "البيانات على الهاتف", "clear": "مسح", "cancel": "إلغاء",
               "clear_cache": "مسح ذاكرة التخزين المؤقت", "cache_q": "مسح ذاكرة التخزين المؤقت؟",
               "cache_msg": "سيُعاد تنزيل الصور وردود الموقع من الشبكة. يبقى تسجيل الدخول والمفضلة والسجل.",
               "clear_favorites": "مسح المفضلة", "favorites_q": "مسح المفضلة؟",
               "favorites_msg": "ستُحذف كل الإعلانات المحفوظة من هذا الهاتف.",
               "clear_viewed": "مسح ما شوهد مؤخرًا", "viewed_q": "مسح ما شوهد مؤخرًا؟",
               "viewed_msg": "ستُحذف قائمة الإعلانات التي شاهدتها من هذا الهاتف.",
               "clear_search": "مسح سجل البحث", "search_q": "مسح سجل البحث؟",
               "search_msg": "لن تظهر عمليات البحث السابقة تحت حقل البحث بعد الآن.",
               "data_footer": "تُحفظ المفضلة والسجل على هذا الهاتف فقط وتُمحى عند تسجيل الخروج.",
               "data_footer_synced": "تُحفظ المفضلة في حسابك على الموقع، أما السجل فيبقى على هذا الهاتف فقط ويُمحى عند تسجيل الخروج.",
               "about": "حول التطبيق", "version": "الإصدار", "build": "رقم البناء",
               "logout_row": "تسجيل الخروج",
               "logout_footer": "سجّل الخروج من حسابك على الموقع: عندها يُغلق الخادم الجلسة ويتوقف عن إرسال الإشعارات إلى هذا الهاتف، ويمحو التطبيق بيانات الحساب."]
    ]
}
