import Foundation

/**
 Тексты окон кабинета, которые раньше открывали страницу сайта: «Удалить аккаунт» (acctDelOpen сайта, adl_*),
 «Стать продавцом» перед верификацией (verPromo сайта, vp_*) и обращение в поддержку (dataReqOpen сайта, dreq_*, sup_*).
 Русские — дословно из js_i18n-cabinet-ru.js и js/cabinet.min.js сайта; казахские, английские и арабские — перевод тех
 же фраз. Своих фраз несколько, и каждая объясняет то, что на сайте делается на месте: eGov — на защищённой странице
 сайта (ver_site_note, adl_egov_site), статус верификации (ver_done_*, ver_rej) и тема обращения (sup_topic_*).
 */
enum ОкнаКабинетаText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    private static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    private static let ru: [String: String] = [
        // Удаление аккаунта (acctDelOpen)
        "adl_t": "Удалить аккаунт?", "adl_s": "Это удаление, а не пауза. Вот что произойдёт.",
        "adl_l1": "Объявления уйдут с витрины", "adl_l2": "Вход перестанет работать — этим аккаунтом больше не войти",
        "adl_l3": "Переписки закроются, написать вам будет нельзя",
        "adl_keep": "Записи о завершённых сделках мы обязаны хранить 365 дней — этого требует учёт. Аккаунт при этом удалён: он не виден другим, и войти в него нельзя.",
        "adl_undo": "Передумали — восстановить аккаунт можно в течение 365 дней по обращению в поддержку.",
        "adl_send": "Продолжить", "adl_cancel": "Оставить аккаунт", "adl_fail": "Не удалось продолжить",
        "adl_egov": "Удаление подтверждается через eGov — тем же способом, что вывод денег.",
        "adl_egov_site": "Подтверждение через eGov проходит на защищённой странице сайта: откроется кабинет, там «Настройки» → «Удалить аккаунт».",
        "adl_ok_egov": "Подтвердить через eGov",
        "adl_pass_alt": "Не проходит проверка eGov? Подтвердить паролем",
        "adl_sup_alt": "Не проходит проверка eGov? Напишите в поддержку — удалим по обращению",
        "adl_pass_h": "Введите пароль от аккаунта — удаление необратимо.", "adl_pass_ph": "Ваш пароль",
        "adl_code_h": "Введите %@ — так мы убедимся, что нажали не случайно", "adl_code_ph": "Код с экрана",
        "adl_code_bad": "Код не совпадает", "adl_why": "Почему уходите? (необязательно)", "adl_ok": "Удалить аккаунт",
        "adl_done": "Аккаунт удалён. Вход этим аккаунтом больше не работает.", "adl_bye": "Закрыть",
        "phc_net": "Нет связи", "err_generic": "Ошибка", "close": "Закрыть",
        // Верификация (verPromo, requestVerification)
        "vp_title": "Стать продавцом",
        "vp_sub": "Проверка личности через eGov — около минуты, нужен код из SMS. После неё объявления выходят на витрину, а оплата идёт через гаранта.",
        "vp_b1_t": "Безопасные сделки", "vp_b1_d": "Оплата через гаранта — деньги под защитой до получения товара",
        "vp_b2_t": "Значок «Проверенный»", "vp_b2_d": "Больше доверия покупателей — и больше продаж",
        "vp_b3_t": "Все способы связи", "vp_b3_d": "Номер и WhatsApp прямо в объявлении",
        "vp_b4_t": "PRO и Магазин", "vp_b4_d": "Витрина, опт и бизнес-инструменты для продаж",
        "vp_b5_t": "Больше Kliko AI-помощи", "vp_b5_d": "50 Kliko AI-запросов вместо 5 — быстрые объявления и цены",
        "vp_go": "Пройти верификацию", "vp_later": "Позже",
        "vp_note": "Не обязательно прямо сейчас — можно в любой момент из кабинета",
        "ver_site_note": "Сама проверка идёт через eGov — на защищённой странице сайта, она откроется в приложении.",
        "ver_done_t": "Проверенный продавец", "ver_done_s": "Верификация пройдена — значок «Проверенный» уже в ваших объявлениях.",
        "ver_rej": "Прошлая проверка отклонена — пройдите её ещё раз.",
        "ver_off": "Подтверждение личности временно недоступно — идут технические работы. Попробуйте позже.",
        // Обращение в поддержку (dataReqOpen, support.php?action=create)
        "sup_title": "Обращение в поддержку", "sup_topic_payment": "Тема: оплата", "sup_topic_other": "Тема: другое",
        "sup_topic_access": "Тема: доступ к аккаунту",
        "sup_hint": "Опишите, что случилось. Ваш аккаунт определим автоматически — логин/ID вводить не нужно.",
        "sup_ph": "Сообщение…", "sup_min": "Опишите подробнее — минимум 10 символов", "sup_send": "Отправить обращение",
        "sup_sending": "Отправка…", "sup_done": "Обращение принято. Номер: %@. Ответ придёт в поддержке.",
        "sup_open": "Открыть обращение", "sup_err": "Ошибка, попробуйте позже", "sup_no_conn": "Нет соединения",
        "sup_site": "Открыть страницу поддержки на сайте",
    ]

    private static let kk: [String: String] = [
        "adl_t": "Аккаунтты жою керек пе?", "adl_s": "Бұл үзіліс емес, жою. Міне, не болады.",
        "adl_l1": "Хабарландырулар витринадан кетеді", "adl_l2": "Кіру жұмыс істемейді — бұл аккаунтпен енді кіре алмайсыз",
        "adl_l3": "Хат алмасулар жабылады, сізге жазу мүмкін болмайды",
        "adl_keep": "Аяқталған мәмілелер туралы жазбаларды 365 күн сақтауға міндеттіміз — мұны есеп талап етеді. Бұл ретте аккаунт жойылады: ол басқаларға көрінбейді және оған кіру мүмкін емес.",
        "adl_undo": "Ойыңыз өзгерсе — аккаунтты 365 күн ішінде қолдау қызметіне өтініш арқылы қалпына келтіруге болады.",
        "adl_send": "Жалғастыру", "adl_cancel": "Аккаунтты қалдыру", "adl_fail": "Жалғастыру мүмкін болмады",
        "adl_egov": "Жою eGov арқылы расталады — ақша шығару сияқты тәсілмен.",
        "adl_egov_site": "eGov арқылы растау сайттың қорғалған бетінде өтеді: кабинет ашылады, онда «Баптаулар» → «Аккаунтты жою».",
        "adl_ok_egov": "eGov арқылы растау",
        "adl_pass_alt": "eGov тексеруі өтпей ме? Құпиясөзбен растау",
        "adl_sup_alt": "eGov тексеруі өтпей ме? Қолдау қызметіне жазыңыз — өтініш бойынша жоямыз",
        "adl_pass_h": "Аккаунт құпиясөзін енгізіңіз — жою қайтарылмайды.", "adl_pass_ph": "Құпиясөзіңіз",
        "adl_code_h": "%@ енгізіңіз — кездейсоқ басылмағанына көз жеткіземіз", "adl_code_ph": "Экрандағы код",
        "adl_code_bad": "Код сәйкес келмейді", "adl_why": "Неге кетесіз? (міндетті емес)", "adl_ok": "Аккаунтты жою",
        "adl_done": "Аккаунт жойылды. Бұл аккаунтпен кіру енді жұмыс істемейді.", "adl_bye": "Жабу",
        "phc_net": "Байланыс жоқ", "err_generic": "Қате", "close": "Жабу",
        "vp_title": "Сатушы болу",
        "vp_sub": "eGov арқылы жеке басты тексеру — шамамен бір минут, SMS-код қажет. Одан кейін хабарландырулар витринаға шығады, ал төлем кепілгер арқылы жүреді.",
        "vp_b1_t": "Қауіпсіз мәмілелер", "vp_b1_d": "Кепілгер арқылы төлем — тауар алынғанға дейін ақша қорғалған",
        "vp_b2_t": "«Тексерілген» белгісі", "vp_b2_d": "Сатып алушылардың сенімі көбірек — сату да көбірек",
        "vp_b3_t": "Байланыстың барлық тәсілдері", "vp_b3_d": "Нөмір мен WhatsApp тікелей хабарландыруда",
        "vp_b4_t": "PRO және Дүкен", "vp_b4_d": "Витрина, көтерме және сатуға арналған бизнес-құралдар",
        "vp_b5_t": "Kliko AI көмегі көбірек", "vp_b5_d": "5 орнына 50 Kliko AI сұрауы — жылдам хабарландырулар мен бағалар",
        "vp_go": "Верификациядан өту", "vp_later": "Кейінірек",
        "vp_note": "Дәл қазір міндетті емес — кабинеттен кез келген уақытта болады",
        "ver_site_note": "Тексерудің өзі eGov арқылы — сайттың қорғалған бетінде өтеді, ол қосымшада ашылады.",
        "ver_done_t": "Тексерілген сатушы", "ver_done_s": "Верификация өтті — «Тексерілген» белгісі хабарландыруларыңызда тұр.",
        "ver_rej": "Алдыңғы тексеру қабылданбады — оны қайта өтіңіз.",
        "ver_off": "Жеке басты растау уақытша қолжетімсіз — техникалық жұмыстар жүріп жатыр. Кейінірек көріңіз.",
        "sup_title": "Қолдау қызметіне өтініш", "sup_topic_payment": "Тақырып: төлем", "sup_topic_other": "Тақырып: басқа",
        "sup_topic_access": "Тақырып: аккаунтқа кіру",
        "sup_hint": "Не болғанын сипаттаңыз. Аккаунтыңызды өзіміз анықтаймыз — логин/ID енгізу қажет емес.",
        "sup_ph": "Хабарлама…", "sup_min": "Толығырақ сипаттаңыз — кемінде 10 таңба", "sup_send": "Өтінішті жіберу",
        "sup_sending": "Жіберілуде…", "sup_done": "Өтініш қабылданды. Нөмірі: %@. Жауап қолдау қызметінде келеді.",
        "sup_open": "Өтінішті ашу", "sup_err": "Қате, кейінірек көріңіз", "sup_no_conn": "Байланыс жоқ",
        "sup_site": "Сайттағы қолдау бетін ашу",
    ]

    private static let en: [String: String] = [
        "adl_t": "Delete account?", "adl_s": "This is deletion, not a pause. Here is what will happen.",
        "adl_l1": "Your listings will leave the storefront", "adl_l2": "Sign-in will stop working — you can no longer use this account",
        "adl_l3": "Chats will close, nobody will be able to message you",
        "adl_keep": "We are required to keep records of completed deals for 365 days for accounting. The account itself is deleted: others cannot see it and nobody can sign in to it.",
        "adl_undo": "Changed your mind? The account can be restored within 365 days through support.",
        "adl_send": "Continue", "adl_cancel": "Keep account", "adl_fail": "Could not continue",
        "adl_egov": "Deletion is confirmed with eGov — the same way as withdrawing money.",
        "adl_egov_site": "eGov confirmation runs on a secure page of the website: your account will open there, then “Settings” → “Delete account”.",
        "adl_ok_egov": "Confirm with eGov",
        "adl_pass_alt": "eGov check not working? Confirm with your password",
        "adl_sup_alt": "eGov check not working? Write to support — we will delete it on request",
        "adl_pass_h": "Enter your account password — deletion cannot be undone.", "adl_pass_ph": "Your password",
        "adl_code_h": "Enter %@ so we know it was not tapped by accident", "adl_code_ph": "Code from the screen",
        "adl_code_bad": "The code does not match", "adl_why": "Why are you leaving? (optional)", "adl_ok": "Delete account",
        "adl_done": "The account is deleted. Signing in with it no longer works.", "adl_bye": "Close",
        "phc_net": "No connection", "err_generic": "Error", "close": "Close",
        "vp_title": "Become a seller",
        "vp_sub": "Identity check with eGov takes about a minute and needs an SMS code. After it your listings go to the storefront and payment goes through the escrow.",
        "vp_b1_t": "Safe deals", "vp_b1_d": "Payment through the escrow — the money is protected until the item is received",
        "vp_b2_t": "“Verified” badge", "vp_b2_d": "More trust from buyers — and more sales",
        "vp_b3_t": "All contact options", "vp_b3_d": "Phone and WhatsApp right in the listing",
        "vp_b4_t": "PRO and Shop", "vp_b4_d": "Storefront, wholesale and business tools for sales",
        "vp_b5_t": "More Kliko AI help", "vp_b5_d": "50 Kliko AI requests instead of 5 — quick listings and prices",
        "vp_go": "Get verified", "vp_later": "Later",
        "vp_note": "Not required right now — you can do it any time from your account",
        "ver_site_note": "The check itself runs through eGov on a secure page of the website, which opens inside the app.",
        "ver_done_t": "Verified seller", "ver_done_s": "Verification passed — the “Verified” badge is already on your listings.",
        "ver_rej": "The previous check was rejected — please go through it again.",
        "ver_off": "Identity verification is temporarily unavailable due to maintenance. Please try later.",
        "sup_title": "Support request", "sup_topic_payment": "Topic: payment", "sup_topic_other": "Topic: other",
        "sup_topic_access": "Topic: account access",
        "sup_hint": "Describe what happened. We will identify your account automatically — no need to enter a login or ID.",
        "sup_ph": "Message…", "sup_min": "Please describe in more detail — at least 10 characters", "sup_send": "Send request",
        "sup_sending": "Sending…", "sup_done": "Request received. Number: %@. The reply will come in support.",
        "sup_open": "Open request", "sup_err": "Error, please try later", "sup_no_conn": "No connection",
        "sup_site": "Open the support page on the website",
    ]

    private static let ar: [String: String] = [
        "adl_t": "حذف الحساب؟", "adl_s": "هذا حذف وليس إيقافًا مؤقتًا. إليك ما سيحدث.",
        "adl_l1": "ستُزال إعلاناتك من الواجهة", "adl_l2": "سيتوقف تسجيل الدخول — لن تتمكن من استخدام هذا الحساب بعد الآن",
        "adl_l3": "ستُغلق المحادثات ولن يتمكن أحد من مراسلتك",
        "adl_keep": "نحن ملزمون بحفظ سجلات الصفقات المكتملة لمدة 365 يومًا لأغراض المحاسبة. أما الحساب فيُحذف: لا يراه الآخرون ولا يمكن الدخول إليه.",
        "adl_undo": "إذا غيّرت رأيك، يمكن استعادة الحساب خلال 365 يومًا عبر الدعم.",
        "adl_send": "متابعة", "adl_cancel": "الإبقاء على الحساب", "adl_fail": "تعذّرت المتابعة",
        "adl_egov": "يُؤكَّد الحذف عبر eGov — بالطريقة نفسها المتبعة في سحب الأموال.",
        "adl_egov_site": "يجري التأكيد عبر eGov في صفحة آمنة على الموقع: سيُفتح حسابك هناك، ثم «الإعدادات» ← «حذف الحساب».",
        "adl_ok_egov": "التأكيد عبر eGov",
        "adl_pass_alt": "لا ينجح التحقق عبر eGov؟ أكّد بكلمة المرور",
        "adl_sup_alt": "لا ينجح التحقق عبر eGov؟ راسل الدعم — سنحذفه بناءً على طلبك",
        "adl_pass_h": "أدخل كلمة مرور الحساب — لا يمكن التراجع عن الحذف.", "adl_pass_ph": "كلمة المرور",
        "adl_code_h": "أدخل %@ لنتأكد أن الضغط لم يكن عن طريق الخطأ", "adl_code_ph": "الرمز الظاهر على الشاشة",
        "adl_code_bad": "الرمز غير مطابق", "adl_why": "لماذا تغادر؟ (اختياري)", "adl_ok": "حذف الحساب",
        "adl_done": "تم حذف الحساب. لم يعد تسجيل الدخول به ممكنًا.", "adl_bye": "إغلاق",
        "phc_net": "لا يوجد اتصال", "err_generic": "خطأ", "close": "إغلاق",
        "vp_title": "كن بائعًا",
        "vp_sub": "التحقق من الهوية عبر eGov يستغرق نحو دقيقة ويتطلب رمزًا من رسالة SMS. بعده تظهر إعلاناتك في الواجهة ويتم الدفع عبر الضامن.",
        "vp_b1_t": "صفقات آمنة", "vp_b1_d": "الدفع عبر الضامن — المال محمي حتى استلام السلعة",
        "vp_b2_t": "شارة «موثَّق»", "vp_b2_d": "ثقة أكبر من المشترين — ومبيعات أكثر",
        "vp_b3_t": "جميع وسائل التواصل", "vp_b3_d": "الرقم وواتساب مباشرة في الإعلان",
        "vp_b4_t": "PRO والمتجر", "vp_b4_d": "واجهة وبيع بالجملة وأدوات أعمال للمبيعات",
        "vp_b5_t": "مساعدة أكبر من Kliko AI", "vp_b5_d": "50 طلبًا من Kliko AI بدلًا من 5 — إعلانات وأسعار سريعة",
        "vp_go": "إجراء التحقق", "vp_later": "لاحقًا",
        "vp_note": "ليس ضروريًا الآن — يمكنك ذلك في أي وقت من حسابك",
        "ver_site_note": "يجري التحقق نفسه عبر eGov في صفحة آمنة على الموقع تُفتح داخل التطبيق.",
        "ver_done_t": "بائع موثَّق", "ver_done_s": "تم التحقق — شارة «موثَّق» ظاهرة بالفعل في إعلاناتك.",
        "ver_rej": "رُفض التحقق السابق — يرجى إجراؤه مرة أخرى.",
        "ver_off": "تأكيد الهوية غير متاح مؤقتًا بسبب أعمال فنية. حاول لاحقًا.",
        "sup_title": "طلب إلى الدعم", "sup_topic_payment": "الموضوع: الدفع", "sup_topic_other": "الموضوع: أخرى",
        "sup_topic_access": "الموضوع: الوصول إلى الحساب",
        "sup_hint": "صف ما حدث. سنتعرف على حسابك تلقائيًا — لا حاجة لإدخال اسم المستخدم أو المعرّف.",
        "sup_ph": "الرسالة…", "sup_min": "صف بتفصيل أكبر — 10 أحرف على الأقل", "sup_send": "إرسال الطلب",
        "sup_sending": "جارٍ الإرسال…", "sup_done": "تم استلام الطلب. رقمه: %@. سيصل الرد في قسم الدعم.",
        "sup_open": "فتح الطلب", "sup_err": "خطأ، حاول لاحقًا", "sup_no_conn": "لا يوجد اتصال",
        "sup_site": "فتح صفحة الدعم على الموقع",
    ]
}
