import Foundation

/**
 Тексты входа, регистрации, выхода и сеанса (этап 40, владелец 26.09.2026) на языке телефона (kk/ru/en/ar).

 Русские — слово в слово с сайта: словари js/i18n-auth-ru.js и js/i18n-cabinet-ru.js (ключи auth_*, reg_*,
 terms_renew_*, cab_logout, no_conn, app_err), тексты, зашитые в скрипт гостевой страницы («Ошибка входа», «Аккаунт
 удалён», «Восстановить доступ», «Аккаунт создан»), window.__klkSA.txt (сеанс) и KLK_TXT маски номера (у него у сайта
 есть и kz/en/ar — они здесь дословно). Остальные языки — перевод тех же фраз.
 */
enum ВходText {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    private static let ru: [String: String] = [
        "seller_cab": "Личный кабинет продавца",
        "auth_login": "Войти",
        "auth_register": "Регистрация",
        "auth_phone": "Номер телефона",
        "auth_pass": "Пароль",
        "auth_forgot": "Забыли пароль?",
        "auth_no_acc": "Нет аккаунта?",
        "auth_do_register": "Зарегистрируйтесь",
        "auth_reg_hint": "Введите номер — аккаунт создадим сразу, а пароль предложим сохранить в Связку ключей.",
        "auth_agree": "Я прочитал(а) и принимаю %@ и %@, включая условия гарант-сервиса и комиссии платформы",
        "auth_terms_link": "Пользовательское соглашение",
        "auth_privacy_link": "Политику конфиденциальности",
        "auth_create": "Создать аккаунт",
        "auth_have_acc": "Есть аккаунт?",
        "auth_do_login": "Войдите",
        "auth_or_via": "или войдите через",
        "auth_agree_soc": "Продолжая, вы принимаете %@ и %@",
        "auth_via_egov": "Войти через eGov",
        "auth_via_apple": "Войти через Apple",
        "auth_phone_note": "Номер телефона попросим в любом случае — он обязателен (но его можно скрыть в кабинете).",
        "no_conn": "Нет соединения",
        "app_err": "Ошибка приложения. Обновите страницу и попробуйте ещё раз",
        "login_err": "Ошибка входа",
        "err": "Ошибка",
        "need_agree": "Необходимо принять Пользовательское соглашение",
        "phone_code": "Кода оператора %@ нет — проверьте номер",
        "phone_short": "Введите номер полностью: +7 и 10 цифр",
        "reg_confirm_title": "Подтвердите номер",
        "reg_confirm_text": "На этот номер привяжем аккаунт и пришлём доступ. Убедитесь, что он верный — иначе не сможете войти.",
        "reg_confirm_ok": "Всё верно, создать",
        "reg_confirm_edit": "Изменить номер",
        "reg_exists_title": "Номер уже зарегистрирован",
        "reg_exists_text": "У этого номера уже есть аккаунт. Восстановите доступ по ИИН через eGov или войдите по паролю.",
        "reg_iin_title": "ИИН уже зарегистрирован",
        "reg_iin_text": "Этот ИИН уже привязан к аккаунту. Восстановите доступ по ИИН через eGov (номер можно не вводить) или войдите по паролю.",
        "reg_recover_egov": "Восстановить по ИИН (eGov)",
        "reg_recover_pass": "Войти по паролю",
        "deleted_t": "Аккаунт удалён",
        "deleted_s": "Вход закрыт. Если это ошибка — напишите в поддержку, мы поможем восстановить доступ.",
        "deleted_reason": "Причина",
        "deleted_support": "Обратиться в поддержку",
        "close": "Закрыть",
        "rec_t": "Восстановить доступ",
        "rec_s_bio": "Восстановите доступ по ИИН через eGov — код из SMS, и вы снова в своём аккаунте. Или используйте способ ниже.",
        "rec_s_off": "Восстановить доступ поможет поддержка — напишите нам, и мы вернём вход в аккаунт.",
        "rec_support": "Напишите в поддержку",
        "cr_t": "Аккаунт создан",
        "cr_s": "Вы уже вошли — сохраните доступ",
        "cr_phone": "Телефон",
        "cr_pass": "Пароль",
        "cr_txt": "Файл .txt",
        "cr_change": "Пароль можно сменить в кабинете в любой момент",
        "cr_go": "Продолжить",
        "cr_file_btn": "Сохранить файлом",
        "cr_kc_wait": "Предлагаем сохранить пароль в Связку ключей…",
        "cr_kc_ok": "Сохранено в Связку ключей — пароль подставится сам при следующем входе.",
        "cr_kc_no": "В Связку ключей пароль не сохранён — скопируйте его или сохраните файлом.",
        "cr_copy": "Копировать",
        "cr_copied": "Скопировано",
        "cr_file": "Kliko.kz — доступ к аккаунту\n\nТелефон: %@\nПароль: %@\n\nСохраните этот файл. Пароль можно сменить в кабинете.",
        "terms_renew_t": "Условия обновились",
        "terms_renew_gate_s": "Мы обновили пользовательское соглашение. Чтобы продолжить работу в кабинете, примите новую редакцию.",
        "terms_renew_link": "Читать соглашение",
        "terms_renew_ok": "Принимаю",
        "terms_renew_done": "Спасибо — новая редакция принята",
        "cab_logout": "Выйти",
        "logout_q": "Выйти из аккаунта?",
        "logout_msg": "Сервер закроет сессию и перестанет присылать уведомления на этот телефон, а приложение сотрёт с него всё, что связано с аккаунтом.",
        "logout_footer": "Выход закрывает сессию на сервере и стирает с телефона избранное, историю, черновики и всё, что сайт хранил для этого аккаунта.",
        "kick_q_t": "В ваш аккаунт вошли с другого устройства",
        "live_q_t": "Вход в ваш аккаунт с нового устройства",
        "q": "Это были вы?",
        "kick_t": "Вы вышли на этом устройстве",
        "kick_s": "В аккаунт вошли с другого устройства. Если это были не вы — войдите и смените пароль.",
        "info_s": "Вход подтверждён через eGov — с проверкой лица владельца аккаунта.",
        "live_info_t": "Вход через eGov с другого устройства",
        "self_t": "Сеанс завершён из настроек аккаунта",
        "self_s": "Если это были не вы — войдите и смените пароль.",
        "den_t": "Вход отклонён владельцем аккаунта",
        "den_s": "Владелец аккаунта ответил, что этот вход — не его. Войти снова можно только через eGov.",
        "sess_login": "Войти",
        "sess_answer": "Ответить в кабинете",
        "show_pass": "Показать пароль",
        "hide_pass": "Скрыть пароль"
    ]

    private static let kk: [String: String] = [
        "seller_cab": "Сатушының жеке кабинеті",
        "auth_login": "Кіру",
        "auth_register": "Тіркелу",
        "auth_phone": "Телефон нөмірі",
        "auth_pass": "Құпиясөз",
        "auth_forgot": "Құпиясөзді ұмыттыңыз ба?",
        "auth_no_acc": "Аккаунтыңыз жоқ па?",
        "auth_do_register": "Тіркеліңіз",
        "auth_reg_hint": "Нөміріңізді енгізіңіз — аккаунтты бірден ашамыз, ал құпиясөзді Кілттер бауына сақтауды ұсынамыз.",
        "auth_agree": "Мен %@ және %@ оқыдым және қабылдаймын, соның ішінде кепіл-сервис шарттары мен платформа комиссиясы",
        "auth_terms_link": "Пайдаланушы келісімін",
        "auth_privacy_link": "Құпиялылық саясатын",
        "auth_create": "Аккаунт ашу",
        "auth_have_acc": "Аккаунтыңыз бар ма?",
        "auth_do_login": "Кіріңіз",
        "auth_or_via": "немесе мыналар арқылы кіріңіз",
        "auth_agree_soc": "Жалғастыра отырып, сіз %@ және %@ қабылдайсыз",
        "auth_via_egov": "eGov арқылы кіру",
        "auth_via_apple": "Apple арқылы кіру",
        "auth_phone_note": "Телефон нөмірін бәрібір сұраймыз — ол міндетті (бірақ оны кабинетте жасыруға болады).",
        "no_conn": "Байланыс жоқ",
        "app_err": "Қосымша қатесі. Бетті жаңартып, қайталап көріңіз",
        "login_err": "Кіру қатесі",
        "err": "Қате",
        "need_agree": "Пайдаланушы келісімін қабылдау қажет",
        "phone_code": "%@ операторлық коды жоқ — нөмірді тексеріңіз",
        "phone_short": "Нөмірді толық енгізіңіз: +7 және 10 цифр",
        "reg_confirm_title": "Нөмірді растаңыз",
        "reg_confirm_text": "Аккаунтты осы нөмірге байлап, кіру деректерін жібереміз. Нөмірдің дұрыс екеніне көз жеткізіңіз — әйтпесе кіре алмайсыз.",
        "reg_confirm_ok": "Бәрі дұрыс, ашу",
        "reg_confirm_edit": "Нөмірді өзгерту",
        "reg_exists_title": "Нөмір тіркелген",
        "reg_exists_text": "Бұл нөмірдің аккаунты бар. eGov арқылы ЖСН бойынша қолжетімділікті қалпына келтіріңіз немесе құпиясөзбен кіріңіз.",
        "reg_iin_title": "ЖСН тіркелген",
        "reg_iin_text": "Бұл ЖСН аккаунтқа байланған. eGov арқылы ЖСН бойынша қалпына келтіріңіз (нөмірді енгізбеуге болады) немесе құпиясөзбен кіріңіз.",
        "reg_recover_egov": "ЖСН бойынша қалпына келтіру (eGov)",
        "reg_recover_pass": "Құпиясөзбен кіру",
        "deleted_t": "Аккаунт жойылған",
        "deleted_s": "Кіру жабық. Егер бұл қате болса — қолдау қызметіне жазыңыз, қолжетімділікті қалпына келтіруге көмектесеміз.",
        "deleted_reason": "Себебі",
        "deleted_support": "Қолдау қызметіне жүгіну",
        "close": "Жабу",
        "rec_t": "Қолжетімділікті қалпына келтіру",
        "rec_s_bio": "eGov арқылы ЖСН бойынша қалпына келтіріңіз — SMS коды, және сіз қайтадан өз аккаунтыңыздасыз. Немесе төмендегі тәсілді пайдаланыңыз.",
        "rec_s_off": "Қолжетімділікті қалпына келтіруге қолдау қызметі көмектеседі — бізге жазыңыз, аккаунтқа кіруді қайтарамыз.",
        "rec_support": "Қолдау қызметіне жазу",
        "cr_t": "Аккаунт ашылды",
        "cr_s": "Сіз кірдіңіз — кіру деректерін сақтаңыз",
        "cr_phone": "Телефон",
        "cr_pass": "Құпиясөз",
        "cr_txt": ".txt файлы",
        "cr_change": "Құпиясөзді кабинетте кез келген уақытта өзгертуге болады",
        "cr_go": "Жалғастыру",
        "cr_file_btn": "Файлмен сақтау",
        "cr_kc_wait": "Құпиясөзді Кілттер бауына сақтауды ұсынып жатырмыз…",
        "cr_kc_ok": "Кілттер бауына сақталды — келесі кіргенде құпиясөз өзі қойылады.",
        "cr_kc_no": "Құпиясөз Кілттер бауына сақталмады — оны көшіріп алыңыз немесе файлмен сақтаңыз.",
        "cr_copy": "Көшіру",
        "cr_copied": "Көшірілді",
        "cr_file": "Kliko.kz — аккаунтқа кіру\n\nТелефон: %@\nҚұпиясөз: %@\n\nОсы файлды сақтаңыз. Құпиясөзді кабинетте өзгертуге болады.",
        "terms_renew_t": "Шарттар жаңартылды",
        "terms_renew_gate_s": "Біз пайдаланушы келісімін жаңарттық. Кабинетте жұмысты жалғастыру үшін жаңа редакцияны қабылдаңыз.",
        "terms_renew_link": "Келісімді оқу",
        "terms_renew_ok": "Қабылдаймын",
        "terms_renew_done": "Рақмет — жаңа редакция қабылданды",
        "cab_logout": "Шығу",
        "logout_q": "Аккаунттан шығу керек пе?",
        "logout_msg": "Сервер сессияны жабады және осы телефонға хабарландыру жіберуді тоқтатады, ал қосымша телефоннан аккаунтқа қатысты бәрін өшіреді.",
        "logout_footer": "Шығу сервердегі сессияны жабады және телефоннан таңдаулыларды, тарихты, жобаларды және сайт осы аккаунт үшін сақтағанның бәрін өшіреді.",
        "kick_q_t": "Аккаунтыңызға басқа құрылғыдан кірді",
        "live_q_t": "Аккаунтыңызға жаңа құрылғыдан кіру",
        "q": "Бұл сіз бе едіңіз?",
        "kick_t": "Сіз осы құрылғыда шықтыңыз",
        "kick_s": "Аккаунтқа басқа құрылғыдан кірді. Егер бұл сіз болмасаңыз — кіріп, құпиясөзді өзгертіңіз.",
        "info_s": "Кіру eGov арқылы расталды — аккаунт иесінің бетін тексерумен.",
        "live_info_t": "Басқа құрылғыдан eGov арқылы кіру",
        "self_t": "Сеанс аккаунт баптауларынан аяқталды",
        "self_s": "Егер бұл сіз болмасаңыз — кіріп, құпиясөзді өзгертіңіз.",
        "den_t": "Кіруді аккаунт иесі қабылдамады",
        "den_s": "Аккаунт иесі бұл кіру оныкі емес деп жауап берді. Қайта кіру тек eGov арқылы мүмкін.",
        "sess_login": "Кіру",
        "sess_answer": "Кабинетте жауап беру",
        "show_pass": "Құпиясөзді көрсету",
        "hide_pass": "Құпиясөзді жасыру"
    ]

    private static let en: [String: String] = [
        "seller_cab": "Seller account",
        "auth_login": "Sign in",
        "auth_register": "Sign up",
        "auth_phone": "Phone number",
        "auth_pass": "Password",
        "auth_forgot": "Forgot password?",
        "auth_no_acc": "No account?",
        "auth_do_register": "Sign up",
        "auth_reg_hint": "Enter your number and we'll create the account right away, then offer to save the password to iCloud Keychain.",
        "auth_agree": "I have read and accept the %@ and the %@, including the guarantee service terms and platform fees",
        "auth_terms_link": "User Agreement",
        "auth_privacy_link": "Privacy Policy",
        "auth_create": "Create account",
        "auth_have_acc": "Have an account?",
        "auth_do_login": "Sign in",
        "auth_or_via": "or sign in with",
        "auth_agree_soc": "By continuing, you accept the %@ and the %@",
        "auth_via_egov": "Sign in with eGov",
        "auth_via_apple": "Sign in with Apple",
        "auth_phone_note": "We'll ask for a phone number either way — it's required (but you can hide it in your account).",
        "no_conn": "No connection",
        "app_err": "App error. Refresh the page and try again",
        "login_err": "Sign-in error",
        "err": "Error",
        "need_agree": "You need to accept the User Agreement",
        "phone_code": "There is no operator code %@ — check the number",
        "phone_short": "Enter the full number: +7 and 10 digits",
        "reg_confirm_title": "Confirm your number",
        "reg_confirm_text": "We'll link the account to this number and send access to it. Make sure it's correct — otherwise you won't be able to sign in.",
        "reg_confirm_ok": "Correct, create",
        "reg_confirm_edit": "Change number",
        "reg_exists_title": "Number already registered",
        "reg_exists_text": "This number already has an account. Restore access by IIN via eGov or sign in with your password.",
        "reg_iin_title": "IIN already registered",
        "reg_iin_text": "This IIN is already linked to an account. Restore access by IIN via eGov (no number needed) or sign in with your password.",
        "reg_recover_egov": "Restore by IIN (eGov)",
        "reg_recover_pass": "Sign in with password",
        "deleted_t": "Account deleted",
        "deleted_s": "Sign-in is closed. If this is a mistake, contact support and we'll help restore access.",
        "deleted_reason": "Reason",
        "deleted_support": "Contact support",
        "close": "Close",
        "rec_t": "Restore access",
        "rec_s_bio": "Restore access by IIN via eGov — an SMS code, and you're back in your account. Or use the method below.",
        "rec_s_off": "Our support team will help you restore access — write to us and we'll get you back into your account.",
        "rec_support": "Contact support",
        "cr_t": "Account created",
        "cr_s": "You're signed in — save your access",
        "cr_phone": "Phone",
        "cr_pass": "Password",
        "cr_txt": ".txt file",
        "cr_change": "You can change the password in your account at any time",
        "cr_go": "Continue",
        "cr_file_btn": "Save as file",
        "cr_kc_wait": "Offering to save the password to iCloud Keychain…",
        "cr_kc_ok": "Saved to iCloud Keychain — the password will fill in by itself next time you sign in.",
        "cr_kc_no": "The password wasn't saved to iCloud Keychain — copy it or save it as a file.",
        "cr_copy": "Copy",
        "cr_copied": "Copied",
        "cr_file": "Kliko.kz — account access\n\nPhone: %@\nPassword: %@\n\nKeep this file. You can change the password in your account.",
        "terms_renew_t": "The terms have been updated",
        "terms_renew_gate_s": "We've updated the user agreement. To keep using your account, accept the new version.",
        "terms_renew_link": "Read the agreement",
        "terms_renew_ok": "I accept",
        "terms_renew_done": "Thank you — the new version is accepted",
        "cab_logout": "Sign out",
        "logout_q": "Sign out of your account?",
        "logout_msg": "The server will close the session and stop sending notifications to this phone, and the app will erase everything related to the account from it.",
        "logout_footer": "Signing out closes the session on the server and erases favorites, history, drafts and everything the site stored for this account from the phone.",
        "kick_q_t": "Someone signed in to your account from another device",
        "live_q_t": "Sign-in to your account from a new device",
        "q": "Was it you?",
        "kick_t": "You were signed out on this device",
        "kick_s": "Someone signed in to the account from another device. If it wasn't you, sign in and change your password.",
        "info_s": "The sign-in was confirmed via eGov, with a face check of the account owner.",
        "live_info_t": "Sign-in via eGov from another device",
        "self_t": "The session was ended from the account settings",
        "self_s": "If it wasn't you, sign in and change your password.",
        "den_t": "Sign-in rejected by the account owner",
        "den_s": "The account owner replied that this sign-in isn't theirs. You can sign in again only via eGov.",
        "sess_login": "Sign in",
        "sess_answer": "Answer in your account",
        "show_pass": "Show password",
        "hide_pass": "Hide password"
    ]

    private static let ar: [String: String] = [
        "seller_cab": "الحساب الشخصي للبائع",
        "auth_login": "تسجيل الدخول",
        "auth_register": "التسجيل",
        "auth_phone": "رقم الهاتف",
        "auth_pass": "كلمة المرور",
        "auth_forgot": "نسيت كلمة المرور؟",
        "auth_no_acc": "ليس لديك حساب؟",
        "auth_do_register": "سجّل",
        "auth_reg_hint": "أدخل رقمك وسننشئ الحساب فورًا، ثم نعرض حفظ كلمة المرور في سلسلة مفاتيح iCloud.",
        "auth_agree": "قرأت وأقبل %@ و%@، بما في ذلك شروط خدمة الضمان وعمولة المنصة",
        "auth_terms_link": "اتفاقية المستخدم",
        "auth_privacy_link": "سياسة الخصوصية",
        "auth_create": "إنشاء حساب",
        "auth_have_acc": "لديك حساب؟",
        "auth_do_login": "سجّل الدخول",
        "auth_or_via": "أو سجّل الدخول عبر",
        "auth_agree_soc": "بالمتابعة، أنت تقبل %@ و%@",
        "auth_via_egov": "الدخول عبر eGov",
        "auth_via_apple": "الدخول عبر Apple",
        "auth_phone_note": "سنطلب رقم الهاتف في كل الأحوال — فهو إلزامي (ويمكن إخفاؤه في الحساب).",
        "no_conn": "لا يوجد اتصال",
        "app_err": "خطأ في التطبيق. حدّث الصفحة وحاول مرة أخرى",
        "login_err": "خطأ في تسجيل الدخول",
        "err": "خطأ",
        "need_agree": "يجب قبول اتفاقية المستخدم",
        "phone_code": "لا يوجد رمز مشغل %@ — تحقّق من الرقم",
        "phone_short": "أدخل الرقم كاملًا: +7 و10 أرقام",
        "reg_confirm_title": "أكّد الرقم",
        "reg_confirm_text": "سنربط الحساب بهذا الرقم ونرسل إليه بيانات الدخول. تأكد أنه صحيح — وإلا فلن تتمكن من الدخول.",
        "reg_confirm_ok": "صحيح، أنشئ",
        "reg_confirm_edit": "تغيير الرقم",
        "reg_exists_title": "الرقم مسجّل بالفعل",
        "reg_exists_text": "لهذا الرقم حساب بالفعل. استعد الوصول بالرقم الشخصي عبر eGov أو سجّل الدخول بكلمة المرور.",
        "reg_iin_title": "الرقم الشخصي مسجّل بالفعل",
        "reg_iin_text": "هذا الرقم الشخصي مرتبط بحساب بالفعل. استعد الوصول به عبر eGov (لا حاجة للرقم) أو سجّل الدخول بكلمة المرور.",
        "reg_recover_egov": "الاستعادة بالرقم الشخصي (eGov)",
        "reg_recover_pass": "الدخول بكلمة المرور",
        "deleted_t": "الحساب محذوف",
        "deleted_s": "الدخول مغلق. إن كان ذلك خطأً فاكتب إلى الدعم وسنساعدك على استعادة الوصول.",
        "deleted_reason": "السبب",
        "deleted_support": "التواصل مع الدعم",
        "close": "إغلاق",
        "rec_t": "استعادة الوصول",
        "rec_s_bio": "استعد الوصول بالرقم الشخصي عبر eGov — رمز من SMS وتعود إلى حسابك. أو استخدم الطريقة أدناه.",
        "rec_s_off": "سيساعدك الدعم على استعادة الوصول — اكتب إلينا وسنعيد لك الدخول إلى حسابك.",
        "rec_support": "اكتب إلى الدعم",
        "cr_t": "تم إنشاء الحساب",
        "cr_s": "لقد سجّلت الدخول — احفظ بيانات الوصول",
        "cr_phone": "الهاتف",
        "cr_pass": "كلمة المرور",
        "cr_txt": "ملف ‎.txt",
        "cr_change": "يمكنك تغيير كلمة المرور من الحساب في أي وقت",
        "cr_go": "متابعة",
        "cr_file_btn": "حفظ كملف",
        "cr_kc_wait": "نعرض حفظ كلمة المرور في سلسلة مفاتيح iCloud…",
        "cr_kc_ok": "حُفظت في سلسلة مفاتيح iCloud — ستُملأ كلمة المرور تلقائيًا عند الدخول التالي.",
        "cr_kc_no": "لم تُحفظ كلمة المرور في سلسلة مفاتيح iCloud — انسخها أو احفظها كملف.",
        "cr_copy": "نسخ",
        "cr_copied": "تم النسخ",
        "cr_file": "Kliko.kz — الوصول إلى الحساب\n\nالهاتف: %@\nكلمة المرور: %@\n\nاحفظ هذا الملف. يمكن تغيير كلمة المرور من الحساب.",
        "terms_renew_t": "تم تحديث الشروط",
        "terms_renew_gate_s": "حدّثنا اتفاقية المستخدم. لمتابعة العمل في الحساب، اقبل النسخة الجديدة.",
        "terms_renew_link": "قراءة الاتفاقية",
        "terms_renew_ok": "أقبل",
        "terms_renew_done": "شكرًا — تم قبول النسخة الجديدة",
        "cab_logout": "تسجيل الخروج",
        "logout_q": "تسجيل الخروج من الحساب؟",
        "logout_msg": "سيغلق الخادم الجلسة ويتوقف عن إرسال الإشعارات إلى هذا الهاتف، وسيمحو التطبيق منه كل ما يتعلق بالحساب.",
        "logout_footer": "تسجيل الخروج يغلق الجلسة على الخادم ويمحو من الهاتف المفضلة والسجل والمسودات وكل ما حفظه الموقع لهذا الحساب.",
        "kick_q_t": "تم الدخول إلى حسابك من جهاز آخر",
        "live_q_t": "دخول إلى حسابك من جهاز جديد",
        "q": "هل كان هذا أنت؟",
        "kick_t": "تم تسجيل خروجك على هذا الجهاز",
        "kick_s": "تم الدخول إلى الحساب من جهاز آخر. إن لم يكن أنت فسجّل الدخول وغيّر كلمة المرور.",
        "info_s": "تم تأكيد الدخول عبر eGov مع التحقق من وجه صاحب الحساب.",
        "live_info_t": "دخول عبر eGov من جهاز آخر",
        "self_t": "أُنهيت الجلسة من إعدادات الحساب",
        "self_s": "إن لم يكن أنت فسجّل الدخول وغيّر كلمة المرور.",
        "den_t": "رفض صاحب الحساب الدخول",
        "den_s": "أجاب صاحب الحساب بأن هذا الدخول ليس له. يمكن الدخول مجددًا عبر eGov فقط.",
        "sess_login": "تسجيل الدخول",
        "sess_answer": "الرد في الحساب",
        "show_pass": "إظهار كلمة المرور",
        "hide_pass": "إخفاء كلمة المرور"
    ]
}
