import Foundation

/**
 Тексты «Отслеживания доставки» (владелец: статусы Яндекс Доставки, СДЭК, Казпочты и других — нативно внутри
 приложения, без перехода на сайт и сайты перевозчиков) на языке приложения: ru, kk, en, ar.

 Русские подписи статусов Яндекса — слово в слово с сайта (clocalYaLabel, ключи yastat_* словаря кабинета), этапы
 перевозчика — dealCarStage (car_st_*). Остальное — свои слова экрана. Где нужно число — %d, строка — %@.
 */
enum ТрекText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    /// Язык текстов — первый предпочитаемый, не из четырёх — русский (как у остальных *Text.swift).
    static var язык: String {
        let код = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        return тексты[код] != nil ? код : "ru"
    }

    /// Локаль дат и времени — та же, что у сделок (ru-RU, kk-KZ, en-US, ar-EG).
    static var локаль: Locale {
        switch язык {
        case "kk": return Locale(identifier: "kk_KZ")
        case "en": return Locale(identifier: "en_US")
        case "ar": return Locale(identifier: "ar_EG")
        default:   return Locale(identifier: "ru_RU")
        }
    }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    // MARK: - Русский

    private static let ru: [String: String] = [
        "title": "Отслеживание",
        "live": "В реальном времени",
        "c_yandex": "Яндекс Доставка",
        "c_cdek": "СДЭК",
        "c_kazpost": "Казпочта",
        "c_other": "Служба доставки",
        "st_created": "Отправка оформлена",
        "st_accepted": "Принято перевозчиком",
        "st_in_transit": "В пути",
        "st_arrived_pickup": "В пункте выдачи — можно забирать",
        "st_out_for_delivery": "Курьер везёт посылку",
        "st_delivered": "Вручено",
        "st_returned": "Возврат отправителю",
        "st_problem": "Задержка — перевозчик разбирается",
        "st_cancelled": "Отправка отменена",
        "st_unknown": "Статус уточняется",
        "sh_created": "Оформлено",
        "sh_accepted": "Принято",
        "sh_in_transit": "В пути",
        "sh_arrived_pickup": "В пункте выдачи",
        "sh_out_for_delivery": "Курьер везёт",
        "sh_delivered": "Вручено",
        "sh_returned": "Возврат",
        "sh_problem": "Задержка",
        "sh_cancelled": "Отменено",
        "sh_unknown": "Уточняется",
        "step_1": "Принято",
        "step_2": "В пути",
        "step_3": "Рядом",
        "step_4": "Вручено",
        "a11y_step": "Этап %d из %d",
        "updated_now": "Обновлено только что",
        "updated_min": "Обновлено %d мин назад",
        "updated_at": "Обновлено %@",
        "refresh": "Обновить",
        "eta": "Ожидается",
        "eta_soon": "вот-вот",
        "eta_min": "через ~%d мин · %@",
        "eta_at": "к %@",
        "eta_to_seller": "Курьер будет у продавца",
        "eta_to_you": "Курьер будет у вас",
        "eta_to_buyer": "Привезёт покупателю",
        "eta_to_you2": "Привезёт вам",
        "eta_back": "Вернёт продавцу",
        "courier": "Курьер",
        "call": "Позвонить курьеру",
        "call_t": "Звонок курьеру",
        "call_num": "Номер: %@",
        "call_ext": "Добавочный: %@",
        "call_hint": "Номер подменный: настоящий номер курьера не показывается. Наберите его, а когда попросят — добавочный.",
        "call_ttl": "Номер действует ~%d мин.",
        "call_go": "Позвонить",
        "close": "Закрыть",
        "code_s": "Код для курьера — назовите его, когда отдаёте товар",
        "code_b": "Код для курьера — назовите его, когда получаете товар",
        "code_ret": "Код для курьера — назовите его, когда забираете товар обратно",
        "code_left": "Попыток ввода: %d",
        "code_sms_s": "Курьер попросит код из SMS — оно придёт на ваш номер.",
        "code_sms_b": "Курьер попросит код из SMS — оно придёт на ваш номер.",
        "events": "История доставки",
        "show_all": "Показать все (%d)",
        "show_less": "Свернуть",
        "no_data_t": "Перевозчик пока не передал статусы",
        "no_data_s": "Как только посылку отсканируют, история появится здесь. Мы проверяем сами — обновлять не нужно.",
        "no_track_t": "Трек-номер ещё не добавлен",
        "no_track_s": "Когда продавец сдаст посылку или вызовет курьера, статусы появятся здесь.",
        "open_carrier": "Открыть страницу перевозчика",
        "track_no": "Трек-номер",
        "copy": "Скопировать номер",
        "copied": "Номер скопирован",
        "edit": "Изменить трек или ссылку",
        "add": "Добавить отслеживание",
        "edit_t": "Трек-номер или ссылка",
        "edit_ph": "Номер СДЭК, Казпочты или ссылка Яндекс Go",
        "edit_hint": "Скопируйте номер или ссылку на заказ в приложении службы — перевозчика мы определим сами. Вторая сторона увидит статусы в сделке.",
        "clip_seen": "В буфере есть ссылка — вставьте её одной кнопкой",
        "detected": "Перевозчик: %@",
        "detected_none": "Перевозчик не определён — проверьте номер",
        "save": "Сохранить",
        "remove": "Убрать отслеживание",
        "saved": "Сохранено",
        "removed": "Отслеживание убрано",
        "e_host_t": "Только ссылки курьерских служб",
        "e_host": "Сюда вставляют ссылку на заказ из приложения службы. Другие ссылки внутри сделки мы не показываем: под видом отслеживания легко подсунуть страницу оплаты.",
        "e_long": "Ссылка слишком длинная. Скопируйте ссылку на заказ целиком, но без лишнего текста вокруг неё.",
        "e_no_srv": "Сервер не принял трек-номер — вставьте ссылку на заказ.",
        "e_conn": "Нет связи. Проверьте интернет и попробуйте ещё раз.",
        "e_failed": "Не удалось",
        "e_auth": "Войдите в аккаунт, чтобы видеть доставку",
        "retry": "Повторить",
        "ya_failed": "Яндекс не нашёл курьера или заявку отменили.",
        "yastat_new": "Создаём заявку…",
        "yastat_est": "Рассчитываем стоимость…",
        "yastat_ready": "Готово к подтверждению",
        "yastat_accepted": "Заявка принята",
        "yastat_lookup": "Ищем курьера…",
        "yastat_found": "Курьер назначен — едет за товаром",
        "yastat_atseller": "Курьер у продавца",
        "yastat_picked": "Курьер забрал — везёт покупателю",
        "yastat_atbuyer": "Курьер у покупателя",
        "yastat_handed": "Вручено",
        "yastat_delivered": "Доставлено",
        "yastat_returning": "Возврат продавцу",
        "yastat_atseller_ret": "Курьер у продавца (возврат)",
        "yastat_returned_seller": "Возвращено продавцу",
        "yastat_returned": "Возвращено",
        "yastat_cancelled": "Заказ отменён",
        "yastat_cancelled_taxi": "Отменён службой",
        "yastat_nocourier": "Курьер не найден"
    ]

    // MARK: - Қазақша

    private static let kk: [String: String] = [
        "title": "Жеткізуді бақылау",
        "live": "Нақты уақытта",
        "c_yandex": "Яндекс Жеткізу",
        "c_cdek": "СДЭК",
        "c_kazpost": "Қазпошта",
        "c_other": "Жеткізу қызметі",
        "st_created": "Жөнелту рәсімделді",
        "st_accepted": "Тасымалдаушы қабылдады",
        "st_in_transit": "Жолда",
        "st_arrived_pickup": "Беру пунктінде — алуға болады",
        "st_out_for_delivery": "Курьер сәлемдемені әкеле жатыр",
        "st_delivered": "Табысталды",
        "st_returned": "Жіберушіге қайтарылуда",
        "st_problem": "Кідіріс — тасымалдаушы анықтап жатыр",
        "st_cancelled": "Жөнелту тоқтатылды",
        "st_unknown": "Мәртебе нақтылануда",
        "sh_created": "Рәсімделді",
        "sh_accepted": "Қабылданды",
        "sh_in_transit": "Жолда",
        "sh_arrived_pickup": "Беру пунктінде",
        "sh_out_for_delivery": "Курьер әкелуде",
        "sh_delivered": "Табысталды",
        "sh_returned": "Қайтару",
        "sh_problem": "Кідіріс",
        "sh_cancelled": "Тоқтатылды",
        "sh_unknown": "Нақтылануда",
        "step_1": "Қабылданды",
        "step_2": "Жолда",
        "step_3": "Жақын",
        "step_4": "Табысталды",
        "a11y_step": "%d-кезең, барлығы %d",
        "updated_now": "Жаңа ғана жаңартылды",
        "updated_min": "%d мин бұрын жаңартылды",
        "updated_at": "Жаңартылды: %@",
        "refresh": "Жаңарту",
        "eta": "Күтілуде",
        "eta_soon": "қазір-ақ",
        "eta_min": "~%d минуттан кейін · %@",
        "eta_at": "%@ қарай",
        "eta_to_seller": "Курьер сатушыға келеді",
        "eta_to_you": "Курьер сізге келеді",
        "eta_to_buyer": "Сатып алушыға жеткізеді",
        "eta_to_you2": "Сізге жеткізеді",
        "eta_back": "Сатушыға қайтарады",
        "courier": "Курьер",
        "call": "Курьерге қоңырау шалу",
        "call_t": "Курьерге қоңырау",
        "call_num": "Нөмір: %@",
        "call_ext": "Қосымша нөмір: %@",
        "call_hint": "Нөмір алмастырылған: курьердің нақты нөмірі көрсетілмейді. Оны теріңіз, сұраған кезде — қосымша нөмірді.",
        "call_ttl": "Нөмір ~%d мин жарамды.",
        "call_go": "Қоңырау шалу",
        "close": "Жабу",
        "code_s": "Курьерге арналған код — тауарды бергенде айтыңыз",
        "code_b": "Курьерге арналған код — тауарды алғанда айтыңыз",
        "code_ret": "Курьерге арналған код — тауарды кері алғанда айтыңыз",
        "code_left": "Енгізу мүмкіндігі: %d",
        "code_sms_s": "Курьер SMS-тегі кодты сұрайды — ол сіздің нөміріңізге келеді.",
        "code_sms_b": "Курьер SMS-тегі кодты сұрайды — ол сіздің нөміріңізге келеді.",
        "events": "Жеткізу тарихы",
        "show_all": "Барлығын көрсету (%d)",
        "show_less": "Жию",
        "no_data_t": "Тасымалдаушы әзірге мәртебе бермеді",
        "no_data_s": "Сәлемдеме сканерленген бойда тарих осында шығады. Біз өзіміз тексереміз — жаңартудың қажеті жоқ.",
        "no_track_t": "Трек-нөмір әлі қосылмаған",
        "no_track_s": "Сатушы сәлемдемені тапсырғанда немесе курьер шақырғанда мәртебелер осында шығады.",
        "open_carrier": "Тасымалдаушы бетін ашу",
        "track_no": "Трек-нөмір",
        "copy": "Нөмірді көшіру",
        "copied": "Нөмір көшірілді",
        "edit": "Тректі немесе сілтемені өзгерту",
        "add": "Бақылауды қосу",
        "edit_t": "Трек-нөмір немесе сілтеме",
        "edit_ph": "СДЭК, Қазпошта нөмірі немесе Яндекс Go сілтемесі",
        "edit_hint": "Қызмет қосымшасынан тапсырыс нөмірін немесе сілтемесін көшіріңіз — тасымалдаушыны өзіміз анықтаймыз. Екінші тарап мәртебелерді мәміледе көреді.",
        "clip_seen": "Буферде сілтеме бар — бір түймемен қойыңыз",
        "detected": "Тасымалдаушы: %@",
        "detected_none": "Тасымалдаушы анықталмады — нөмірді тексеріңіз",
        "save": "Сақтау",
        "remove": "Бақылауды алып тастау",
        "saved": "Сақталды",
        "removed": "Бақылау алып тасталды",
        "e_host_t": "Тек курьерлік қызметтердің сілтемелері",
        "e_host": "Мұнда қызмет қосымшасындағы тапсырыс сілтемесін қояды. Басқа сілтемелерді мәміле ішінде көрсетпейміз: бақылау атымен төлем бетін жіберу оңай.",
        "e_long": "Сілтеме тым ұзын. Тапсырыс сілтемесін толық, бірақ айналасындағы артық мәтінсіз көшіріңіз.",
        "e_no_srv": "Сервер трек-нөмірді қабылдамады — тапсырыс сілтемесін қойыңыз.",
        "e_conn": "Байланыс жоқ. Интернетті тексеріп, қайталап көріңіз.",
        "e_failed": "Сәтсіз аяқталды",
        "e_auth": "Жеткізуді көру үшін аккаунтқа кіріңіз",
        "retry": "Қайталау",
        "ya_failed": "Яндекс курьер таппады немесе өтінім тоқтатылды.",
        "yastat_new": "Өтінім жасалуда…",
        "yastat_est": "Құны есептелуде…",
        "yastat_ready": "Растауға дайын",
        "yastat_accepted": "Өтінім қабылданды",
        "yastat_lookup": "Курьер ізделуде…",
        "yastat_found": "Курьер тағайындалды — тауарға бара жатыр",
        "yastat_atseller": "Курьер сатушыда",
        "yastat_picked": "Курьер алды — сатып алушыға әкеле жатыр",
        "yastat_atbuyer": "Курьер сатып алушыда",
        "yastat_handed": "Табысталды",
        "yastat_delivered": "Жеткізілді",
        "yastat_returning": "Сатушыға қайтару",
        "yastat_atseller_ret": "Курьер сатушыда (қайтару)",
        "yastat_returned_seller": "Сатушыға қайтарылды",
        "yastat_returned": "Қайтарылды",
        "yastat_cancelled": "Тапсырыс тоқтатылды",
        "yastat_cancelled_taxi": "Қызмет тоқтатты",
        "yastat_nocourier": "Курьер табылмады"
    ]

    // MARK: - English

    private static let en: [String: String] = [
        "title": "Tracking",
        "live": "Live",
        "c_yandex": "Yandex Delivery",
        "c_cdek": "CDEK",
        "c_kazpost": "Kazpost",
        "c_other": "Delivery service",
        "st_created": "Shipment created",
        "st_accepted": "Accepted by carrier",
        "st_in_transit": "In transit",
        "st_arrived_pickup": "At the pickup point — ready to collect",
        "st_out_for_delivery": "Out for delivery",
        "st_delivered": "Delivered",
        "st_returned": "Returning to sender",
        "st_problem": "Delayed — the carrier is looking into it",
        "st_cancelled": "Shipment cancelled",
        "st_unknown": "Status pending",
        "sh_created": "Created",
        "sh_accepted": "Accepted",
        "sh_in_transit": "In transit",
        "sh_arrived_pickup": "At pickup point",
        "sh_out_for_delivery": "Out for delivery",
        "sh_delivered": "Delivered",
        "sh_returned": "Returning",
        "sh_problem": "Delayed",
        "sh_cancelled": "Cancelled",
        "sh_unknown": "Pending",
        "step_1": "Accepted",
        "step_2": "In transit",
        "step_3": "Nearby",
        "step_4": "Delivered",
        "a11y_step": "Step %d of %d",
        "updated_now": "Updated just now",
        "updated_min": "Updated %d min ago",
        "updated_at": "Updated %@",
        "refresh": "Refresh",
        "eta": "Expected",
        "eta_soon": "any moment",
        "eta_min": "in ~%d min · %@",
        "eta_at": "by %@",
        "eta_to_seller": "Courier arrives at the seller",
        "eta_to_you": "Courier arrives at your place",
        "eta_to_buyer": "Delivers to the buyer",
        "eta_to_you2": "Delivers to you",
        "eta_back": "Returns to the seller",
        "courier": "Courier",
        "call": "Call the courier",
        "call_t": "Call the courier",
        "call_num": "Number: %@",
        "call_ext": "Extension: %@",
        "call_hint": "This is a proxy number: the courier's real number stays hidden. Dial it and enter the extension when asked.",
        "call_ttl": "The number works for ~%d min.",
        "call_go": "Call",
        "close": "Close",
        "code_s": "Code for the courier — say it when you hand over the item",
        "code_b": "Code for the courier — say it when you receive the item",
        "code_ret": "Code for the courier — say it when you take the item back",
        "code_left": "Attempts left: %d",
        "code_sms_s": "The courier will ask for a code from an SMS sent to your number.",
        "code_sms_b": "The courier will ask for a code from an SMS sent to your number.",
        "events": "Delivery history",
        "show_all": "Show all (%d)",
        "show_less": "Show less",
        "no_data_t": "The carrier hasn't shared any updates yet",
        "no_data_s": "The history appears here as soon as the parcel is scanned. We check automatically — no need to refresh.",
        "no_track_t": "No tracking number yet",
        "no_track_s": "Updates appear here once the seller drops off the parcel or calls a courier.",
        "open_carrier": "Open the carrier's page",
        "track_no": "Tracking number",
        "copy": "Copy number",
        "copied": "Number copied",
        "edit": "Change tracking number or link",
        "add": "Add tracking",
        "edit_t": "Tracking number or link",
        "edit_ph": "CDEK or Kazpost number, or a Yandex Go link",
        "edit_hint": "Copy the order number or link from the delivery app — we'll detect the carrier. The other party will see the updates in the deal.",
        "clip_seen": "There's a link on your clipboard — paste it with one tap",
        "detected": "Carrier: %@",
        "detected_none": "Carrier not recognised — check the number",
        "save": "Save",
        "remove": "Remove tracking",
        "saved": "Saved",
        "removed": "Tracking removed",
        "e_host_t": "Delivery service links only",
        "e_host": "Paste the order link from the delivery app here. We don't show other links inside a deal: a fake tracking page could hide a payment form.",
        "e_long": "The link is too long. Copy the whole order link without any extra text around it.",
        "e_no_srv": "The server didn't accept the tracking number — paste the order link instead.",
        "e_conn": "No connection. Check the internet and try again.",
        "e_failed": "Something went wrong",
        "e_auth": "Sign in to see the delivery",
        "retry": "Try again",
        "ya_failed": "Yandex couldn't find a courier, or the request was cancelled.",
        "yastat_new": "Creating the request…",
        "yastat_est": "Calculating the price…",
        "yastat_ready": "Ready to confirm",
        "yastat_accepted": "Request accepted",
        "yastat_lookup": "Looking for a courier…",
        "yastat_found": "Courier assigned — on the way to pick up",
        "yastat_atseller": "Courier is at the seller",
        "yastat_picked": "Picked up — on the way to the buyer",
        "yastat_atbuyer": "Courier is at the buyer",
        "yastat_handed": "Handed over",
        "yastat_delivered": "Delivered",
        "yastat_returning": "Returning to the seller",
        "yastat_atseller_ret": "Courier is at the seller (return)",
        "yastat_returned_seller": "Returned to the seller",
        "yastat_returned": "Returned",
        "yastat_cancelled": "Order cancelled",
        "yastat_cancelled_taxi": "Cancelled by the service",
        "yastat_nocourier": "No courier found"
    ]

    // MARK: - العربية

    private static let ar: [String: String] = [
        "title": "تتبّع الشحنة",
        "live": "مباشر",
        "c_yandex": "ياندكس للتوصيل",
        "c_cdek": "CDEK",
        "c_kazpost": "بريد كازاخستان",
        "c_other": "خدمة التوصيل",
        "st_created": "تم إنشاء الشحنة",
        "st_accepted": "استلمتها شركة الشحن",
        "st_in_transit": "في الطريق",
        "st_arrived_pickup": "في نقطة الاستلام — يمكنك استلامها",
        "st_out_for_delivery": "المندوب في طريقه بالطرد",
        "st_delivered": "تم التسليم",
        "st_returned": "تُعاد إلى المرسل",
        "st_problem": "تأخير — شركة الشحن تتحقق",
        "st_cancelled": "أُلغيت الشحنة",
        "st_unknown": "الحالة قيد التحديث",
        "sh_created": "أُنشئت",
        "sh_accepted": "مستلمة",
        "sh_in_transit": "في الطريق",
        "sh_arrived_pickup": "في نقطة الاستلام",
        "sh_out_for_delivery": "مع المندوب",
        "sh_delivered": "سُلّمت",
        "sh_returned": "إرجاع",
        "sh_problem": "تأخير",
        "sh_cancelled": "ملغاة",
        "sh_unknown": "قيد التحديث",
        "step_1": "مستلمة",
        "step_2": "في الطريق",
        "step_3": "قريبة",
        "step_4": "سُلّمت",
        "a11y_step": "المرحلة %d من %d",
        "updated_now": "حُدّثت الآن",
        "updated_min": "حُدّثت قبل %d دقيقة",
        "updated_at": "حُدّثت %@",
        "refresh": "تحديث",
        "eta": "الموعد المتوقع",
        "eta_soon": "خلال لحظات",
        "eta_min": "خلال ~%d دقيقة · %@",
        "eta_at": "بحلول %@",
        "eta_to_seller": "يصل المندوب إلى البائع",
        "eta_to_you": "يصل المندوب إليك",
        "eta_to_buyer": "يوصلها إلى المشتري",
        "eta_to_you2": "يوصلها إليك",
        "eta_back": "يعيدها إلى البائع",
        "courier": "المندوب",
        "call": "اتصل بالمندوب",
        "call_t": "الاتصال بالمندوب",
        "call_num": "الرقم: %@",
        "call_ext": "الرقم الداخلي: %@",
        "call_hint": "هذا رقم وسيط: رقم المندوب الحقيقي لا يظهر. اتصل به وأدخل الرقم الداخلي عند الطلب.",
        "call_ttl": "يعمل الرقم لمدة ~%d دقيقة.",
        "call_go": "اتصال",
        "close": "إغلاق",
        "code_s": "رمز للمندوب — قله عند تسليم السلعة",
        "code_b": "رمز للمندوب — قله عند استلام السلعة",
        "code_ret": "رمز للمندوب — قله عند استرجاع السلعة",
        "code_left": "المحاولات المتبقية: %d",
        "code_sms_s": "سيطلب المندوب رمزًا من رسالة SMS تصل إلى رقمك.",
        "code_sms_b": "سيطلب المندوب رمزًا من رسالة SMS تصل إلى رقمك.",
        "events": "سجل التوصيل",
        "show_all": "عرض الكل (%d)",
        "show_less": "طيّ",
        "no_data_t": "لم تُرسل شركة الشحن أي تحديثات بعد",
        "no_data_s": "سيظهر السجل هنا فور مسح الطرد. نتحقق تلقائيًا — لا حاجة للتحديث.",
        "no_track_t": "لم يُضف رقم التتبع بعد",
        "no_track_s": "ستظهر التحديثات هنا عندما يسلّم البائع الطرد أو يطلب مندوبًا.",
        "open_carrier": "فتح صفحة شركة الشحن",
        "track_no": "رقم التتبع",
        "copy": "نسخ الرقم",
        "copied": "تم نسخ الرقم",
        "edit": "تغيير رقم التتبع أو الرابط",
        "add": "إضافة تتبّع",
        "edit_t": "رقم التتبع أو الرابط",
        "edit_ph": "رقم CDEK أو بريد كازاخستان أو رابط Yandex Go",
        "edit_hint": "انسخ رقم الطلب أو رابطه من تطبيق خدمة التوصيل — وسنحدد شركة الشحن بأنفسنا. سيرى الطرف الآخر التحديثات في الصفقة.",
        "clip_seen": "في الحافظة رابط — الصقه بلمسة واحدة",
        "detected": "شركة الشحن: %@",
        "detected_none": "لم نتعرّف على شركة الشحن — تحقّق من الرقم",
        "save": "حفظ",
        "remove": "إزالة التتبّع",
        "saved": "تم الحفظ",
        "removed": "أُزيل التتبّع",
        "e_host_t": "روابط خدمات التوصيل فقط",
        "e_host": "الصق هنا رابط الطلب من تطبيق خدمة التوصيل. لا نعرض روابط أخرى داخل الصفقة: فصفحة تتبّع مزيّفة قد تُخفي نموذج دفع.",
        "e_long": "الرابط طويل جدًا. انسخ رابط الطلب كاملًا دون أي نص إضافي حوله.",
        "e_no_srv": "لم يقبل الخادم رقم التتبع — الصق رابط الطلب بدلًا منه.",
        "e_conn": "لا يوجد اتصال. تحقّق من الإنترنت وحاول مرة أخرى.",
        "e_failed": "تعذّر ذلك",
        "e_auth": "سجّل الدخول لرؤية التوصيل",
        "retry": "إعادة المحاولة",
        "ya_failed": "لم تجد ياندكس مندوبًا أو أُلغي الطلب.",
        "yastat_new": "جارٍ إنشاء الطلب…",
        "yastat_est": "جارٍ حساب التكلفة…",
        "yastat_ready": "جاهز للتأكيد",
        "yastat_accepted": "تم قبول الطلب",
        "yastat_lookup": "نبحث عن مندوب…",
        "yastat_found": "تم تعيين مندوب — في طريقه لاستلام السلعة",
        "yastat_atseller": "المندوب عند البائع",
        "yastat_picked": "استلم المندوب السلعة — في طريقه إلى المشتري",
        "yastat_atbuyer": "المندوب عند المشتري",
        "yastat_handed": "تم التسليم",
        "yastat_delivered": "تم التوصيل",
        "yastat_returning": "إرجاع إلى البائع",
        "yastat_atseller_ret": "المندوب عند البائع (إرجاع)",
        "yastat_returned_seller": "أُعيدت إلى البائع",
        "yastat_returned": "أُعيدت",
        "yastat_cancelled": "أُلغي الطلب",
        "yastat_cancelled_taxi": "ألغته الخدمة",
        "yastat_nocourier": "لم يُعثر على مندوب"
    ]
}
