import Foundation

/**
 Тексты переноса объявлений (этап 50) на языке телефона (kk/ru/en/ar).

 Русские — слово в слово с сайта: словарь js/i18n-cabinet-ru.js (imp_*, aii_*, ai_out_*, ai_ended_*) и фразы, зашитые в
 код: js/cabinet-aiimport.min.js (_impСпособы, _impProPane, _aiParseSingle, _aiJobDrive, _aiJobPhotos, _aiJobFail,
 aiJobCheck, aiJobDrop, _aiRowHTML, aiRenderRows, aiPublish) и js/cabinet.min.js (_liOneHtml, _liMassHtml, liGo,
 liMassGo, _liProgOpen). <b> и &nbsp; сайта — обычным текстом. Свои слова приложения — экран итога («Черновики
 готовы», «Проверить и опубликовать», «Открыть «Мои объявления»»), кнопки выбора фото и файла и VoiceOver.
 */
enum ИмпортText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    static func т(_ ключ: String, _ замены: [String: String]) -> String {
        var итог = т(ключ)
        for (имя, значение) in замены {
            итог = итог.replacingOccurrences(of: "{" + имя + "}", with: значение)
        }
        return итог
    }

    static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    // MARK: - Русский (сайт)

    private static let ru: [String: String] = [
        "imp_t": "Перенести объявления",
        "imp_sub": "Уже продаёте где-то ещё? Принесите как есть — ссылкой, прайсом или фотографиями. Карточки заполним сами.",
        "imp_q": "Что у вас есть?",
        "src_link_t": "Ссылка на объявление",
        "src_link_s": "Одно объявление с другой площадки",
        "src_free": "бесплатно",
        "src_many_t": "Список ссылок",
        "src_many_s": "До 20 объявлений за один заход",
        "src_many_free": "5 бесплатно",
        "src_in_tariff": "входит в тариф",
        "src_cat_t": "Прайс, таблица или фото",
        "src_cat_s": "Каталогом — распознаёт Kliko AI",
        "src_pro": "PRO",
        "imp_s1": "Переносим",
        "imp_s1s": "Читаем объявление и заполняем карточку",
        "imp_s2": "Вы проверяете",
        "imp_s2s": "Цена, город и состояние — ваше слово",
        "imp_s3": "Публикуете",
        "imp_s3s": "Только после этого объявление выходит на витрину",
        "imp_draft": "Всё перенесённое ложится черновиками в «Неактивные». На витрину ничего не уйдёт, пока вы не нажмёте «Опубликовать».",
        // Одна ссылка
        "li_q": "Ссылка на ваше объявление",
        "li_sub": "Заполним форму за вас — останется проверить цену и опубликовать.",
        "li_ph": "https://www.olx.kz/d/obyavlenie/...",
        "paste": "Вставить",
        "li_own": "Это моё объявление, я его разместил",
        "li_go": "Перенести",
        "li_note": "Работает с olx.kz, krisha.kz и kolesa.kz",
        "li_need_own": "Отметьте, что объявление ваше",
        "li_need_url": "Вставьте ссылку на объявление",
        "li_bad_host": "Работает с olx.kz, krisha.kz и kolesa.kz — проверьте ссылку",
        "lip_t": "Переносим объявление",
        "lip_open": "Открываем страницу объявления…",
        "lip_parse": "Разбираем поля объявления",
        "lip_photo": "фото {i} из {n}",
        "lip_done": "Готово",
        "li_fail": "Не удалось прочитать объявление",
        // Список ссылок
        "lm_q": "Список ссылок",
        "lm_sub": "По одной ссылке в строке. Каждое объявление ляжет черновиком в «Неактивные» — проверите цену и опубликуете.",
        "lm_free": "Бесплатно — до 5 ссылок за раз.",
        "lm_own": "Это мои объявления, я их размещал",
        "lm_go": "Перенести все",
        "lm_go_n": "Перенести все ({n})",
        "lm_cnt": "Ссылок: {n}",
        "lm_foreign": " · не наших площадок: {n}",
        "lm_max": "За один раз — до 20 ссылок. Остальные перенесите следующим заходом",
        "lm_free_max": "Бесплатно — до 5 ссылок за раз. Больше переносит тариф PRO",
        "lm_need_own": "Отметьте, что объявления ваши",
        "lm_need": "Вставьте ссылки — по одной в строке",
        "lm_item": "Объявление {i} из {n} · {site}",
        "lm_none": "Ни одно объявление не удалось прочитать. Проверьте ссылки",
        "lm_unread": "Не прочитано: {n}",
        // Каталог
        "pro_t": "Каталогом переносит Kliko AI",
        "pro_s": "Читает прайс, таблицу, снимок листа с ценами или фотографии товаров и заводит карточки пачкой — с названием, ценой и разделом. Это работа тарифа PRO.",
        "pro_alt": "Пока перенесу по ссылке",
        "howto": "Как проще всего: скопируйте прайс из Excel или WhatsApp и вставьте в поле ниже. Не нужно ничего форматировать — годится «название — цена» в строчку, таблица со столбцами или сплошной текст. Не текстом? Сфотографируйте прайс или загрузите файл кнопками ниже.",
        "text_ph": "Вставьте прайс как есть. Например:\niPhone 13 128ГБ чёрный, б/у — 350000\nКуртка Nike зимняя, размер L — 45000\nДиван угловой серый, эко-кожа — 180000",
        "or_upload": "или загрузите",
        "src_file": "Файл или таблица",
        "src_file_none": "CSV / Excel / TXT · не выбран",
        "src_img": "Фото прайса",
        "src_img_hint": "Kliko AI распознает с картинки",
        "src_photos": "Фото товаров",
        "src_photos_hint": "по порядку · необязательно",
        "parse": "Разобрать через Kliko AI",
        "aii_photo_big": "Фото больше 10 МБ",
        "aii_uploading": "загрузка…",
        "aii_prohibited": "запрещённый контент",
        "aii_photo_fail": "не удалось загрузить фото",
        "aii_uploading_n": "загрузка {i}/{n}…",
        "aii_photos_done": "{n} фото загружено",
        "aii_reading": "читаю файл…",
        "aii_file_read": "Файл прочитан — жмите «Разобрать через Kliko AI»",
        "aii_file_fail": "Не удалось прочитать файл",
        "aii_file_big": "Файл больше 15 МБ",
        "need_input": "Вставьте данные, файл или фото прайса",
        // Ход разбора
        "prog_t": "Kliko AI разбирает прайс",
        "prog_single": "анализирую ваш прайс",
        "prog_part": "часть {i} из {n} · уже {k}",
        "prog_upload": "загружаю прайс: {c} из {n} строк",
        "prog_read": "прочитано {p}% прайса",
        "prog_photos": "фото по ссылкам: {a} из {t}",
        "prog_got": " · загружено {g}",
        "prog_done": "Готово — распознано товаров",
        "prog_done_s": "проверьте строки и опубликуйте",
        "prog_found": "Найдено: {n}",
        "no_rows": "Не удалось выделить товары — проверьте данные",
        "job_fallback": "Не удалось открыть задание — разбираю обычным способом",
        "job_upload_fail": "Связь оборвалась при загрузке прайса — попробуйте ещё раз",
        "paused_t": "Связь оборвалась",
        "paused_s": "Распознанное сохранено на сервере — продолжим с той же части",
        "resume_from": "Продолжить с {n}-й позиции",
        // Отказы (_aiJobFail)
        "e_csrf": "Сессия истекла — войдите заново. Распознанное сохранено.",
        "e_auth": "Вы вышли из аккаунта — войдите заново. Распознанное сохранено.",
        "e_gone": "Задание не найдено — запустите разбор заново",
        "e_ai_off": "Kliko AI временно недоступен",
        "e_prefix": "Ошибка: ",
        "e_fail": "не удалось",
        "lim_t": "Достигнут лимит",
        "lim_s": "Лимит объявлений достигнут.",
        "lim_verify": "Пройти верификацию (+5)",
        "lim_slots": "Расширить слоты",
        "later": "Позже",
        "ai_out_t": "Лимит Kliko AI исчерпан",
        "ai_out_d": "Оформите пакет ниже — Kliko AI-разборы станут безлимитными на выбранный срок.",
        "ai_ended_t": "Бесплатные Kliko AI-разборы закончились",
        "ai_ended_d": "Пройдите верификацию — лимит вырастет до 50 в месяц. Или оформите пакет ниже для безлимита.",
        "verify": "Пройти верификацию",
        "no_digital": "Эта возможность недоступна в приложении.",
        "on_site": "Открыть в кабинете на сайте",
        // Незаконченный разбор (aiJobCheck, aiJobDrop)
        "unf_t": "Незаконченный разбор",
        "unf_s": "Найдено {n} товаров, прочитано {p}% прайса. Продолжим с того же места — платить заново не нужно.",
        "unf_go": "Продолжить",
        "unf_drop": "Начать заново",
        "unf_drop_q": "Начать заново?",
        "unf_drop_s": "Распознанные строки этого прогона будут удалены, и Kliko AI придётся запускать сначала.",
        // Проверка строк (aiRenderRows, _aiRowHTML)
        "rv_n": "Распознано {n}",
        "rv_sum": "на сумму {s} · черновики уйдут в «Неактивные» и пройдут модерацию",
        "rv_ai": "Kliko AI",
        "rv_ai_left": "Kliko AI · осталось {n}",
        "rv_local": "локальный парсер",
        "rv_link": "по ссылке",
        "rv_redo": "Заново",
        "rv_all": "Выбрать все",
        "rv_sel": "Выбрано {n} из {l}",
        "rv_sel_sum": " · на {s}",
        "rv_hint": "Снимите галочку у строк, которые не нужно публиковать. Пустая цена или название — товар пропустится.",
        "rv_pub": "Добавить в «Неактивные»",
        "rv_adding": "Добавляем… {a} из {n}",
        "rv_title": "Название",
        "rv_brand": "Бренд",
        "rv_price": "Цена",
        "rv_cat": "Категория",
        "rv_ok": "готово",
        "rv_warn": "добавьте цену",
        "used": "Б/у",
        "new": "Новый",
        "rv_more": "Характеристики и описание",
        "rv_desc": "Описание (Kliko AI добавит плюсы товара)",
        "rv_del": "Убрать строку",
        "rv_pick": "Публиковать эту строку",
        "cat_other": "Другое",
        "spec_cpu": "Процессор",
        "spec_gpu": "Видеокарта",
        "spec_ram": "ОЗУ",
        "spec_storage": "Накопитель",
        "spec_year": "Год выпуска",
        "no_sel": "Нет строк",
        // Публикация (aiPublish, liMassGo)
        "pub_net": "Связь оборвалась на {r}-й строке. Добавлено: {n}. Нажмите «Продолжить» — оставшееся дозаведём.",
        "pub_continue": "Продолжить добавление",
        "pub_ok": "Импортировано в «Неактивные»: {n}",
        "pub_skipped": "Пропущено {n}",
        "sk_title": "{n} без названия",
        "sk_banned": "{n} запрещённый контент",
        "sk_cap": "{n} сверх лимита",
        "pub_after": "Откройте раздел, добавьте цену где нужно и активируйте — они пройдут модерацию.",
        "li_pub_ok": "Перенесено: {n} — в «Неактивных»",
        "pub_fail": "Не удалось создать черновики",
        "pub_pro": "Перенос каталогом — в тарифе PRO",
        // Итог (свои слова приложения)
        "done_t": "Черновики готовы",
        "drafts": "Черновики",
        "edit": "Проверить и опубликовать",
        "open_items": "Открыть «Мои объявления»",
        "more_import": "Перенести ещё",
        "close": "Закрыть",
        "cancel": "Отмена",
        "retry": "Повторить",
        "no_conn": "Нет соединения",
        "err_generic": "Ошибка",
        "pick_photos": "Выбрать фото",
        "pick_file": "Выбрать файл",
        "remove": "Убрать",
        "a11y_selected": "выбрано",
        // Пример (aiDemoFill, aiPublish при _aiDemoMode)
        "imp_demo": "Показать на примере",
        "demo_prog_t": "Распознаю товары…",
        "demo_prog_n": "распознано {i} из {n}",
        "demo_pub": "Это демонстрация — черновики не создаются. В реальном импорте товары уйдут в «Неактивные».",
        // Фото строки (_aiPhotoCellHTML, _aiOpenPhotoPicker, _aiPickGridHTML, aiRowPhotoUpload)
        "ph_t": "Фото товара",
        "ph_up": "Загрузить",
        "ph_done": "Готово",
        "ph_sub": "Загрузите фото с устройства или выберите из уже загруженных — привяжется к товару.",
        "ph_empty": "Загруженных фото пока нет.\nНажмите «Загрузить» — снимок привяжется к товару.",
        "ph_max": "Не больше 8 фото на товар",
        "ph_loading": "Загружаю фото…",
        "ph_added": "Фото добавлено",
        "ph_del": "Убрать",
        "ph_add": "Добавить фото",
        "ph_this": "У этого товара · {n} из {m}",
        "ph_pool": "Загруженные",
        "ph_owner": "№{n}",
        "ph_owner_a11y": "уже у товара №{n}",
        "ph_prog": "{i} из {n}",
    ]

    // MARK: - Қазақша

    private static let kk: [String: String] = [
        "imp_t": "Хабарландыруларды көшіру",
        "imp_sub": "Басқа жерде сатып жүрсіз бе? Барын әкеліңіз — сілтемемен, прайспен немесе фотолармен. Карточкаларды өзіміз толтырамыз.",
        "imp_q": "Сізде не бар?",
        "src_link_t": "Хабарландыру сілтемесі",
        "src_link_s": "Басқа алаңнан бір хабарландыру",
        "src_free": "тегін",
        "src_many_t": "Сілтемелер тізімі",
        "src_many_s": "Бір кіруде 20 хабарландыруға дейін",
        "src_many_free": "5 тегін",
        "src_in_tariff": "тарифке кіреді",
        "src_cat_t": "Прайс, кесте немесе фото",
        "src_cat_s": "Каталогпен — Kliko AI таниды",
        "src_pro": "PRO",
        "imp_s1": "Көшіреміз",
        "imp_s1s": "Хабарландыруды оқып, карточканы толтырамыз",
        "imp_s2": "Сіз тексересіз",
        "imp_s2s": "Баға, қала және күйі — сіздің сөзіңіз",
        "imp_s3": "Жариялайсыз",
        "imp_s3s": "Содан кейін ғана хабарландыру витринаға шығады",
        "imp_draft": "Көшірілгеннің бәрі «Белсенді емес» бөліміне жоба болып түседі. «Жариялау» баспайынша витринаға ештеңе шықпайды.",
        "li_q": "Хабарландыруыңыздың сілтемесі",
        "li_sub": "Форманы сіз үшін толтырамыз — бағаны тексеріп, жариялау ғана қалады.",
        "paste": "Қою",
        "li_own": "Бұл менің хабарландыруым, мен орналастырдым",
        "li_go": "Көшіру",
        "li_note": "olx.kz, krisha.kz және kolesa.kz сайттарымен жұмыс істейді",
        "li_need_own": "Хабарландыру сіздікі екенін белгілеңіз",
        "li_need_url": "Хабарландыру сілтемесін қойыңыз",
        "li_bad_host": "olx.kz, krisha.kz және kolesa.kz сайттарымен жұмыс істейді — сілтемені тексеріңіз",
        "lip_t": "Хабарландыруды көшіріп жатырмыз",
        "lip_open": "Хабарландыру бетін ашып жатырмыз…",
        "lip_parse": "Хабарландыру өрістерін талдап жатырмыз",
        "lip_photo": "фото {i} / {n}",
        "lip_done": "Дайын",
        "li_fail": "Хабарландыруды оқу мүмкін болмады",
        "lm_q": "Сілтемелер тізімі",
        "lm_sub": "Әр жолға бір сілтеме. Әр хабарландыру «Белсенді емес» бөліміне жоба болып түседі — бағаны тексеріп, жариялайсыз.",
        "lm_free": "Тегін — бір рет 5 сілтемеге дейін.",
        "lm_own": "Бұлар менің хабарландыруларым, мен орналастырдым",
        "lm_go": "Барлығын көшіру",
        "lm_go_n": "Барлығын көшіру ({n})",
        "lm_cnt": "Сілтемелер: {n}",
        "lm_foreign": " · біздің алаң емес: {n}",
        "lm_max": "Бір рет — 20 сілтемеге дейін. Қалғанын келесі жолы көшіріңіз",
        "lm_free_max": "Тегін — бір рет 5 сілтемеге дейін. Көбін PRO тарифі көшіреді",
        "lm_need_own": "Хабарландырулар сіздікі екенін белгілеңіз",
        "lm_need": "Сілтемелерді қойыңыз — әр жолға біреуден",
        "lm_item": "Хабарландыру {i} / {n} · {site}",
        "lm_none": "Бірде-бір хабарландыруды оқу мүмкін болмады. Сілтемелерді тексеріңіз",
        "lm_unread": "Оқылмады: {n}",
        "pro_t": "Каталогпен Kliko AI көшіреді",
        "pro_s": "Прайсты, кестені, бағалар парағының суретін немесе тауар фотоларын оқиды да, карточкаларды топтап жасайды — атауымен, бағасымен және бөлімімен. Бұл — PRO тарифінің жұмысы.",
        "pro_alt": "Әзірге сілтемемен көшіремін",
        "howto": "Ең оңайы: прайсты Excel немесе WhatsApp-тан көшіріп, төмендегі өріске қойыңыз. Ештеңені пішімдеудің қажеті жоқ — жолдағы «атауы — бағасы», бағандары бар кесте немесе тұтас мәтін жарайды. Мәтін емес пе? Прайсты суретке түсіріңіз немесе файлды төмендегі батырмалармен жүктеңіз.",
        "text_ph": "Прайсты сол күйінде қойыңыз. Мысалы:\niPhone 13 128ГБ қара, қолданылған — 350000\nNike қысқы күртеше, L өлшемі — 45000",
        "or_upload": "немесе жүктеңіз",
        "src_file": "Файл немесе кесте",
        "src_file_none": "CSV / Excel / TXT · таңдалмаған",
        "src_img": "Прайс фотосы",
        "src_img_hint": "Kliko AI суреттен таниды",
        "src_photos": "Тауар фотолары",
        "src_photos_hint": "ретімен · міндетті емес",
        "parse": "Kliko AI арқылы талдау",
        "aii_photo_big": "Фото 10 МБ-тан үлкен",
        "aii_uploading": "жүктелуде…",
        "aii_prohibited": "тыйым салынған мазмұн",
        "aii_photo_fail": "фотоны жүктеу мүмкін болмады",
        "aii_uploading_n": "жүктелуде {i}/{n}…",
        "aii_photos_done": "{n} фото жүктелді",
        "aii_reading": "файлды оқып жатырмын…",
        "aii_file_read": "Файл оқылды — «Kliko AI арқылы талдау» басыңыз",
        "aii_file_fail": "Файлды оқу мүмкін болмады",
        "aii_file_big": "Файл 15 МБ-тан үлкен",
        "need_input": "Деректерді, файлды немесе прайс фотосын қойыңыз",
        "prog_t": "Kliko AI прайсты талдап жатыр",
        "prog_single": "прайсыңызды талдап жатырмын",
        "prog_part": "бөлік {i} / {n} · қазір {k}",
        "prog_upload": "прайсты жүктеп жатырмын: {c} / {n} жол",
        "prog_read": "прайстың {p}% оқылды",
        "prog_photos": "сілтемедегі фотолар: {a} / {t}",
        "prog_got": " · жүктелді {g}",
        "prog_done": "Дайын — тауарлар танылды",
        "prog_done_s": "жолдарды тексеріп, жариялаңыз",
        "prog_found": "Табылды: {n}",
        "no_rows": "Тауарларды бөліп алу мүмкін болмады — деректерді тексеріңіз",
        "job_fallback": "Тапсырманы ашу мүмкін болмады — әдеттегідей талдаймын",
        "job_upload_fail": "Прайсты жүктеу кезінде байланыс үзілді — қайта көріңіз",
        "paused_t": "Байланыс үзілді",
        "paused_s": "Танылғаны серверде сақталды — сол бөліктен жалғастырамыз",
        "resume_from": "{n}-позициядан жалғастыру",
        "e_csrf": "Сессия аяқталды — қайта кіріңіз. Танылғаны сақталды.",
        "e_auth": "Сіз аккаунттан шықтыңыз — қайта кіріңіз. Танылғаны сақталды.",
        "e_gone": "Тапсырма табылмады — талдауды қайта бастаңыз",
        "e_ai_off": "Kliko AI уақытша қолжетімсіз",
        "e_prefix": "Қате: ",
        "e_fail": "мүмкін болмады",
        "lim_t": "Шекке жеттіңіз",
        "lim_s": "Хабарландыру шегіне жеттіңіз.",
        "lim_verify": "Верификациядан өту (+5)",
        "lim_slots": "Слоттарды кеңейту",
        "later": "Кейінірек",
        "ai_out_t": "Kliko AI шегі таусылды",
        "ai_out_d": "Төмендегі пакетті рәсімдеңіз — Kliko AI талдаулары таңдалған мерзімге шексіз болады.",
        "ai_ended_t": "Тегін Kliko AI талдаулары бітті",
        "ai_ended_d": "Верификациядан өтіңіз — шек айына 50-ге дейін өседі. Немесе шексіз үшін төмендегі пакетті рәсімдеңіз.",
        "verify": "Верификациядан өту",
        "no_digital": "Бұл мүмкіндік қосымшада қолжетімсіз.",
        "on_site": "Сайттағы кабинетте ашу",
        "unf_t": "Аяқталмаған талдау",
        "unf_s": "{n} тауар табылды, прайстың {p}% оқылды. Сол жерден жалғастырамыз — қайта төлеудің қажеті жоқ.",
        "unf_go": "Жалғастыру",
        "unf_drop": "Қайта бастау",
        "unf_drop_q": "Қайта бастау керек пе?",
        "unf_drop_s": "Осы талдаудың танылған жолдары жойылады, Kliko AI-ды басынан іске қосу керек болады.",
        "rv_n": "Танылды: {n}",
        "rv_sum": "сомасы {s} · жобалар «Белсенді емес» бөліміне түсіп, модерациядан өтеді",
        "rv_ai": "Kliko AI",
        "rv_ai_left": "Kliko AI · қалды {n}",
        "rv_local": "жергілікті талдағыш",
        "rv_link": "сілтеме бойынша",
        "rv_redo": "Қайтадан",
        "rv_all": "Барлығын таңдау",
        "rv_sel": "Таңдалды {n} / {l}",
        "rv_sel_sum": " · {s}",
        "rv_hint": "Жариялаудың қажеті жоқ жолдардың белгісін алыңыз. Бағасы немесе атауы бос тауар өткізіліп жіберіледі.",
        "rv_pub": "«Белсенді емес» бөліміне қосу",
        "rv_adding": "Қосып жатырмыз… {a} / {n}",
        "rv_title": "Атауы",
        "rv_brand": "Бренд",
        "rv_price": "Баға",
        "rv_cat": "Санат",
        "rv_ok": "дайын",
        "rv_warn": "бағаны қосыңыз",
        "used": "Қолданылған",
        "new": "Жаңа",
        "rv_more": "Сипаттамалар мен сипаттама",
        "rv_desc": "Сипаттама (Kliko AI тауардың артықшылықтарын қосады)",
        "rv_del": "Жолды алып тастау",
        "rv_pick": "Осы жолды жариялау",
        "cat_other": "Басқа",
        "spec_cpu": "Процессор",
        "spec_gpu": "Бейнекарта",
        "spec_ram": "Жедел жад",
        "spec_storage": "Жинақтағыш",
        "spec_year": "Шығарылған жылы",
        "no_sel": "Жолдар жоқ",
        "pub_net": "{r}-жолда байланыс үзілді. Қосылды: {n}. «Жалғастыру» басыңыз — қалғанын қосамыз.",
        "pub_continue": "Қосуды жалғастыру",
        "pub_ok": "«Белсенді емес» бөліміне импортталды: {n}",
        "pub_skipped": "Өткізілді {n}",
        "sk_title": "{n} атаусыз",
        "sk_banned": "{n} тыйым салынған мазмұн",
        "sk_cap": "{n} шектен тыс",
        "pub_after": "Бөлімді ашып, қажет жерге баға қосып, белсендіріңіз — олар модерациядан өтеді.",
        "li_pub_ok": "Көшірілді: {n} — «Белсенді емес» бөлімінде",
        "pub_fail": "Жобаларды жасау мүмкін болмады",
        "pub_pro": "Каталогпен көшіру — PRO тарифінде",
        "done_t": "Жобалар дайын",
        "drafts": "Жобалар",
        "edit": "Тексеріп, жариялау",
        "open_items": "«Менің хабарландыруларымды» ашу",
        "more_import": "Тағы көшіру",
        "close": "Жабу",
        "cancel": "Бас тарту",
        "retry": "Қайталау",
        "no_conn": "Байланыс жоқ",
        "err_generic": "Қате",
        "pick_photos": "Фото таңдау",
        "pick_file": "Файл таңдау",
        "remove": "Алып тастау",
        "a11y_selected": "таңдалды",
        "imp_demo": "Мысалмен көрсету",
        "demo_prog_t": "Тауарларды танып жатырмын…",
        "demo_prog_n": "{n} ішінен {i} танылды",
        "demo_pub": "Бұл — көрсетілім, жобалар жасалмайды. Нақты импортта тауарлар «Белсенді емес» бөліміне түседі.",
        "ph_t": "Тауар фотосы",
        "ph_up": "Жүктеу",
        "ph_done": "Дайын",
        "ph_sub": "Фотоны құрылғыдан жүктеңіз немесе бұрын жүктелгендерден таңдаңыз — тауарға бекітіледі.",
        "ph_empty": "Жүктелген фото әзірге жоқ.\n«Жүктеу» түймесін басыңыз — сурет тауарға бекітіледі.",
        "ph_max": "Бір тауарға 8 фотодан артық емес",
        "ph_loading": "Фото жүктеліп жатыр…",
        "ph_added": "Фото қосылды",
        "ph_del": "Алып тастау",
        "ph_add": "Фото қосу",
        "ph_this": "Осы тауарда · {m} ішінен {n}",
        "ph_pool": "Жүктелгендер",
        "ph_owner": "№{n}",
        "ph_owner_a11y": "№{n} тауарда бар",
        "ph_prog": "{n} ішінен {i}",
    ]

    // MARK: - English

    private static let en: [String: String] = [
        "imp_t": "Import listings",
        "imp_sub": "Already selling elsewhere? Bring it as is — a link, a price list or photos. We'll fill in the cards.",
        "imp_q": "What do you have?",
        "src_link_t": "Listing link",
        "src_link_s": "One listing from another marketplace",
        "src_free": "free",
        "src_many_t": "List of links",
        "src_many_s": "Up to 20 listings at a time",
        "src_many_free": "5 free",
        "src_in_tariff": "included in plan",
        "src_cat_t": "Price list, table or photo",
        "src_cat_s": "As a catalog — recognized by Kliko AI",
        "src_pro": "PRO",
        "imp_s1": "We import",
        "imp_s1s": "We read the listing and fill in the card",
        "imp_s2": "You review",
        "imp_s2s": "Price, city and condition are up to you",
        "imp_s3": "You publish",
        "imp_s3s": "Only then does the listing go live",
        "imp_draft": "Everything imported lands as drafts in “Inactive”. Nothing goes live until you tap “Publish”.",
        "li_q": "Link to your listing",
        "li_sub": "We'll fill in the form for you — you just check the price and publish.",
        "paste": "Paste",
        "li_own": "This is my listing, I posted it",
        "li_go": "Import",
        "li_note": "Works with olx.kz, krisha.kz and kolesa.kz",
        "li_need_own": "Confirm that the listing is yours",
        "li_need_url": "Paste the listing link",
        "li_bad_host": "Works with olx.kz, krisha.kz and kolesa.kz — check the link",
        "lip_t": "Importing the listing",
        "lip_open": "Opening the listing page…",
        "lip_parse": "Reading the listing fields",
        "lip_photo": "photo {i} of {n}",
        "lip_done": "Done",
        "li_fail": "Couldn't read the listing",
        "lm_q": "List of links",
        "lm_sub": "One link per line. Each listing lands as a draft in “Inactive” — check the price and publish.",
        "lm_free": "Free — up to 5 links at a time.",
        "lm_own": "These are my listings, I posted them",
        "lm_go": "Import all",
        "lm_go_n": "Import all ({n})",
        "lm_cnt": "Links: {n}",
        "lm_foreign": " · other sites: {n}",
        "lm_max": "Up to 20 links at a time. Import the rest next time",
        "lm_free_max": "Free — up to 5 links at a time. The PRO plan imports more",
        "lm_need_own": "Confirm that the listings are yours",
        "lm_need": "Paste links — one per line",
        "lm_item": "Listing {i} of {n} · {site}",
        "lm_none": "Couldn't read any of the listings. Check the links",
        "lm_unread": "Not read: {n}",
        "pro_t": "Kliko AI imports whole catalogs",
        "pro_s": "It reads a price list, a table, a photo of a price sheet or product photos and creates cards in bulk — with title, price and section. This is a PRO plan feature.",
        "pro_alt": "Import by link for now",
        "howto": "The easiest way: copy your price list from Excel or WhatsApp and paste it below. No formatting needed — “name — price” per line, a table with columns or plain text all work. Not text? Photograph the price list or upload a file with the buttons below.",
        "text_ph": "Paste your price list as is. For example:\niPhone 13 128GB black, used — 350000\nNike winter jacket, size L — 45000",
        "or_upload": "or upload",
        "src_file": "File or table",
        "src_file_none": "CSV / Excel / TXT · none selected",
        "src_img": "Price list photo",
        "src_img_hint": "Kliko AI reads it from the picture",
        "src_photos": "Product photos",
        "src_photos_hint": "in order · optional",
        "parse": "Parse with Kliko AI",
        "aii_photo_big": "Photo is larger than 10 MB",
        "aii_uploading": "uploading…",
        "aii_prohibited": "prohibited content",
        "aii_photo_fail": "couldn't upload the photo",
        "aii_uploading_n": "uploading {i}/{n}…",
        "aii_photos_done": "{n} photos uploaded",
        "aii_reading": "reading the file…",
        "aii_file_read": "File read — tap “Parse with Kliko AI”",
        "aii_file_fail": "Couldn't read the file",
        "aii_file_big": "File is larger than 15 MB",
        "need_input": "Paste data, a file or a price list photo",
        "prog_t": "Kliko AI is reading the price list",
        "prog_single": "analyzing your price list",
        "prog_part": "part {i} of {n} · {k} so far",
        "prog_upload": "uploading the price list: {c} of {n} lines",
        "prog_read": "{p}% of the price list read",
        "prog_photos": "photos from links: {a} of {t}",
        "prog_got": " · uploaded {g}",
        "prog_done": "Done — products recognized",
        "prog_done_s": "check the rows and publish",
        "prog_found": "Found: {n}",
        "no_rows": "Couldn't find products — check the data",
        "job_fallback": "Couldn't open a job — parsing the usual way",
        "job_upload_fail": "Connection lost while uploading the price list — try again",
        "paused_t": "Connection lost",
        "paused_s": "What was recognized is saved on the server — we'll continue from the same part",
        "resume_from": "Continue from item {n}",
        "e_csrf": "Session expired — sign in again. Recognized rows are saved.",
        "e_auth": "You signed out — sign in again. Recognized rows are saved.",
        "e_gone": "Job not found — start parsing again",
        "e_ai_off": "Kliko AI is temporarily unavailable",
        "e_prefix": "Error: ",
        "e_fail": "failed",
        "lim_t": "Limit reached",
        "lim_s": "Listing limit reached.",
        "lim_verify": "Get verified (+5)",
        "lim_slots": "Add slots",
        "later": "Later",
        "ai_out_t": "Kliko AI limit used up",
        "ai_out_d": "Get a package below — Kliko AI parsing becomes unlimited for the chosen period.",
        "ai_ended_t": "Free Kliko AI parses are used up",
        "ai_ended_d": "Get verified — the limit grows to 50 a month. Or get a package below for unlimited use.",
        "verify": "Get verified",
        "no_digital": "This feature isn't available in the app.",
        "on_site": "Open in the cabinet on the website",
        "unf_t": "Unfinished parsing",
        "unf_s": "Found {n} products, {p}% of the price list read. We'll continue from the same place — no need to pay again.",
        "unf_go": "Continue",
        "unf_drop": "Start over",
        "unf_drop_q": "Start over?",
        "unf_drop_s": "Rows recognized in this run will be deleted and Kliko AI will have to start from the beginning.",
        "rv_n": "Recognized {n}",
        "rv_sum": "worth {s} · drafts go to “Inactive” and pass moderation",
        "rv_ai": "Kliko AI",
        "rv_ai_left": "Kliko AI · {n} left",
        "rv_local": "local parser",
        "rv_link": "by link",
        "rv_redo": "Start over",
        "rv_all": "Select all",
        "rv_sel": "Selected {n} of {l}",
        "rv_sel_sum": " · {s}",
        "rv_hint": "Untick rows you don't want to publish. Items with an empty price or title are skipped.",
        "rv_pub": "Add to “Inactive”",
        "rv_adding": "Adding… {a} of {n}",
        "rv_title": "Title",
        "rv_brand": "Brand",
        "rv_price": "Price",
        "rv_cat": "Category",
        "rv_ok": "ready",
        "rv_warn": "add a price",
        "used": "Used",
        "new": "New",
        "rv_more": "Specs and description",
        "rv_desc": "Description (Kliko AI will add the product's strengths)",
        "rv_del": "Remove row",
        "rv_pick": "Publish this row",
        "cat_other": "Other",
        "spec_cpu": "Processor",
        "spec_gpu": "Graphics card",
        "spec_ram": "RAM",
        "spec_storage": "Storage",
        "spec_year": "Year",
        "no_sel": "No rows",
        "pub_net": "Connection lost at row {r}. Added: {n}. Tap “Continue” — we'll add the rest.",
        "pub_continue": "Continue adding",
        "pub_ok": "Imported to “Inactive”: {n}",
        "pub_skipped": "Skipped {n}",
        "sk_title": "{n} without a title",
        "sk_banned": "{n} prohibited content",
        "sk_cap": "{n} over the limit",
        "pub_after": "Open the section, add prices where needed and activate — they'll pass moderation.",
        "li_pub_ok": "Imported: {n} — in “Inactive”",
        "pub_fail": "Couldn't create drafts",
        "pub_pro": "Catalog import is on the PRO plan",
        "done_t": "Drafts are ready",
        "drafts": "Drafts",
        "edit": "Review and publish",
        "open_items": "Open “My listings”",
        "more_import": "Import more",
        "close": "Close",
        "cancel": "Cancel",
        "retry": "Retry",
        "no_conn": "No connection",
        "err_generic": "Error",
        "pick_photos": "Choose photos",
        "pick_file": "Choose file",
        "remove": "Remove",
        "a11y_selected": "selected",
        "imp_demo": "Show an example",
        "demo_prog_t": "Recognizing products…",
        "demo_prog_n": "recognized {i} of {n}",
        "demo_pub": "This is a demo — no drafts are created. In a real import the products go to “Inactive”.",
        "ph_t": "Product photos",
        "ph_up": "Upload",
        "ph_done": "Done",
        "ph_sub": "Upload photos from your device or pick from the ones already uploaded — they will be attached to the product.",
        "ph_empty": "No uploaded photos yet.\nTap “Upload” — the photo will be attached to the product.",
        "ph_max": "No more than 8 photos per product",
        "ph_loading": "Uploading photos…",
        "ph_added": "Photo added",
        "ph_del": "Remove",
        "ph_add": "Add photo",
        "ph_this": "This product · {n} of {m}",
        "ph_pool": "Uploaded",
        "ph_owner": "#{n}",
        "ph_owner_a11y": "already on product #{n}",
        "ph_prog": "{i} of {n}",
    ]

    // MARK: - العربية

    private static let ar: [String: String] = [
        "imp_t": "نقل الإعلانات",
        "imp_sub": "تبيع في مكان آخر؟ أحضر ما لديك كما هو — رابطًا أو قائمة أسعار أو صورًا. سنملأ البطاقات بأنفسنا.",
        "imp_q": "ماذا لديك؟",
        "src_link_t": "رابط إعلان",
        "src_link_s": "إعلان واحد من منصة أخرى",
        "src_free": "مجانًا",
        "src_many_t": "قائمة روابط",
        "src_many_s": "حتى 20 إعلانًا في المرة",
        "src_many_free": "5 مجانًا",
        "src_in_tariff": "ضمن الباقة",
        "src_cat_t": "قائمة أسعار أو جدول أو صورة",
        "src_cat_s": "ككتالوج — يتعرّف عليه Kliko AI",
        "src_pro": "PRO",
        "imp_s1": "ننقل",
        "imp_s1s": "نقرأ الإعلان ونملأ البطاقة",
        "imp_s2": "تراجع أنت",
        "imp_s2s": "السعر والمدينة والحالة — قرارك",
        "imp_s3": "تنشر",
        "imp_s3s": "بعدها فقط يظهر الإعلان في الواجهة",
        "imp_draft": "كل ما يُنقل يصبح مسودات في «غير النشطة». لن يظهر شيء في الواجهة حتى تضغط «نشر».",
        "li_q": "رابط إعلانك",
        "li_sub": "سنملأ النموذج عنك — يبقى أن تتحقق من السعر وتنشر.",
        "paste": "لصق",
        "li_own": "هذا إعلاني، أنا من نشره",
        "li_go": "نقل",
        "li_note": "يعمل مع olx.kz وkrisha.kz وkolesa.kz",
        "li_need_own": "أكّد أن الإعلان لك",
        "li_need_url": "الصق رابط الإعلان",
        "li_bad_host": "يعمل مع olx.kz وkrisha.kz وkolesa.kz — تحقّق من الرابط",
        "lip_t": "ننقل الإعلان",
        "lip_open": "نفتح صفحة الإعلان…",
        "lip_parse": "نقرأ حقول الإعلان",
        "lip_photo": "الصورة {i} من {n}",
        "lip_done": "تم",
        "li_fail": "تعذّرت قراءة الإعلان",
        "lm_q": "قائمة روابط",
        "lm_sub": "رابط واحد في كل سطر. سيصبح كل إعلان مسودة في «غير النشطة» — تحقّق من السعر وانشر.",
        "lm_free": "مجانًا — حتى 5 روابط في المرة.",
        "lm_own": "هذه إعلاناتي، أنا من نشرها",
        "lm_go": "نقل الكل",
        "lm_go_n": "نقل الكل ({n})",
        "lm_cnt": "الروابط: {n}",
        "lm_foreign": " · من منصات أخرى: {n}",
        "lm_max": "حتى 20 رابطًا في المرة. انقل الباقي في المرة القادمة",
        "lm_free_max": "مجانًا — حتى 5 روابط في المرة. باقة PRO تنقل أكثر",
        "lm_need_own": "أكّد أن الإعلانات لك",
        "lm_need": "الصق الروابط — رابطًا في كل سطر",
        "lm_item": "الإعلان {i} من {n} · {site}",
        "lm_none": "تعذّرت قراءة أي إعلان. تحقّق من الروابط",
        "lm_unread": "لم يُقرأ: {n}",
        "pro_t": "Kliko AI ينقل الكتالوجات كاملة",
        "pro_s": "يقرأ قائمة الأسعار أو الجدول أو صورة ورقة الأسعار أو صور المنتجات وينشئ البطاقات دفعة واحدة — بالاسم والسعر والقسم. هذه ميزة باقة PRO.",
        "pro_alt": "سأنقل بالرابط حاليًا",
        "howto": "الأسهل: انسخ قائمة الأسعار من Excel أو WhatsApp والصقها في الحقل أدناه. لا حاجة لأي تنسيق — «الاسم — السعر» في كل سطر أو جدول بأعمدة أو نص متصل. ليست نصًا؟ صوّر القائمة أو ارفع ملفًا بالأزرار أدناه.",
        "text_ph": "الصق قائمة الأسعار كما هي. مثلاً:\niPhone 13 128GB أسود، مستعمل — 350000\nجاكيت Nike شتوي، مقاس L — 45000",
        "or_upload": "أو ارفع",
        "src_file": "ملف أو جدول",
        "src_file_none": "CSV / Excel / TXT · لم يُختر",
        "src_img": "صورة قائمة الأسعار",
        "src_img_hint": "يقرؤها Kliko AI من الصورة",
        "src_photos": "صور المنتجات",
        "src_photos_hint": "بالترتيب · اختياري",
        "parse": "التحليل عبر Kliko AI",
        "aii_photo_big": "الصورة أكبر من 10 ميغابايت",
        "aii_uploading": "جارٍ الرفع…",
        "aii_prohibited": "محتوى محظور",
        "aii_photo_fail": "تعذّر رفع الصورة",
        "aii_uploading_n": "جارٍ الرفع {i}/{n}…",
        "aii_photos_done": "تم رفع {n} صور",
        "aii_reading": "أقرأ الملف…",
        "aii_file_read": "تمت قراءة الملف — اضغط «التحليل عبر Kliko AI»",
        "aii_file_fail": "تعذّرت قراءة الملف",
        "aii_file_big": "الملف أكبر من 15 ميغابايت",
        "need_input": "الصق البيانات أو ملفًا أو صورة قائمة الأسعار",
        "prog_t": "Kliko AI يحلّل قائمة الأسعار",
        "prog_single": "أحلّل قائمة أسعارك",
        "prog_part": "الجزء {i} من {n} · حتى الآن {k}",
        "prog_upload": "أرفع القائمة: {c} من {n} سطر",
        "prog_read": "قُرئ {p}% من القائمة",
        "prog_photos": "صور من الروابط: {a} من {t}",
        "prog_got": " · رُفع {g}",
        "prog_done": "تم — تم التعرّف على المنتجات",
        "prog_done_s": "راجع الأسطر وانشر",
        "prog_found": "وُجد: {n}",
        "no_rows": "تعذّر استخراج المنتجات — تحقّق من البيانات",
        "job_fallback": "تعذّر فتح مهمة — أحلّل بالطريقة المعتادة",
        "job_upload_fail": "انقطع الاتصال أثناء رفع القائمة — حاول مرة أخرى",
        "paused_t": "انقطع الاتصال",
        "paused_s": "ما تم التعرّف عليه محفوظ على الخادم — سنكمل من الجزء نفسه",
        "resume_from": "المتابعة من العنصر {n}",
        "e_csrf": "انتهت الجلسة — سجّل الدخول مجددًا. ما تم التعرّف عليه محفوظ.",
        "e_auth": "خرجت من الحساب — سجّل الدخول مجددًا. ما تم التعرّف عليه محفوظ.",
        "e_gone": "المهمة غير موجودة — ابدأ التحليل من جديد",
        "e_ai_off": "Kliko AI غير متاح مؤقتًا",
        "e_prefix": "خطأ: ",
        "e_fail": "تعذّر",
        "lim_t": "تم بلوغ الحد",
        "lim_s": "تم بلوغ حد الإعلانات.",
        "lim_verify": "توثيق الحساب (+5)",
        "lim_slots": "توسيع الخانات",
        "later": "لاحقًا",
        "ai_out_t": "نفد حد Kliko AI",
        "ai_out_d": "اشترك في باقة أدناه — تصبح تحليلات Kliko AI غير محدودة للمدة المختارة.",
        "ai_ended_t": "انتهت تحليلات Kliko AI المجانية",
        "ai_ended_d": "وثّق حسابك — يرتفع الحد إلى 50 شهريًا. أو اشترك في باقة أدناه لاستخدام غير محدود.",
        "verify": "توثيق الحساب",
        "no_digital": "هذه الميزة غير متاحة في التطبيق.",
        "on_site": "فتح في الحساب على الموقع",
        "unf_t": "تحليل غير مكتمل",
        "unf_s": "وُجد {n} منتجات، وقُرئ {p}% من القائمة. سنكمل من المكان نفسه — لا حاجة للدفع مجددًا.",
        "unf_go": "متابعة",
        "unf_drop": "البدء من جديد",
        "unf_drop_q": "البدء من جديد؟",
        "unf_drop_s": "ستُحذف الأسطر المتعرَّف عليها في هذا التشغيل، وسيبدأ Kliko AI من البداية.",
        "rv_n": "تم التعرّف على {n}",
        "rv_sum": "بقيمة {s} · ستذهب المسودات إلى «غير النشطة» وتمر بالمراجعة",
        "rv_ai": "Kliko AI",
        "rv_ai_left": "Kliko AI · متبقٍ {n}",
        "rv_local": "محلل محلي",
        "rv_link": "عبر الرابط",
        "rv_redo": "من جديد",
        "rv_all": "تحديد الكل",
        "rv_sel": "محدد {n} من {l}",
        "rv_sel_sum": " · {s}",
        "rv_hint": "أزل العلامة عن الأسطر التي لا تريد نشرها. يُتخطّى المنتج بلا سعر أو اسم.",
        "rv_pub": "إضافة إلى «غير النشطة»",
        "rv_adding": "نضيف… {a} من {n}",
        "rv_title": "الاسم",
        "rv_brand": "العلامة",
        "rv_price": "السعر",
        "rv_cat": "الفئة",
        "rv_ok": "جاهز",
        "rv_warn": "أضف السعر",
        "used": "مستعمل",
        "new": "جديد",
        "rv_more": "المواصفات والوصف",
        "rv_desc": "الوصف (سيضيف Kliko AI مزايا المنتج)",
        "rv_del": "إزالة السطر",
        "rv_pick": "نشر هذا السطر",
        "cat_other": "أخرى",
        "spec_cpu": "المعالج",
        "spec_gpu": "بطاقة الرسوميات",
        "spec_ram": "الذاكرة",
        "spec_storage": "التخزين",
        "spec_year": "سنة الصنع",
        "no_sel": "لا أسطر",
        "pub_net": "انقطع الاتصال عند السطر {r}. أضيف: {n}. اضغط «متابعة» — سنضيف الباقي.",
        "pub_continue": "متابعة الإضافة",
        "pub_ok": "تم الاستيراد إلى «غير النشطة»: {n}",
        "pub_skipped": "تم التخطي {n}",
        "sk_title": "{n} بلا اسم",
        "sk_banned": "{n} محتوى محظور",
        "sk_cap": "{n} فوق الحد",
        "pub_after": "افتح القسم وأضف الأسعار حيث يلزم وفعّلها — ستمر بالمراجعة.",
        "li_pub_ok": "تم النقل: {n} — في «غير النشطة»",
        "pub_fail": "تعذّر إنشاء المسودات",
        "pub_pro": "النقل ككتالوج ضمن باقة PRO",
        "done_t": "المسودات جاهزة",
        "drafts": "المسودات",
        "edit": "المراجعة والنشر",
        "open_items": "فتح «إعلاناتي»",
        "more_import": "نقل المزيد",
        "close": "إغلاق",
        "cancel": "إلغاء",
        "retry": "إعادة المحاولة",
        "no_conn": "لا يوجد اتصال",
        "err_generic": "خطأ",
        "pick_photos": "اختيار الصور",
        "pick_file": "اختيار ملف",
        "remove": "إزالة",
        "a11y_selected": "محدد",
        "imp_demo": "عرض مثال",
        "demo_prog_t": "أتعرّف على المنتجات…",
        "demo_prog_n": "تم التعرّف على {i} من {n}",
        "demo_pub": "هذا عرض توضيحي — لا تُنشأ مسودات. في الاستيراد الحقيقي تذهب المنتجات إلى «غير النشطة».",
        "ph_t": "صور المنتج",
        "ph_up": "رفع",
        "ph_done": "تم",
        "ph_sub": "ارفع الصور من جهازك أو اختر من الصور المرفوعة — ستُربط بالمنتج.",
        "ph_empty": "لا توجد صور مرفوعة بعد.\nاضغط «رفع» — ستُربط الصورة بالمنتج.",
        "ph_max": "لا أكثر من 8 صور للمنتج",
        "ph_loading": "جارٍ رفع الصور…",
        "ph_added": "أضيفت الصورة",
        "ph_del": "إزالة",
        "ph_add": "إضافة صورة",
        "ph_this": "هذا المنتج · {n} من {m}",
        "ph_pool": "المرفوعة",
        "ph_owner": "№{n}",
        "ph_owner_a11y": "موجودة لدى المنتج №{n}",
        "ph_prog": "{i} من {n}",
    ]
}
