import Foundation

/**
 Тексты «Моих объявлений» (этап 41, владелец 26.09.2026: «всё одно и то же, просто код разный») на языке телефона
 (kk/ru/en/ar).

 Русские — слово в слово с сайта: словарь js/i18n-cabinet-ru.js (cab_empty_*, chip_*, held_verify_*, adv_*, btn_*,
 mod_recheck_*, republish_ok_*, wl_*, promo_free_bumps, slot_*, stat_title…), вкладки и поиск из разметки кабинета
 (U @168213, @169351) и фразы, зашитые в js/cabinet.min.js (окна подтверждения deactivateItem / softDeleteItem /
 deletePermanent, окно модерации showModerationProgress, showAiBlocked, showProhibitedWarning, склад advStockHTML,
 «кто» advWhoToggle, блок «Работа» с запасными текстами _vT). Где у сайта %s или {n} — здесь %@ / %d. Остальные языки —
 перевод тех же фраз.
 */
enum МоиОбъявленияText {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    /// Язык дат и чисел «Не в ленте с 5 октября» — тот же, что у текстов (ru-RU сайта для русского).
    static var локаль: Locale {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        switch язык {
        case "kk": return Locale(identifier: "kk_KZ")
        case "en": return Locale(identifier: "en_US")
        case "ar": return Locale(identifier: "ar")
        default:   return Locale(identifier: "ru_RU")
        }
    }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    private static let ru: [String: String] = [
        "title": "Мои объявления",
        "tab_published": "Опубликованные", "tab_inactive": "Неактивные", "tab_deleted": "Удалённые",
        "search": "Поиск: название, бренд, ID", "search_clear": "Сбросить поиск",
        "not_found": "Ничего не найдено по «%@»",
        "loading": "Загрузка…", "load_err": "Ошибка загрузки", "no_conn": "Нет соединения", "retry": "Повторить",
        "empty_published": "Нет опубликованных объявлений", "empty_inactive": "Нет неактивных объявлений",
        "empty_deleted": "Нет удалённых объявлений",
        "imp_t": "Уже продаёте на другой площадке?",
        "imp_s": "Вставьте ссылку с OLX, Krisha или Kolesa — объявление перенесётся со всеми фото за минуту.",
        "imp_b": "Перенести по ссылке",
        "add": "+ Добавить объявление",
        // человеческие статусы (прохождение новичка)
        "st_pub": "Опубликовано", "st_review": "На проверке — до 24 ч", "st_sold": "Продано",
        "st_verify": "Не видно покупателям — подтвердите личность через eGov", "verify_go": "Подтвердить через eGov",
        "st_off": "Снято с публикации", "st_rejected": "Отклонено", "st_rejected_why": "Отклонено — %@",
        "st_expired": "Срок истёк — продлите", "st_limit": "Не показывается: достигнут лимит объявлений",
        "st_queue": "Опубликуется %@", "st_draft": "Черновик", "bump_in": "Бесплатно поднимем через %d дн.",
        "btn_more": "Ещё", "empty_first": "Сфотографируйте первую вещь",
        "empty_first_s": "Фото — и объявление почти готово. Остальное подскажем.",
        "imp_link": "Перенести объявления с других сайтов",
        // значки
        "held_verify_badge": "Нужна верификация", "held_verify_t": "Остался один шаг",
        "held_verify_s": "Пройдите верификацию — и оно выйдет на витрину.", "held_verify_go": "Пройти",
        "exp_badge": "Срок истёк", "chip_manual_review": "На ручной проверке",
        "chip_manual_why": "Kliko AI не смог проверить — смотрит модератор",
        "chip_redacting": "Скрываем номера на фото…", "chip_ai_check": "Проверяется Kliko AI…",
        "chip_sold_out": "Распродано · пополните склад", "chip_sold_off": "Снято с витрины",
        "chip_draft_import": "Черновик · импорт", "pq_chip": "В очереди · %@", "pq_chip_wait": "Ждёт свободный слот",
        "pq_today": "сегодня", "pq_tomorrow": "завтра",
        "chip_held_auto": "Сверх лимита · вернётся само", "chip_held_slot": "Расширьте лимит",
        "chip_sold_slot": "Продано · слот освобождён", "chip_paused_slot": "На паузе · слот держится",
        "chip_inactive": "Неактивный", "chip_deleted": "Удалено", "approved": "Одобрено",
        "manual_body": "Ожидает проверки модератором — обычно до 24 часов.",
        "reason": "Причина: %@", "attempt": "(попытка %d/5)",
        "blocked_body": "Отклонено несколько раз. Исправьте объявление — его посмотрит модератор.",
        "adv_top": "ТОП", "adv_top_until": "В ТОПе до %@",
        "promo_free_bumps": "Бесплатные авто-поднятия (день 7·14·21) — включены",
        "promo_next_in": "следующее через %d дн.",
        // срок жизни
        "life_30": "Срок 30 дней", "life_gone": "Не в ленте с %@",
        "adv_autorenew_in": "Авто-продление · обновится через %d дн.", "adv_active_left": "Активно ещё %d дн. из 30",
        "adv_expires_today": "Истекает сегодня", "adv_autorenew": "Авто-продление",
        "autorenew_hint": "Продлевать объявление автоматически каждые 30 дней",
        "autorenew_on": "Авто-продление включено", "autorenew_off": "Авто-продление выключено",
        // кнопки
        "btn_edit": "Изменить", "btn_view": "Смотреть", "btn_share": "Поделиться", "btn_promote": "Продвинуть",
        "btn_extend_top": "Продлить ТОП", "btn_pause": "Снять", "btn_activate": "Активировать",
        "btn_restore": "Восстановить", "btn_recheck": "Проверить сейчас", "btn_delete": "Удалить",
        "btn_delete_forever": "Удалить навсегда", "btn_edit_recheck": "Редактировать → на проверку",
        "adv_id_copy": "Скопировать ID", "adv_id_copied": "ID скопирован", "adv_open": "Открыть",
        // цена
        "price_negotiable": "Договорная", "torg": "Торг", "unit_day": "сут", "unit_month": "мес", "adv_sale": "продажа",
        // статистика
        "views": "Просмотры", "likes": "Добавили в избранное", "msgs": "Написали сообщение",
        "calls": "Нажали «Позвонить»", "shares": "Поделились", "guest": "Гость",
        "who_empty": "Пока никто — данные появятся когда покупатели начнут взаимодействовать",
        "wl_pill": "Ждут появления", "wl_hint_t": "%d ждут этот товар",
        "wl_hint_m": "Эти люди попросили сообщить, когда товар снова появится. Пополните остаток — им уйдёт уведомление.",
        "wl_hint_go": "К остатку", "later": "Позже",
        // склад
        "stock_lbl": "На складе", "stock_out": "· Распродано", "stock_none": "· не ведётся",
        "stock_minus": "Продал офлайн — убавить", "stock_plus": "Пополнить", "stock_unit": "шт", "stock_save": "Сохранить",
        "stock_hint": "− продал вне платформы · + пополнил склад · можно ввести число",
        "stock_hint_none": "Укажите остаток — товар начнёт списываться при сделках",
        "stock_bad": "Введите число ≥ 0", "stock_sold": "Распродано — объявление скрыто из витрины",
        "stock_ok": "Склад обновлён: %d шт", "stock_err": "Ошибка склада",
        // подтверждения и итоги
        "deact_q": "Деактивировать объявление?", "deact_msg": "«%@» скроется с сайта и перейдёт в раздел Неактивные.",
        "deact_ok": "Деактивировать", "deact_done": "Объявление деактивировано",
        "del_q": "Удалить объявление?",
        "del_msg": "«%@» перейдёт в раздел Удалённые. Оттуда можно восстановить или удалить навсегда.",
        "del_ok": "Удалить", "del_done": "Объявление перемещено в удалённые",
        "perm_q": "Удалить навсегда?",
        "perm_msg": "«%@» будет уничтожено без возможности восстановления. Это действие нельзя отменить.",
        "perm_ok": "Да, удалить навсегда", "perm_done": "Объявление удалено навсегда",
        "err_prefix": "Ошибка: %@", "conn_err": "Ошибка соединения", "err_generic": "Ошибка", "err_net": "Ошибка сети",
        "cancel": "Отмена",
        // модерация
        "mod_title": "Kliko AI проверяет объявление", "mod_init": "Инициализация…",
        "mod_s1": "Загружаю объявление…", "mod_s2": "Анализирую фотографии…", "mod_s3": "Проверяю описание…",
        "mod_s4": "Проверяю категорию…", "mod_s5": "Выношу вердикт…",
        "mod_ok": "Одобрено!", "mod_rej": "Отклонено", "mod_blk": "Заблокировано", "mod_done": "Проверка завершена",
        "published": "Объявление опубликовано!",
        "rej_t": "Объявление отклонено", "rej_d": "Не соответствует правилам", "rej_ok": "Понятно, исправлю",
        "wait_t": "Объявление на проверке",
        "wait_b": "Kliko AI ещё анализирует ваше объявление.\nРезультат появится в разделе Неактивные в течение 1–2 минут.",
        "btn_ok": "Хорошо", "sec_short": "с",
        "republish_t": "Отлично!", "republish_b": "Объявление снова опубликовано и видно в маркете.",
        "ai_blk_t": "Kliko AI-модерация заблокирована",
        "ai_blk_b": "Вы превысили лимит отклонений.\nKliko AI-проверка недоступна ещё %@ ч.",
        "ai_blk_s": "После разблокировки убедитесь что фото товара чёткое и товар хорошо виден",
        "to_manual": "Отправить на ручную проверку", "close": "Закрыть",
        "manual_done": "Отправлено на ручную проверку — до 24 часов", "manual_err": "попробуйте ещё раз",
        "prh_soft_t": "Фото не загружено",
        "prh_soft_b": "Автоматическая проверка отнесла кадр к категории «%@» и не пропустила его.\n\nС аккаунтом ничего не произошло: ограничений нет. Попробуйте другой кадр — а если считаете, что проверка ошиблась, напишите в поддержку, посмотрим вручную.",
        "prh_t": "Запрещённый контент",
        "prh_first": "Обнаружен «%@» — материал удалён. Публикация таких товаров запрещена.\n\nЭто предупреждение. При повторе Kliko AI-функции блокируются: 15 мин → 1 час → 24 часа → 7 дней.",
        "prh_blk_t": "Kliko AI заблокирован",
        "prh_blk": "Снова «%@» — материал удалён. Kliko AI-функции заблокированы на %@.",
        "prh_blk_more": "При повторе срок увеличится.",
        "prh_now": "Обнаружен «%@» — материал удалён. Kliko AI-функции сейчас заблокированы.",
        "prh_cat": "запрещённый контент", "ok_btn": "Понятно",
        "need_verify_t": "Нужна верификация", "need_verify_go": "Пройти верификацию",
        "limit_t": "Вы достигли лимита!", "limit_d": "Достигнут лимит объявлений.", "limit_slots": "Расширить лимит",
        "limit_verify": "Пройти верификацию (+5)",
        "recheck_run": "Проверяем…", "recheck_ok": "Проверено — объявление на витрине",
        "recheck_wait": "Проверка ещё идёт — вернёмся к ней через минуту", "recheck_done": "Проверка закончена",
        // поделиться
        "share_t": "Поделитесь объявлением", "share_link": "Ссылка", "link_copied": "Ссылка скопирована",
        // «Доступно»
        "stat_title": "Доступно", "cab_listings": "Объявления", "slot_free": "Свободно", "slot_full_sub": "Лимит достигнут",
        "slot_plan": "тариф %d ещё %d дн.", "slot_free_in": "место освободится через %d дн.", "cab_expand": "Расширить",
        "ai_over": "Закончились",
        // работа
        "as_jobs": "Работа", "hov_vacancy": "Вакансия", "hov_resume": "Резюме", "badge_top": "ТОП",
        "jb_expired": "Истёк срок", "jb_restore": "Восстановить", "jb_delete": "Удалить", "jb_top": "В ТОП",
        "jb_edit": "Изменить", "jb_off": "Снять", "jb_off_q": "Снять объявление?",
        "jb_off_s": "Оно пропадёт из раздела «Работа». Восстановить можно будет здесь же.",
        "jw_fail": "Не удалось", "no_net": "Нет связи",
        // VoiceOver
        "a11y_photo": "Фото объявления «%@»", "a11y_stat": "%@: %d", "a11y_minus": "Продал офлайн — убавить",
        "a11y_tab": "Вкладка «%@»"
    ]

    private static let kk: [String: String] = [
        "title": "Менің хабарландыруларым",
        "tab_published": "Жарияланғандар", "tab_inactive": "Белсенді емес", "tab_deleted": "Жойылғандар",
        "search": "Іздеу: атауы, бренд, ID", "search_clear": "Іздеуді тазалау",
        "not_found": "«%@» бойынша ештеңе табылмады",
        "loading": "Жүктелуде…", "load_err": "Жүктеу қатесі", "no_conn": "Байланыс жоқ", "retry": "Қайталау",
        "empty_published": "Жарияланған хабарландырулар жоқ", "empty_inactive": "Белсенді емес хабарландырулар жоқ",
        "empty_deleted": "Жойылған хабарландырулар жоқ",
        "imp_t": "Басқа алаңда сатып жүрсіз бе?",
        "imp_s": "OLX, Krisha немесе Kolesa сілтемесін қойыңыз — хабарландыру барлық фотосымен бір минутта көшеді.",
        "imp_b": "Сілтеме арқылы көшіру",
        "add": "+ Хабарландыру қосу",
        // человеческие статусы (прохождение новичка)
        "st_pub": "Жарияланды", "st_review": "Тексеруде — 24 сағатқа дейін", "st_sold": "Сатылды",
        "st_verify": "Сатып алушыларға көрінбейді — жеке басыңызды eGov арқылы растаңыз", "verify_go": "eGov арқылы растау",
        "st_off": "Жариялаудан алынды", "st_rejected": "Қабылданбады", "st_rejected_why": "Қабылданбады — %@",
        "st_expired": "Мерзімі өтті — ұзартыңыз", "st_limit": "Көрсетілмейді: хабарландыру лимитіне жеттіңіз",
        "st_queue": "%@ жарияланады", "st_draft": "Жоба", "bump_in": "%d күннен кейін тегін көтереміз",
        "btn_more": "Тағы", "empty_first": "Алғашқы затыңызды суретке түсіріңіз",
        "empty_first_s": "Сурет — және хабарландыру дайын дерлік. Қалғанын айтып береміз.",
        "imp_link": "Басқа сайттардан хабарландыруларды көшіру",
        "held_verify_badge": "Верификация қажет", "held_verify_t": "Бір қадам қалды",
        "held_verify_s": "Верификациядан өтіңіз — сонда ол витринаға шығады.", "held_verify_go": "Өту",
        "exp_badge": "Мерзімі өтті", "chip_manual_review": "Қолмен тексеруде",
        "chip_manual_why": "Kliko AI тексере алмады — модератор қарап жатыр",
        "chip_redacting": "Фотодағы нөмірлерді жасырып жатырмыз…", "chip_ai_check": "Kliko AI тексеруде…",
        "chip_sold_out": "Сатылып бітті · қойманы толтырыңыз", "chip_sold_off": "Витринадан алынды",
        "chip_draft_import": "Жоба · импорт", "pq_chip": "Кезекте · %@", "pq_chip_wait": "Бос орынды күтуде",
        "pq_today": "бүгін", "pq_tomorrow": "ертең",
        "chip_held_auto": "Лимиттен тыс · өзі қайтады", "chip_held_slot": "Лимитті кеңейтіңіз",
        "chip_sold_slot": "Сатылды · орын босады", "chip_paused_slot": "Үзілісте · орын сақталады",
        "chip_inactive": "Белсенді емес", "chip_deleted": "Жойылды", "approved": "Мақұлданды",
        "manual_body": "Модератордың тексеруін күтуде — әдетте 24 сағатқа дейін.",
        "reason": "Себебі: %@", "attempt": "(%d/5 әрекет)",
        "blocked_body": "Бірнеше рет қабылданбады. Хабарландыруды түзетіңіз — оны модератор қарайды.",
        "adv_top": "ТОП", "adv_top_until": "%@ дейін ТОП-та",
        "promo_free_bumps": "Тегін авто-көтерулер (7·14·21-күн) — қосулы",
        "promo_next_in": "келесісі %d күннен кейін",
        "life_30": "Мерзімі 30 күн", "life_gone": "%@ бастап лентада жоқ",
        "adv_autorenew_in": "Авто-ұзарту · %d күннен кейін жаңарады", "adv_active_left": "Тағы %d күн белсенді, 30 күннен",
        "adv_expires_today": "Бүгін аяқталады", "adv_autorenew": "Авто-ұзарту",
        "autorenew_hint": "Хабарландыруды әр 30 күн сайын автоматты түрде ұзарту",
        "autorenew_on": "Авто-ұзарту қосылды", "autorenew_off": "Авто-ұзарту өшірілді",
        "btn_edit": "Өзгерту", "btn_view": "Қарау", "btn_share": "Бөлісу", "btn_promote": "Жарнамалау",
        "btn_extend_top": "ТОП-ты ұзарту", "btn_pause": "Алу", "btn_activate": "Белсендіру",
        "btn_restore": "Қалпына келтіру", "btn_recheck": "Қазір тексеру", "btn_delete": "Жою",
        "btn_delete_forever": "Біржола жою", "btn_edit_recheck": "Өңдеу → тексеруге",
        "adv_id_copy": "ID көшіру", "adv_id_copied": "ID көшірілді", "adv_open": "Ашу",
        "price_negotiable": "Келісімді", "torg": "Саудаласу", "unit_day": "тәул", "unit_month": "ай", "adv_sale": "сату",
        "views": "Қаралымдар", "likes": "Таңдаулыға қосқандар", "msgs": "Хабарлама жазғандар",
        "calls": "«Қоңырау шалу» басқандар", "shares": "Бөліскендер", "guest": "Қонақ",
        "who_empty": "Әзірге ешкім — сатып алушылар әрекет ете бастағанда деректер пайда болады",
        "wl_pill": "Пайда болуын күтеді", "wl_hint_t": "%d адам бұл тауарды күтеді",
        "wl_hint_m": "Бұл адамдар тауар қайта пайда болғанда хабарлауды сұрады. Қалдықты толтырыңыз — оларға хабарландыру кетеді.",
        "wl_hint_go": "Қалдыққа", "later": "Кейін",
        "stock_lbl": "Қоймада", "stock_out": "· Сатылып бітті", "stock_none": "· жүргізілмейді",
        "stock_minus": "Офлайн саттым — азайту", "stock_plus": "Толтыру", "stock_unit": "дана", "stock_save": "Сақтау",
        "stock_hint": "− платформадан тыс саттым · + қойманы толтырдым · сан енгізуге болады",
        "stock_hint_none": "Қалдықты көрсетіңіз — тауар мәмілелер кезінде есептен шығарыла бастайды",
        "stock_bad": "≥ 0 сан енгізіңіз", "stock_sold": "Сатылып бітті — хабарландыру витринадан жасырылды",
        "stock_ok": "Қойма жаңартылды: %d дана", "stock_err": "Қойма қатесі",
        "deact_q": "Хабарландыруды өшіру керек пе?", "deact_msg": "«%@» сайттан жасырылып, Белсенді емес бөліміне өтеді.",
        "deact_ok": "Өшіру", "deact_done": "Хабарландыру өшірілді",
        "del_q": "Хабарландыруды жою керек пе?",
        "del_msg": "«%@» Жойылғандар бөліміне өтеді. Сол жерден қалпына келтіруге немесе біржола жоюға болады.",
        "del_ok": "Жою", "del_done": "Хабарландыру жойылғандарға көшірілді",
        "perm_q": "Біржола жою керек пе?",
        "perm_msg": "«%@» қалпына келтіру мүмкіндігінсіз жойылады. Бұл әрекетті болдырмау мүмкін емес.",
        "perm_ok": "Иә, біржола жою", "perm_done": "Хабарландыру біржола жойылды",
        "err_prefix": "Қате: %@", "conn_err": "Байланыс қатесі", "err_generic": "Қате", "err_net": "Желі қатесі",
        "cancel": "Бас тарту",
        "mod_title": "Kliko AI хабарландыруды тексеріп жатыр", "mod_init": "Іске қосылуда…",
        "mod_s1": "Хабарландыруды жүктеп жатырмын…", "mod_s2": "Фотоларды талдап жатырмын…",
        "mod_s3": "Сипаттаманы тексеріп жатырмын…", "mod_s4": "Санатты тексеріп жатырмын…",
        "mod_s5": "Шешім шығарып жатырмын…",
        "mod_ok": "Мақұлданды!", "mod_rej": "Қабылданбады", "mod_blk": "Бұғатталды", "mod_done": "Тексеру аяқталды",
        "published": "Хабарландыру жарияланды!",
        "rej_t": "Хабарландыру қабылданбады", "rej_d": "Ережелерге сәйкес келмейді", "rej_ok": "Түсінікті, түзетемін",
        "wait_t": "Хабарландыру тексеруде",
        "wait_b": "Kliko AI хабарландыруыңызды әлі талдап жатыр.\nНәтиже 1–2 минут ішінде Белсенді емес бөлімінде пайда болады.",
        "btn_ok": "Жақсы", "sec_short": "с",
        "republish_t": "Керемет!", "republish_b": "Хабарландыру қайта жарияланды және маркетте көрінеді.",
        "ai_blk_t": "Kliko AI-модерация бұғатталды",
        "ai_blk_b": "Сіз қабылданбау лимитінен асып кеттіңіз.\nKliko AI-тексеру тағы %@ сағ. қолжетімсіз.",
        "ai_blk_s": "Бұғаттан шыққан соң тауар фотосы анық және тауар жақсы көрінетініне көз жеткізіңіз",
        "to_manual": "Қолмен тексеруге жіберу", "close": "Жабу",
        "manual_done": "Қолмен тексеруге жіберілді — 24 сағатқа дейін", "manual_err": "қайталап көріңіз",
        "prh_soft_t": "Фото жүктелмеді",
        "prh_soft_b": "Автоматты тексеру кадрды «%@» санатына жатқызып, өткізбеді.\n\nАккаунтыңызға ештеңе болған жоқ: шектеулер жоқ. Басқа кадрды байқап көріңіз — ал тексеру қателесті деп ойласаңыз, қолдау қызметіне жазыңыз, қолмен қараймыз.",
        "prh_t": "Тыйым салынған мазмұн",
        "prh_first": "«%@» анықталды — материал жойылды. Мұндай тауарларды жариялауға тыйым салынған.\n\nБұл ескерту. Қайталанса, Kliko AI-функциялары бұғатталады: 15 мин → 1 сағат → 24 сағат → 7 күн.",
        "prh_blk_t": "Kliko AI бұғатталды",
        "prh_blk": "Тағы да «%@» — материал жойылды. Kliko AI-функциялары %@ бұғатталды.",
        "prh_blk_more": "Қайталанса, мерзім ұзарады.",
        "prh_now": "«%@» анықталды — материал жойылды. Kliko AI-функциялары қазір бұғатталған.",
        "prh_cat": "тыйым салынған мазмұн", "ok_btn": "Түсінікті",
        "need_verify_t": "Верификация қажет", "need_verify_go": "Верификациядан өту",
        "limit_t": "Сіз лимитке жеттіңіз!", "limit_d": "Хабарландырулар лимитіне жетті.", "limit_slots": "Лимитті кеңейту",
        "limit_verify": "Верификациядан өту (+5)",
        "recheck_run": "Тексеріп жатырмыз…", "recheck_ok": "Тексерілді — хабарландыру витринада",
        "recheck_wait": "Тексеру әлі жүріп жатыр — бір минуттан кейін ораламыз", "recheck_done": "Тексеру аяқталды",
        "share_t": "Хабарландырумен бөлісіңіз", "share_link": "Сілтеме", "link_copied": "Сілтеме көшірілді",
        "stat_title": "Қолжетімді", "cab_listings": "Хабарландырулар", "slot_free": "Бос", "slot_full_sub": "Лимитке жетті",
        "slot_plan": "тариф %d тағы %d күн", "slot_free_in": "орын %d күннен кейін босайды", "cab_expand": "Кеңейту",
        "ai_over": "Бітті",
        "as_jobs": "Жұмыс", "hov_vacancy": "Бос орын", "hov_resume": "Түйіндеме", "badge_top": "ТОП",
        "jb_expired": "Мерзімі өтті", "jb_restore": "Қалпына келтіру", "jb_delete": "Жою", "jb_top": "ТОП-қа",
        "jb_edit": "Өзгерту", "jb_off": "Алу", "jb_off_q": "Хабарландыруды алу керек пе?",
        "jb_off_s": "Ол «Жұмыс» бөлімінен жоғалады. Осы жерден қалпына келтіруге болады.",
        "jw_fail": "Сәтсіз аяқталды", "no_net": "Байланыс жоқ",
        "a11y_photo": "«%@» хабарландыруының фотосы", "a11y_stat": "%@: %d", "a11y_minus": "Офлайн саттым — азайту",
        "a11y_tab": "«%@» қойындысы"
    ]

    private static let en: [String: String] = [
        "title": "My listings",
        "tab_published": "Published", "tab_inactive": "Inactive", "tab_deleted": "Deleted",
        "search": "Search: title, brand, ID", "search_clear": "Clear search",
        "not_found": "Nothing found for “%@”",
        "loading": "Loading…", "load_err": "Loading error", "no_conn": "No connection", "retry": "Retry",
        "empty_published": "No published listings", "empty_inactive": "No inactive listings",
        "empty_deleted": "No deleted listings",
        "imp_t": "Already selling on another platform?",
        "imp_s": "Paste a link from OLX, Krisha or Kolesa — the listing moves over with all photos in a minute.",
        "imp_b": "Move by link",
        "add": "+ Add listing",
        // человеческие статусы (прохождение новичка)
        "st_pub": "Published", "st_review": "Under review — up to 24 h", "st_sold": "Sold",
        "st_verify": "Not visible to buyers — confirm your identity via eGov", "verify_go": "Confirm via eGov",
        "st_off": "Unpublished", "st_rejected": "Rejected", "st_rejected_why": "Rejected — %@",
        "st_expired": "Expired — renew it", "st_limit": "Not shown: listing limit reached",
        "st_queue": "Goes live %@", "st_draft": "Draft", "bump_in": "Free bump in %d d.",
        "btn_more": "More", "empty_first": "Photograph your first item",
        "empty_first_s": "One photo and your listing is almost ready. We'll help with the rest.",
        "imp_link": "Move listings from other sites",
        "held_verify_badge": "Verification needed", "held_verify_t": "One step left",
        "held_verify_s": "Get verified — and it will appear in the storefront.", "held_verify_go": "Verify",
        "exp_badge": "Expired", "chip_manual_review": "Manual review",
        "chip_manual_why": "Kliko AI couldn't check it — a moderator is looking",
        "chip_redacting": "Hiding numbers in photos…", "chip_ai_check": "Kliko AI is checking…",
        "chip_sold_out": "Sold out · restock", "chip_sold_off": "Removed from storefront",
        "chip_draft_import": "Draft · import", "pq_chip": "Queued · %@", "pq_chip_wait": "Waiting for a free slot",
        "pq_today": "today", "pq_tomorrow": "tomorrow",
        "chip_held_auto": "Over the limit · returns by itself", "chip_held_slot": "Raise the limit",
        "chip_sold_slot": "Sold · slot freed", "chip_paused_slot": "Paused · slot kept",
        "chip_inactive": "Inactive", "chip_deleted": "Deleted", "approved": "Approved",
        "manual_body": "Awaiting a moderator's review — usually within 24 hours.",
        "reason": "Reason: %@", "attempt": "(attempt %d/5)",
        "blocked_body": "Rejected several times. Fix the listing and a moderator will review it.",
        "adv_top": "TOP", "adv_top_until": "In TOP until %@",
        "promo_free_bumps": "Free auto-bumps (days 7·14·21) — on",
        "promo_next_in": "next in %d d.",
        "life_30": "30-day term", "life_gone": "Not in the feed since %@",
        "adv_autorenew_in": "Auto-renew · renews in %d d.", "adv_active_left": "Active for %d more d. of 30",
        "adv_expires_today": "Expires today", "adv_autorenew": "Auto-renew",
        "autorenew_hint": "Renew the listing automatically every 30 days",
        "autorenew_on": "Auto-renew on", "autorenew_off": "Auto-renew off",
        "btn_edit": "Edit", "btn_view": "View", "btn_share": "Share", "btn_promote": "Promote",
        "btn_extend_top": "Extend TOP", "btn_pause": "Unpublish", "btn_activate": "Activate",
        "btn_restore": "Restore", "btn_recheck": "Check now", "btn_delete": "Delete",
        "btn_delete_forever": "Delete forever", "btn_edit_recheck": "Edit → send for review",
        "adv_id_copy": "Copy ID", "adv_id_copied": "ID copied", "adv_open": "Open",
        "price_negotiable": "Negotiable", "torg": "Negotiable", "unit_day": "day", "unit_month": "mo", "adv_sale": "sale",
        "views": "Views", "likes": "Added to favorites", "msgs": "Sent a message",
        "calls": "Tapped “Call”", "shares": "Shared", "guest": "Guest",
        "who_empty": "Nobody yet — data will appear when buyers start interacting",
        "wl_pill": "Waiting for it", "wl_hint_t": "%d are waiting for this item",
        "wl_hint_m": "These people asked to be told when the item is back. Restock it — they'll get a notification.",
        "wl_hint_go": "To stock", "later": "Later",
        "stock_lbl": "In stock", "stock_out": "· Sold out", "stock_none": "· not tracked",
        "stock_minus": "Sold offline — decrease", "stock_plus": "Restock", "stock_unit": "pcs", "stock_save": "Save",
        "stock_hint": "− sold outside the platform · + restocked · you can type a number",
        "stock_hint_none": "Enter the stock — it will be written off with deals",
        "stock_bad": "Enter a number ≥ 0", "stock_sold": "Sold out — the listing is hidden from the storefront",
        "stock_ok": "Stock updated: %d pcs", "stock_err": "Stock error",
        "deact_q": "Deactivate the listing?", "deact_msg": "“%@” will be hidden from the site and moved to Inactive.",
        "deact_ok": "Deactivate", "deact_done": "Listing deactivated",
        "del_q": "Delete the listing?",
        "del_msg": "“%@” will move to Deleted. From there you can restore it or delete it forever.",
        "del_ok": "Delete", "del_done": "Listing moved to deleted",
        "perm_q": "Delete forever?",
        "perm_msg": "“%@” will be destroyed with no way to restore it. This can't be undone.",
        "perm_ok": "Yes, delete forever", "perm_done": "Listing deleted forever",
        "err_prefix": "Error: %@", "conn_err": "Connection error", "err_generic": "Error", "err_net": "Network error",
        "cancel": "Cancel",
        "mod_title": "Kliko AI is checking the listing", "mod_init": "Starting…",
        "mod_s1": "Loading the listing…", "mod_s2": "Analyzing photos…", "mod_s3": "Checking the description…",
        "mod_s4": "Checking the category…", "mod_s5": "Reaching a verdict…",
        "mod_ok": "Approved!", "mod_rej": "Rejected", "mod_blk": "Blocked", "mod_done": "Check finished",
        "published": "Listing published!",
        "rej_t": "Listing rejected", "rej_d": "Doesn't meet the rules", "rej_ok": "Got it, I'll fix it",
        "wait_t": "Listing under review",
        "wait_b": "Kliko AI is still analyzing your listing.\nThe result will appear in Inactive within 1–2 minutes.",
        "btn_ok": "OK", "sec_short": "s",
        "republish_t": "Great!", "republish_b": "The listing is published again and visible in the market.",
        "ai_blk_t": "Kliko AI moderation blocked",
        "ai_blk_b": "You've exceeded the rejection limit.\nKliko AI check is unavailable for %@ more h.",
        "ai_blk_s": "After unblocking, make sure the photo is sharp and the item is clearly visible",
        "to_manual": "Send for manual review", "close": "Close",
        "manual_done": "Sent for manual review — up to 24 hours", "manual_err": "please try again",
        "prh_soft_t": "Photo not uploaded",
        "prh_soft_b": "The automatic check classified the picture as “%@” and didn't let it through.\n\nNothing happened to your account: there are no restrictions. Try another picture — and if you think the check was wrong, write to support and we'll look manually.",
        "prh_t": "Prohibited content",
        "prh_first": "“%@” detected — the material was removed. Publishing such items is prohibited.\n\nThis is a warning. If it happens again, Kliko AI features are blocked: 15 min → 1 hour → 24 hours → 7 days.",
        "prh_blk_t": "Kliko AI blocked",
        "prh_blk": "“%@” again — the material was removed. Kliko AI features are blocked for %@.",
        "prh_blk_more": "If it happens again, the term will grow.",
        "prh_now": "“%@” detected — the material was removed. Kliko AI features are blocked right now.",
        "prh_cat": "prohibited content", "ok_btn": "Got it",
        "need_verify_t": "Verification needed", "need_verify_go": "Get verified",
        "limit_t": "You've reached the limit!", "limit_d": "Listing limit reached.", "limit_slots": "Raise the limit",
        "limit_verify": "Get verified (+5)",
        "recheck_run": "Checking…", "recheck_ok": "Checked — the listing is in the storefront",
        "recheck_wait": "Still checking — we'll come back to it in a minute", "recheck_done": "Check finished",
        "share_t": "Share your listing", "share_link": "Link", "link_copied": "Link copied",
        "stat_title": "Available", "cab_listings": "Listings", "slot_free": "Free", "slot_full_sub": "Limit reached",
        "slot_plan": "plan %d, %d more d.", "slot_free_in": "a spot frees up in %d d.", "cab_expand": "Expand",
        "ai_over": "Used up",
        "as_jobs": "Jobs", "hov_vacancy": "Vacancy", "hov_resume": "Résumé", "badge_top": "TOP",
        "jb_expired": "Expired", "jb_restore": "Restore", "jb_delete": "Delete", "jb_top": "To TOP",
        "jb_edit": "Edit", "jb_off": "Unpublish", "jb_off_q": "Unpublish the listing?",
        "jb_off_s": "It will disappear from Jobs. You'll be able to restore it right here.",
        "jw_fail": "Failed", "no_net": "No connection",
        "a11y_photo": "Photo of “%@”", "a11y_stat": "%@: %d", "a11y_minus": "Sold offline — decrease",
        "a11y_tab": "“%@” tab"
    ]

    private static let ar: [String: String] = [
        "title": "إعلاناتي",
        "tab_published": "المنشورة", "tab_inactive": "غير النشطة", "tab_deleted": "المحذوفة",
        "search": "بحث: العنوان، العلامة، المعرّف", "search_clear": "مسح البحث",
        "not_found": "لم يُعثر على شيء لـ «%@»",
        "loading": "جارٍ التحميل…", "load_err": "خطأ في التحميل", "no_conn": "لا يوجد اتصال", "retry": "إعادة المحاولة",
        "empty_published": "لا توجد إعلانات منشورة", "empty_inactive": "لا توجد إعلانات غير نشطة",
        "empty_deleted": "لا توجد إعلانات محذوفة",
        "imp_t": "تبيع بالفعل على منصة أخرى؟",
        "imp_s": "الصق رابطًا من OLX أو Krisha أو Kolesa — سينتقل الإعلان بكل صوره خلال دقيقة.",
        "imp_b": "النقل عبر رابط",
        "add": "+ إضافة إعلان",
        // человеческие статусы (прохождение новичка)
        "st_pub": "منشور", "st_review": "قيد المراجعة — حتى 24 ساعة", "st_sold": "تم البيع",
        "st_verify": "غير مرئي للمشترين — أكّد هويتك عبر eGov", "verify_go": "التأكيد عبر eGov",
        "st_off": "أُلغي النشر", "st_rejected": "مرفوض", "st_rejected_why": "مرفوض — %@",
        "st_expired": "انتهت المدة — جدّده", "st_limit": "لا يظهر: تم بلوغ حد الإعلانات",
        "st_queue": "يُنشر %@", "st_draft": "مسودة", "bump_in": "رفع مجاني بعد %d يوم",
        "btn_more": "المزيد", "empty_first": "صوّر أول غرض لك",
        "empty_first_s": "صورة واحدة ويصبح إعلانك شبه جاهز. سنساعدك في الباقي.",
        "imp_link": "نقل الإعلانات من مواقع أخرى",
        "held_verify_badge": "التحقق مطلوب", "held_verify_t": "بقيت خطوة واحدة",
        "held_verify_s": "أكمل التحقق — وسيظهر في الواجهة.", "held_verify_go": "التحقق",
        "exp_badge": "انتهت المدة", "chip_manual_review": "مراجعة يدوية",
        "chip_manual_why": "لم يتمكن Kliko AI من الفحص — المشرف يراجع",
        "chip_redacting": "نُخفي الأرقام في الصور…", "chip_ai_check": "Kliko AI يفحص…",
        "chip_sold_out": "نفدت الكمية · أعد التعبئة", "chip_sold_off": "أُزيل من الواجهة",
        "chip_draft_import": "مسودة · استيراد", "pq_chip": "في الطابور · %@", "pq_chip_wait": "ينتظر خانة فارغة",
        "pq_today": "اليوم", "pq_tomorrow": "غدًا",
        "chip_held_auto": "فوق الحد · سيعود تلقائيًا", "chip_held_slot": "وسّع الحد",
        "chip_sold_slot": "بيع · تحررت الخانة", "chip_paused_slot": "متوقف · الخانة محفوظة",
        "chip_inactive": "غير نشط", "chip_deleted": "محذوف", "approved": "مقبول",
        "manual_body": "بانتظار مراجعة المشرف — عادة خلال 24 ساعة.",
        "reason": "السبب: %@", "attempt": "(المحاولة %d/5)",
        "blocked_body": "رُفض عدة مرات. عدّل الإعلان وسيراجعه المشرف.",
        "adv_top": "TOP", "adv_top_until": "في TOP حتى %@",
        "promo_free_bumps": "الرفع التلقائي المجاني (الأيام 7·14·21) — مفعّل",
        "promo_next_in": "التالي بعد %d يوم",
        "life_30": "المدة 30 يومًا", "life_gone": "خارج الخلاصة منذ %@",
        "adv_autorenew_in": "التجديد التلقائي · يتجدد بعد %d يوم", "adv_active_left": "نشط لمدة %d يوم أخرى من 30",
        "adv_expires_today": "ينتهي اليوم", "adv_autorenew": "التجديد التلقائي",
        "autorenew_hint": "تجديد الإعلان تلقائيًا كل 30 يومًا",
        "autorenew_on": "تم تفعيل التجديد التلقائي", "autorenew_off": "تم إيقاف التجديد التلقائي",
        "btn_edit": "تعديل", "btn_view": "عرض", "btn_share": "مشاركة", "btn_promote": "ترويج",
        "btn_extend_top": "تمديد TOP", "btn_pause": "إيقاف النشر", "btn_activate": "تفعيل",
        "btn_restore": "استعادة", "btn_recheck": "افحص الآن", "btn_delete": "حذف",
        "btn_delete_forever": "حذف نهائي", "btn_edit_recheck": "تعديل ← للمراجعة",
        "adv_id_copy": "نسخ المعرّف", "adv_id_copied": "تم نسخ المعرّف", "adv_open": "فتح",
        "price_negotiable": "قابل للتفاوض", "torg": "قابل للتفاوض", "unit_day": "يوم", "unit_month": "شهر", "adv_sale": "بيع",
        "views": "المشاهدات", "likes": "أضافوا إلى المفضلة", "msgs": "أرسلوا رسالة",
        "calls": "ضغطوا «اتصال»", "shares": "شاركوا", "guest": "زائر",
        "who_empty": "لا أحد بعد — ستظهر البيانات عندما يبدأ المشترون بالتفاعل",
        "wl_pill": "ينتظرون توفره", "wl_hint_t": "%d ينتظرون هذا المنتج",
        "wl_hint_m": "طلب هؤلاء إبلاغهم عند توفر المنتج مجددًا. أعد تعبئة المخزون — وسيصلهم إشعار.",
        "wl_hint_go": "إلى المخزون", "later": "لاحقًا",
        "stock_lbl": "في المخزون", "stock_out": "· نفدت الكمية", "stock_none": "· غير متتبَّع",
        "stock_minus": "بعت خارج المنصة — إنقاص", "stock_plus": "تعبئة", "stock_unit": "قطعة", "stock_save": "حفظ",
        "stock_hint": "− بعت خارج المنصة · + عبّأت المخزون · يمكنك إدخال رقم",
        "stock_hint_none": "أدخل الكمية — سيُخصم المنتج مع الصفقات",
        "stock_bad": "أدخل رقمًا ≥ 0", "stock_sold": "نفدت الكمية — أُخفي الإعلان من الواجهة",
        "stock_ok": "تم تحديث المخزون: %d قطعة", "stock_err": "خطأ في المخزون",
        "deact_q": "إيقاف الإعلان؟", "deact_msg": "سيُخفى «%@» من الموقع وينتقل إلى غير النشطة.",
        "deact_ok": "إيقاف", "deact_done": "تم إيقاف الإعلان",
        "del_q": "حذف الإعلان؟",
        "del_msg": "سينتقل «%@» إلى المحذوفة. من هناك يمكن استعادته أو حذفه نهائيًا.",
        "del_ok": "حذف", "del_done": "نُقل الإعلان إلى المحذوفة",
        "perm_q": "حذف نهائي؟",
        "perm_msg": "سيُتلف «%@» دون إمكانية الاستعادة. لا يمكن التراجع عن هذا الإجراء.",
        "perm_ok": "نعم، احذف نهائيًا", "perm_done": "حُذف الإعلان نهائيًا",
        "err_prefix": "خطأ: %@", "conn_err": "خطأ في الاتصال", "err_generic": "خطأ", "err_net": "خطأ في الشبكة",
        "cancel": "إلغاء",
        "mod_title": "Kliko AI يفحص الإعلان", "mod_init": "جارٍ البدء…",
        "mod_s1": "أحمّل الإعلان…", "mod_s2": "أحلل الصور…", "mod_s3": "أتحقق من الوصف…",
        "mod_s4": "أتحقق من الفئة…", "mod_s5": "أصدر الحكم…",
        "mod_ok": "مقبول!", "mod_rej": "مرفوض", "mod_blk": "محظور", "mod_done": "انتهى الفحص",
        "published": "تم نشر الإعلان!",
        "rej_t": "رُفض الإعلان", "rej_d": "لا يتوافق مع القواعد", "rej_ok": "فهمت، سأصلحه",
        "wait_t": "الإعلان قيد المراجعة",
        "wait_b": "ما زال Kliko AI يحلل إعلانك.\nستظهر النتيجة في غير النشطة خلال 1–2 دقيقة.",
        "btn_ok": "حسنًا", "sec_short": "ث",
        "republish_t": "ممتاز!", "republish_b": "نُشر الإعلان مجددًا وهو ظاهر في السوق.",
        "ai_blk_t": "مراجعة Kliko AI محظورة",
        "ai_blk_b": "لقد تجاوزت حد الرفض.\nفحص Kliko AI غير متاح لمدة %@ ساعة أخرى.",
        "ai_blk_s": "بعد رفع الحظر تأكد أن صورة المنتج واضحة وأن المنتج ظاهر جيدًا",
        "to_manual": "إرسال للمراجعة اليدوية", "close": "إغلاق",
        "manual_done": "أُرسل للمراجعة اليدوية — حتى 24 ساعة", "manual_err": "حاول مرة أخرى",
        "prh_soft_t": "لم تُرفع الصورة",
        "prh_soft_b": "صنّف الفحص التلقائي الصورة ضمن «%@» ولم يسمح بها.\n\nلم يحدث شيء لحسابك: لا توجد قيود. جرّب صورة أخرى — وإن رأيت أن الفحص أخطأ، اكتب للدعم وسنراجع يدويًا.",
        "prh_t": "محتوى محظور",
        "prh_first": "اكتُشف «%@» — حُذفت المادة. نشر مثل هذه المنتجات محظور.\n\nهذا تحذير. عند التكرار تُحظر ميزات Kliko AI: 15 دقيقة ← ساعة ← 24 ساعة ← 7 أيام.",
        "prh_blk_t": "Kliko AI محظور",
        "prh_blk": "مجددًا «%@» — حُذفت المادة. ميزات Kliko AI محظورة لمدة %@.",
        "prh_blk_more": "عند التكرار ستطول المدة.",
        "prh_now": "اكتُشف «%@» — حُذفت المادة. ميزات Kliko AI محظورة الآن.",
        "prh_cat": "محتوى محظور", "ok_btn": "فهمت",
        "need_verify_t": "التحقق مطلوب", "need_verify_go": "إكمال التحقق",
        "limit_t": "لقد بلغت الحد!", "limit_d": "تم بلوغ حد الإعلانات.", "limit_slots": "توسيع الحد",
        "limit_verify": "إكمال التحقق (+5)",
        "recheck_run": "نفحص…", "recheck_ok": "تم الفحص — الإعلان في الواجهة",
        "recheck_wait": "الفحص ما زال جاريًا — سنعود إليه بعد دقيقة", "recheck_done": "انتهى الفحص",
        "share_t": "شارك إعلانك", "share_link": "رابط", "link_copied": "تم نسخ الرابط",
        "stat_title": "المتاح", "cab_listings": "الإعلانات", "slot_free": "متاح", "slot_full_sub": "تم بلوغ الحد",
        "slot_plan": "الباقة %d، %d يوم أخرى", "slot_free_in": "تتحرر خانة بعد %d يوم", "cab_expand": "توسيع",
        "ai_over": "نفدت",
        "as_jobs": "عمل", "hov_vacancy": "وظيفة", "hov_resume": "سيرة ذاتية", "badge_top": "TOP",
        "jb_expired": "انتهت المدة", "jb_restore": "استعادة", "jb_delete": "حذف", "jb_top": "إلى TOP",
        "jb_edit": "تعديل", "jb_off": "إيقاف النشر", "jb_off_q": "إيقاف نشر الإعلان؟",
        "jb_off_s": "سيختفي من قسم «عمل». يمكنك استعادته من هنا.",
        "jw_fail": "تعذّر ذلك", "no_net": "لا يوجد اتصال",
        "a11y_photo": "صورة «%@»", "a11y_stat": "%@: %d", "a11y_minus": "بعت خارج المنصة — إنقاص",
        "a11y_tab": "تبويب «%@»"
    ]
}
