import Foundation

/**
 Тексты режима «Выбрать» и масс-редактора «Моих объявлений» на языке телефона (kk/ru/en/ar).

 Русские — слово в слово с сайта: словарь js/i18n-cabinet-ru.js (adv_select_btn, adv_selected, adv_all, pp_none,
 adv_done, adv_deact, adv_activate, adv_price, adv_promote, adv_more, btn_restore, adv_nosel, adv_onreview, pr_*,
 pq_*, ct_refine*, shopsec_*) и фразы, зашитые в js/cabinet.min.js (advBulkPrice, advBulkMore, advTableOpen,
 advBulkDelete, advBulkPurge, _advBulkApply). Сводка вопроса и итог по объявлениям — свои (просьба владельца).
 Где у сайта {n} — здесь %d / %@. Остальные языки — перевод тех же фраз.
 */
enum МассовыйРедакторText {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    private static let ru: [String: String] = [
        "hdr_add": "Добавить", "a11y_add": "Добавить объявление",
        "sel_btn": "Выбрать", "sel_cancel": "Отмена", "a11y_check": "Выбрать «%@»",
        "selected": "выбрано", "all": "Все", "none": "Снять все", "done": "Готово",
        "b_table": "Таблицей", "b_deact": "Снять", "b_price": "Цена", "b_promote": "Продвинуть", "b_more": "Ещё",
        "b_activate": "Активировать", "b_sched": "По расписанию", "b_restore": "Восстановить",
        "b_purge": "Удалить навсегда",
        "nosel": "Ничего не выбрано — отметьте объявления галочкой",
        "onreview": "Эти объявления на проверке — активировать можно после модерации",
        "nothing_avail": "Нет объявлений, доступных для действия",
        "none_applicable": "Нет применимых объявлений",
        "pick_pub": "Выберите опубликованные объявления",
        "pr_of": "из", "pr_done": "Готово", "pr_deactivating": "Снимаю с публикации…", "pr_activating": "Активирую…",
        "pr_deleting": "Удаляю в корзину…", "pr_purging": "Удаляю навсегда", "pr_applying": "Применяю изменения…",
        "res_done": "%d из %d — готово", "res_review": " · %d на проверке", "res_trash": "%d в корзине",
        "res_purged": "%d из %d — удалено навсегда", "res_noslot": " · %d не влезло", "res_phone": " · %d ждут номер",
        "res_test": " · тест-режим: до 10", "res_fail": "Не получилось", "res_fail_list": "Не вышло",
        "res_not_updated": "Не изменено: %d", "res_not_updated_why": "Сервер не принял правку для этих объявлений",
        "close": "Закрыть",
        "need_pro": "Масс-редактор — в тарифе Kliko PRO",
        "err_generic": "Ошибка", "conn_err": "Ошибка соединения", "prohibited": "Запрещённый контент",
        "ai_blocked": "Kliko AI заблокирован", "slots_full": "Лимит объявлений",
        "q_apply": "Применить", "q_cancel": "Отмена", "q_count": "Объявлений: %d", "q_more": "и ещё %d",
        "q_skip": "Пропущено: %d", "q_skip_review": "Пропущено: %d — на проверке",
        "q_edit_t": "Применить к выбранным?",
        "q_deact_t": "Снять с публикации — %d шт.?", "q_deact_b": "Снять",
        "q_act_t": "Активировать — %d шт.?", "q_act_s": "Каждое объявление проверит Kliko AI",
        "q_act_b": "Активировать",
        "q_rest_t": "Восстановить — %d шт.?", "q_rest_b": "Восстановить",
        "q_trash_t": "Удалить %d в корзину?",
        "q_trash_s": "Объявления перейдут в раздел «Удалённые» — оттуда можно восстановить.", "q_trash_b": "Удалить",
        "q_purge_t": "Удалить навсегда?",
        "q_purge_s": "%d объявлений будет уничтожено без возможности восстановления. Это действие нельзя отменить.",
        "q_purge_b": "Да, удалить навсегда",
        "price_t": "Цена — %d шт.", "price_how": "Насколько", "price_down": "Снизить", "price_up": "Поднять",
        "price_note": "Округление до 10 ₸. Договорные (без цены) пропускаются.", "price_enter": "Введите значение",
        "price_down_done": "Цена снижена", "price_up_done": "Цена поднята", "price_sum": "Цена: %@",
        "price_skip": "договорные",
        "more_t": "Для выбранных — %d шт.",
        "city_l": "Город (из списка РК)", "city_ph": "Начните вводить город…", "set": "Задать",
        "city_enter": "Введите город", "city_pick": "Выберите город из списка", "city_done": "Город задан",
        "city_sum": "Город: %@",
        "cond_l": "Состояние", "cond_new": "Новое", "cond_used": "Б/у", "cond_new_done": "Помечено новым",
        "cond_used_done": "Помечено б/у",
        "pay_l": "Оплата", "pay_inst": "Рассрочка", "pay_credit": "Кредит", "pay_off": "Выкл",
        "pay_off_done": "Оплата выключена", "pay_inst_done": "Рассрочка включена", "pay_credit_done": "Кредит включён",
        "ship_l": "Доставка", "ship_free": "Бесплатная", "ship_paid": "Платная", "ship_free_done": "Бесплатная доставка",
        "ship_paid_done": "Платная доставка", "ship_days_ph": "Срок доставки, напр. 1–3 дня",
        "ship_days_enter": "Укажите срок", "ship_days_done": "Срок доставки задан", "ship_days_sum": "Срок доставки: %@",
        "warr_l": "Гарантия Б/у · 3–730 дн (до 24 мес)", "warr_ph": "Дней · 0 чтобы убрать",
        "warr_enter": "Укажите дней: 0 убрать, иначе 3–365", "warr_done": "Гарантия %d дн.", "warr_off": "Гарантия убрана",
        "stock_l": "Склад · Опт", "stock_ph": "Количество на складе", "stock_enter": "Укажите количество",
        "stock_done": "Склад: %d", "ws_off": "Опт выключить", "ws_off_done": "Опт выключен",
        "sec_l": "Раздел магазина", "sec_none": "Без раздела", "sec_assign": "Назначить", "sec_done": "Раздел назначен",
        "sec_cleared": "Раздел снят", "sec_sum": "Раздел: %@",
        "ct_refine": "Уточнить тип",
        "ct_refine_hint": "Выберите объявления одной подкатегории (напр. только «Компьютеры»), чтобы уточнить тип — ноутбук / ПК и т.п.",
        "ct_refine_note": "Опубликованные после смены типа уйдут на повторную проверку.",
        "ct_refine_apply": "Уточнить", "ct_type_done": "Тип уточнён", "ct_pick_type": "Выберите тип", "ct_sum": "Тип: %@",
        "trash_btn": "В корзину — удалить %d шт.", "loading": "Загрузка…",
        "tbl_t": "Правка таблицей — %d", "tbl_all": "Всем сразу", "tbl_val": "значение", "tbl_apply_all": "Применить всем",
        "tbl_none": "Изменений нет", "tbl_changed": "Изменено строк: %d", "tbl_save": "Сохранить",
        "tbl_nochange": "Ничего не изменено", "tbl_saving": "Правки сохранены", "tbl_set": "«%@»: проставлено в %d",
        "f_price": "Цена", "f_cond": "Состояние", "f_city": "Город", "f_stock": "Склад", "f_warr": "Гарантия, дн",
        "pq_title": "Публикация по расписанию", "pq_w1": "объявление", "pq_w2": "объявления", "pq_w5": "объявлений",
        "pq_hours": "Часы", "pq_days": "Дни", "pq_batch": "По сколько", "pq_every": "Как часто", "pq_min": "мин",
        "pq_cancel": "Отмена", "pq_go": "Поставить в очередь", "pq_go_wait": "Ставим…", "pq_today": "сегодня",
        "pq_tomorrow": "завтра", "pq_one_day": "Оставьте хотя бы один день",
        "pq_fail": "Не получилось поставить в очередь", "pq_queued": "В очереди %d", "pq_first": "первое %@",
        "pq_skipped": "%d пропущено", "pq_nofit_s": "%d не поместилось в выбранные дни",
        "pq_pick_pub": "Выберите объявления, которые можно опубликовать",
        "pq_sum": "С %@ по %@, по %d каждые %d мин", "pq_less": "меньше", "pq_more_a": "больше",
        "promo_t": "Продвинуть — %d шт.",
        "promo_note": "ТОП и поднятия покупаются для каждого объявления отдельно — через App Store."
    ]

    private static let kk: [String: String] = [
        "hdr_add": "Қосу", "a11y_add": "Хабарландыру қосу",
        "sel_btn": "Таңдау", "sel_cancel": "Болдырмау", "a11y_check": "«%@» таңдау",
        "selected": "таңдалды", "all": "Барлығы", "none": "Барлығын алу", "done": "Дайын",
        "b_table": "Кестемен", "b_deact": "Алу", "b_price": "Баға", "b_promote": "Жылжыту", "b_more": "Тағы",
        "b_activate": "Белсендіру", "b_sched": "Кесте бойынша", "b_restore": "Қалпына келтіру",
        "b_purge": "Біржола жою",
        "nosel": "Ештеңе таңдалмады — хабарландыруларды белгілеңіз",
        "onreview": "Бұл хабарландырулар тексерісте — модерациядан кейін белсендіруге болады",
        "nothing_avail": "Әрекетке қолжетімді хабарландыру жоқ",
        "none_applicable": "Сәйкес хабарландыру жоқ",
        "pick_pub": "Жарияланған хабарландыруларды таңдаңыз",
        "pr_of": "/", "pr_done": "Дайын", "pr_deactivating": "Жариялаудан алып жатырмын…",
        "pr_activating": "Белсендіріп жатырмын…", "pr_deleting": "Себетке жойып жатырмын…",
        "pr_purging": "Біржола жойып жатырмын", "pr_applying": "Өзгерістерді қолданып жатырмын…",
        "res_done": "%d / %d — дайын", "res_review": " · %d тексерісте", "res_trash": "%d себетте",
        "res_purged": "%d / %d — біржола жойылды", "res_noslot": " · %d сыймады", "res_phone": " · %d нөмір күтуде",
        "res_test": " · тест режимі: 10-ға дейін", "res_fail": "Болмады", "res_fail_list": "Шықпады",
        "res_not_updated": "Өзгермеді: %d", "res_not_updated_why": "Сервер бұл хабарландыруларға түзетуді қабылдамады",
        "close": "Жабу",
        "need_pro": "Жаппай түзету — Kliko PRO тарифінде",
        "err_generic": "Қате", "conn_err": "Байланыс қатесі", "prohibited": "Тыйым салынған мазмұн",
        "ai_blocked": "Kliko AI бұғатталды", "slots_full": "Хабарландыру лимиті",
        "q_apply": "Қолдану", "q_cancel": "Болдырмау", "q_count": "Хабарландырулар: %d", "q_more": "тағы %d",
        "q_skip": "Өткізілді: %d", "q_skip_review": "Өткізілді: %d — тексерісте",
        "q_edit_t": "Таңдалғандарға қолдану керек пе?",
        "q_deact_t": "Жариялаудан алу — %d дана?", "q_deact_b": "Алу",
        "q_act_t": "Белсендіру — %d дана?", "q_act_s": "Әр хабарландыруды Kliko AI тексереді",
        "q_act_b": "Белсендіру",
        "q_rest_t": "Қалпына келтіру — %d дана?", "q_rest_b": "Қалпына келтіру",
        "q_trash_t": "%d хабарландыруды себетке жою керек пе?",
        "q_trash_s": "Хабарландырулар «Жойылғандар» бөліміне өтеді — сол жерден қалпына келтіруге болады.",
        "q_trash_b": "Жою",
        "q_purge_t": "Біржола жою керек пе?",
        "q_purge_s": "%d хабарландыру қалпына келтіру мүмкіндігінсіз жойылады. Бұл әрекетті болдырмау мүмкін емес.",
        "q_purge_b": "Иә, біржола жою",
        "price_t": "Баға — %d дана", "price_how": "Қаншаға", "price_down": "Төмендету", "price_up": "Көтеру",
        "price_note": "10 ₸-ге дейін дөңгелектеледі. Келісімді (бағасыз) өткізіледі.", "price_enter": "Мәнді енгізіңіз",
        "price_down_done": "Баға төмендетілді", "price_up_done": "Баға көтерілді", "price_sum": "Баға: %@",
        "price_skip": "келісімді",
        "more_t": "Таңдалғандар үшін — %d дана",
        "city_l": "Қала (ҚР тізімінен)", "city_ph": "Қаланы енгізе бастаңыз…", "set": "Орнату",
        "city_enter": "Қаланы енгізіңіз", "city_pick": "Тізімнен қаланы таңдаңыз", "city_done": "Қала орнатылды",
        "city_sum": "Қала: %@",
        "cond_l": "Күйі", "cond_new": "Жаңа", "cond_used": "Қолданылған", "cond_new_done": "Жаңа деп белгіленді",
        "cond_used_done": "Қолданылған деп белгіленді",
        "pay_l": "Төлем", "pay_inst": "Бөліп төлеу", "pay_credit": "Несие", "pay_off": "Өшір",
        "pay_off_done": "Төлем өшірілді", "pay_inst_done": "Бөліп төлеу қосылды", "pay_credit_done": "Несие қосылды",
        "ship_l": "Жеткізу", "ship_free": "Тегін", "ship_paid": "Ақылы", "ship_free_done": "Тегін жеткізу",
        "ship_paid_done": "Ақылы жеткізу", "ship_days_ph": "Жеткізу мерзімі, мыс. 1–3 күн",
        "ship_days_enter": "Мерзімді көрсетіңіз", "ship_days_done": "Жеткізу мерзімі орнатылды",
        "ship_days_sum": "Жеткізу мерзімі: %@",
        "warr_l": "Қолданылғанға кепілдік · 3–730 күн (24 айға дейін)", "warr_ph": "Күн · алып тастау үшін 0",
        "warr_enter": "Күнді көрсетіңіз: 0 — алып тастау, әйтпесе 3–365", "warr_done": "Кепілдік %d күн",
        "warr_off": "Кепілдік алынды",
        "stock_l": "Қойма · Көтерме", "stock_ph": "Қоймадағы саны", "stock_enter": "Санын көрсетіңіз",
        "stock_done": "Қойма: %d", "ws_off": "Көтермені өшіру", "ws_off_done": "Көтерме өшірілді",
        "sec_l": "Дүкен бөлімі", "sec_none": "Бөлімсіз", "sec_assign": "Тағайындау", "sec_done": "Бөлім тағайындалды",
        "sec_cleared": "Бөлім алынды", "sec_sum": "Бөлім: %@",
        "ct_refine": "Түрін нақтылау",
        "ct_refine_hint": "Түрін нақтылау үшін бір ішкі санаттағы хабарландыруларды таңдаңыз (мыс. тек «Компьютерлер») — ноутбук / ДК т.б.",
        "ct_refine_note": "Түрі өзгергеннен кейін жарияланғандар қайта тексеріске жіберіледі.",
        "ct_refine_apply": "Нақтылау", "ct_type_done": "Түрі нақтыланды", "ct_pick_type": "Түрін таңдаңыз",
        "ct_sum": "Түрі: %@",
        "trash_btn": "Себетке — %d дана жою", "loading": "Жүктелуде…",
        "tbl_t": "Кестемен түзету — %d", "tbl_all": "Барлығына бірден", "tbl_val": "мән",
        "tbl_apply_all": "Барлығына қолдану", "tbl_none": "Өзгеріс жоқ", "tbl_changed": "Өзгерген жолдар: %d",
        "tbl_save": "Сақтау", "tbl_nochange": "Ештеңе өзгерген жоқ", "tbl_saving": "Түзетулер сақталды",
        "tbl_set": "«%@»: %d жолға қойылды",
        "f_price": "Баға", "f_cond": "Күйі", "f_city": "Қала", "f_stock": "Қойма", "f_warr": "Кепілдік, күн",
        "pq_title": "Кесте бойынша жариялау", "pq_w1": "хабарландыру", "pq_w2": "хабарландыру",
        "pq_w5": "хабарландыру",
        "pq_hours": "Сағаттар", "pq_days": "Күндер", "pq_batch": "Нешеден", "pq_every": "Қаншалықты жиі",
        "pq_min": "мин", "pq_cancel": "Болдырмау", "pq_go": "Кезекке қою", "pq_go_wait": "Қоюдамыз…",
        "pq_today": "бүгін", "pq_tomorrow": "ертең", "pq_one_day": "Кемінде бір күн қалдырыңыз",
        "pq_fail": "Кезекке қою мүмкін болмады", "pq_queued": "Кезекте %d", "pq_first": "біріншісі %@",
        "pq_skipped": "%d өткізілді", "pq_nofit_s": "%d таңдалған күндерге сыймады",
        "pq_pick_pub": "Жариялауға болатын хабарландыруларды таңдаңыз",
        "pq_sum": "%@ бастап %@ дейін, %d-ден әр %d мин", "pq_less": "азырақ", "pq_more_a": "көбірек",
        "promo_t": "Жылжыту — %d дана",
        "promo_note": "ТОП пен көтерулер әр хабарландыруға бөлек сатып алынады — App Store арқылы."
    ]

    private static let en: [String: String] = [
        "hdr_add": "Add", "a11y_add": "Add a listing",
        "sel_btn": "Select", "sel_cancel": "Cancel", "a11y_check": "Select «%@»",
        "selected": "selected", "all": "All", "none": "Deselect all", "done": "Done",
        "b_table": "As table", "b_deact": "Unpublish", "b_price": "Price", "b_promote": "Promote", "b_more": "More",
        "b_activate": "Activate", "b_sched": "On schedule", "b_restore": "Restore", "b_purge": "Delete forever",
        "nosel": "Nothing selected — tick the listings",
        "onreview": "These listings are under review — they can be activated after moderation",
        "nothing_avail": "No listings available for this action",
        "none_applicable": "No applicable listings",
        "pick_pub": "Select published listings",
        "pr_of": "of", "pr_done": "Done", "pr_deactivating": "Unpublishing…", "pr_activating": "Activating…",
        "pr_deleting": "Moving to trash…", "pr_purging": "Deleting forever", "pr_applying": "Applying changes…",
        "res_done": "%d of %d — done", "res_review": " · %d under review", "res_trash": "%d in trash",
        "res_purged": "%d of %d — deleted forever", "res_noslot": " · %d didn't fit",
        "res_phone": " · %d waiting for a phone number", "res_test": " · test mode: up to 10",
        "res_fail": "Didn't work", "res_fail_list": "Failed",
        "res_not_updated": "Not changed: %d", "res_not_updated_why": "The server did not accept the edit for these listings",
        "close": "Close",
        "need_pro": "The bulk editor is part of Kliko PRO",
        "err_generic": "Error", "conn_err": "Connection error", "prohibited": "Prohibited content",
        "ai_blocked": "Kliko AI is blocked", "slots_full": "Listing limit",
        "q_apply": "Apply", "q_cancel": "Cancel", "q_count": "Listings: %d", "q_more": "and %d more",
        "q_skip": "Skipped: %d", "q_skip_review": "Skipped: %d — under review",
        "q_edit_t": "Apply to the selected?",
        "q_deact_t": "Unpublish %d listings?", "q_deact_b": "Unpublish",
        "q_act_t": "Activate %d listings?", "q_act_s": "Kliko AI will check each listing", "q_act_b": "Activate",
        "q_rest_t": "Restore %d listings?", "q_rest_b": "Restore",
        "q_trash_t": "Move %d to trash?",
        "q_trash_s": "The listings will move to «Deleted» — you can restore them from there.", "q_trash_b": "Delete",
        "q_purge_t": "Delete forever?",
        "q_purge_s": "%d listings will be destroyed with no way to restore them. This cannot be undone.",
        "q_purge_b": "Yes, delete forever",
        "price_t": "Price — %d pcs", "price_how": "By how much", "price_down": "Lower", "price_up": "Raise",
        "price_note": "Rounded to 10 ₸. Negotiable (no price) listings are skipped.", "price_enter": "Enter a value",
        "price_down_done": "Price lowered", "price_up_done": "Price raised", "price_sum": "Price: %@",
        "price_skip": "negotiable",
        "more_t": "For the selected — %d pcs",
        "city_l": "City (from the Kazakhstan list)", "city_ph": "Start typing a city…", "set": "Set",
        "city_enter": "Enter a city", "city_pick": "Pick a city from the list", "city_done": "City set",
        "city_sum": "City: %@",
        "cond_l": "Condition", "cond_new": "New", "cond_used": "Used", "cond_new_done": "Marked as new",
        "cond_used_done": "Marked as used",
        "pay_l": "Payment", "pay_inst": "Installments", "pay_credit": "Credit", "pay_off": "Off",
        "pay_off_done": "Payment options off", "pay_inst_done": "Installments on", "pay_credit_done": "Credit on",
        "ship_l": "Delivery", "ship_free": "Free", "ship_paid": "Paid", "ship_free_done": "Free delivery",
        "ship_paid_done": "Paid delivery", "ship_days_ph": "Delivery time, e.g. 1–3 days",
        "ship_days_enter": "Enter the time", "ship_days_done": "Delivery time set", "ship_days_sum": "Delivery time: %@",
        "warr_l": "Warranty for used · 3–730 days (up to 24 months)", "warr_ph": "Days · 0 to remove",
        "warr_enter": "Enter days: 0 to remove, otherwise 3–365", "warr_done": "Warranty %d days",
        "warr_off": "Warranty removed",
        "stock_l": "Stock · Wholesale", "stock_ph": "Quantity in stock", "stock_enter": "Enter the quantity",
        "stock_done": "Stock: %d", "ws_off": "Turn wholesale off", "ws_off_done": "Wholesale off",
        "sec_l": "Shop section", "sec_none": "No section", "sec_assign": "Assign", "sec_done": "Section assigned",
        "sec_cleared": "Section removed", "sec_sum": "Section: %@",
        "ct_refine": "Refine type",
        "ct_refine_hint": "Select listings from one subcategory (e.g. only «Computers») to refine the type — laptop / PC etc.",
        "ct_refine_note": "Published listings will be re-checked after the type changes.",
        "ct_refine_apply": "Refine", "ct_type_done": "Type refined", "ct_pick_type": "Pick a type", "ct_sum": "Type: %@",
        "trash_btn": "To trash — delete %d pcs", "loading": "Loading…",
        "tbl_t": "Table edit — %d", "tbl_all": "All at once", "tbl_val": "value", "tbl_apply_all": "Apply to all",
        "tbl_none": "No changes", "tbl_changed": "Rows changed: %d", "tbl_save": "Save",
        "tbl_nochange": "Nothing changed", "tbl_saving": "Edits saved", "tbl_set": "«%@»: set in %d",
        "f_price": "Price", "f_cond": "Condition", "f_city": "City", "f_stock": "Stock", "f_warr": "Warranty, days",
        "pq_title": "Scheduled publishing", "pq_w1": "listing", "pq_w2": "listings", "pq_w5": "listings",
        "pq_hours": "Hours", "pq_days": "Days", "pq_batch": "How many at a time", "pq_every": "How often",
        "pq_min": "min", "pq_cancel": "Cancel", "pq_go": "Add to queue", "pq_go_wait": "Adding…", "pq_today": "today",
        "pq_tomorrow": "tomorrow", "pq_one_day": "Keep at least one day",
        "pq_fail": "Couldn't add to the queue", "pq_queued": "Queued %d", "pq_first": "first %@",
        "pq_skipped": "%d skipped", "pq_nofit_s": "%d didn't fit into the chosen days",
        "pq_pick_pub": "Select listings that can be published",
        "pq_sum": "From %@ to %@, %d every %d min", "pq_less": "fewer", "pq_more_a": "more",
        "promo_t": "Promote — %d pcs",
        "promo_note": "TOP and bumps are bought for each listing separately — through the App Store."
    ]

    private static let ar: [String: String] = [
        "hdr_add": "إضافة", "a11y_add": "إضافة إعلان",
        "sel_btn": "تحديد", "sel_cancel": "إلغاء", "a11y_check": "تحديد «%@»",
        "selected": "محدد", "all": "الكل", "none": "إلغاء تحديد الكل", "done": "تم",
        "b_table": "كجدول", "b_deact": "إيقاف النشر", "b_price": "السعر", "b_promote": "ترويج", "b_more": "المزيد",
        "b_activate": "تفعيل", "b_sched": "حسب الجدول", "b_restore": "استعادة", "b_purge": "حذف نهائي",
        "nosel": "لم يُحدَّد شيء — ضع علامة على الإعلانات",
        "onreview": "هذه الإعلانات قيد المراجعة — يمكن تفعيلها بعد الإشراف",
        "nothing_avail": "لا توجد إعلانات متاحة لهذا الإجراء",
        "none_applicable": "لا توجد إعلانات مناسبة",
        "pick_pub": "حدد الإعلانات المنشورة",
        "pr_of": "من", "pr_done": "تم", "pr_deactivating": "جارٍ إيقاف النشر…", "pr_activating": "جارٍ التفعيل…",
        "pr_deleting": "جارٍ النقل إلى السلة…", "pr_purging": "جارٍ الحذف النهائي", "pr_applying": "جارٍ تطبيق التغييرات…",
        "res_done": "%d من %d — تم", "res_review": " · %d قيد المراجعة", "res_trash": "%d في السلة",
        "res_purged": "%d من %d — حُذفت نهائيًا", "res_noslot": " · %d لم تتسع", "res_phone": " · %d بانتظار رقم الهاتف",
        "res_test": " · وضع الاختبار: حتى 10", "res_fail": "لم ينجح", "res_fail_list": "لم ينجح",
        "res_not_updated": "لم يتغير: %d", "res_not_updated_why": "لم يقبل الخادم التعديل لهذه الإعلانات",
        "close": "إغلاق",
        "need_pro": "المحرر الجماعي ضمن باقة Kliko PRO",
        "err_generic": "خطأ", "conn_err": "خطأ في الاتصال", "prohibited": "محتوى محظور",
        "ai_blocked": "Kliko AI محظور", "slots_full": "حد الإعلانات",
        "q_apply": "تطبيق", "q_cancel": "إلغاء", "q_count": "الإعلانات: %d", "q_more": "و%d أخرى",
        "q_skip": "تم التخطي: %d", "q_skip_review": "تم التخطي: %d — قيد المراجعة",
        "q_edit_t": "تطبيق على المحدد؟",
        "q_deact_t": "إيقاف نشر %d إعلان؟", "q_deact_b": "إيقاف النشر",
        "q_act_t": "تفعيل %d إعلان؟", "q_act_s": "سيفحص Kliko AI كل إعلان", "q_act_b": "تفعيل",
        "q_rest_t": "استعادة %d إعلان؟", "q_rest_b": "استعادة",
        "q_trash_t": "نقل %d إلى السلة؟",
        "q_trash_s": "ستنتقل الإعلانات إلى قسم «المحذوفة» — ويمكن استعادتها من هناك.", "q_trash_b": "حذف",
        "q_purge_t": "حذف نهائي؟",
        "q_purge_s": "سيتم إتلاف %d إعلان دون إمكانية الاستعادة. لا يمكن التراجع عن هذا الإجراء.",
        "q_purge_b": "نعم، احذف نهائيًا",
        "price_t": "السعر — %d", "price_how": "بمقدار", "price_down": "تخفيض", "price_up": "رفع",
        "price_note": "التقريب إلى 10 ₸. تُتخطى الإعلانات بسعر قابل للتفاوض (بلا سعر).", "price_enter": "أدخل قيمة",
        "price_down_done": "تم تخفيض السعر", "price_up_done": "تم رفع السعر", "price_sum": "السعر: %@",
        "price_skip": "بسعر قابل للتفاوض",
        "more_t": "للمحدد — %d",
        "city_l": "المدينة (من قائمة كازاخستان)", "city_ph": "ابدأ بكتابة المدينة…", "set": "تعيين",
        "city_enter": "أدخل المدينة", "city_pick": "اختر مدينة من القائمة", "city_done": "تم تعيين المدينة",
        "city_sum": "المدينة: %@",
        "cond_l": "الحالة", "cond_new": "جديد", "cond_used": "مستعمل", "cond_new_done": "وُضعت علامة جديد",
        "cond_used_done": "وُضعت علامة مستعمل",
        "pay_l": "الدفع", "pay_inst": "تقسيط", "pay_credit": "ائتمان", "pay_off": "إيقاف",
        "pay_off_done": "تم إيقاف خيارات الدفع", "pay_inst_done": "تم تفعيل التقسيط", "pay_credit_done": "تم تفعيل الائتمان",
        "ship_l": "التوصيل", "ship_free": "مجاني", "ship_paid": "مدفوع", "ship_free_done": "توصيل مجاني",
        "ship_paid_done": "توصيل مدفوع", "ship_days_ph": "مدة التوصيل، مثل 1–3 أيام",
        "ship_days_enter": "حدد المدة", "ship_days_done": "تم تعيين مدة التوصيل", "ship_days_sum": "مدة التوصيل: %@",
        "warr_l": "ضمان المستعمل · 3–730 يومًا (حتى 24 شهرًا)", "warr_ph": "أيام · 0 للإزالة",
        "warr_enter": "حدد الأيام: 0 للإزالة، وإلا 3–365", "warr_done": "ضمان %d يومًا", "warr_off": "تمت إزالة الضمان",
        "stock_l": "المخزون · الجملة", "stock_ph": "الكمية في المخزون", "stock_enter": "حدد الكمية",
        "stock_done": "المخزون: %d", "ws_off": "إيقاف الجملة", "ws_off_done": "تم إيقاف الجملة",
        "sec_l": "قسم المتجر", "sec_none": "بلا قسم", "sec_assign": "تعيين", "sec_done": "تم تعيين القسم",
        "sec_cleared": "تمت إزالة القسم", "sec_sum": "القسم: %@",
        "ct_refine": "تحديد النوع",
        "ct_refine_hint": "حدد إعلانات من فئة فرعية واحدة (مثل «الحواسيب» فقط) لتحديد النوع — حاسوب محمول / مكتبي إلخ.",
        "ct_refine_note": "ستُعاد مراجعة الإعلانات المنشورة بعد تغيير النوع.",
        "ct_refine_apply": "تحديد", "ct_type_done": "تم تحديد النوع", "ct_pick_type": "اختر النوع", "ct_sum": "النوع: %@",
        "trash_btn": "إلى السلة — حذف %d", "loading": "جارٍ التحميل…",
        "tbl_t": "تعديل كجدول — %d", "tbl_all": "للكل دفعة واحدة", "tbl_val": "القيمة", "tbl_apply_all": "تطبيق على الكل",
        "tbl_none": "لا تغييرات", "tbl_changed": "الصفوف المعدلة: %d", "tbl_save": "حفظ",
        "tbl_nochange": "لم يتغير شيء", "tbl_saving": "تم حفظ التعديلات", "tbl_set": "«%@»: عُيّن في %d",
        "f_price": "السعر", "f_cond": "الحالة", "f_city": "المدينة", "f_stock": "المخزون", "f_warr": "الضمان، أيام",
        "pq_title": "النشر حسب الجدول", "pq_w1": "إعلان", "pq_w2": "إعلانات", "pq_w5": "إعلانًا",
        "pq_hours": "الساعات", "pq_days": "الأيام", "pq_batch": "كم في كل مرة", "pq_every": "كم مرة",
        "pq_min": "د", "pq_cancel": "إلغاء", "pq_go": "إضافة إلى الطابور", "pq_go_wait": "جارٍ الإضافة…",
        "pq_today": "اليوم", "pq_tomorrow": "غدًا", "pq_one_day": "اترك يومًا واحدًا على الأقل",
        "pq_fail": "تعذّرت الإضافة إلى الطابور", "pq_queued": "في الطابور %d", "pq_first": "الأول %@",
        "pq_skipped": "تم تخطي %d", "pq_nofit_s": "%d لم تتسع في الأيام المختارة",
        "pq_pick_pub": "حدد إعلانات يمكن نشرها",
        "pq_sum": "من %@ إلى %@، %d كل %d د", "pq_less": "أقل", "pq_more_a": "أكثر",
        "promo_t": "ترويج — %d",
        "promo_note": "تُشترى الـTOP والرفعات لكل إعلان على حدة — عبر App Store."
    ]
}
