import Foundation

/**
 ТЕКСТЫ НАТИВНОГО ПОТОКА eGov. Русские — дословно из словарей сайта: js/i18n-cabinet-ru.js (ключи bio, otp, iin_taken,
 egov_success, sec_egov_confirm) и EGT экрана входа (need_agree, phone_opt). Остальные (шаги, «как это пройдёт»,
 лист eGov) — свои: у сайта их нет, у него одно окно с iframe.
 */
enum ТекстыEgov {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    /// Арабский — справа налево.
    static var справаНалево: Bool {
        String((Locale.preferredLanguages.first ?? "ru").prefix(2)) == "ar"
    }

    /// locale окна biometric.kz: kz / ru / en, как у сайта (арабского у eGov нет — ru).
    static var языкEgov: String {
        switch String((Locale.preferredLanguages.first ?? "ru").prefix(2)) {
        case "kk": return "kz"
        case "en": return "en"
        default: return "ru"
        }
    }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    private static let ru: [String: String] = [
        "title_kyc": "Верификация через eGov",
        "title_confirm": "Подтвердите вход через eGov",
        "otp_title": "Подтверждение по eGov",
        "otp_hint": "Подтвердите действие кодом из SMS (eGov). Проверьте ИИН и телефон.",
        "hint_kyc": "Введите ИИН и телефон, привязанный в eGov. Дальше подтвердите вход кодом из SMS — на защищённом экране eGov.",
        "hint_login": "Введите ИИН и телефон, привязанный в eGov. Подтвердите код из SMS — и вы сразу войдёте с верификацией.",
        "confirm_s": "Пароль верный. В этом аккаунте включена защита входа: подтвердите, что это вы, кодом из SMS на экране eGov. Номер и ИИН — те, что привязаны к аккаунту.",
        "why": "Проверка личности через eGov — около минуты, нужен код из SMS. После неё объявления выходят на витрину, а оплата идёт через гаранта.",
        "iin": "ИИН",
        "phone": "Телефон (привязан в eGov)",
        "phone_opt": "— можно не вводить при восстановлении по ИИН",
        "phone_short": "Телефон",
        "phone_must": "Номер обязательно должен быть привязан к вашему eGov. С другим номером проверка не пройдёт.",
        "need_phone": "Укажите телефон, привязанный в eGov",
        "need_agree": "Необходимо принять условия площадки",
        "need_iin": "ИИН — 12 цифр",
        "continue": "Продолжить",
        "starting": "Запускаем безопасную верификацию…",
        "sec_note": "Данные передаются в зашифрованном виде. Код из SMS вы вводите только на экране eGov — мы его не видим.",
        "cfm_t": "Проверьте данные",
        "cfm_m": "Этот номер привязан к вашему eGov, а ИИН верный?",
        "cfm_ok": "Да, верно",
        "cfm_edit": "Изменить",
        "confirm_wait": "Подтвердите код из SMS на экране eGov.",
        "wait_s": "Экран eGov открыт поверх: введите там код из SMS и пройдите проверку лица. Итог приложение узнает само.",
        "reopen": "Открыть экран eGov",
        "cancel": "Отменить",
        "checking": "Ждём ответ eGov…",
        "timeout": "Время подтверждения истекло. Проверьте код из SMS и попробуйте ещё раз.",
        "succ_title": "Поздравляем!",
        "succ_msg": "Вы прошли верификацию. Аккаунт подтверждён — доступны безопасные сделки.",
        "step_ok": "Подтверждено через eGov",
        "done_ok": "Готово",
        "ok_new": "Готово! Аккаунт создан и верифицирован. Входим…",
        "ok_login": "Готово! Вы вошли, аккаунт верифицирован. Загружаем…",
        "alert_title": "Не удалось",
        "retry": "Повторить",
        "alert_ok": "Понятно",
        "iin_taken": "Этот ИИН уже зарегистрирован на другом аккаунте.",
        "iin_taken_t": "ИИН уже зарегистрирован",
        "start_fail": "Не удалось отправить код и начать верификацию. Попробуйте ещё раз.",
        "not_passed": "Проверка eGov не пройдена. Попробуйте ещё раз: номер должен быть привязан к eGov, код — из последнего SMS.",
        "page_stale": "Страница устарела — обновите её и попробуйте снова.",
        "need_login": "Вы вышли из аккаунта на этом устройстве. Войдите снова и повторите проверку.",
        "srv_err": "Сервер не ответил на проверку. Попробуйте ещё раз через минуту — если повторится, напишите в поддержку.",
        "net_fail": "Не удалось связаться с сервером. Попробуйте ещё раз.",
        "tech": "Тех. деталь",
        "fail_face": "Не удалось распознать лицо. Встаньте лицом к свету, снимите очки и головной убор, держите камеру на уровне глаз — и попробуйте ещё раз. С компьютера не получается — пройдите с телефона.",
        "fail_otp": "Неверный или просроченный код из SMS. Запросите новый и попробуйте снова.",
        "fail_mcdb": "Ваших биометрических данных нет в базе eGov. Скорее всего, вы не проходили биометрическую регистрацию — обратитесь в ЦОН, затем повторите.",
        "fail_document": "Нет доступа к документу в eGov: код мог истечь. Попробуйте ещё раз.",
        "fail_expired": "Время проверки истекло. Начните её заново.",
        "fail_generic_face": "Проверка не пройдена: не удалось подтвердить лицо или код из SMS. Встаньте лицом к свету, снимите очки — и попробуйте ещё раз.",
        "close": "Закрыть",
        "back": "Назад",
        "step_data": "Данные",
        "step_egov": "eGov",
        "step_done": "Готово",
        "how_t": "Как это пройдёт",
        "how1_t": "ИИН и номер — здесь",
        "how1_s": "Номер должен быть привязан к вашему eGov.",
        "how2_t": "Код из SMS и лицо — на экране eGov",
        "how2_s": "Защищённая страница eGov откроется поверх; камера нужна для проверки лица.",
        "how3_t": "Итог — сразу здесь",
        "how3_s": "Приложение само узнает результат, ничего обновлять не нужно.",
        "web_title": "eGov",
        "web_a11y": "Экран проверки eGov"
    ]

    private static let kk: [String: String] = [
        "title_kyc": "eGov арқылы верификация",
        "title_confirm": "Кіруді eGov арқылы растаңыз",
        "otp_title": "eGov арқылы растау",
        "otp_hint": "Әрекетті SMS кодымен (eGov) растаңыз. ЖСН мен телефонды тексеріңіз.",
        "hint_kyc": "ЖСН мен eGov-қа байланған телефонды енгізіңіз. Кейін кіруді SMS кодымен eGov-тың қорғалған экранында растайсыз.",
        "hint_login": "ЖСН мен eGov-қа байланған телефонды енгізіңіз. SMS кодын растаңыз — және бірден верификациямен кіресіз.",
        "confirm_s": "Құпиясөз дұрыс. Бұл аккаунтта кіруді қорғау қосулы: бұл сіз екеніңізді eGov экранындағы SMS кодымен растаңыз. Нөмір мен ЖСН — аккаунтқа байланғандары.",
        "why": "eGov арқылы жеке басты тексеру — шамамен бір минут, SMS коды керек. Одан кейін хабарландырулар витринаға шығады, ал төлем кепіл арқылы өтеді.",
        "iin": "ЖСН",
        "phone": "Телефон (eGov-қа байланған)",
        "phone_opt": "— ЖСН бойынша қалпына келтіргенде енгізбеуге болады",
        "phone_short": "Телефон",
        "phone_must": "Нөмір міндетті түрде сіздің eGov-қа байланған болуы керек. Басқа нөмірмен тексеру өтпейді.",
        "need_phone": "eGov-қа байланған телефонды көрсетіңіз",
        "need_agree": "Алаң шарттарын қабылдау қажет",
        "need_iin": "ЖСН — 12 сан",
        "continue": "Жалғастыру",
        "starting": "Қауіпсіз верификацияны іске қосып жатырмыз…",
        "sec_note": "Деректер шифрланып жіберіледі. SMS кодын тек eGov экранына енгізесіз — біз оны көрмейміз.",
        "cfm_t": "Деректерді тексеріңіз",
        "cfm_m": "Бұл нөмір сіздің eGov-қа байланған ба, ал ЖСН дұрыс па?",
        "cfm_ok": "Иә, дұрыс",
        "cfm_edit": "Өзгерту",
        "confirm_wait": "SMS кодын eGov экранында растаңыз.",
        "wait_s": "eGov экраны үстінен ашық: сонда SMS кодын енгізіп, бетті тексеруден өтіңіз. Нәтижені қосымша өзі біледі.",
        "reopen": "eGov экранын ашу",
        "cancel": "Бас тарту",
        "checking": "eGov жауабын күтеміз…",
        "timeout": "Растау уақыты өтіп кетті. SMS кодын тексеріп, қайталап көріңіз.",
        "succ_title": "Құттықтаймыз!",
        "succ_msg": "Сіз верификациядан өттіңіз. Аккаунт расталды — қауіпсіз мәмілелер қолжетімді.",
        "step_ok": "eGov арқылы расталды",
        "done_ok": "Дайын",
        "ok_new": "Дайын! Аккаунт құрылып, верификацияланды. Кіріп жатырмыз…",
        "ok_login": "Дайын! Сіз кірдіңіз, аккаунт верификацияланған. Жүктеп жатырмыз…",
        "alert_title": "Сәтсіз",
        "retry": "Қайталау",
        "alert_ok": "Түсінікті",
        "iin_taken": "Бұл ЖСН басқа аккаунтта тіркелген.",
        "iin_taken_t": "ЖСН тіркелген",
        "start_fail": "Кодты жіберіп, верификацияны бастау мүмкін болмады. Қайталап көріңіз.",
        "not_passed": "eGov тексеруі өтпеді. Қайталап көріңіз: нөмір eGov-қа байланған, код — соңғы SMS-тен болуы керек.",
        "page_stale": "Бет ескірді — оны жаңартып, қайталап көріңіз.",
        "need_login": "Сіз осы құрылғыда аккаунттан шықтыңыз. Қайта кіріп, тексеруді қайталаңыз.",
        "srv_err": "Сервер тексеруге жауап бермеді. Бір минуттан кейін қайталаңыз — қайталанса, қолдау қызметіне жазыңыз.",
        "net_fail": "Сервермен байланысу мүмкін болмады. Қайталап көріңіз.",
        "tech": "Тех. мәлімет",
        "fail_face": "Бетті тану мүмкін болмады. Жарыққа қарай тұрыңыз, көзілдірік пен бас киімді шешіңіз, камераны көз деңгейінде ұстаңыз — және қайталаңыз. Компьютерден болмаса — телефоннан өтіңіз.",
        "fail_otp": "SMS коды қате немесе мерзімі өткен. Жаңасын сұрап, қайталаңыз.",
        "fail_mcdb": "Сіздің биометриялық деректеріңіз eGov базасында жоқ. Сірә, биометриялық тіркеуден өтпегенсіз — ХҚКО-ға жүгініп, кейін қайталаңыз.",
        "fail_document": "eGov-тағы құжатқа қолжетімділік жоқ: кодтың мерзімі өтуі мүмкін. Қайталап көріңіз.",
        "fail_expired": "Тексеру уақыты өтті. Оны қайта бастаңыз.",
        "fail_generic_face": "Тексеру өтпеді: бетті немесе SMS кодын растау мүмкін болмады. Жарыққа қарай тұрып, көзілдірікті шешіңіз — және қайталаңыз.",
        "close": "Жабу",
        "back": "Артқа",
        "step_data": "Деректер",
        "step_egov": "eGov",
        "step_done": "Дайын",
        "how_t": "Бұл қалай өтеді",
        "how1_t": "ЖСН мен нөмір — осында",
        "how1_s": "Нөмір сіздің eGov-қа байланған болуы керек.",
        "how2_t": "SMS коды мен бет — eGov экранында",
        "how2_s": "eGov-тың қорғалған беті үстінен ашылады; камера бетті тексеру үшін керек.",
        "how3_t": "Нәтиже — бірден осында",
        "how3_s": "Қосымша нәтижені өзі біледі, ештеңені жаңартудың қажеті жоқ.",
        "web_title": "eGov",
        "web_a11y": "eGov тексеру экраны"
    ]

    private static let en: [String: String] = [
        "title_kyc": "eGov verification",
        "title_confirm": "Confirm sign-in via eGov",
        "otp_title": "eGov confirmation",
        "otp_hint": "Confirm the action with the SMS code (eGov). Check your IIN and phone.",
        "hint_kyc": "Enter your IIN and the phone linked in eGov. Then confirm with the SMS code on the secure eGov screen.",
        "hint_login": "Enter your IIN and the phone linked in eGov. Confirm the SMS code — and you're signed in, verified.",
        "confirm_s": "The password is correct. This account has sign-in protection: confirm it's you with the SMS code on the eGov screen. The number and IIN are the ones linked to the account.",
        "why": "Identity check via eGov takes about a minute and needs an SMS code. After it, your listings go live and payments go through the escrow.",
        "iin": "IIN",
        "phone": "Phone (linked in eGov)",
        "phone_opt": "— optional when recovering by IIN",
        "phone_short": "Phone",
        "phone_must": "The number must be linked to your eGov. With another number the check won't pass.",
        "need_phone": "Enter the phone linked in eGov",
        "need_agree": "Please accept the marketplace terms",
        "need_iin": "IIN — 12 digits",
        "continue": "Continue",
        "starting": "Starting secure verification…",
        "sec_note": "Data is sent encrypted. You enter the SMS code only on the eGov screen — we don't see it.",
        "cfm_t": "Check your details",
        "cfm_m": "Is this number linked to your eGov, and is the IIN correct?",
        "cfm_ok": "Yes, correct",
        "cfm_edit": "Edit",
        "confirm_wait": "Confirm the SMS code on the eGov screen.",
        "wait_s": "The eGov screen is open on top: enter the SMS code there and pass the face check. The app will learn the result by itself.",
        "reopen": "Open the eGov screen",
        "cancel": "Cancel",
        "checking": "Waiting for eGov…",
        "timeout": "Confirmation time is up. Check the SMS code and try again.",
        "succ_title": "Congratulations!",
        "succ_msg": "You're verified. The account is confirmed — safe deals are available.",
        "step_ok": "Confirmed via eGov",
        "done_ok": "Done",
        "ok_new": "Done! The account is created and verified. Signing in…",
        "ok_login": "Done! You're signed in and verified. Loading…",
        "alert_title": "Something went wrong",
        "retry": "Retry",
        "alert_ok": "OK",
        "iin_taken": "This IIN is already registered to another account.",
        "iin_taken_t": "IIN already registered",
        "start_fail": "Couldn't send the code and start verification. Please try again.",
        "not_passed": "The eGov check didn't pass. Try again: the number must be linked to eGov and the code must be from the latest SMS.",
        "page_stale": "The page is outdated — refresh it and try again.",
        "need_login": "You've signed out on this device. Sign in again and repeat the check.",
        "srv_err": "The server didn't respond to the check. Try again in a minute — if it repeats, contact support.",
        "net_fail": "Couldn't reach the server. Please try again.",
        "tech": "Tech detail",
        "fail_face": "We couldn't recognise your face. Face the light, remove glasses and headwear, hold the camera at eye level — and try again. If it fails on a computer, use your phone.",
        "fail_otp": "Wrong or expired SMS code. Request a new one and try again.",
        "fail_mcdb": "Your biometric data isn't in the eGov database. You probably haven't done biometric registration — visit a PSC, then try again.",
        "fail_document": "No access to the document in eGov: the code may have expired. Please try again.",
        "fail_expired": "The check has expired. Start it again.",
        "fail_generic_face": "Check failed: couldn't confirm your face or the SMS code. Face the light, remove glasses — and try again.",
        "close": "Close",
        "back": "Back",
        "step_data": "Details",
        "step_egov": "eGov",
        "step_done": "Done",
        "how_t": "How it works",
        "how1_t": "IIN and number — here",
        "how1_s": "The number must be linked to your eGov.",
        "how2_t": "SMS code and face — on the eGov screen",
        "how2_s": "The secure eGov page opens on top; the camera is needed for the face check.",
        "how3_t": "The result — right here",
        "how3_s": "The app learns the result by itself, nothing to refresh.",
        "web_title": "eGov",
        "web_a11y": "eGov check screen"
    ]

    private static let ar: [String: String] = [
        "title_kyc": "التحقق عبر eGov",
        "title_confirm": "أكّد تسجيل الدخول عبر eGov",
        "otp_title": "التأكيد عبر eGov",
        "otp_hint": "أكّد الإجراء برمز SMS (eGov). تحقق من الرقم الفردي والهاتف.",
        "hint_kyc": "أدخل الرقم الفردي والهاتف المرتبط في eGov. ثم أكّد برمز SMS على شاشة eGov الآمنة.",
        "hint_login": "أدخل الرقم الفردي والهاتف المرتبط في eGov. أكّد رمز SMS — وستدخل فورًا بحساب موثّق.",
        "confirm_s": "كلمة المرور صحيحة. في هذا الحساب حماية تسجيل الدخول مفعّلة: أكّد أنك أنت برمز SMS على شاشة eGov. الرقم والرقم الفردي هما المرتبطان بالحساب.",
        "why": "التحقق من الهوية عبر eGov يستغرق دقيقة تقريبًا ويتطلب رمز SMS. بعده تظهر إعلاناتك في الواجهة ويتم الدفع عبر الضامن.",
        "iin": "الرقم الفردي (IIN)",
        "phone": "الهاتف (المرتبط في eGov)",
        "phone_opt": "— يمكن تركه فارغًا عند الاستعادة بالرقم الفردي",
        "phone_short": "الهاتف",
        "phone_must": "يجب أن يكون الرقم مرتبطًا بحسابك في eGov. برقم آخر لن ينجح التحقق.",
        "need_phone": "أدخل الهاتف المرتبط في eGov",
        "need_agree": "يجب قبول شروط المنصة",
        "need_iin": "الرقم الفردي — 12 رقمًا",
        "continue": "متابعة",
        "starting": "نبدأ التحقق الآمن…",
        "sec_note": "تُرسل البيانات مشفّرة. تُدخل رمز SMS على شاشة eGov فقط — ونحن لا نراه.",
        "cfm_t": "تحقّق من البيانات",
        "cfm_m": "هل هذا الرقم مرتبط بحسابك في eGov، والرقم الفردي صحيح؟",
        "cfm_ok": "نعم، صحيح",
        "cfm_edit": "تعديل",
        "confirm_wait": "أكّد رمز SMS على شاشة eGov.",
        "wait_s": "شاشة eGov مفتوحة في الأعلى: أدخل فيها رمز SMS واجتز التحقق من الوجه. سيعرف التطبيق النتيجة بنفسه.",
        "reopen": "فتح شاشة eGov",
        "cancel": "إلغاء",
        "checking": "بانتظار رد eGov…",
        "timeout": "انتهى وقت التأكيد. تحقّق من رمز SMS وحاول مرة أخرى.",
        "succ_title": "تهانينا!",
        "succ_msg": "اجتزت التحقق. الحساب مؤكَّد — الصفقات الآمنة متاحة.",
        "step_ok": "تم التأكيد عبر eGov",
        "done_ok": "تم",
        "ok_new": "تم! أُنشئ الحساب وتم توثيقه. جارٍ الدخول…",
        "ok_login": "تم! دخلت والحساب موثّق. جارٍ التحميل…",
        "alert_title": "تعذّر ذلك",
        "retry": "إعادة المحاولة",
        "alert_ok": "حسنًا",
        "iin_taken": "هذا الرقم الفردي مسجّل بالفعل في حساب آخر.",
        "iin_taken_t": "الرقم الفردي مسجّل بالفعل",
        "start_fail": "تعذّر إرسال الرمز وبدء التحقق. حاول مرة أخرى.",
        "not_passed": "لم ينجح تحقق eGov. حاول مرة أخرى: يجب أن يكون الرقم مرتبطًا بـ eGov والرمز من آخر رسالة SMS.",
        "page_stale": "الصفحة قديمة — حدّثها وحاول مرة أخرى.",
        "need_login": "خرجت من الحساب على هذا الجهاز. سجّل الدخول مجددًا وكرّر التحقق.",
        "srv_err": "لم يستجب الخادم للتحقق. حاول بعد دقيقة — وإن تكرر، راسل الدعم.",
        "net_fail": "تعذّر الاتصال بالخادم. حاول مرة أخرى.",
        "tech": "تفصيل تقني",
        "fail_face": "تعذّر التعرّف على الوجه. قف مواجهًا للضوء، وانزع النظارة وغطاء الرأس، وأمسك الكاميرا بمستوى العينين — ثم حاول مجددًا. إن لم ينجح من الحاسوب — استخدم الهاتف.",
        "fail_otp": "رمز SMS خاطئ أو منتهي الصلاحية. اطلب رمزًا جديدًا وحاول مجددًا.",
        "fail_mcdb": "بياناتك الحيوية غير موجودة في قاعدة eGov. على الأرجح لم تجتز التسجيل الحيوي — راجع مركز خدمة السكان ثم أعد المحاولة.",
        "fail_document": "لا وصول إلى الوثيقة في eGov: ربما انتهت صلاحية الرمز. حاول مرة أخرى.",
        "fail_expired": "انتهى وقت التحقق. ابدأه من جديد.",
        "fail_generic_face": "لم ينجح التحقق: تعذّر تأكيد الوجه أو رمز SMS. قف مواجهًا للضوء وانزع النظارة — ثم حاول مجددًا.",
        "close": "إغلاق",
        "back": "رجوع",
        "step_data": "البيانات",
        "step_egov": "eGov",
        "step_done": "تم",
        "how_t": "كيف يتم ذلك",
        "how1_t": "الرقم الفردي والهاتف — هنا",
        "how1_s": "يجب أن يكون الرقم مرتبطًا بحسابك في eGov.",
        "how2_t": "رمز SMS والوجه — على شاشة eGov",
        "how2_s": "تُفتح صفحة eGov الآمنة في الأعلى؛ الكاميرا لازمة للتحقق من الوجه.",
        "how3_t": "النتيجة — هنا مباشرة",
        "how3_s": "يعرف التطبيق النتيجة بنفسه، لا حاجة إلى التحديث.",
        "web_title": "eGov",
        "web_a11y": "شاشة تحقق eGov"
    ]
}
