// Мост окна к основному процессу: только нужные действия, без доступа к Node.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('app', {
  state: () => ipcRenderer.invoke('state'),
  save: (patch) => ipcRenderer.invoke('save', patch),
  forgetToken: () => ipcRenderer.invoke('forget-token'),
  start: () => ipcRenderer.invoke('start'),
  stop: () => ipcRenderer.invoke('stop'),
  restart: () => ipcRenderer.invoke('restart'),
  probe: (url) => ipcRenderer.invoke('probe', url),
  why: (id) => ipcRenderer.invoke('why', id),
  openData: () => ipcRenderer.invoke('open-data'),
  openUrl: (url) => ipcRenderer.invoke('open-url', url),
  users: () => ipcRenderer.invoke('users'),
  grant: (userId, days, product) => ipcRenderer.invoke('grant', { userId, days, product }),
  revoke: (userId) => ipcRenderer.invoke('revoke', { userId }),
  vipOptions: () => ipcRenderer.invoke('vip-options'),
  vipGrant: (userId, path, city, days) => ipcRenderer.invoke('vip-grant', { userId, path, city, days }),
  vipEnd: (lockId) => ipcRenderer.invoke('vip-end', { lockId }),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  deploy: (opts) => ipcRenderer.invoke('deploy', opts),
  bringBack: (opts) => ipcRenderer.invoke('bring-back', opts),
  serverStatus: (opts) => ipcRenderer.invoke('server-status', opts),
  serverRestart: (opts) => ipcRenderer.invoke('server-restart', opts),
  onDeployLog: (fn) => ipcRenderer.on('deploy-log', (_e, text) => fn(text)),
  onState: (fn) => ipcRenderer.on('state', (_e, s) => fn(s)),
  onLog: (fn) => ipcRenderer.on('log', (_e, lines) => fn(lines)),
  onProbe: (fn) => ipcRenderer.on('probe', (_e, text) => fn(text)),
});
