import Foundation

/// Тексты этапа 38 — чат по объявлению и «Предложить цену» — на языке телефона (kk/ru/en/ar), тем же способом, что
/// лента (FeedText).
///
/// Русские слова — сайта (js/i18n-marketplace-ru.js, разметка #mk-chat-scrim страницы объявления и строки в
/// js/marketplace.min.js), а не придуманные: «Чат с продавцом» — chat_with_seller, «Kliko AI-ассистент отвечает · » —
/// ai_replying, «Продавец · » и «на связи» — seller_pfx и online_now, «Продавец скоро подключится» — seller_soon, «Нет
/// соединения — переподключение…» — reconnecting, «Объявление» — listing_word, «Продано» / «Услуга больше не актуальна» /
/// «Объект сдан» — chat_gone_*, «Все товары продавца» / «Все услуги продавца» — chat_seller_*, «Продавец» —
/// dl_role_seller, «Kliko AI-ассистент» — ai_assistant, приветствие ассистента, «Продавец на связи», «С вами продавец»,
/// «Продавец уведомлён и скоро подключится», «Зову продавца — он скоро подключится», «Продавец уведомлён — подключится, как
/// будет онлайн», «Не удалось — попробуйте ещё раз», «✓✓ Прочитано» / «✓ Отправлено», «Не удалось загрузить чат», «Нет
/// соединения», «из Telegram», тексты окон входа и верификации («Войти / Регистрация», «Пройти верификацию») — строки
/// mkChatOpen, mkChatRender, mkChatSendNow, mkChatCallSeller, mkViaTg; «Позвать продавца» и «Напишите сообщение…» —
/// разметка; карточки предложения — of_* (of_mine, of_gone, of_replaced, of_ctr_answered, of_accepted, of_used, of_held,
/// of_m_*, of_mon, of_ctr_*); гео — mkGeoCard и call_yandex, on_map; блокировка — chat_you_blocked,
/// chat_seller_blocked, unblock, request_unblock, unblock_req_sent, failed; полоса сделки — of_ctr_took, deal_go,
/// deal_live_h, co_goto; окно предложения — offer_sticky_t, offer_seller_price, offer_sub_haggle, offer_dial_l,
/// offer_dial_hint, offer_own, offer_save, offer_over, offer_under, offer_args_h, arg_pickup, arg_take_both, arg_pickup_s,
/// offer_send; «Покупатели» — вкладка лидов кабинета (msg-filters).
///
/// Своих строк у сайта нет для «Собеседник печатает» (VoiceOver у трёх точек), «Закрыть» (aria-label «×» окна
/// предложения — есть у сайта только разметкой), «Повторить» (как у ленты) и для «Лимит Kliko AI-ассистента исчерпан.» —
/// это начало строки сайта без призыва оформить подписку: покупок цифрового внутри приложения не предлагаем (как
/// klkAppNoDigital сайта прячет продвижение в приложении).
enum ListingChatText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? тексты["ru"]!
        return словарь[ключ] ?? тексты["ru"]![ключ] ?? ключ
    }

    static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    private static let тексты: [String: [String: String]] = [
        "ru": [
            "title": "Чат с продавцом", "sub_ai": "Kliko AI-ассистент отвечает · %@", "seller_lc": "продавец",
            "sub_seller": "Продавец · %@", "online_now": "на связи", "sub_soon": "Продавец скоро подключится",
            "reconnecting": "Нет соединения — переподключение…", "listing": "Объявление",
            "gone_goods": "Продано", "gone_service": "Услуга больше не актуальна", "gone_rent": "Объект сдан",
            "seller_goods": "Все товары продавца", "seller_services": "Все услуги продавца",
            "who_seller": "Продавец", "who_ai": "Kliko AI-ассистент", "via_tg": "из Telegram",
            "greeting": "Здравствуйте! Я Kliko AI-ассистент продавца. Спрашивайте о товаре — отвечу сразу. Когда будете готовы купить, подключу продавца.",
            "loading": "Загрузка…", "load_failed": "Не удалось загрузить чат", "no_conn": "Нет соединения",
            "retry": "Повторить", "read": "✓✓ Прочитано", "sent": "✓ Отправлено",
            "st_online": "Продавец на связи", "st_with": "С вами продавец",
            "st_hot": "Продавец уведомлён и скоро подключится",
            "escalated": "Зову продавца — он скоро подключится",
            "called": "Продавец уведомлён — подключится, как будет онлайн",
            "call_failed": "Не удалось — попробуйте ещё раз", "call_seller": "Позвать продавца",
            "typing": "Собеседник печатает",
            "of_mine": "Ваше предложение", "of_gone": "Отозвано", "of_replaced": "Заменено новым предложением",
            "of_ctr_answered": "Вы приняли встречную цену · {sum}", "of_accepted": "Принято продавцом",
            "of_used": "Договорённость использована", "of_held": "Подкреплено",
            "of_m_inst": "В рассрочку", "of_m_cred": "В кредит", "of_m_cash": "Наличными", "of_mon": "мес",
            "of_ctr_seller": "Встречная цена продавца", "of_ctr_plus": "+{step}% к вашим {sum}",
            "of_ctr_took": "Цена согласована", "of_ctr_refused": "Вы отказались",
            "of_ctr_gone": "Неактуально — вы предложили новую цену",
            "of_ctr_take": "Принять · {sum}", "of_ctr_no": "Отказаться",
            "geo_me": "Вы отправили геолокацию", "geo_seller": "Геолокация — точка доставки",
            "call_yandex": "Вызвать (Яндекс)", "gis": "2ГИС", "on_map": "На карте",
            "gate_ai": "Чтобы пообщаться с Kliko AI-ассистентом, войдите или зарегистрируйтесь — это быстро.",
            "gate_seller": "Войдите, чтобы написать продавцу — это быстро.", "gate_login": "Войти / Регистрация",
            "gate_verify": "Пройдите верификацию в кабинете, чтобы продолжить.",
            "gate_verify_free": "Бесплатный период закончился. Пройдите верификацию, чтобы продолжить.",
            "gate_verify_btn": "Пройти верификацию", "gate_paid": "Лимит Kliko AI-ассистента исчерпан.",
            "blocked_toast": "Общение недоступно — блокировка",
            "you_blocked": "Вы заблокировали продавца — общение недоступно. История сохранена.",
            "seller_blocked": "Продавец ограничил общение. Можно отправить запрос на разблокировку раз в 72 часа.",
            "unblock": "Разблокировать", "request_unblock": "Запросить разблокировку",
            "unblock_req_sent": "Запрос на разблокировку отправлен продавцу", "failed": "Не удалось",
            "agreed": "Цена согласована · %@", "deal_go": "Оформить за %@", "deal_live": "Сделка оформлена",
            "deal_open": "Перейти к сделке", "placeholder": "Напишите сообщение…", "buyers": "Покупатели",
            "offer_seller_price": "Цена продавца:",
            "offer_sub": "Не готовы по этой цене — предложите свою: сумма уйдёт продавцу в чат, оплата после согласия.",
            "offer_dial": "Ваша цена", "offer_hint": "Потяните ползунок — предложите свою цену",
            "offer_own": "Или своя сумма", "offer_save": "экономия %@",
            "offer_over": "Выше цены продавца предлагать незачем — для этого есть «Купить безопасно»",
            "offer_under": "Больше {n}% скидки предложить нельзя", "offer_args": "Чем подкрепить просьбу",
            "arg_pickup": "Заберу сам", "arg_take_both": "Заберу или оплачу доставку сам",
            "arg_pickup_s": "вам не нужно возиться с передачей", "offer_send": "Отправить предложение",
            "close": "Закрыть"
        ],
        "kk": [
            "title": "Сатушымен чат", "sub_ai": "Kliko AI-көмекшісі жауап береді · %@", "seller_lc": "сатушы",
            "sub_seller": "Сатушы · %@", "online_now": "байланыста", "sub_soon": "Сатушы жақында қосылады",
            "reconnecting": "Байланыс жоқ — қайта қосылуда…", "listing": "Хабарландыру",
            "gone_goods": "Сатылды", "gone_service": "Қызмет енді өзекті емес", "gone_rent": "Нысан жалға берілді",
            "seller_goods": "Сатушының барлық тауарлары", "seller_services": "Сатушының барлық қызметтері",
            "who_seller": "Сатушы", "who_ai": "Kliko AI-көмекшісі", "via_tg": "Telegram-нан",
            "greeting": "Сәлеметсіз бе! Мен сатушының Kliko AI-көмекшісімін. Тауар туралы сұраңыз — бірден жауап беремін. Сатып алуға дайын болғанда, сатушыны қосамын.",
            "loading": "Жүктелуде…", "load_failed": "Чатты жүктеу мүмкін болмады", "no_conn": "Байланыс жоқ",
            "retry": "Қайталау", "read": "✓✓ Оқылды", "sent": "✓ Жіберілді",
            "st_online": "Сатушы байланыста", "st_with": "Сізбен сатушы",
            "st_hot": "Сатушыға хабарланды, жақында қосылады",
            "escalated": "Сатушыны шақырып жатырмын — ол жақында қосылады",
            "called": "Сатушыға хабарланды — желіге шыққанда қосылады",
            "call_failed": "Болмады — қайталап көріңіз", "call_seller": "Сатушыны шақыру",
            "typing": "Әңгімелесуші жазып жатыр",
            "of_mine": "Сіздің ұсынысыңыз", "of_gone": "Кері қайтарылды", "of_replaced": "Жаңа ұсыныспен ауыстырылды",
            "of_ctr_answered": "Сіз қарсы бағаны қабылдадыңыз · {sum}", "of_accepted": "Сатушы қабылдады",
            "of_used": "Келісім пайдаланылды", "of_held": "Ақшамен бекітілді",
            "of_m_inst": "Бөліп төлеуге", "of_m_cred": "Несиеге", "of_m_cash": "Қолма-қол", "of_mon": "ай",
            "of_ctr_seller": "Сатушының қарсы бағасы", "of_ctr_plus": "+{step}% сіздің {sum} бағаңызға",
            "of_ctr_took": "Баға келісілді", "of_ctr_refused": "Сіз бас тарттыңыз",
            "of_ctr_gone": "Өзекті емес — сіз жаңа баға ұсындыңыз",
            "of_ctr_take": "Қабылдау · {sum}", "of_ctr_no": "Бас тарту",
            "geo_me": "Сіз геолокация жібердіңіз", "geo_seller": "Геолокация — жеткізу нүктесі",
            "call_yandex": "Шақыру (Яндекс)", "gis": "2GIS", "on_map": "Картада",
            "gate_ai": "Kliko AI-көмекшісімен сөйлесу үшін кіріңіз немесе тіркеліңіз — бұл жылдам.",
            "gate_seller": "Сатушыға жазу үшін кіріңіз — бұл жылдам.", "gate_login": "Кіру / Тіркелу",
            "gate_verify": "Жалғастыру үшін кабинетте верификациядан өтіңіз.",
            "gate_verify_free": "Тегін кезең аяқталды. Жалғастыру үшін верификациядан өтіңіз.",
            "gate_verify_btn": "Верификациядан өту", "gate_paid": "Kliko AI-көмекшісінің лимиті таусылды.",
            "blocked_toast": "Байланыс мүмкін емес — бұғаттау",
            "you_blocked": "Сіз сатушыны бұғаттадыңыз — байланыс мүмкін емес. Тарих сақталды.",
            "seller_blocked": "Сатушы байланысты шектеді. Бұғаттан шығаруды 72 сағатта бір рет сұрауға болады.",
            "unblock": "Бұғаттан шығару", "request_unblock": "Бұғаттан шығаруды сұрау",
            "unblock_req_sent": "Бұғаттан шығару сұрауы сатушыға жіберілді", "failed": "Болмады",
            "agreed": "Баға келісілді · %@", "deal_go": "%@ бағасына рәсімдеу", "deal_live": "Мәміле рәсімделді",
            "deal_open": "Мәмілеге өту", "placeholder": "Хабарлама жазыңыз…", "buyers": "Сатып алушылар",
            "offer_seller_price": "Сатушы бағасы:",
            "offer_sub": "Бұл бағаға дайын емессіз бе — өз бағаңызды ұсыныңыз: сома сатушыға чатқа кетеді, төлем келісімнен кейін.",
            "offer_dial": "Сіздің бағаңыз", "offer_hint": "Жүгірткіні тартыңыз — өз бағаңызды ұсыныңыз",
            "offer_own": "Немесе өз сомаңыз", "offer_save": "үнемдеу %@",
            "offer_over": "Сатушы бағасынан жоғары ұсынудың қажеті жоқ — ол үшін «Қауіпсіз сатып алу» бар",
            "offer_under": "{n}%-дан артық жеңілдік ұсынуға болмайды", "offer_args": "Өтінішті немен бекітесіз",
            "arg_pickup": "Өзім алып кетемін", "arg_take_both": "Өзім алып кетемін немесе жеткізуді өзім төлеймін",
            "arg_pickup_s": "сізге тауарды берумен әуре болудың қажеті жоқ", "offer_send": "Ұсынысты жіберу",
            "close": "Жабу"
        ],
        "en": [
            "title": "Chat with the seller", "sub_ai": "Kliko AI assistant is replying · %@", "seller_lc": "seller",
            "sub_seller": "Seller · %@", "online_now": "online", "sub_soon": "The seller will join soon",
            "reconnecting": "No connection — reconnecting…", "listing": "Listing",
            "gone_goods": "Sold", "gone_service": "This service is no longer available", "gone_rent": "Already rented",
            "seller_goods": "All seller's items", "seller_services": "All seller's services",
            "who_seller": "Seller", "who_ai": "Kliko AI assistant", "via_tg": "from Telegram",
            "greeting": "Hello! I'm the seller's Kliko AI assistant. Ask about the item — I'll answer right away. When you're ready to buy, I'll bring in the seller.",
            "loading": "Loading…", "load_failed": "Couldn't load the chat", "no_conn": "No connection",
            "retry": "Try again", "read": "✓✓ Read", "sent": "✓ Sent",
            "st_online": "The seller is online", "st_with": "The seller is with you",
            "st_hot": "The seller has been notified and will join soon",
            "escalated": "Calling the seller — they'll join soon",
            "called": "The seller has been notified — they'll join once online",
            "call_failed": "Didn't work — please try again", "call_seller": "Call the seller",
            "typing": "Typing",
            "of_mine": "Your offer", "of_gone": "Withdrawn", "of_replaced": "Replaced by a new offer",
            "of_ctr_answered": "You accepted the counter price · {sum}", "of_accepted": "Accepted by the seller",
            "of_used": "Agreement used", "of_held": "Backed with money",
            "of_m_inst": "In installments", "of_m_cred": "On credit", "of_m_cash": "In cash", "of_mon": "mo",
            "of_ctr_seller": "Seller's counter price", "of_ctr_plus": "+{step}% to your {sum}",
            "of_ctr_took": "Price agreed", "of_ctr_refused": "You declined",
            "of_ctr_gone": "Outdated — you offered a new price",
            "of_ctr_take": "Accept · {sum}", "of_ctr_no": "Decline",
            "geo_me": "You sent your location", "geo_seller": "Location — delivery point",
            "call_yandex": "Order (Yandex)", "gis": "2GIS", "on_map": "On the map",
            "gate_ai": "To chat with the Kliko AI assistant, sign in or sign up — it's quick.",
            "gate_seller": "Sign in to message the seller — it's quick.", "gate_login": "Sign in / Sign up",
            "gate_verify": "Get verified in your account to continue.",
            "gate_verify_free": "Your free period has ended. Get verified to continue.",
            "gate_verify_btn": "Get verified", "gate_paid": "The Kliko AI assistant limit has been reached.",
            "blocked_toast": "Messaging unavailable — blocked",
            "you_blocked": "You blocked the seller — messaging is unavailable. History is kept.",
            "seller_blocked": "The seller restricted messaging. You can request unblocking once every 72 hours.",
            "unblock": "Unblock", "request_unblock": "Request unblocking",
            "unblock_req_sent": "Unblock request sent to the seller", "failed": "Failed",
            "agreed": "Price agreed · %@", "deal_go": "Check out for %@", "deal_live": "Deal placed",
            "deal_open": "Go to the deal", "placeholder": "Write a message…", "buyers": "Buyers",
            "offer_seller_price": "Seller's price:",
            "offer_sub": "Not ready at this price? Offer your own: the amount goes to the seller in chat, you pay after they agree.",
            "offer_dial": "Your price", "offer_hint": "Drag the slider to offer your price",
            "offer_own": "Or your own amount", "offer_save": "you save %@",
            "offer_over": "No need to offer more than the seller's price — that's what «Buy safely» is for",
            "offer_under": "You can't offer more than {n}% off", "offer_args": "Make your request stronger",
            "arg_pickup": "I'll pick it up myself", "arg_take_both": "I'll pick it up or pay for delivery myself",
            "arg_pickup_s": "you won't have to deal with the handover", "offer_send": "Send offer",
            "close": "Close"
        ],
        "ar": [
            "title": "الدردشة مع البائع", "sub_ai": "مساعد Kliko الذكي يرد · %@", "seller_lc": "البائع",
            "sub_seller": "البائع · %@", "online_now": "متصل", "sub_soon": "سينضم البائع قريبًا",
            "reconnecting": "لا يوجد اتصال — جارٍ إعادة الاتصال…", "listing": "الإعلان",
            "gone_goods": "تم البيع", "gone_service": "الخدمة لم تعد متاحة", "gone_rent": "تم التأجير",
            "seller_goods": "كل منتجات البائع", "seller_services": "كل خدمات البائع",
            "who_seller": "البائع", "who_ai": "مساعد Kliko الذكي", "via_tg": "من Telegram",
            "greeting": "مرحبًا! أنا مساعد Kliko الذكي للبائع. اسأل عن المنتج وسأجيب فورًا. عندما تكون مستعدًا للشراء سأوصلك بالبائع.",
            "loading": "جارٍ التحميل…", "load_failed": "تعذّر تحميل الدردشة", "no_conn": "لا يوجد اتصال",
            "retry": "إعادة المحاولة", "read": "✓✓ تمت القراءة", "sent": "✓ تم الإرسال",
            "st_online": "البائع متصل", "st_with": "البائع معك",
            "st_hot": "تم إبلاغ البائع وسينضم قريبًا",
            "escalated": "أستدعي البائع — سينضم قريبًا",
            "called": "تم إبلاغ البائع — سينضم عندما يكون متصلًا",
            "call_failed": "لم ينجح — حاول مرة أخرى", "call_seller": "استدعاء البائع",
            "typing": "يكتب الآن",
            "of_mine": "عرضك", "of_gone": "تم السحب", "of_replaced": "استُبدل بعرض جديد",
            "of_ctr_answered": "قبلت السعر المقابل · {sum}", "of_accepted": "قبله البائع",
            "of_used": "تم استخدام الاتفاق", "of_held": "مدعوم بالمال",
            "of_m_inst": "بالتقسيط", "of_m_cred": "بالائتمان", "of_m_cash": "نقدًا", "of_mon": "شهر",
            "of_ctr_seller": "السعر المقابل من البائع", "of_ctr_plus": "+{step}% على {sum} التي عرضتها",
            "of_ctr_took": "تم الاتفاق على السعر", "of_ctr_refused": "رفضت",
            "of_ctr_gone": "لم يعد صالحًا — عرضت سعرًا جديدًا",
            "of_ctr_take": "قبول · {sum}", "of_ctr_no": "رفض",
            "geo_me": "أرسلت موقعك", "geo_seller": "الموقع — نقطة التسليم",
            "call_yandex": "طلب (Yandex)", "gis": "2GIS", "on_map": "على الخريطة",
            "gate_ai": "للدردشة مع مساعد Kliko الذكي سجّل الدخول أو أنشئ حسابًا — الأمر سريع.",
            "gate_seller": "سجّل الدخول لمراسلة البائع — الأمر سريع.", "gate_login": "تسجيل الدخول / إنشاء حساب",
            "gate_verify": "أكمل التحقق في حسابك للمتابعة.",
            "gate_verify_free": "انتهت الفترة المجانية. أكمل التحقق للمتابعة.",
            "gate_verify_btn": "إكمال التحقق", "gate_paid": "تم بلوغ حد مساعد Kliko الذكي.",
            "blocked_toast": "المراسلة غير متاحة — حظر",
            "you_blocked": "لقد حظرت البائع — المراسلة غير متاحة. السجل محفوظ.",
            "seller_blocked": "قيّد البائع المراسلة. يمكنك طلب رفع الحظر مرة كل 72 ساعة.",
            "unblock": "إلغاء الحظر", "request_unblock": "طلب رفع الحظر",
            "unblock_req_sent": "تم إرسال طلب رفع الحظر إلى البائع", "failed": "تعذّر",
            "agreed": "تم الاتفاق على السعر · %@", "deal_go": "إتمام الشراء مقابل %@", "deal_live": "تم إنشاء الصفقة",
            "deal_open": "الانتقال إلى الصفقة", "placeholder": "اكتب رسالة…", "buyers": "المشترون",
            "offer_seller_price": "سعر البائع:",
            "offer_sub": "لست مستعدًا لهذا السعر؟ اقترح سعرك: سيصل المبلغ إلى البائع في الدردشة، والدفع بعد موافقته.",
            "offer_dial": "سعرك", "offer_hint": "اسحب المؤشر لاقتراح سعرك",
            "offer_own": "أو مبلغك الخاص", "offer_save": "توفير %@",
            "offer_over": "لا داعي لعرض أكثر من سعر البائع — لذلك يوجد «اشترِ بأمان»",
            "offer_under": "لا يمكن عرض خصم أكبر من {n}%", "offer_args": "ما يدعم طلبك",
            "arg_pickup": "سأستلمه بنفسي", "arg_take_both": "سأستلمه أو أدفع التوصيل بنفسي",
            "arg_pickup_s": "لن تحتاج إلى عناء التسليم", "offer_send": "إرسال العرض",
            "close": "إغلاق"
        ]
    ]
}
