import Foundation

/**
 Тексты настроек и профиля — этап 46 (владелец 26.09.2026: «всё одно и то же, просто код разный»). Русские — дословно из
 js_i18n-cabinet-ru.js сайта (cabset_*, hero_*, pw_*, ph_*, phv_*, cc_*, sec_*, pg_*, pp_*, pay_*, esc_*, cabwiz_* …), а
 там, где сайт пишет текст прямо в коде (окна «Чаты», «Личные данные на фото», «Применить к объявлениям?», ошибки пароля
 и номера), — оттуда, из js/cabinet.min.js. Казахские, английские и арабские — перевод тех же фраз.

 Своих фраз четыре, и каждая объясняет то, чего на сайте нет, потому что там это делается на месте: «точка на карте
 ставится на сайте» (pg_map_note), «выключить eGov-вход можно только с eGov — на сайте» (sec_egov_off_site), «язык
 приложения и сайта, выбор — в аккаунте» (lang_note) и «удаление — на сайте» (del_footer); плюс подписи для VoiceOver (a11y_*).
 */
enum НастройкиText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    private static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    /// cabApplyDone сайта: «Применено к {n} объявлению/объявлениям.» — cabPlu: 1, 21, 31… — «объявлению», иначе
    /// «объявлениям» (11–19 — тоже «объявлениям»).
    static func применено(_ n: Int) -> String {
        switch язык {
        case "kk": return String(n) + " хабарландыруға қолданылды."
        case "en": return n == 1 ? "Applied to 1 listing." : "Applied to " + String(n) + " listings."
        case "ar": return "طُبِّق على " + String(n) + " إعلان."
        default:
            let остаток = abs(n) % 100
            let слово = (остаток > 10 && остаток < 20) ? "объявлениям" : (остаток % 10 == 1 ? "объявлению" : "объявлениям")
            return "Применено к " + String(n) + " " + слово + "."
        }
    }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    private static let ru: [String: String] = [
        // Лист «Настройки» (cabSettings)
        "cab_settings": "Настройки", "cabset_account": "Аккаунт", "hero_profile": "Профиль", "hero_pass": "Пароль",
        "cabset_num": "Номер и контакты", "cabset_chat": "Чаты", "cabset_listings": "Объявления",
        "cabset_cats": "Мои категории", "cabset_geo": "Регион и адрес", "cabset_hours": "Режим работы",
        "cabset_redact": "Личные данные на фото", "cabset_sales": "Продажи и оплата", "cabset_escrow": "Гарант-сделка",
        "esc_on_short": "вкл", "esc_off_short": "выкл", "cabset_pay": "Рассрочка и кредит",
        "cabset_reserve": "Бронь товара после оплаты", "sec_devices": "Устройства и входы", "cabset_app": "Приложение",
        "cabwiz_t": "Начало работы", "cabset_lang": "Язык", "cabset_del": "Удалить аккаунт",
        "del_footer": "Удаление аккаунта — в кабинете на сайте: «Настройки» → «Удалить аккаунт». Там же его подтверждают через eGov или паролем.",
        "close": "Закрыть", "cancel": "Отмена", "save": "Сохранить", "saving": "Сохраняем…", "processing": "Оформляем…",
        "err_generic": "Ошибка", "err_no_conn": "Нет соединения", "err_net": "Ошибка сети",
        "auth": "Сессия истекла, войдите заново", "loading": "Загрузка…",
        // Профиль и верификация
        "ver_ok": "Проверенный продавец", "ver_row": "Верификация через eGov",
        "ver_row_s": "Откроет безопасные сделки через гаранта", "ver_rejected": "Отклонено",
        "ver_go": "Пройти верификацию",
        "ver_off": "Подтверждение личности временно недоступно — идут технические работы. Попробуйте позже.",
        "av_change": "Сменить фото", "av_saved": "Фото профиля обновлено", "av_big": "Фото больше 12 МБ",
        "phone_hidden": "скрыт от покупателей · связь через чат",
        // Пароль
        "pw_title_change": "Сменить пароль", "pw_title_set": "Установить свой пароль",
        "pw_hint_change": "Для смены нужен текущий пароль — защита аккаунта.",
        "pw_hint_set": "Старый вводить не нужно — задаёте впервые. Придумайте пароль, который запомните.",
        "pw_old_ph": "Текущий пароль", "pw_new_ph": "Новый пароль (мин. 6 символов)", "pw_new2_ph": "Повторите пароль",
        "pw_short": "Пароль — минимум 6 символов", "pw_mismatch": "Пароли не совпадают", "pw_saved": "Пароль сохранён",
        // Номер и контакты
        "ph_title": "Изменить номер телефона",
        "ph_hint": "Укажите **настоящий** номер — это ваши контакты для сделок и покупателей. Если случайно зарегистрировались не на тот номер, исправьте здесь. После подтверждения через eGov номер закрепится за вашим ИИН.",
        "ph_hint_v": "Номер привязан к вашему ИИН и подтверждён через eGov: он и есть ваши контакты для сделок. Поменялся в eGov — пройдите подтверждение заново, здесь он обновится сам.",
        "ph_egov_change": "Сменить номер через eGov", "ph_bad": "Введите корректный номер (+7 …)",
        "ph_changed_t": "Номер сохранён",
        "ph_changed_m": "Публиковать объявления можно с номера, привязанного к eGov. Пройдите верификацию, чтобы связать этот.",
        "ph_go": "Пройти", "later": "Позже", "ph_saved": "Номер сохранён",
        "phv_title": "Как с вами связаться",
        "phv_hint": "Чат доступен всегда. При «Чат и звонок» вошедший покупатель может позвонить вам и написать в WhatsApp, при «Только чат» номер не видит никто.",
        "phv_blocked_week": "За неделю номер не увидели: {n}", "phv_blocked_none": "За неделю все желающие увидели номер",
        "phv_saved": "Настройка сохранена", "cc_ways_title": "Способы связи", "cc_wa_on": "WhatsApp на этом номере",
        "cc_tg_ph": "@username в Telegram",
        "cc_tg_hint": "Юзернейм не раскрывает ваш номер. Мессенджеры открыты верифицированным покупателям.",
        // Чаты
        "chat_hint": "Как работает общение с покупателями в чате.", "chat_ai_t": "Kliko AI-помощник в чате",
        "chat_ai_s": "Отвечает покупателям от вашего имени, пока вы офлайн, и передаёт вам горячие заявки. По умолчанию выключен — сообщения идут сразу вам.",
        "chat_ai_note": "Для работы Kliko AI-помощника нужна активная **Kliko AI-подписка** (квота Kliko AI). Без неё сообщения покупателей приходят вам напрямую.",
        "chat_ai_buy": "Оформить Kliko AI", "cabset_chat_saved": "Настройки чата сохранены",
        // Мои категории
        "cabset_cats_hint": "Отметьте разделы, в которых продаёте — в форме добавления останутся только они. Пусто = все разделы.",
        "cabset_cats_saved": "Категории сохранены",
        // Регион и адрес
        "cabset_geo_hint": "Подставим в форму добавления автоматически — при создании объявления можно изменить.",
        "pg_region_l": "Регион", "form_region_ph": "Область / город", "pg_district_l": "Район",
        "pg_district_none": "Не указан", "pg_city_l": "Город или посёлок", "pg_city_ph": "Например, Косшы",
        "pg_addr_l": "Улица и дом", "pg_addr_ph": "Необязательно", "pg_map_l": "Точка на карте", "pg_map_on": "Отмечена",
        "pg_map_off": "Не отмечена",
        "pg_map_note": "Нажмите на карту, чтобы поставить точку.", "pg_map_clear": "Убрать точку",
        "pg_recv": "Это и адрес получения",
        "pg_recv_s": "Подставим его в сделке, когда вы что-то покупаете. Изменить можно прямо там.",
        "del_where_t": "Куда отправляю", "del_where_all": "Весь Казахстан", "del_where_all_s": "отправляете в любой регион",
        "del_where_regions": "Своя область и выбранные", "del_where_regions_s": "отметьте области, куда отправляете",
        "del_where_city": "Только свой город", "del_where_city_s": "встреча, самовывоз и курьер по городу",
        "del_where_own": "своя",
        "del_where_note": "Встреча и самовывоз доступны покупателю из любого региона — ограничение касается только отправки.",
        "cabset_geo_saved": "Регион и адрес сохранены",
        // Режим работы
        "cabset_hours_hint": "Подставим в форму добавления — при создании объявления можно изменить.",
        "hours_247": "Круглосуточно 24/7", "cabset_hours_range": "Своё время", "cabset_hours_none": "Не указывать",
        "hours_from": "С", "hours_to": "До", "cabset_hours_saved": "Режим работы по умолчанию сохранён",
        // Личные данные на фото
        "pr_hint": "После публикации Kliko AI находит на снимках серийные номера, IMEI, номера документов и госномера машин и размывает их. Ждать не нужно: объявление побудет «На проверке» и выйдет на витрину, когда всё скрыто.",
        "pr_off_t": "Не проверять", "pr_off_s": "Снимки уходят как есть, публикация не ждёт проверки",
        "pr_on_t": "Проверять и скрывать", "pr_on_s": "Номера скрываются фоном — на витрину уже без них",
        "pr_note": "Скрыть номер на одном фото можно и без этого — кнопкой с замком на миниатюре. Включите, если переносите объявления пачкой с других площадок: на таких снимках часто чужие номера.",
        "pr_demo_on": "Пример: номера скрыты", "pr_demo_off": "Пример: номера видны",
        "pr_saved_on": "Номера на фото будут скрываться после публикации — ждать не нужно",
        "pr_saved_off": "Проверка снимков выключена",
        "pr_fail": "Не сохранилось — проверьте связь и нажмите «Сохранить» ещё раз",
        // Гарант-сделка
        "esc_pref_hint": "С этим выбором откроется окно публикации. В каждом объявлении гарант можно переключить отдельно — при публикации и в правке.",
        "esc_pref_t": "Гарант в новых объявлениях",
        "pc_esc_g1": "Покупатель платит через Kliko ещё до передачи — верить на слово не нужно",
        "pc_esc_g2": "Kliko держит деньги, пока покупатель не получит вещь, — потом они приходят вам",
        "pc_esc_g3": "В карточке — кнопка «Купить безопасно» и знак «Гарант»",
        "pc_esc_verify": "Заработает после верификации личности",
        "pc_esc_off": "Выключено — покупатель сможет только связаться с вами",
        "esc_pref_auto": "Не работает, запчасти или цена ниже {n} — гарант выключается сам.",
        "esc_pref_saved": "Гарант по умолчанию сохранён",
        // Применить к объявлениям (cabApplyPrefAsk)
        "capp_geo_t": "Применить адрес к объявлениям?",
        "capp_geo_s": "Обновим регион и адрес у всех ваших текущих объявлений. Новые объявления и так подставляют дефолт автоматически.",
        "capp_hours_t": "Применить режим к объявлениям?",
        "capp_hours_s": "Обновим время связи у всех ваших товаров. Услуги не затрагиваем — там режим задаётся отдельно.",
        "esc_apply_on_t": "Включить гарант во всех объявлениях?", "esc_apply_off_t": "Выключить гарант во всех объявлениях?",
        "esc_apply_s": "Обновим ваши текущие объявления. Где вещь не работает, это запчасти или цена ниже порога — гаранта не будет и так.",
        "capp_skip": "Пропустить", "capp_run": "Применить", "capp_running": "Применяем…", "capp_done": "Готово",
        "capp_fail_t": "Не вышло", "capp_fail": "Не удалось применить",
        "capp_zero": "У вас пока нет объявлений — новые подхватят значение автоматически.", "capp_ok": "Понятно",
        // Рассрочка и кредит
        "pp_hint": "Действует на все объявления, где оплата не настроена отдельно.", "pay_installment": "Рассрочка",
        "pay_with_bank": "С банком", "pay_notary": "Без банка · нотариус", "pay_markup": "Наценка за рассрочку",
        "pp_banks": "Банки", "pp_links": "Ссылки на оплату в банке",
        "pp_empty": "Отметьте банк выше — появится поле для его ссылки на оплату.",
        "pp_link_bad": "Нужна ссылка с сайта банка: {d}",
        "pp_inst_note": "Покупатель откроет ссылку в приложении банка — эта оплата идёт мимо гаранта Kliko, и мы прямо говорим ему об этом. Ссылки принимаем только с сайтов банков. У Kaspi рассрочка по ссылке доступна не всем продавцам — проверьте в Kaspi Pay. Нет ссылки — покупатель напишет вам в чат.",
        "pay_credit": "Кредит", "pay_annual_rate": "Годовая ставка",
        "pp_cred_note": "Покупатель увидит предварительный расчёт. Оформление кредита прямо в Kliko — в разработке.",
        "pp_err_link": "Ссылка должна вести на сайт выбранного банка", "pp_saved": "Рассрочка и кредит сохранены",
        // Бронь товара
        "cabset_reserve_hint": "Сколько держать штучный товар за покупателем после оплаты (самовывоз/город), пока он не задаст адрес или не вызовет курьера.",
        "cabset_reserve_why_t": "Зачем это нужно",
        "cabset_reserve_why1": "Товар держится только за оплатившим — двое не купят одно и то же.",
        "cabset_reserve_why2": "Покупатель тянет — бронь сгорает, деньги ему возвращаются, товар снова в продаже.",
        "cabset_reserve_why3": "Отсчёт подгоняет к сделке, а тем, кто ждал, уходит пуш «снова доступен».",
        "min_short": "мин", "cabset_reserve_saved": "Время брони сохранено",
        // Устройства и входы
        "sec_one_t": "Только одно устройство",
        "sec_one_s": "Вход на новом устройстве завершает сеансы на остальных — там покажем, откуда был вход, и спросим, вы ли это.",
        "sec_egov_t": "Подтверждать вход через eGov",
        "sec_egov_s": "После пароля, Telegram или Apple — ещё код из SMS на экране eGov. Выключить можно тоже только через eGov.",
        "sec_now": "Сейчас вошли", "sec_this": "это устройство", "sec_end": "Завершить",
        "sec_end_all": "Выйти на всех других устройствах", "sec_none_others": "Других устройств нет",
        "sec_log": "Последние входы", "sec_active_now": "активен сейчас", "sec_ago_min": "{n} мин назад",
        "sec_ago_h": "{n} ч назад", "sec_ended": "Сеансы завершены: {n}",
        "sec_egov_on": "Вход теперь подтверждается через eGov", "sec_egov_off": "Подтверждение входа через eGov выключено",
        "sec_via_password": "пароль", "sec_via_egov": "eGov", "sec_via_register": "регистрация",
        "sec_via_legacy": "вход до обновления", "sec_via_dev": "разработка", "sec_egov_on_btn": "Включить",
        "sec_egov_off_site": "Выключить подтверждение входа можно только с проверкой eGov — это делается в кабинете на сайте: «Настройки» → «Устройства и входы».",
        "open_site": "Открыть кабинет на сайте",
        // Язык
        "lang_note": "Язык приложения и сайта. Выбор сохраняется в аккаунте.",
        // Оформление и мастер «Начало работы»
        "cabwiz_theme_t": "Оформление", "cabwiz_theme_hint": "Меняется сразу. «{auto}» — как настроено на телефоне.",
        "ap_auto": "Как в системе", "ap_light": "Светлая", "ap_dark": "Тёмная", "cabwiz_ready": "Готово",
        "ap_save_fail": "Не сохранилось на аккаунт — на этом устройстве видно",
        "cabwiz_lead": "Настроим кабинет за пару минут. Каждый шаг сохраняется сразу — остановиться можно в любой момент.",
        "cabwiz_meta": "{n} шагов · около {m} минут", "cabwiz_go": "Начать", "cabwiz_skip": "Пропустить",
        "cabwiz_step": "Шаг {n} из {m}", "cabwiz_skip_step": "Пропустить шаг", "cabwiz_back": "Назад",
        "cabwiz_next": "Далее", "cabwiz_s_theme": "Светлая, тёмная или как на телефоне",
        "cabwiz_s_geo": "Откуда вы и куда отправляете — подставим в каждое объявление",
        "cabwiz_s_cats": "Какие разделы показывать при подаче объявления",
        "cabwiz_s_hours": "Когда с вами можно связаться", "cabwiz_photo_t": "Личные данные на фото",
        "cabwiz_s_photo": "Скрывать ли номера и документы на снимках",
        "cabwiz_ver_t": "Последний шаг — верификация",
        "cabwiz_ver_s": "Через eGov за пару минут. Откроет безопасные сделки через гаранта и значок «Проверенный». Настройки уже сохранены.",
        "cabwiz_ver_go": "Пройти верификацию", "cabwiz_later": "Позже", "cabwiz_done_t": "Кабинет настроен",
        "cabwiz_done_s": "Выбранное уже работает и подставляется в новые объявления. Поменять можно в Настройках.",
        "cabwiz_add": "Добавить объявление", "cabwiz_home": "В кабинет",
        // VoiceOver
        "a11y_avatar": "Фото профиля", "a11y_uploading": "Загружаем фото", "a11y_checked": "выбрано",
        "a11y_verified": "проверенный продавец"
    ]

    private static let kk: [String: String] = [
        "cab_settings": "Баптаулар", "cabset_account": "Аккаунт", "hero_profile": "Профиль", "hero_pass": "Құпиясөз",
        "cabset_num": "Нөмір және байланыс", "cabset_chat": "Чаттар", "cabset_listings": "Хабарландырулар",
        "cabset_cats": "Менің санаттарым", "cabset_geo": "Өңір және мекенжай", "cabset_hours": "Жұмыс уақыты",
        "cabset_redact": "Фотодағы жеке деректер", "cabset_sales": "Сату және төлем", "cabset_escrow": "Кепіл-мәміле",
        "esc_on_short": "қосулы", "esc_off_short": "өшірулі", "cabset_pay": "Бөліп төлеу және несие",
        "cabset_reserve": "Төлемнен кейінгі тауар броны", "sec_devices": "Құрылғылар мен кірулер", "cabset_app": "Қосымша",
        "cabwiz_t": "Жұмысты бастау", "cabset_lang": "Тіл", "cabset_del": "Аккаунтты жою",
        "del_footer": "Аккаунтты жою — сайттағы кабинетте: «Баптаулар» → «Аккаунтты жою». Сол жерде eGov немесе құпиясөз арқылы расталады.",
        "close": "Жабу", "cancel": "Бас тарту", "save": "Сақтау", "saving": "Сақтап жатырмыз…", "processing": "Рәсімдеп жатырмыз…",
        "err_generic": "Қате", "err_no_conn": "Байланыс жоқ", "err_net": "Желі қатесі",
        "auth": "Сессия аяқталды, қайта кіріңіз", "loading": "Жүктелуде…",
        "ver_ok": "Тексерілген сатушы", "ver_row": "eGov арқылы верификация",
        "ver_row_s": "Кепіл арқылы қауіпсіз мәмілелерді ашады", "ver_rejected": "Қабылданбады",
        "ver_go": "Верификациядан өту",
        "ver_off": "Жеке басты растау уақытша қолжетімсіз — техникалық жұмыстар жүріп жатыр. Кейінірек көріңіз.",
        "av_change": "Фотоны ауыстыру", "av_saved": "Профиль фотосы жаңартылды", "av_big": "Фото 12 МБ-тан үлкен",
        "phone_hidden": "сатып алушылардан жасырылған · байланыс чат арқылы",
        "pw_title_change": "Құпиясөзді ауыстыру", "pw_title_set": "Өз құпиясөзіңізді орнату",
        "pw_hint_change": "Ауыстыру үшін қазіргі құпиясөз керек — аккаунтты қорғау.",
        "pw_hint_set": "Ескісін енгізудің қажеті жоқ — алғаш рет орнатасыз. Есте қалатын құпиясөз ойлап табыңыз.",
        "pw_old_ph": "Қазіргі құпиясөз", "pw_new_ph": "Жаңа құпиясөз (кемінде 6 таңба)", "pw_new2_ph": "Құпиясөзді қайталаңыз",
        "pw_short": "Құпиясөз — кемінде 6 таңба", "pw_mismatch": "Құпиясөздер сәйкес емес", "pw_saved": "Құпиясөз сақталды",
        "ph_title": "Телефон нөмірін өзгерту",
        "ph_hint": "**Нақты** нөміріңізді көрсетіңіз — бұл мәмілелер мен сатып алушыларға арналған байланысыңыз. Қате нөмірге тіркеліп қалсаңыз, осында түзетіңіз. eGov арқылы растағаннан кейін нөмір ЖСН-ға бекітіледі.",
        "ph_hint_v": "Нөмір ЖСН-ға байланған және eGov арқылы расталған: мәмілелерге арналған байланысыңыз осы. eGov-та өзгерсе — растаудан қайта өтіңіз, мұнда өзі жаңарады.",
        "ph_egov_change": "Нөмірді eGov арқылы ауыстыру", "ph_bad": "Дұрыс нөмір енгізіңіз (+7 …)",
        "ph_changed_t": "Нөмір сақталды",
        "ph_changed_m": "Хабарландыруларды eGov-қа байланған нөмірден жариялауға болады. Осы нөмірді байланыстыру үшін верификациядан өтіңіз.",
        "ph_go": "Өту", "later": "Кейінірек", "ph_saved": "Нөмір сақталды",
        "phv_title": "Сізбен қалай байланысу керек",
        "phv_hint": "Чат әрқашан қолжетімді. «Чат және қоңырау» кезінде кірген сатып алушы сізге қоңырау шалып, WhatsApp-қа жаза алады, «Тек чат» кезінде нөміріңізді ешкім көрмейді.",
        "phv_blocked_week": "Бір аптада нөмірді көрмегендер: {n}", "phv_blocked_none": "Бір аптада қалағандардың бәрі нөмірді көрді",
        "phv_saved": "Баптау сақталды", "cc_ways_title": "Байланыс тәсілдері", "cc_wa_on": "Осы нөмірдегі WhatsApp",
        "cc_tg_ph": "Telegram-дағы @username",
        "cc_tg_hint": "Юзернейм нөміріңізді ашпайды. Мессенджерлер верификациядан өткен сатып алушыларға ашық.",
        "chat_hint": "Чатта сатып алушылармен сөйлесу қалай жұмыс істейді.", "chat_ai_t": "Чаттағы Kliko AI-көмекшісі",
        "chat_ai_s": "Сіз офлайн кезде сатып алушыларға сіздің атыңыздан жауап береді және ыстық өтінімдерді сізге береді. Әдепкіде өшірулі — хабарламалар бірден сізге келеді.",
        "chat_ai_note": "Kliko AI-көмекшісі жұмыс істеуі үшін белсенді **Kliko AI-жазылымы** (Kliko AI квотасы) керек. Онсыз сатып алушылардың хабарламалары сізге тікелей келеді.",
        "chat_ai_buy": "Kliko AI рәсімдеу", "cabset_chat_saved": "Чат баптаулары сақталды",
        "cabset_cats_hint": "Сататын бөлімдерді белгілеңіз — қосу формасында тек солар қалады. Бос = барлық бөлімдер.",
        "cabset_cats_saved": "Санаттар сақталды",
        "cabset_geo_hint": "Қосу формасына автоматты түрде қоямыз — хабарландыру жасағанда өзгертуге болады.",
        "pg_region_l": "Өңір", "form_region_ph": "Облыс / қала", "pg_district_l": "Аудан",
        "pg_district_none": "Көрсетілмеген", "pg_city_l": "Қала немесе кент", "pg_city_ph": "Мысалы, Қосшы",
        "pg_addr_l": "Көше және үй", "pg_addr_ph": "Міндетті емес", "pg_map_l": "Картадағы нүкте", "pg_map_on": "Белгіленген",
        "pg_map_off": "Белгіленбеген",
        "pg_map_note": "Нүкте қою үшін картаны басыңыз.", "pg_map_clear": "Нүктені алып тастау",
        "pg_recv": "Бұл алу мекенжайы да",
        "pg_recv_s": "Бірдеңе сатып алғанда мәмілеге қоямыз. Сол жерде өзгертуге болады.",
        "del_where_t": "Қайда жіберемін", "del_where_all": "Бүкіл Қазақстан", "del_where_all_s": "кез келген өңірге жібересіз",
        "del_where_regions": "Өз облысым және таңдалғандар", "del_where_regions_s": "жіберетін облыстарды белгілеңіз",
        "del_where_city": "Тек өз қалам", "del_where_city_s": "кездесу, өзі алып кету және қала ішіндегі курьер",
        "del_where_own": "өзімдікі",
        "del_where_note": "Кездесу мен өзі алып кету кез келген өңірдегі сатып алушыға қолжетімді — шектеу тек жіберуге қатысты.",
        "cabset_geo_saved": "Өңір мен мекенжай сақталды",
        "cabset_hours_hint": "Қосу формасына қоямыз — хабарландыру жасағанда өзгертуге болады.",
        "hours_247": "Тәулік бойы 24/7", "cabset_hours_range": "Өз уақытым", "cabset_hours_none": "Көрсетпеу",
        "hours_from": "Бастап", "hours_to": "Дейін", "cabset_hours_saved": "Әдепкі жұмыс уақыты сақталды",
        "pr_hint": "Жарияланғаннан кейін Kliko AI суреттерден сериялық нөмірлерді, IMEI, құжат нөмірлерін және көлік нөмірлерін тауып, бұлдыратады. Күтудің қажеті жоқ: хабарландыру «Тексеруде» болады да, бәрі жасырылғанда витринаға шығады.",
        "pr_off_t": "Тексермеу", "pr_off_s": "Суреттер сол күйінде кетеді, жариялау тексеруді күтпейді",
        "pr_on_t": "Тексеру және жасыру", "pr_on_s": "Нөмірлер фонда жасырылады — витринаға оларсыз шығады",
        "pr_note": "Бір фотодағы нөмірді мұнсыз да жасыруға болады — миниатюрадағы құлып батырмасымен. Хабарландыруларды басқа алаңдардан топтап көшірсеңіз, қосыңыз: ондай суреттерде бөтен нөмірлер жиі болады.",
        "pr_demo_on": "Мысал: нөмірлер жасырылған", "pr_demo_off": "Мысал: нөмірлер көрінеді",
        "pr_saved_on": "Фотодағы нөмірлер жарияланғаннан кейін жасырылады — күтудің қажеті жоқ",
        "pr_saved_off": "Суреттерді тексеру өшірілді",
        "pr_fail": "Сақталмады — байланысты тексеріп, «Сақтау» батырмасын қайта басыңыз",
        "esc_pref_hint": "Жариялау терезесі осы таңдаумен ашылады. Әр хабарландыруда кепілді бөлек ауыстыруға болады — жариялағанда және түзеткенде.",
        "esc_pref_t": "Жаңа хабарландырулардағы кепіл",
        "pc_esc_g1": "Сатып алушы тапсыруға дейін Kliko арқылы төлейді — сөзге сенудің қажеті жоқ",
        "pc_esc_g2": "Сатып алушы затты алғанша Kliko ақшаны ұстайды — содан кейін ол сізге келеді",
        "pc_esc_g3": "Карточкада — «Қауіпсіз сатып алу» батырмасы және «Кепіл» белгісі",
        "pc_esc_verify": "Жеке басты верификациялағаннан кейін жұмыс істейді",
        "pc_esc_off": "Өшірулі — сатып алушы тек сізбен байланыса алады",
        "esc_pref_auto": "Жұмыс істемесе, қосалқы бөлшек болса немесе баға {n}-ден төмен болса — кепіл өзі өшеді.",
        "esc_pref_saved": "Әдепкі кепіл сақталды",
        "capp_geo_t": "Мекенжайды хабарландыруларға қолдану керек пе?",
        "capp_geo_s": "Барлық ағымдағы хабарландыруларыңыздың өңірі мен мекенжайын жаңартамыз. Жаңа хабарландырулар әдепкіні өзі қояды.",
        "capp_hours_t": "Уақытты хабарландыруларға қолдану керек пе?",
        "capp_hours_s": "Барлық тауарларыңыздың байланыс уақытын жаңартамыз. Қызметтерге тимейміз — онда уақыт бөлек беріледі.",
        "esc_apply_on_t": "Барлық хабарландыруларда кепілді қосу керек пе?", "esc_apply_off_t": "Барлық хабарландыруларда кепілді өшіру керек пе?",
        "esc_apply_s": "Ағымдағы хабарландыруларыңызды жаңартамыз. Зат жұмыс істемесе, қосалқы бөлшек болса немесе баға шектен төмен болса — кепіл онсыз да болмайды.",
        "capp_skip": "Өткізіп жіберу", "capp_run": "Қолдану", "capp_running": "Қолданып жатырмыз…", "capp_done": "Дайын",
        "capp_fail_t": "Болмады", "capp_fail": "Қолдану мүмкін болмады",
        "capp_zero": "Әзірге хабарландыруларыңыз жоқ — жаңалары мәнді автоматты түрде алады.", "capp_ok": "Түсінікті",
        "pp_hint": "Төлемі бөлек бапталмаған барлық хабарландыруларға әсер етеді.", "pay_installment": "Бөліп төлеу",
        "pay_with_bank": "Банкпен", "pay_notary": "Банксіз · нотариус", "pay_markup": "Бөліп төлеуге үстеме",
        "pp_banks": "Банктер", "pp_links": "Банктегі төлем сілтемелері",
        "pp_empty": "Жоғарыдан банкті белгілеңіз — оның төлем сілтемесіне арналған өріс пайда болады.",
        "pp_link_bad": "Банк сайтындағы сілтеме керек: {d}",
        "pp_inst_note": "Сатып алушы сілтемені банк қосымшасында ашады — бұл төлем Kliko кепілінен тыс өтеді, біз оған мұны тура айтамыз. Сілтемелерді тек банк сайттарынан қабылдаймыз. Kaspi-де сілтеме бойынша бөліп төлеу барлық сатушыға қолжетімді емес — Kaspi Pay-де тексеріңіз. Сілтеме болмаса — сатып алушы сізге чатқа жазады.",
        "pay_credit": "Несие", "pay_annual_rate": "Жылдық мөлшерлеме",
        "pp_cred_note": "Сатып алушы алдын ала есепті көреді. Несиені тікелей Kliko-да рәсімдеу — әзірленуде.",
        "pp_err_link": "Сілтеме таңдалған банктің сайтына апаруы керек", "pp_saved": "Бөліп төлеу мен несие сақталды",
        "cabset_reserve_hint": "Төлемнен кейін (өзі алып кету/қала) сатып алушы мекенжай бермейінше немесе курьер шақырмайынша дана тауарды қанша уақыт ұстау керек.",
        "cabset_reserve_why_t": "Бұл не үшін керек",
        "cabset_reserve_why1": "Тауар тек төлегенге ұсталады — екі адам бір затты сатып алмайды.",
        "cabset_reserve_why2": "Сатып алушы созса — брон күйеді, ақшасы қайтарылады, тауар қайта сатылымда.",
        "cabset_reserve_why3": "Кері санақ мәмілеге итермелейді, ал күткендерге «қайта қолжетімді» пуші кетеді.",
        "min_short": "мин", "cabset_reserve_saved": "Брон уақыты сақталды",
        "sec_one_t": "Тек бір құрылғы",
        "sec_one_s": "Жаңа құрылғыдан кіру қалғандарындағы сеанстарды аяқтайды — онда кіру қайдан болғанын көрсетіп, сіз бе екеніңізді сұраймыз.",
        "sec_egov_t": "Кіруді eGov арқылы растау",
        "sec_egov_s": "Құпиясөз, Telegram немесе Apple-ден кейін — eGov экранындағы SMS-код. Өшіру де тек eGov арқылы.",
        "sec_now": "Қазір кірген", "sec_this": "осы құрылғы", "sec_end": "Аяқтау",
        "sec_end_all": "Басқа барлық құрылғылардан шығу", "sec_none_others": "Басқа құрылғылар жоқ",
        "sec_log": "Соңғы кірулер", "sec_active_now": "қазір белсенді", "sec_ago_min": "{n} мин бұрын",
        "sec_ago_h": "{n} сағ бұрын", "sec_ended": "Сеанстар аяқталды: {n}",
        "sec_egov_on": "Кіру енді eGov арқылы расталады", "sec_egov_off": "eGov арқылы кіруді растау өшірілді",
        "sec_via_password": "құпиясөз", "sec_via_egov": "eGov", "sec_via_register": "тіркелу",
        "sec_via_legacy": "жаңартуға дейінгі кіру", "sec_via_dev": "әзірлеу", "sec_egov_on_btn": "Қосу",
        "sec_egov_off_site": "Кіруді растауды тек eGov тексеруімен өшіруге болады — бұл сайттағы кабинетте жасалады: «Баптаулар» → «Құрылғылар мен кірулер».",
        "open_site": "Сайттағы кабинетті ашу",
        "lang_note": "Қосымша мен сайттың тілі. Таңдау аккаунтта сақталады.",
        "cabwiz_theme_t": "Безендіру", "cabwiz_theme_hint": "Бірден өзгереді. «{auto}» — телефондағы баптау бойынша.",
        "ap_auto": "Жүйедегідей", "ap_light": "Ашық", "ap_dark": "Қараңғы", "cabwiz_ready": "Дайын",
        "ap_save_fail": "Аккаунтқа сақталмады — осы құрылғыда көрінеді",
        "cabwiz_lead": "Кабинетті бірнеше минутта баптаймыз. Әр қадам бірден сақталады — кез келген сәтте тоқтауға болады.",
        "cabwiz_meta": "{n} қадам · шамамен {m} минут", "cabwiz_go": "Бастау", "cabwiz_skip": "Өткізіп жіберу",
        "cabwiz_step": "{m} қадамның {n}-і", "cabwiz_skip_step": "Қадамды өткізу", "cabwiz_back": "Артқа",
        "cabwiz_next": "Әрі қарай", "cabwiz_s_theme": "Ашық, қараңғы немесе телефондағыдай",
        "cabwiz_s_geo": "Қайдансыз және қайда жібересіз — әр хабарландыруға қоямыз",
        "cabwiz_s_cats": "Хабарландыру бергенде қандай бөлімдерді көрсету",
        "cabwiz_s_hours": "Сізбен қашан байланысуға болады", "cabwiz_photo_t": "Фотодағы жеке деректер",
        "cabwiz_s_photo": "Суреттердегі нөмірлер мен құжаттарды жасыру керек пе",
        "cabwiz_ver_t": "Соңғы қадам — верификация",
        "cabwiz_ver_s": "eGov арқылы бірнеше минутта. Кепіл арқылы қауіпсіз мәмілелер мен «Тексерілген» белгісін ашады. Баптаулар сақталып қойған.",
        "cabwiz_ver_go": "Верификациядан өту", "cabwiz_later": "Кейінірек", "cabwiz_done_t": "Кабинет бапталды",
        "cabwiz_done_s": "Таңдалғандар жұмыс істеп тұр және жаңа хабарландыруларға қойылады. Баптауларда өзгертуге болады.",
        "cabwiz_add": "Хабарландыру қосу", "cabwiz_home": "Кабинетке",
        "a11y_avatar": "Профиль фотосы", "a11y_uploading": "Фото жүктелуде", "a11y_checked": "таңдалған",
        "a11y_verified": "тексерілген сатушы"
    ]

    private static let en: [String: String] = [
        "cab_settings": "Settings", "cabset_account": "Account", "hero_profile": "Profile", "hero_pass": "Password",
        "cabset_num": "Number and contacts", "cabset_chat": "Chats", "cabset_listings": "Listings",
        "cabset_cats": "My categories", "cabset_geo": "Region and address", "cabset_hours": "Working hours",
        "cabset_redact": "Personal data in photos", "cabset_sales": "Sales and payment", "cabset_escrow": "Safe deal",
        "esc_on_short": "on", "esc_off_short": "off", "cabset_pay": "Instalments and credit",
        "cabset_reserve": "Item hold after payment", "sec_devices": "Devices and sign-ins", "cabset_app": "App",
        "cabwiz_t": "Getting started", "cabset_lang": "Language", "cabset_del": "Delete account",
        "del_footer": "Deleting the account is done in your account on the website: “Settings” → “Delete account”. It is confirmed there with eGov or your password.",
        "close": "Close", "cancel": "Cancel", "save": "Save", "saving": "Saving…", "processing": "Processing…",
        "err_generic": "Error", "err_no_conn": "No connection", "err_net": "Network error",
        "auth": "Session expired, please sign in again", "loading": "Loading…",
        "ver_ok": "Verified seller", "ver_row": "Verification via eGov",
        "ver_row_s": "Unlocks safe deals through the escrow", "ver_rejected": "Rejected",
        "ver_go": "Get verified",
        "ver_off": "Identity verification is temporarily unavailable due to maintenance. Please try later.",
        "av_change": "Change photo", "av_saved": "Profile photo updated", "av_big": "The photo is larger than 12 MB",
        "phone_hidden": "hidden from buyers · contact via chat",
        "pw_title_change": "Change password", "pw_title_set": "Set your own password",
        "pw_hint_change": "Your current password is required to change it — this protects your account.",
        "pw_hint_set": "No need to enter the old one — you are setting it for the first time. Choose a password you will remember.",
        "pw_old_ph": "Current password", "pw_new_ph": "New password (min. 6 characters)", "pw_new2_ph": "Repeat the password",
        "pw_short": "Password — at least 6 characters", "pw_mismatch": "Passwords do not match", "pw_saved": "Password saved",
        "ph_title": "Change phone number",
        "ph_hint": "Enter your **real** number — it is your contact for deals and buyers. If you registered with the wrong number by mistake, fix it here. After confirmation via eGov the number is tied to your IIN.",
        "ph_hint_v": "The number is tied to your IIN and confirmed via eGov: it is your contact for deals. If it changed in eGov, confirm again and it will update here by itself.",
        "ph_egov_change": "Change number via eGov", "ph_bad": "Enter a valid number (+7 …)",
        "ph_changed_t": "Number saved",
        "ph_changed_m": "Listings can be published from a number linked to eGov. Get verified to link this one.",
        "ph_go": "Continue", "later": "Later", "ph_saved": "Number saved",
        "phv_title": "How to contact you",
        "phv_hint": "Chat is always available. With “Chat and call” a signed-in buyer can call you and write on WhatsApp; with “Chat only” nobody sees the number.",
        "phv_blocked_week": "Didn't see the number this week: {n}", "phv_blocked_none": "Everyone who wanted saw the number this week",
        "phv_saved": "Setting saved", "cc_ways_title": "Ways to contact", "cc_wa_on": "WhatsApp on this number",
        "cc_tg_ph": "@username on Telegram",
        "cc_tg_hint": "The username doesn't reveal your number. Messengers are open to verified buyers.",
        "chat_hint": "How chatting with buyers works.", "chat_ai_t": "Kliko AI assistant in chat",
        "chat_ai_s": "Replies to buyers on your behalf while you are offline and passes hot leads to you. Off by default — messages come straight to you.",
        "chat_ai_note": "The Kliko AI assistant needs an active **Kliko AI subscription** (Kliko AI quota). Without it, buyers' messages come to you directly.",
        "chat_ai_buy": "Get Kliko AI", "cabset_chat_saved": "Chat settings saved",
        "cabset_cats_hint": "Tick the sections you sell in — only they will remain in the posting form. Empty = all sections.",
        "cabset_cats_saved": "Categories saved",
        "cabset_geo_hint": "We'll fill it into the posting form automatically — you can change it when creating a listing.",
        "pg_region_l": "Region", "form_region_ph": "Region / city", "pg_district_l": "District",
        "pg_district_none": "Not specified", "pg_city_l": "City or village", "pg_city_ph": "For example, Kosshy",
        "pg_addr_l": "Street and house", "pg_addr_ph": "Optional", "pg_map_l": "Point on the map", "pg_map_on": "Set",
        "pg_map_off": "Not set",
        "pg_map_note": "Tap the map to set a point.", "pg_map_clear": "Remove point",
        "pg_recv": "This is also my delivery address",
        "pg_recv_s": "We'll fill it into a deal when you buy something. You can change it right there.",
        "del_where_t": "Where I ship", "del_where_all": "All of Kazakhstan", "del_where_all_s": "you ship to any region",
        "del_where_regions": "My region and selected ones", "del_where_regions_s": "tick the regions you ship to",
        "del_where_city": "My city only", "del_where_city_s": "meeting, pickup and courier within the city",
        "del_where_own": "mine",
        "del_where_note": "Meeting and pickup are available to buyers from any region — the limit applies to shipping only.",
        "cabset_geo_saved": "Region and address saved",
        "cabset_hours_hint": "We'll fill it into the posting form — you can change it when creating a listing.",
        "hours_247": "24/7", "cabset_hours_range": "Custom hours", "cabset_hours_none": "Don't specify",
        "hours_from": "From", "hours_to": "To", "cabset_hours_saved": "Default working hours saved",
        "pr_hint": "After publishing, Kliko AI finds serial numbers, IMEI, document numbers and car plates in photos and blurs them. No need to wait: the listing stays “Under review” and goes live once everything is hidden.",
        "pr_off_t": "Don't check", "pr_off_s": "Photos go as they are, publishing doesn't wait for a check",
        "pr_on_t": "Check and hide", "pr_on_s": "Numbers are hidden in the background — they go live without them",
        "pr_note": "You can hide a number on a single photo without this — with the lock button on the thumbnail. Turn it on if you move listings in bulk from other sites: such photos often show other people's numbers.",
        "pr_demo_on": "Example: numbers hidden", "pr_demo_off": "Example: numbers visible",
        "pr_saved_on": "Numbers in photos will be hidden after publishing — no need to wait",
        "pr_saved_off": "Photo check turned off",
        "pr_fail": "Not saved — check your connection and tap “Save” again",
        "esc_pref_hint": "The publishing window will open with this choice. The escrow can be switched separately in every listing — when publishing and editing.",
        "esc_pref_t": "Escrow in new listings",
        "pc_esc_g1": "The buyer pays through Kliko before the handover — no need to take anyone's word",
        "pc_esc_g2": "Kliko holds the money until the buyer gets the item — then it comes to you",
        "pc_esc_g3": "The card shows a “Buy safely” button and the “Escrow” badge",
        "pc_esc_verify": "Will work after identity verification",
        "pc_esc_off": "Off — the buyer can only contact you",
        "esc_pref_auto": "If it doesn't work, is a spare part or the price is below {n}, the escrow turns off by itself.",
        "esc_pref_saved": "Default escrow saved",
        "capp_geo_t": "Apply the address to your listings?",
        "capp_geo_s": "We'll update the region and address in all your current listings. New listings use the default automatically anyway.",
        "capp_hours_t": "Apply the hours to your listings?",
        "capp_hours_s": "We'll update the contact hours of all your goods. Services are not affected — their hours are set separately.",
        "esc_apply_on_t": "Turn on the escrow in all listings?", "esc_apply_off_t": "Turn off the escrow in all listings?",
        "esc_apply_s": "We'll update your current listings. Where the item doesn't work, is a spare part or the price is below the threshold, there will be no escrow anyway.",
        "capp_skip": "Skip", "capp_run": "Apply", "capp_running": "Applying…", "capp_done": "Done",
        "capp_fail_t": "Didn't work", "capp_fail": "Couldn't apply",
        "capp_zero": "You have no listings yet — new ones will pick up the value automatically.", "capp_ok": "Got it",
        "pp_hint": "Applies to all listings where payment isn't set up separately.", "pay_installment": "Instalments",
        "pay_with_bank": "With a bank", "pay_notary": "Without a bank · notary", "pay_markup": "Instalment markup",
        "pp_banks": "Banks", "pp_links": "Payment links in the bank",
        "pp_empty": "Tick a bank above — a field for its payment link will appear.",
        "pp_link_bad": "A link from the bank's website is required: {d}",
        "pp_inst_note": "The buyer opens the link in the bank's app — this payment bypasses the Kliko escrow, and we tell them so plainly. We only accept links from bank websites. Kaspi instalments by link are not available to every seller — check in Kaspi Pay. No link — the buyer will write to you in chat.",
        "pay_credit": "Credit", "pay_annual_rate": "Annual rate",
        "pp_cred_note": "The buyer will see a preliminary calculation. Getting credit right in Kliko is in development.",
        "pp_err_link": "The link must lead to the selected bank's website", "pp_saved": "Instalments and credit saved",
        "cabset_reserve_hint": "How long to hold a single item for the buyer after payment (pickup/city) until they give an address or call a courier.",
        "cabset_reserve_why_t": "Why it matters",
        "cabset_reserve_why1": "The item is held only for the one who paid — two people won't buy the same thing.",
        "cabset_reserve_why2": "If the buyer stalls, the hold expires, the money is refunded and the item is back on sale.",
        "cabset_reserve_why3": "The countdown nudges towards the deal, and those who waited get a “back in stock” push.",
        "min_short": "min", "cabset_reserve_saved": "Hold time saved",
        "sec_one_t": "One device only",
        "sec_one_s": "Signing in on a new device ends the sessions on the others — there we'll show where the sign-in came from and ask whether it was you.",
        "sec_egov_t": "Confirm sign-in via eGov",
        "sec_egov_s": "After the password, Telegram or Apple — also an SMS code on the eGov screen. It can be turned off only via eGov as well.",
        "sec_now": "Signed in now", "sec_this": "this device", "sec_end": "End",
        "sec_end_all": "Sign out on all other devices", "sec_none_others": "No other devices",
        "sec_log": "Recent sign-ins", "sec_active_now": "active now", "sec_ago_min": "{n} min ago",
        "sec_ago_h": "{n} h ago", "sec_ended": "Sessions ended: {n}",
        "sec_egov_on": "Sign-in is now confirmed via eGov", "sec_egov_off": "Sign-in confirmation via eGov turned off",
        "sec_via_password": "password", "sec_via_egov": "eGov", "sec_via_register": "registration",
        "sec_via_legacy": "sign-in before the update", "sec_via_dev": "development", "sec_egov_on_btn": "Turn on",
        "sec_egov_off_site": "Sign-in confirmation can only be turned off with an eGov check — this is done in your account on the website: “Settings” → “Devices and sign-ins”.",
        "open_site": "Open the account on the website",
        "lang_note": "Language of the app and the website. Your choice is saved to your account.",
        "cabwiz_theme_t": "Appearance", "cabwiz_theme_hint": "Changes right away. “{auto}” — as set on the phone.",
        "ap_auto": "As in system", "ap_light": "Light", "ap_dark": "Dark", "cabwiz_ready": "Done",
        "ap_save_fail": "Not saved to the account — visible on this device",
        "cabwiz_lead": "We'll set up your account in a couple of minutes. Each step is saved right away — you can stop at any moment.",
        "cabwiz_meta": "{n} steps · about {m} minutes", "cabwiz_go": "Start", "cabwiz_skip": "Skip",
        "cabwiz_step": "Step {n} of {m}", "cabwiz_skip_step": "Skip step", "cabwiz_back": "Back",
        "cabwiz_next": "Next", "cabwiz_s_theme": "Light, dark or as on the phone",
        "cabwiz_s_geo": "Where you are and where you ship — we'll fill it into every listing",
        "cabwiz_s_cats": "Which sections to show when posting a listing",
        "cabwiz_s_hours": "When you can be contacted", "cabwiz_photo_t": "Personal data in photos",
        "cabwiz_s_photo": "Whether to hide numbers and documents in photos",
        "cabwiz_ver_t": "Last step — verification",
        "cabwiz_ver_s": "Via eGov in a couple of minutes. Unlocks safe deals through the escrow and the “Verified” badge. Your settings are already saved.",
        "cabwiz_ver_go": "Get verified", "cabwiz_later": "Later", "cabwiz_done_t": "Your account is set up",
        "cabwiz_done_s": "Your choices already work and are filled into new listings. You can change them in Settings.",
        "cabwiz_add": "Add a listing", "cabwiz_home": "To my account",
        "a11y_avatar": "Profile photo", "a11y_uploading": "Uploading photo", "a11y_checked": "selected",
        "a11y_verified": "verified seller"
    ]

    private static let ar: [String: String] = [
        "cab_settings": "الإعدادات", "cabset_account": "الحساب", "hero_profile": "الملف الشخصي", "hero_pass": "كلمة المرور",
        "cabset_num": "الرقم وجهات الاتصال", "cabset_chat": "المحادثات", "cabset_listings": "الإعلانات",
        "cabset_cats": "فئاتي", "cabset_geo": "المنطقة والعنوان", "cabset_hours": "ساعات العمل",
        "cabset_redact": "البيانات الشخصية في الصور", "cabset_sales": "المبيعات والدفع", "cabset_escrow": "صفقة مضمونة",
        "esc_on_short": "مفعّل", "esc_off_short": "متوقف", "cabset_pay": "التقسيط والائتمان",
        "cabset_reserve": "حجز السلعة بعد الدفع", "sec_devices": "الأجهزة وعمليات الدخول", "cabset_app": "التطبيق",
        "cabwiz_t": "بداية العمل", "cabset_lang": "اللغة", "cabset_del": "حذف الحساب",
        "del_footer": "يتم حذف الحساب من حسابك على الموقع: «الإعدادات» ← «حذف الحساب». وهناك يتم تأكيده عبر eGov أو بكلمة المرور.",
        "close": "إغلاق", "cancel": "إلغاء", "save": "حفظ", "saving": "جارٍ الحفظ…", "processing": "جارٍ التنفيذ…",
        "err_generic": "خطأ", "err_no_conn": "لا يوجد اتصال", "err_net": "خطأ في الشبكة",
        "auth": "انتهت الجلسة، سجّل الدخول من جديد", "loading": "جارٍ التحميل…",
        "ver_ok": "بائع موثّق", "ver_row": "التوثيق عبر eGov",
        "ver_row_s": "يتيح الصفقات الآمنة عبر الضامن", "ver_rejected": "مرفوض",
        "ver_go": "إجراء التوثيق",
        "ver_off": "تأكيد الهوية غير متاح مؤقتًا بسبب أعمال فنية. حاول لاحقًا.",
        "av_change": "تغيير الصورة", "av_saved": "تم تحديث صورة الملف الشخصي", "av_big": "الصورة أكبر من 12 ميغابايت",
        "phone_hidden": "مخفي عن المشترين · التواصل عبر المحادثة",
        "pw_title_change": "تغيير كلمة المرور", "pw_title_set": "تعيين كلمة مرور خاصة بك",
        "pw_hint_change": "لتغييرها تلزم كلمة المرور الحالية — لحماية الحساب.",
        "pw_hint_set": "لا حاجة لإدخال القديمة — أنت تعيّنها لأول مرة. اختر كلمة مرور تتذكرها.",
        "pw_old_ph": "كلمة المرور الحالية", "pw_new_ph": "كلمة مرور جديدة (6 أحرف على الأقل)", "pw_new2_ph": "كرّر كلمة المرور",
        "pw_short": "كلمة المرور — 6 أحرف على الأقل", "pw_mismatch": "كلمتا المرور غير متطابقتين", "pw_saved": "تم حفظ كلمة المرور",
        "ph_title": "تغيير رقم الهاتف",
        "ph_hint": "أدخل رقمك **الحقيقي** — فهو وسيلة التواصل للصفقات والمشترين. إذا سجّلت برقم خاطئ بالخطأ فصحّحه هنا. بعد التأكيد عبر eGov يُربط الرقم برقمك الوطني (IIN).",
        "ph_hint_v": "الرقم مربوط برقمك الوطني ومؤكَّد عبر eGov: هو وسيلة التواصل للصفقات. إذا تغيّر في eGov فأعد التأكيد، وسيتحدّث هنا تلقائيًا.",
        "ph_egov_change": "تغيير الرقم عبر eGov", "ph_bad": "أدخل رقمًا صحيحًا (+7 …)",
        "ph_changed_t": "تم حفظ الرقم",
        "ph_changed_m": "يمكن نشر الإعلانات من رقم مربوط بـ eGov. أكمل التوثيق لربط هذا الرقم.",
        "ph_go": "متابعة", "later": "لاحقًا", "ph_saved": "تم حفظ الرقم",
        "phv_title": "كيف يتواصلون معك",
        "phv_hint": "المحادثة متاحة دائمًا. مع «محادثة واتصال» يمكن للمشتري المسجّل الاتصال بك والكتابة في واتساب، ومع «محادثة فقط» لا يرى أحد الرقم.",
        "phv_blocked_week": "لم يروا الرقم هذا الأسبوع: {n}", "phv_blocked_none": "كل من أراد رأى الرقم هذا الأسبوع",
        "phv_saved": "تم حفظ الإعداد", "cc_ways_title": "طرق التواصل", "cc_wa_on": "واتساب على هذا الرقم",
        "cc_tg_ph": "‏@username في تيليغرام",
        "cc_tg_hint": "اسم المستخدم لا يكشف رقمك. المراسلات متاحة للمشترين الموثّقين.",
        "chat_hint": "كيف يعمل التواصل مع المشترين في المحادثة.", "chat_ai_t": "مساعد Kliko AI في المحادثة",
        "chat_ai_s": "يرد على المشترين باسمك عندما تكون غير متصل ويحوّل إليك الطلبات الساخنة. متوقف افتراضيًا — تصلك الرسائل مباشرة.",
        "chat_ai_note": "يحتاج مساعد Kliko AI إلى **اشتراك Kliko AI** فعّال (حصة Kliko AI). بدونه تصلك رسائل المشترين مباشرة.",
        "chat_ai_buy": "الاشتراك في Kliko AI", "cabset_chat_saved": "تم حفظ إعدادات المحادثة",
        "cabset_cats_hint": "حدّد الأقسام التي تبيع فيها — ستبقى وحدها في نموذج الإضافة. فارغ = كل الأقسام.",
        "cabset_cats_saved": "تم حفظ الفئات",
        "cabset_geo_hint": "سنضعه في نموذج الإضافة تلقائيًا — يمكن تغييره عند إنشاء الإعلان.",
        "pg_region_l": "المنطقة", "form_region_ph": "المقاطعة / المدينة", "pg_district_l": "الحي",
        "pg_district_none": "غير محدد", "pg_city_l": "المدينة أو البلدة", "pg_city_ph": "مثلًا، قوسشي",
        "pg_addr_l": "الشارع والمبنى", "pg_addr_ph": "اختياري", "pg_map_l": "نقطة على الخريطة", "pg_map_on": "محددة",
        "pg_map_off": "غير محددة",
        "pg_map_note": "اضغط على الخريطة لتحديد نقطة.", "pg_map_clear": "إزالة النقطة",
        "pg_recv": "وهذا أيضًا عنوان الاستلام",
        "pg_recv_s": "سنضعه في الصفقة عندما تشتري شيئًا. يمكن تغييره هناك مباشرة.",
        "del_where_t": "إلى أين أشحن", "del_where_all": "كل كازاخستان", "del_where_all_s": "تشحن إلى أي منطقة",
        "del_where_regions": "منطقتي والمختارة", "del_where_regions_s": "حدّد المناطق التي تشحن إليها",
        "del_where_city": "مدينتي فقط", "del_where_city_s": "لقاء واستلام ذاتي ومندوب داخل المدينة",
        "del_where_own": "منطقتي",
        "del_where_note": "اللقاء والاستلام الذاتي متاحان للمشتري من أي منطقة — القيد يخص الشحن فقط.",
        "cabset_geo_saved": "تم حفظ المنطقة والعنوان",
        "cabset_hours_hint": "سنضعه في نموذج الإضافة — يمكن تغييره عند إنشاء الإعلان.",
        "hours_247": "على مدار الساعة 24/7", "cabset_hours_range": "وقت مخصص", "cabset_hours_none": "عدم التحديد",
        "hours_from": "من", "hours_to": "إلى", "cabset_hours_saved": "تم حفظ ساعات العمل الافتراضية",
        "pr_hint": "بعد النشر يعثر Kliko AI في الصور على الأرقام التسلسلية وIMEI وأرقام الوثائق ولوحات السيارات ويطمسها. لا حاجة للانتظار: يبقى الإعلان «قيد المراجعة» ويظهر في الواجهة عندما يُخفى كل شيء.",
        "pr_off_t": "عدم الفحص", "pr_off_s": "تُرسل الصور كما هي، ولا ينتظر النشر الفحص",
        "pr_on_t": "الفحص والإخفاء", "pr_on_s": "تُخفى الأرقام في الخلفية — وتظهر في الواجهة بدونها",
        "pr_note": "يمكن إخفاء رقم في صورة واحدة بدون هذا — بزر القفل على الصورة المصغّرة. فعّله إذا كنت تنقل إعلانات دفعة واحدة من منصات أخرى: فهذه الصور كثيرًا ما تحمل أرقامًا لآخرين.",
        "pr_demo_on": "مثال: الأرقام مخفية", "pr_demo_off": "مثال: الأرقام ظاهرة",
        "pr_saved_on": "ستُخفى الأرقام في الصور بعد النشر — لا حاجة للانتظار",
        "pr_saved_off": "تم إيقاف فحص الصور",
        "pr_fail": "لم يُحفظ — تحقق من الاتصال واضغط «حفظ» مرة أخرى",
        "esc_pref_hint": "ستُفتح نافذة النشر بهذا الاختيار. يمكن تبديل الضامن في كل إعلان على حدة — عند النشر والتعديل.",
        "esc_pref_t": "الضامن في الإعلانات الجديدة",
        "pc_esc_g1": "يدفع المشتري عبر Kliko قبل التسليم — لا حاجة للثقة بالكلام",
        "pc_esc_g2": "يحتفظ Kliko بالمال حتى يستلم المشتري السلعة — ثم يصل إليك",
        "pc_esc_g3": "في البطاقة زر «اشترِ بأمان» وشارة «الضامن»",
        "pc_esc_verify": "سيعمل بعد توثيق الهوية",
        "pc_esc_off": "متوقف — لن يتمكن المشتري إلا من التواصل معك",
        "esc_pref_auto": "إذا كانت لا تعمل أو كانت قطع غيار أو السعر أقل من {n} — يتوقف الضامن تلقائيًا.",
        "esc_pref_saved": "تم حفظ الضامن الافتراضي",
        "capp_geo_t": "تطبيق العنوان على الإعلانات؟",
        "capp_geo_s": "سنحدّث المنطقة والعنوان في كل إعلاناتك الحالية. الإعلانات الجديدة تأخذ القيمة الافتراضية تلقائيًا.",
        "capp_hours_t": "تطبيق الساعات على الإعلانات؟",
        "capp_hours_s": "سنحدّث وقت التواصل لكل سلعك. لا نمسّ الخدمات — فساعاتها تُحدَّد على حدة.",
        "esc_apply_on_t": "تفعيل الضامن في كل الإعلانات؟", "esc_apply_off_t": "إيقاف الضامن في كل الإعلانات؟",
        "esc_apply_s": "سنحدّث إعلاناتك الحالية. حيث لا تعمل السلعة أو كانت قطع غيار أو السعر أقل من الحد — لن يكون هناك ضامن على أي حال.",
        "capp_skip": "تخطٍّ", "capp_run": "تطبيق", "capp_running": "جارٍ التطبيق…", "capp_done": "تم",
        "capp_fail_t": "لم ينجح", "capp_fail": "تعذّر التطبيق",
        "capp_zero": "لا توجد لديك إعلانات بعد — ستأخذ الجديدة القيمة تلقائيًا.", "capp_ok": "مفهوم",
        "pp_hint": "يسري على كل الإعلانات التي لم يُضبط فيها الدفع على حدة.", "pay_installment": "التقسيط",
        "pay_with_bank": "مع بنك", "pay_notary": "بدون بنك · كاتب عدل", "pay_markup": "زيادة التقسيط",
        "pp_banks": "البنوك", "pp_links": "روابط الدفع في البنك",
        "pp_empty": "حدّد بنكًا أعلاه — سيظهر حقل لرابط الدفع الخاص به.",
        "pp_link_bad": "يلزم رابط من موقع البنك: {d}",
        "pp_inst_note": "يفتح المشتري الرابط في تطبيق البنك — هذا الدفع يتم خارج ضامن Kliko، ونخبره بذلك صراحة. نقبل الروابط من مواقع البنوك فقط. التقسيط عبر الرابط في Kaspi ليس متاحًا لكل البائعين — تحقّق في Kaspi Pay. لا رابط — سيكتب لك المشتري في المحادثة.",
        "pay_credit": "الائتمان", "pay_annual_rate": "النسبة السنوية",
        "pp_cred_note": "سيرى المشتري حسابًا أوليًا. إصدار الائتمان مباشرة في Kliko قيد التطوير.",
        "pp_err_link": "يجب أن يؤدي الرابط إلى موقع البنك المختار", "pp_saved": "تم حفظ التقسيط والائتمان",
        "cabset_reserve_hint": "كم تُحجز السلعة الفردية للمشتري بعد الدفع (استلام ذاتي/المدينة) حتى يحدد العنوان أو يستدعي مندوبًا.",
        "cabset_reserve_why_t": "لماذا هذا مهم",
        "cabset_reserve_why1": "تُحجز السلعة لمن دفع فقط — لن يشتري اثنان الشيء نفسه.",
        "cabset_reserve_why2": "إذا تأخّر المشتري ينتهي الحجز، ويُعاد إليه المال، وتعود السلعة للبيع.",
        "cabset_reserve_why3": "العدّ التنازلي يدفع نحو الصفقة، ويصل لمن انتظر إشعار «متاح مجددًا».",
        "min_short": "د", "cabset_reserve_saved": "تم حفظ مدة الحجز",
        "sec_one_t": "جهاز واحد فقط",
        "sec_one_s": "الدخول من جهاز جديد ينهي الجلسات على الأجهزة الأخرى — وهناك سنُظهر مصدر الدخول ونسأل إن كنت أنت.",
        "sec_egov_t": "تأكيد الدخول عبر eGov",
        "sec_egov_s": "بعد كلمة المرور أو تيليغرام أو Apple — رمز SMS إضافي على شاشة eGov. ولا يمكن إيقافه إلا عبر eGov أيضًا.",
        "sec_now": "المتصلون الآن", "sec_this": "هذا الجهاز", "sec_end": "إنهاء",
        "sec_end_all": "الخروج من كل الأجهزة الأخرى", "sec_none_others": "لا توجد أجهزة أخرى",
        "sec_log": "آخر عمليات الدخول", "sec_active_now": "نشط الآن", "sec_ago_min": "منذ {n} د",
        "sec_ago_h": "منذ {n} س", "sec_ended": "انتهت الجلسات: {n}",
        "sec_egov_on": "أصبح الدخول يُؤكَّد عبر eGov", "sec_egov_off": "تم إيقاف تأكيد الدخول عبر eGov",
        "sec_via_password": "كلمة المرور", "sec_via_egov": "eGov", "sec_via_register": "التسجيل",
        "sec_via_legacy": "دخول قبل التحديث", "sec_via_dev": "التطوير", "sec_egov_on_btn": "تفعيل",
        "sec_egov_off_site": "لا يمكن إيقاف تأكيد الدخول إلا بفحص eGov — ويتم ذلك من حسابك على الموقع: «الإعدادات» ← «الأجهزة وعمليات الدخول».",
        "open_site": "فتح الحساب على الموقع",
        "lang_note": "لغة التطبيق والموقع. يُحفظ اختيارك في الحساب.",
        "cabwiz_theme_t": "المظهر", "cabwiz_theme_hint": "يتغيّر فورًا. «{auto}» — كما هو مضبوط في الهاتف.",
        "ap_auto": "كما في النظام", "ap_light": "فاتح", "ap_dark": "داكن", "cabwiz_ready": "تم",
        "ap_save_fail": "لم يُحفظ في الحساب — ظاهر على هذا الجهاز",
        "cabwiz_lead": "سنضبط حسابك في دقيقتين. تُحفظ كل خطوة فورًا — ويمكن التوقف في أي لحظة.",
        "cabwiz_meta": "{n} خطوات · نحو {m} دقائق", "cabwiz_go": "ابدأ", "cabwiz_skip": "تخطٍّ",
        "cabwiz_step": "الخطوة {n} من {m}", "cabwiz_skip_step": "تخطي الخطوة", "cabwiz_back": "رجوع",
        "cabwiz_next": "التالي", "cabwiz_s_theme": "فاتح أو داكن أو كما في الهاتف",
        "cabwiz_s_geo": "من أين أنت وإلى أين تشحن — سنضعه في كل إعلان",
        "cabwiz_s_cats": "أي الأقسام تُعرض عند نشر إعلان",
        "cabwiz_s_hours": "متى يمكن التواصل معك", "cabwiz_photo_t": "البيانات الشخصية في الصور",
        "cabwiz_s_photo": "هل تُخفى الأرقام والوثائق في الصور",
        "cabwiz_ver_t": "الخطوة الأخيرة — التوثيق",
        "cabwiz_ver_s": "عبر eGov في دقيقتين. يتيح الصفقات الآمنة عبر الضامن وشارة «موثّق». الإعدادات محفوظة بالفعل.",
        "cabwiz_ver_go": "إجراء التوثيق", "cabwiz_later": "لاحقًا", "cabwiz_done_t": "تم ضبط الحساب",
        "cabwiz_done_s": "ما اخترته يعمل الآن ويُضاف إلى الإعلانات الجديدة. يمكن تغييره في الإعدادات.",
        "cabwiz_add": "إضافة إعلان", "cabwiz_home": "إلى الحساب",
        "a11y_avatar": "صورة الملف الشخصي", "a11y_uploading": "جارٍ رفع الصورة", "a11y_checked": "محدد",
        "a11y_verified": "بائع موثّق"
    ]
}
