import Foundation

/**
 Тексты кошелька и баллов — этап 47 (владелец 26.09.2026: «всё одно и то же, просто код разный»), на языке телефона
 (kk/ru/en/ar).

 Русские — слово в слово с сайта: словарь js/i18n-cabinet-ru.js (cab_wallet, wal_*, tx_*, frz_*, topup_*, wd_*, lad_*,
 otp_wd_*, d_short, h_short) и фразы, зашитые в код без ключа: js/cabinet.min.js (баннер «Выплата … готова»,
 payoutOpenLink, wdOutcomeModal, tpmOpen, ссылки «сделка» / «чек» истории), js/cabinet-wallet.min.js (кнопка «Пополнить
 на N ₸», «Минимум 100 ₸», «Баланс пополнен на…», «Нужна верификация» перед выводом, «Далее · N ₸», «Отправка…»,
 «Стать магазином», «Авто-вывод включён», «Без комиссии: … · под комиссию: …») и js/cabinet-deals.min.js (экран «Баллы»:
 «Ваш кэшбэк …», «До уровня …», «Баллов ещё нет …»), разметка экранов #topup-screen, #withdraw-screen, #points-screen
 страницы кабинета. Три строки со ставками (wd_min, wd_bank_hint, wd_term2_s) сервер печатает в объект T страницы —
 их берёт КошелёкМодель со страницы, а здесь лишь запасной текст (карта §5.3.3, §5.6).

 Где у сайта подстановка — здесь {n}, {t}, {p}, {e}, {d}, {c}, {l}, {m}, {a}, {b}, {u}; их заменяет вызывающий.
 Свои слова приложения — только пояснение «пополнение и вывод — в кабинете на сайте», пока Config.деньгиКошелька
 выключен (site_note), просьба нажать ещё раз после eGov (otp_passed) и подписи VoiceOver (a11y_*). Остальные языки —
 перевод тех же фраз.
 */
enum КошелёкText {
    static func т(_ ключ: String) -> String {
        let словарь = тексты[язык] ?? ru
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    /// Текст с одной подстановкой {n} — как .replace("{n}", …) сайта.
    static func т(_ ключ: String, n: String) -> String {
        т(ключ).replacingOccurrences(of: "{n}", with: n)
    }

    /// Текст с подстановками по имени: ["n": "5 000", "p": "6"] → {n}, {p}.
    static func т(_ ключ: String, _ замены: [String: String]) -> String {
        var итог = т(ключ)
        for (имя, значение) in замены {
            итог = итог.replacingOccurrences(of: "{" + имя + "}", with: значение)
        }
        return итог
    }

    static var язык: String { String((Locale.preferredLanguages.first ?? "ru").prefix(2)) }

    private static let тексты: [String: [String: String]] = ["ru": ru, "kk": kk, "en": en, "ar": ar]

    // MARK: - Русский (сайт)

    private static let ru: [String: String] = [
        // Шапка «Кошелёк» (hero-wallet, loadWalletInfo)
        "title": "Кошелёк", "topup": "Пополнить", "withdraw": "Вывести",
        "sub": "Оплата товаров и услуг · продвижение и слоты", "out_can": "Вывести на карту: {n} ₸",
        "held_line": "На удержании {n} ₸ · освободится через {t}", "lock_line": "пополнение с карты {n} ₸ — на услуги Kliko",
        "d_short": "дн.", "h_short": "ч", "held": "На удержании", "held_why": "Срок безопасности",
        "held_left": "освободится через",
        "held_note": "Деньги ваши и никуда не денутся — их можно будет вывести, когда закончится срок. Он короче, если покупатель подтвердил получение.",
        "lock_t": "Пополнение с карты",
        "lock_note": "Пока гарант-сделка на паузе, деньги, пополненные с карты, расходуются только на услуги Kliko — на другие реквизиты их не вывести. Неиспользованный остаток вернём на ту же карту.",
        "lock_sup": "Написать в поддержку", "history": "История операций", "points": "Баллы",
        "site_note": "Пополнение, вывод и выплата на карту открываются в кабинете на сайте.",
        "loading": "Загрузка…", "tx_none": "Операций пока нет", "tx_generic": "Операция", "tx_deal": "сделка",
        "tx_receipt": "чек", "rc_loading": "Загрузка чека…", "no_title": "Без названия",
        "err_generic": "Ошибка", "err_net": "Ошибка сети", "err_no_conn": "Нет соединения", "retry": "Повторить",
        "close": "Закрыть", "cancel": "Отмена", "ok": "Понятно", "later": "Позже",
        // Типы операций (loadWalletInfo, объект e)
        "tx_topup": "Пополнение кошелька", "tx_admin_topup": "Пополнение от администратора", "tx_top": "ТОП-продвижение",
        "tx_discount": "Скидка", "tx_escrow_hold": "Гарант: деньги заморожены",
        "tx_escrow_release": "Гарант: выплата за продажу", "tx_escrow_refund": "Гарант: возврат покупателю",
        "tx_topup_refund": "Возврат пополнения на карту",
        "tx_topup_refund_back": "Возврат на карту не прошёл — деньги на балансе",
        "tx_escrow_cancel": "Гарант: отмена, возврат", "tx_withdraw": "Вывод средств",
        "tx_escrow_new": "Гарант: сделка создана", "tx_escrow_delivered": "Гарант: товар передан",
        "tx_escrow_payout": "Гарант: выплата", "tx_sale": "Продажа", "tx_earn": "Заработок",
        "tx_ai_scan": "Kliko AI: глубокий разбор", "tx_ai_scan_refund": "Kliko AI: возврат за разбор",
        "tx_buy_ai": "Пакет Kliko AI", "tx_admin_deduct": "Списание администратором", "tx_promote": "Поднятие объявления",
        "tx_promote_bulk": "Поднятие нескольких объявлений", "tx_promote_bulk_refund": "Возврат за продвижение",
        "tx_jobs_top": "ТОП в разделе «Работа»", "tx_slots": "Расширение слотов", "tx_combo": "Пакет продвижения",
        "tx_pro": "Подписка PRO", "tx_buy_storefront": "Оформление витрины", "tx_escrow_advance": "Гарант: аванс за услугу",
        "tx_eds_fee": "Подписание договора с подписью eGov", "tx_eds_fee_back": "Возврат платы за подписание",
        "tx_eds_ship": "Курьер Яндекса по сделке", "tx_eds_ship_back": "Возврат доставки",
        // «Заморожено сейчас» (frozenRender, frozenUnfund)
        "frz_title": "Заморожено сейчас", "frz_sub": "Списаны с баланса и ждут исхода. Освободить можно отсюда.",
        "frz_in_deal": "В гарант-сделке", "frz_in_offer": "Обеспечение предложения", "frz_open": "Сделка",
        "frz_cancel_deal": "Вернуть деньги", "frz_unfund": "Вернуть деньги", "frz_dispute": "Спор",
        "frz_why_ship": "Товар отправлен — деньги вернёт спор, не отмена.",
        "frz_why_meet": "Код встречи показан — вещь могли уже отдать.",
        "frz_why_stage": "Сделка закрыта — деньги не заперты.", "frz_why_denied": "Отменяет только сторона сделки.",
        "frz_unfund_t": "Снять предложение?",
        "frz_unfund_s": "Деньги вернутся целиком. Договорённость о цене перестанет действовать.",
        "frz_unfund_ok": "Снять и вернуть", "frz_unfund_done": "Предложение снято, деньги вернулись на баланс",
        // Выплата готова (payoutBannerHTML, payoutOpenLink) и её итог (wdOutcomeModal)
        "po_ready": "Выплата {n} ₸ готова", "po_sub": "Укажите карту на странице банка{d}.", "po_until": " до {d}",
        "po_go": "Указать карту", "po_opening": "Открываем…", "po_unavail": "Ссылка недоступна",
        "po_nonet": "Нет связи — попробуйте ещё раз",
        "out_paid_t": "Деньги отправлены", "out_paid_s": "Банк проводит перевод на вашу карту.",
        "out_fail_t": "Не удалось вывести", "out_fail_s": "Сумма вернулась на баланс — попробуйте ещё раз.",
        "balance": "Баланс",
        // Пополнение (#topup-screen, doTopup, tpmOpen)
        "topup_title": "Пополнить кошелёк",
        "topup_sub": "Единый баланс: **покупки товаров и услуг** через гарант-сделку, а также продвижение, слоты и PRO",
        "topup_pick": "Выберите сумму", "topup_custom_ph": "Своя сумма", "topup_less": "Меньше на 1000",
        "topup_more": "Больше на 1000", "topup_limits": "Любая сумма от 100 ₸ до 1 000 000 ₸ за раз",
        "topup_choose_btn": "Выберите сумму", "topup_btn": "Пополнить на {n} ₸", "topup_max": "Максимум 1 000 000 ₸",
        "topup_min": "Минимум 100 ₸", "topup_processing": "Обработка…", "topup_going": "Переходим к оплате…",
        "topup_consent": "Нажимая кнопку оплаты, вы принимаете [Условия оплаты и возврата]({u}) и соглашаетесь на обработку персональных данных для проведения платежа, в том числе платёжной организацией [ТОО «Freedom Pay»](https://freedompay.kz).",
        "topup_t1": "Без комиссии", "topup_t2": "Зачисление сразу", "topup_t3": "Под защитой",
        "topup_done": "Баланс пополнен на {n} ₸", "topup_off": "Онлайн-оплата временно недоступна",
        "topup_again_q": "Пополнить кошелёк?", "gw_title": "Оплата",
        // Своё приложения (правило App Store 3.1.1, Config.цифровыеПокупки = false): без продвижения, слотов и PRO — их в
        // приложении не продают; «Эта возможность недоступна в приложении.» — текст сайта (klkAppNoDigital).
        "sub_app": "Оплата товаров и услуг через гарант-сделку",
        "topup_sub_app": "Единый баланс для **покупки товаров и услуг** через гарант-сделку",
        "tpm_ok_s_app": "Деньги на балансе — можно оплачивать сделки.",
        "topup_paused_app": "Эта возможность недоступна в приложении.",
        "tpm_proc_t": "Проверяем оплату…", "tpm_proc_s": "Секунду — подтверждаем платёж и зачисляем на кошелёк.",
        "tpm_ok_t": "Кошелёк пополнен", "tpm_ok_s": "Деньги на балансе — можно оплачивать сделки, продвижение и PRO.",
        "tpm_ok_btn": "Отлично", "tpm_pend_t": "Оплата принята",
        "tpm_pend_s": "Если платёж прошёл, баланс обновится в течение пары минут. Обновите страницу или напишите в поддержку, если средства не появятся.",
        "tpm_fail_t": "Оплата не прошла",
        "tpm_fail_s": "Платёж не завершён или отклонён банком. Деньги не списаны — можно попробовать ещё раз.",
        // Вывод (#withdraw-screen, showWithdraw, wdUpdateBtn, doWithdraw, wdResultModal)
        "verify_t": "Нужна верификация",
        "verify_s": "Вывод средств доступен только верифицированным аккаунтам — так деньги под защитой платформы, а выплата гарантированно уходит владельцу.\n\nПополнять баланс можно и без верификации.",
        "verify_go": "Пройти верификацию",
        "wd_title": "Вывод средств", "wd_step_amount": "Сумма", "wd_step_card": "Карта и проверка",
        "wd_sub": "Заработанное с гарант-сделок выводится **без комиссии площадки**. Непроведённые средства (пополнение без сделок) — с комиссией {p}%.",
        "wd_available": "Доступно к выводу", "wd_amount_label": "Сумма вывода", "wd_amount_ph": "Или введите сумму",
        "wd_min": "Минимальная сумма вывода — {n} ₸", "wd_min_tail": "Остаток {n} ₸ выводится целиком",
        "wd_all": "всё", "wd_nothing": "Пока выводить нечего: доступно {n} ₸",
        "wd_cap": "За одну операцию — не больше {n} ₸. Остальное выведете следующей.",
        "wd_over_cap": "Больше потолка за операцию — {n} ₸", "wd_over_avail": "Больше, чем доступно — {n} ₸",
        "wd_bank_fee": "Банковский сбор", "wd_fee_row": "Комиссия {p}% (непроведённые средства)",
        "wd_fee_pct": "Комиссия {p}%", "wd_payout": "К зачислению", "wd_sum_amt": "Сумма вывода",
        "wd_free_ok": "Без комиссии — в пределах заработанного с продаж",
        "wd_free_split": "Без комиссии: {a} ₸ · под комиссию: {b} ₸",
        "wd_next": "Далее", "wd_next_sum": "Далее · {n} ₸", "wd_edit_amount": "Изменить", "wd_sum_is": "Сумма: {n}",
        "wd_method": "Способ вывода", "wd_card": "Банковская карта", "wd_card_note": "Любой банк Казахстана",
        "wd_card_later": "Карту укажете на странице банка", "wd_check_t": "Проверьте данные",
        "wd_chk_note": "Сумма спишется с баланса сейчас. Карту для получения укажете по ссылке, когда мы подтвердим заявку.",
        "wd_confirm_btn": "Всё верно, вывести {n} ₸", "wd_submit": "Вывести средства", "wd_sending": "Отправка…",
        "wd_auto_t": "Авто-вывод", "wd_auto_off": "Выключен — выводите вручную", "wd_auto_on": "Включён · на карту",
        "wd_auto_on_bank": "Включён · на счёт",
        "wd_auto_hint": "При включении заработок с продаж будет автоматически выводиться на привязанный способ (по достижении {n} ₸). Выберите способ выше — он станет привязанным. Для карты реквизиты не нужны: её вы укажете по ссылке, когда выплату подтвердят.",
        "wd_auto_need": "Сначала выберите способ вывода выше", "wd_auto_done_on": "Авто-вывод включён",
        "wd_auto_done_off": "Авто-вывод выключен",
        "wd_term1_t": "Сначала подтверждение, потом карта",
        "wd_term1_s": "Деньги списываются с баланса сразу; когда заявку подтвердят, укажете карту по ссылке",
        "wd_term2_t": "Заработок с продаж — без комиссии",
        "wd_term2_s": "Вывод неиспользованного пополнения — с комиссией {p}%",
        "wd_term3_t": "Уведомим, когда будет готово", "wd_term3_s": "Придёт, когда деньги отправят на ваш счёт",
        "wd_need": "Укажите сумму и способ вывода", "wd_err": "Ошибка: {e}", "wd_err_retry": "попробуйте снова",
        "wd_res_t": "Заявка принята", "wd_res_s": "Сумма списана с баланса и зарезервирована под выплату.",
        "wd_res_amt": "Сумма вывода", "wd_res_fee": "Комиссия", "wd_res_get": "К зачислению",
        "wd_res_now": "Осталось указать карту — номер вводится на странице банка и к нам не попадает.",
        "wd_res_when": "Подтверждение — {t}.", "wd_term_card": "обычно в течение рабочего дня",
        "wd_res_track": "Когда заявку подтвердят, в кошельке появится кнопка «Указать карту» — номер вводится на странице банка.",
        "wd_res_go": "Указать карту", "wd_res_later": "Позже — ссылка останется в кошельке", "wd_res_ok": "Понятно",
        "split_need": "Нужен статус «Магазин»", "split_t": "Стать магазином",
        "split_s": "Вывод на расчётный счёт — для магазинов. Нужно подключить выплаты на счёт компании (проверка реквизитов, 1–3 дня). Перейти к оформлению?",
        "split_go": "Оформить статус «Магазин»",
        "otp_wd_title": "Биометрия для вывода",
        "otp_wd_hint": "Подтвердите вывод биометрией (лицо) и eGov — так деньги под защитой и выплата уходит именно вам.",
        "otp_passed": "Проверка пройдена. Нажмите «Всё верно, вывести» ещё раз.",
        // Ступень доверия (wdLadderCard)
        "lad_op": "За операцию", "lad_month": "За месяц", "lad_next": "До ступени «{l}»: {m}", "lad_deals": "сделок",
        "lad_turnover": "оборота", "lad_days": "суток", "lad_top": "Это верхняя ступень.", "lad_penalty": "ступень снижена",
        // Баллы (#points-screen, showPoints модуля deals)
        "ps_balance": "БАЛАНС БАЛЛОВ", "ps_cashline": "Ваш кэшбэк {c}% · 1 балл = 1 ₸ · до {m}% сделки можно оплатить баллами",
        "ps_next": "До уровня «{l}»: ещё {n} баллов", "ps_max": "Максимальный уровень достигнут!",
        "ps_earn_t": "Как получить баллы", "ps_buyer_b": "Покупка через гарант",
        "ps_buyer_s": " — {n}% от суммы (растёт с уровнем)", "ps_seller_b": "Продажа через гарант",
        "ps_seller_s": " — {n}% от суммы", "ps_spend_t": "Как потратить",
        "ps_spend": "При оплате следующей сделки выберите «Применить баллы» — до {n}% от суммы покрывается баллами автоматически.",
        "ps_levels_t": "Уровни участника", "lvl_0": "Новичок", "lvl_100": "Новичок+", "lvl_500": "Активный",
        "lvl_1000": "Знаток", "lvl_5000": "Эксперт", "ps_pts": "{n} баллов", "ps_pts_tier": "{n} б. · {c}%",
        "ps_log_t": "История начислений", "ps_log_none": "Баллов ещё нет — завершите первую сделку через гарант",
        "ps_deal": "→ сделка",
        // VoiceOver
        "a11y_hide": "Скрыть баланс и контакты", "a11y_show": "Показать баланс и контакты", "a11y_hidden": "Баланс скрыт",
        "a11y_in": "Зачисление", "a11y_out": "Списание", "a11y_bar": "До следующего уровня",
        "a11y_reached": "достигнут", "a11y_site": "откроется сайт"
    ]

    // MARK: - Қазақша

    private static let kk: [String: String] = [
        "title": "Әмиян", "topup": "Толтыру", "withdraw": "Шығару",
        "sub": "Тауарлар мен қызметтерге төлем · жарнама және слоттар", "out_can": "Картаға шығаруға болады: {n} ₸",
        "held_line": "Ұсталуда {n} ₸ · босайды: {t}", "lock_line": "картадан толтыру {n} ₸ — Kliko қызметтеріне",
        "d_short": "күн", "h_short": "сағ", "held": "Ұсталуда", "held_why": "Қауіпсіздік мерзімі", "held_left": "босайды:",
        "held_note": "Ақша сіздікі және еш жаққа кетпейді — мерзім біткенде шығаруға болады. Сатып алушы алғанын растаса, мерзім қысқарады.",
        "lock_t": "Картадан толтыру",
        "lock_note": "Кепіл-мәміле тоқтатылған кезде картадан толтырылған ақша тек Kliko қызметтеріне жұмсалады — оны басқа деректемелерге шығару мүмкін емес. Жұмсалмаған қалдықты сол картаға қайтарамыз.",
        "lock_sup": "Қолдауға жазу", "history": "Операциялар тарихы", "points": "Ұпайлар",
        "site_note": "Толтыру, шығару және картаға төлем сайттағы кабинетте ашылады.",
        "loading": "Жүктелуде…", "tx_none": "Әзірге операциялар жоқ", "tx_generic": "Операция", "tx_deal": "мәміле",
        "tx_receipt": "чек", "rc_loading": "Чек жүктелуде…", "no_title": "Атауы жоқ",
        "err_generic": "Қате", "err_net": "Желі қатесі", "err_no_conn": "Байланыс жоқ", "retry": "Қайталау",
        "close": "Жабу", "cancel": "Бас тарту", "ok": "Түсінікті", "later": "Кейінірек",
        "tx_topup": "Әмиянды толтыру", "tx_admin_topup": "Әкімшіден толтыру", "tx_top": "ТОП-жарнама",
        "tx_discount": "Жеңілдік", "tx_escrow_hold": "Кепіл: ақша бұғатталды", "tx_escrow_release": "Кепіл: сатылым төлемі",
        "tx_escrow_refund": "Кепіл: сатып алушыға қайтару", "tx_topup_refund": "Толтыруды картаға қайтару",
        "tx_topup_refund_back": "Картаға қайтару өтпеді — ақша балансқа түсті",
        "tx_escrow_cancel": "Кепіл: бас тарту, қайтару", "tx_withdraw": "Қаражат шығару",
        "tx_escrow_new": "Кепіл: мәміле құрылды", "tx_escrow_delivered": "Кепіл: тауар берілді",
        "tx_escrow_payout": "Кепіл: төлем", "tx_sale": "Сатылым", "tx_earn": "Табыс",
        "tx_ai_scan": "Kliko AI: терең талдау", "tx_ai_scan_refund": "Kliko AI: талдау үшін қайтару",
        "tx_buy_ai": "Kliko AI пакеті", "tx_admin_deduct": "Әкімші есептен шығарды", "tx_promote": "Хабарландыруды көтеру",
        "tx_promote_bulk": "Бірнеше хабарландыруды көтеру", "tx_promote_bulk_refund": "Жарнама үшін қайтару",
        "tx_jobs_top": "«Жұмыс» бөліміндегі ТОП", "tx_slots": "Слоттарды кеңейту", "tx_combo": "Жарнама пакеті",
        "tx_pro": "PRO жазылымы", "tx_buy_storefront": "Витринаны безендіру", "tx_escrow_advance": "Кепіл: қызмет үшін аванс",
        "tx_eds_fee": "eGov қолтаңбасымен шартқа қол қою", "tx_eds_fee_back": "Қол қою ақысын қайтару",
        "tx_eds_ship": "Мәміле бойынша Яндекс курьері", "tx_eds_ship_back": "Жеткізуді қайтару",
        "frz_title": "Қазір бұғатталған", "frz_sub": "Баланстан алынып, нәтижені күтуде. Осы жерден босатуға болады.",
        "frz_in_deal": "Кепіл-мәміледе", "frz_in_offer": "Ұсынысты қамтамасыз ету", "frz_open": "Мәміле",
        "frz_cancel_deal": "Ақшаны қайтару", "frz_unfund": "Ақшаны қайтару", "frz_dispute": "Дау",
        "frz_why_ship": "Тауар жіберілді — ақшаны бас тарту емес, дау қайтарады.",
        "frz_why_meet": "Кездесу коды көрсетілді — зат берілген болуы мүмкін.",
        "frz_why_stage": "Мәміле жабылды — ақша құлыпталмаған.", "frz_why_denied": "Тек мәміле тарапы бас тарта алады.",
        "frz_unfund_t": "Ұсынысты алып тастау керек пе?",
        "frz_unfund_s": "Ақша толық қайтады. Баға туралы келісім күшін жояды.",
        "frz_unfund_ok": "Алып тастап, қайтару", "frz_unfund_done": "Ұсыныс алынды, ақша балансқа қайтты",
        "po_ready": "{n} ₸ төлем дайын", "po_sub": "Банк бетінде картаны көрсетіңіз{d}.", "po_until": " {d} дейін",
        "po_go": "Картаны көрсету", "po_opening": "Ашылуда…", "po_unavail": "Сілтеме қолжетімсіз",
        "po_nonet": "Байланыс жоқ — қайталап көріңіз",
        "out_paid_t": "Ақша жіберілді", "out_paid_s": "Банк картаңызға аударымды жүргізуде.",
        "out_fail_t": "Шығару мүмкін болмады", "out_fail_s": "Сома балансқа қайтты — қайталап көріңіз.",
        "balance": "Баланс",
        "topup_title": "Әмиянды толтыру",
        "topup_sub": "Бірыңғай баланс: кепіл-мәміле арқылы **тауарлар мен қызметтерді сатып алу**, сондай-ақ жарнама, слоттар және PRO",
        "topup_pick": "Соманы таңдаңыз", "topup_custom_ph": "Өз сомаңыз", "topup_less": "1000-ға азайту",
        "topup_more": "1000-ға көбейту", "topup_limits": "Бір ретте 100 ₸-ден 1 000 000 ₸-ге дейінгі кез келген сома",
        "topup_choose_btn": "Соманы таңдаңыз", "topup_btn": "{n} ₸ толтыру", "topup_max": "Ең көбі 1 000 000 ₸",
        "topup_min": "Ең азы 100 ₸", "topup_processing": "Өңделуде…", "topup_going": "Төлемге өтудеміз…",
        "topup_consent": "Төлем түймесін баса отырып, сіз [Төлем және қайтару шарттарын]({u}) қабылдайсыз және төлем жүргізу үшін дербес деректерді, соның ішінде [«Freedom Pay» ЖШС](https://freedompay.kz) төлем ұйымының өңдеуіне келісесіз.",
        "topup_t1": "Комиссиясыз", "topup_t2": "Бірден түседі", "topup_t3": "Қорғалған",
        "topup_done": "Баланс {n} ₸-ге толтырылды", "topup_off": "Онлайн-төлем уақытша қолжетімсіз",
        "topup_again_q": "Әмиянды толтыру керек пе?", "gw_title": "Төлем",
        "sub_app": "Кепіл-мәміле арқылы тауарлар мен қызметтерге төлем",
        "topup_sub_app": "Кепіл-мәміле арқылы **тауарлар мен қызметтерді сатып алуға** арналған бірыңғай баланс",
        "tpm_ok_s_app": "Ақша балансында — мәмілелерді төлеуге болады.",
        "topup_paused_app": "Бұл мүмкіндік қосымшада қолжетімсіз.",
        "tpm_proc_t": "Төлемді тексерудеміз…", "tpm_proc_s": "Бір сәт — төлемді растап, әмиянға есептейміз.",
        "tpm_ok_t": "Әмиян толтырылды", "tpm_ok_s": "Ақша балансында — мәмілелерді, жарнаманы және PRO-ны төлеуге болады.",
        "tpm_ok_btn": "Тамаша", "tpm_pend_t": "Төлем қабылданды",
        "tpm_pend_s": "Төлем өтсе, баланс бірнеше минут ішінде жаңарады. Қаражат пайда болмаса, бетті жаңартыңыз немесе қолдауға жазыңыз.",
        "tpm_fail_t": "Төлем өтпеді",
        "tpm_fail_s": "Төлем аяқталмады немесе банк қабылдамады. Ақша алынған жоқ — қайталап көруге болады.",
        "verify_t": "Верификация қажет",
        "verify_s": "Қаражат шығару тек верификацияланған аккаунттарға қолжетімді — ақша платформа қорғауында болады, ал төлем міндетті түрде иесіне жетеді.\n\nБалансты верификациясыз да толтыруға болады.",
        "verify_go": "Верификациядан өту",
        "wd_title": "Қаражат шығару", "wd_step_amount": "Сома", "wd_step_card": "Карта және тексеру",
        "wd_sub": "Кепіл-мәмілелерден тапқан ақша **алаң комиссиясыз** шығарылады. Өткізілмеген қаражат (мәмілесіз толтыру) — {p}% комиссиямен.",
        "wd_available": "Шығаруға қолжетімді", "wd_amount_label": "Шығару сомасы", "wd_amount_ph": "Немесе соманы енгізіңіз",
        "wd_min": "Ең аз шығару сомасы — {n} ₸", "wd_min_tail": "{n} ₸ қалдық толығымен шығарылады",
        "wd_all": "барлығы", "wd_nothing": "Әзірге шығаратын ештеңе жоқ: қолжетімді {n} ₸",
        "wd_cap": "Бір операцияда — {n} ₸-ден аспайды. Қалғанын келесіде шығарасыз.",
        "wd_over_cap": "Операция шегінен көп — {n} ₸", "wd_over_avail": "Қолжетімдіден көп — {n} ₸",
        "wd_bank_fee": "Банк алымы", "wd_fee_row": "{p}% комиссия (өткізілмеген қаражат)",
        "wd_fee_pct": "{p}% комиссия", "wd_payout": "Есептеледі", "wd_sum_amt": "Шығару сомасы",
        "wd_free_ok": "Комиссиясыз — сатылымнан тапқан шегінде",
        "wd_free_split": "Комиссиясыз: {a} ₸ · комиссиямен: {b} ₸",
        "wd_next": "Әрі қарай", "wd_next_sum": "Әрі қарай · {n} ₸", "wd_edit_amount": "Өзгерту", "wd_sum_is": "Сома: {n}",
        "wd_method": "Шығару тәсілі", "wd_card": "Банк картасы", "wd_card_note": "Қазақстанның кез келген банкі",
        "wd_card_later": "Картаны банк бетінде көрсетесіз", "wd_check_t": "Деректерді тексеріңіз",
        "wd_chk_note": "Сома баланстан қазір алынады. Алатын картаны өтінімді растағанда сілтеме арқылы көрсетесіз.",
        "wd_confirm_btn": "Бәрі дұрыс, {n} ₸ шығару", "wd_submit": "Қаражат шығару", "wd_sending": "Жіберілуде…",
        "wd_auto_t": "Авто-шығару", "wd_auto_off": "Өшірулі — қолмен шығарасыз", "wd_auto_on": "Қосулы · картаға",
        "wd_auto_on_bank": "Қосулы · шотқа",
        "wd_auto_hint": "Қосылғанда сатылымнан тапқан ақша байланған тәсілге автоматты түрде шығарылады ({n} ₸ жеткенде). Жоғарыдан тәсілді таңдаңыз — ол байланады. Картаға деректеме керек емес: оны төлем расталғанда сілтеме арқылы көрсетесіз.",
        "wd_auto_need": "Алдымен жоғарыдан шығару тәсілін таңдаңыз", "wd_auto_done_on": "Авто-шығару қосылды",
        "wd_auto_done_off": "Авто-шығару өшірілді",
        "wd_term1_t": "Алдымен растау, содан кейін карта",
        "wd_term1_s": "Ақша баланстан бірден алынады; өтінім расталғанда картаны сілтеме арқылы көрсетесіз",
        "wd_term2_t": "Сатылымнан табыс — комиссиясыз",
        "wd_term2_s": "Жұмсалмаған толтыруды шығару — {p}% комиссиямен",
        "wd_term3_t": "Дайын болғанда хабарлаймыз", "wd_term3_s": "Ақша шотыңызға жіберілгенде келеді",
        "wd_need": "Соманы және шығару тәсілін көрсетіңіз", "wd_err": "Қате: {e}", "wd_err_retry": "қайталап көріңіз",
        "wd_res_t": "Өтінім қабылданды", "wd_res_s": "Сома баланстан алынып, төлемге сақталды.",
        "wd_res_amt": "Шығару сомасы", "wd_res_fee": "Комиссия", "wd_res_get": "Есептеледі",
        "wd_res_now": "Картаны көрсету қалды — нөмір банк бетінде енгізіледі және бізге түспейді.",
        "wd_res_when": "Растау — {t}.", "wd_term_card": "әдетте бір жұмыс күні ішінде", "wd_res_track": "Өтінім расталғанда әмиянда «Картаны көрсету» түймесі пайда болады — нөмір банк бетінде енгізіледі.",
        "wd_res_go": "Картаны көрсету", "wd_res_later": "Кейінірек — сілтеме әмиянда қалады", "wd_res_ok": "Түсінікті",
        "split_need": "«Дүкен» мәртебесі қажет", "split_t": "Дүкен болу",
        "split_s": "Есеп айырысу шотына шығару — дүкендерге арналған. Компания шотына төлемдерді қосу керек (деректемелерді тексеру, 1–3 күн). Рәсімдеуге өтесіз бе?",
        "split_go": "«Дүкен» мәртебесін рәсімдеу",
        "otp_wd_title": "Шығаруға арналған биометрия",
        "otp_wd_hint": "Шығаруды биометриямен (бет) және eGov арқылы растаңыз — ақша қорғалады және төлем дәл сізге жетеді.",
        "otp_passed": "Тексеру өтті. «Бәрі дұрыс, шығару» түймесін қайта басыңыз.",
        "lad_op": "Бір операцияға", "lad_month": "Айына", "lad_next": "«{l}» сатысына дейін: {m}", "lad_deals": "мәміле",
        "lad_turnover": "айналым", "lad_days": "тәулік", "lad_top": "Бұл ең жоғары саты.", "lad_penalty": "саты төмендетілді",
        "ps_balance": "ҰПАЙ БАЛАНСЫ", "ps_cashline": "Сіздің кэшбэгіңіз {c}% · 1 ұпай = 1 ₸ · мәміленің {m}%-на дейін ұпаймен төлеуге болады",
        "ps_next": "«{l}» деңгейіне дейін: тағы {n} ұпай", "ps_max": "Ең жоғары деңгейге жеттіңіз!",
        "ps_earn_t": "Ұпайды қалай алуға болады", "ps_buyer_b": "Кепіл арқылы сатып алу",
        "ps_buyer_s": " — соманың {n}% (деңгеймен өседі)", "ps_seller_b": "Кепіл арқылы сату",
        "ps_seller_s": " — соманың {n}%", "ps_spend_t": "Қалай жұмсауға болады",
        "ps_spend": "Келесі мәмілені төлегенде «Ұпайды қолдану» таңдаңыз — соманың {n}%-на дейін ұпаймен автоматты түрде өтеледі.",
        "ps_levels_t": "Қатысушы деңгейлері", "lvl_0": "Жаңадан келген", "lvl_100": "Жаңадан келген+",
        "lvl_500": "Белсенді", "lvl_1000": "Білгір", "lvl_5000": "Сарапшы", "ps_pts": "{n} ұпай",
        "ps_pts_tier": "{n} ұп. · {c}%", "ps_log_t": "Есептеу тарихы",
        "ps_log_none": "Әзірге ұпай жоқ — кепіл арқылы алғашқы мәмілені аяқтаңыз", "ps_deal": "→ мәміле",
        "a11y_hide": "Балансты және байланыстарды жасыру", "a11y_show": "Балансты және байланыстарды көрсету",
        "a11y_hidden": "Баланс жасырылған", "a11y_in": "Есептелді", "a11y_out": "Алынды",
        "a11y_bar": "Келесі деңгейге дейін", "a11y_reached": "жетті", "a11y_site": "сайт ашылады"
    ]

    // MARK: - English

    private static let en: [String: String] = [
        "title": "Wallet", "topup": "Top up", "withdraw": "Withdraw",
        "sub": "Pay for goods and services · promotion and slots", "out_can": "Withdrawable to card: {n} ₸",
        "held_line": "On hold {n} ₸ · released in {t}", "lock_line": "card top-up {n} ₸ — for Kliko services",
        "d_short": "d", "h_short": "h", "held": "On hold", "held_why": "Safety period", "held_left": "released in",
        "held_note": "The money is yours and isn't going anywhere — you can withdraw it when the period ends. It is shorter if the buyer has confirmed receipt.",
        "lock_t": "Card top-up",
        "lock_note": "While the guarantee deal is paused, money topped up from a card can only be spent on Kliko services — it can't be withdrawn to other details. We'll return the unused balance to the same card.",
        "lock_sup": "Contact support", "history": "Transaction history", "points": "Points",
        "site_note": "Top-ups, withdrawals and card payouts open in your account on the website.",
        "loading": "Loading…", "tx_none": "No transactions yet", "tx_generic": "Transaction", "tx_deal": "deal",
        "tx_receipt": "receipt", "rc_loading": "Loading receipt…", "no_title": "Untitled",
        "err_generic": "Error", "err_net": "Network error", "err_no_conn": "No connection", "retry": "Retry",
        "close": "Close", "cancel": "Cancel", "ok": "Got it", "later": "Later",
        "tx_topup": "Wallet top-up", "tx_admin_topup": "Top-up by administrator", "tx_top": "TOP promotion",
        "tx_discount": "Discount", "tx_escrow_hold": "Guarantee: money frozen", "tx_escrow_release": "Guarantee: payout for sale",
        "tx_escrow_refund": "Guarantee: refund to buyer", "tx_topup_refund": "Top-up refund to card",
        "tx_topup_refund_back": "Refund to card failed — money is on the balance",
        "tx_escrow_cancel": "Guarantee: cancelled, refund", "tx_withdraw": "Withdrawal",
        "tx_escrow_new": "Guarantee: deal created", "tx_escrow_delivered": "Guarantee: item handed over",
        "tx_escrow_payout": "Guarantee: payout", "tx_sale": "Sale", "tx_earn": "Earnings",
        "tx_ai_scan": "Kliko AI: deep analysis", "tx_ai_scan_refund": "Kliko AI: analysis refund",
        "tx_buy_ai": "Kliko AI package", "tx_admin_deduct": "Deducted by administrator", "tx_promote": "Listing bump",
        "tx_promote_bulk": "Bump of several listings", "tx_promote_bulk_refund": "Promotion refund",
        "tx_jobs_top": "TOP in «Jobs»", "tx_slots": "Slot expansion", "tx_combo": "Promotion package",
        "tx_pro": "PRO subscription", "tx_buy_storefront": "Storefront design", "tx_escrow_advance": "Guarantee: service advance",
        "tx_eds_fee": "Contract signing with eGov signature", "tx_eds_fee_back": "Signing fee refund",
        "tx_eds_ship": "Yandex courier for a deal", "tx_eds_ship_back": "Delivery refund",
        "frz_title": "Frozen now", "frz_sub": "Taken from the balance and waiting for the outcome. You can release them here.",
        "frz_in_deal": "In a guarantee deal", "frz_in_offer": "Offer deposit", "frz_open": "Deal",
        "frz_cancel_deal": "Get money back", "frz_unfund": "Get money back", "frz_dispute": "Dispute",
        "frz_why_ship": "The item has been shipped — a dispute returns the money, not a cancellation.",
        "frz_why_meet": "The meeting code was shown — the item may already have been handed over.",
        "frz_why_stage": "The deal is closed — the money isn't locked.", "frz_why_denied": "Only a party to the deal can cancel.",
        "frz_unfund_t": "Withdraw the offer?", "frz_unfund_s": "The money will be returned in full. The price agreement will end.",
        "frz_unfund_ok": "Withdraw and refund", "frz_unfund_done": "Offer withdrawn, money returned to the balance",
        "po_ready": "Payout of {n} ₸ is ready", "po_sub": "Enter your card on the bank page{d}.", "po_until": " by {d}",
        "po_go": "Enter card", "po_opening": "Opening…", "po_unavail": "Link unavailable",
        "po_nonet": "No connection — please try again",
        "out_paid_t": "Money sent", "out_paid_s": "The bank is transferring it to your card.",
        "out_fail_t": "Withdrawal failed", "out_fail_s": "The amount has returned to your balance — please try again.",
        "balance": "Balance",
        "topup_title": "Top up wallet",
        "topup_sub": "One balance: **buying goods and services** through a guarantee deal, plus promotion, slots and PRO",
        "topup_pick": "Choose an amount", "topup_custom_ph": "Custom amount", "topup_less": "1000 less",
        "topup_more": "1000 more", "topup_limits": "Any amount from 100 ₸ to 1,000,000 ₸ at a time",
        "topup_choose_btn": "Choose an amount", "topup_btn": "Top up {n} ₸", "topup_max": "Maximum 1,000,000 ₸",
        "topup_min": "Minimum 100 ₸", "topup_processing": "Processing…", "topup_going": "Going to payment…",
        "topup_consent": "By tapping the payment button, you accept the [Payment and refund terms]({u}) and agree to the processing of personal data to make the payment, including by the payment organization [Freedom Pay LLP](https://freedompay.kz).",
        "topup_t1": "No fee", "topup_t2": "Credited instantly", "topup_t3": "Protected",
        "topup_done": "Balance topped up by {n} ₸", "topup_off": "Online payment is temporarily unavailable",
        "topup_again_q": "Top up wallet?", "gw_title": "Payment",
        "sub_app": "Pay for goods and services through a guarantee deal",
        "topup_sub_app": "One balance for **buying goods and services** through a guarantee deal",
        "tpm_ok_s_app": "The money is on your balance — you can pay for deals.",
        "topup_paused_app": "This feature is not available in the app.",
        "tpm_proc_t": "Checking payment…", "tpm_proc_s": "One moment — confirming the payment and crediting your wallet.",
        "tpm_ok_t": "Wallet topped up", "tpm_ok_s": "The money is on your balance — you can pay for deals, promotion and PRO.",
        "tpm_ok_btn": "Great", "tpm_pend_t": "Payment received",
        "tpm_pend_s": "If the payment went through, your balance will update within a couple of minutes. Refresh the page or contact support if the money doesn't appear.",
        "tpm_fail_t": "Payment failed",
        "tpm_fail_s": "The payment wasn't completed or was declined by the bank. No money was charged — you can try again.",
        "verify_t": "Verification required",
        "verify_s": "Withdrawals are only available to verified accounts — this keeps the money protected by the platform and guarantees the payout goes to the owner.\n\nYou can top up without verification.",
        "verify_go": "Get verified",
        "wd_title": "Withdraw funds", "wd_step_amount": "Amount", "wd_step_card": "Card and check",
        "wd_sub": "Earnings from guarantee deals are withdrawn **with no platform fee**. Unspent funds (top-ups without deals) — with a {p}% fee.",
        "wd_available": "Available to withdraw", "wd_amount_label": "Withdrawal amount", "wd_amount_ph": "Or enter an amount",
        "wd_min": "Minimum withdrawal — {n} ₸", "wd_min_tail": "The remaining {n} ₸ is withdrawn in full",
        "wd_all": "all", "wd_nothing": "Nothing to withdraw yet: available {n} ₸",
        "wd_cap": "No more than {n} ₸ per transaction. Withdraw the rest next time.",
        "wd_over_cap": "Above the per-transaction limit — {n} ₸", "wd_over_avail": "More than available — {n} ₸",
        "wd_bank_fee": "Bank fee", "wd_fee_row": "{p}% fee (unspent funds)", "wd_fee_pct": "{p}% fee",
        "wd_payout": "You receive", "wd_sum_amt": "Withdrawal amount",
        "wd_free_ok": "No fee — within your sales earnings", "wd_free_split": "Fee-free: {a} ₸ · with fee: {b} ₸",
        "wd_next": "Next", "wd_next_sum": "Next · {n} ₸", "wd_edit_amount": "Change", "wd_sum_is": "Amount: {n}",
        "wd_method": "Withdrawal method", "wd_card": "Bank card", "wd_card_note": "Any bank in Kazakhstan",
        "wd_card_later": "You'll enter the card on the bank page", "wd_check_t": "Check the details",
        "wd_chk_note": "The amount will be taken from your balance now. You'll enter the receiving card via a link once we confirm the request.",
        "wd_confirm_btn": "All correct, withdraw {n} ₸", "wd_submit": "Withdraw funds", "wd_sending": "Sending…",
        "wd_auto_t": "Auto-withdrawal", "wd_auto_off": "Off — withdraw manually", "wd_auto_on": "On · to card",
        "wd_auto_on_bank": "On · to account",
        "wd_auto_hint": "When on, sales earnings will be withdrawn automatically to the linked method (once they reach {n} ₸). Choose a method above — it will become linked. A card needs no details: you'll enter it via a link once the payout is confirmed.",
        "wd_auto_need": "First choose a withdrawal method above", "wd_auto_done_on": "Auto-withdrawal is on",
        "wd_auto_done_off": "Auto-withdrawal is off",
        "wd_term1_t": "Confirmation first, then card",
        "wd_term1_s": "The money is taken from the balance right away; once the request is confirmed, you'll enter the card via a link",
        "wd_term2_t": "Sales earnings — no fee", "wd_term2_s": "Withdrawing unspent top-ups — with a {p}% fee",
        "wd_term3_t": "We'll let you know when it's ready", "wd_term3_s": "Arrives when the money is sent to your account",
        "wd_need": "Enter the amount and withdrawal method", "wd_err": "Error: {e}", "wd_err_retry": "please try again",
        "wd_res_t": "Request accepted", "wd_res_s": "The amount was taken from your balance and reserved for the payout.",
        "wd_res_amt": "Withdrawal amount", "wd_res_fee": "Fee", "wd_res_get": "You receive",
        "wd_res_now": "Only the card is left — the number is entered on the bank page and never reaches us.",
        "wd_res_when": "Confirmation — {t}.", "wd_term_card": "usually within a business day", "wd_res_track": "Once the request is confirmed, an «Enter card» button will appear in your wallet — the number is entered on the bank page.",
        "wd_res_go": "Enter card", "wd_res_later": "Later — the link will stay in your wallet", "wd_res_ok": "Got it",
        "split_need": "«Shop» status required", "split_t": "Become a shop",
        "split_s": "Withdrawal to a settlement account is for shops. You need to enable payouts to a company account (details check, 1–3 days). Go to setup?",
        "split_go": "Get «Shop» status",
        "otp_wd_title": "Biometrics for withdrawal",
        "otp_wd_hint": "Confirm the withdrawal with biometrics (face) and eGov — this keeps your money protected and the payout goes to you.",
        "otp_passed": "Check passed. Tap «All correct, withdraw» again.",
        "lad_op": "Per transaction", "lad_month": "Per month", "lad_next": "To the «{l}» tier: {m}", "lad_deals": "deals",
        "lad_turnover": "turnover", "lad_days": "days", "lad_top": "This is the top tier.", "lad_penalty": "tier lowered",
        "ps_balance": "POINTS BALANCE", "ps_cashline": "Your cashback {c}% · 1 point = 1 ₸ · up to {m}% of a deal can be paid with points",
        "ps_next": "To the «{l}» level: {n} more points", "ps_max": "Top level reached!",
        "ps_earn_t": "How to earn points", "ps_buyer_b": "Buying through the guarantee",
        "ps_buyer_s": " — {n}% of the amount (grows with level)", "ps_seller_b": "Selling through the guarantee",
        "ps_seller_s": " — {n}% of the amount", "ps_spend_t": "How to spend",
        "ps_spend": "When paying for your next deal, choose «Apply points» — up to {n}% of the amount is covered by points automatically.",
        "ps_levels_t": "Member levels", "lvl_0": "Newcomer", "lvl_100": "Newcomer+", "lvl_500": "Active",
        "lvl_1000": "Connoisseur", "lvl_5000": "Expert", "ps_pts": "{n} points", "ps_pts_tier": "{n} pts · {c}%",
        "ps_log_t": "Points history", "ps_log_none": "No points yet — complete your first deal through the guarantee",
        "ps_deal": "→ deal",
        "a11y_hide": "Hide balance and contacts", "a11y_show": "Show balance and contacts", "a11y_hidden": "Balance hidden",
        "a11y_in": "Credit", "a11y_out": "Debit", "a11y_bar": "Progress to the next level", "a11y_reached": "reached",
        "a11y_site": "opens the website"
    ]

    // MARK: - العربية

    private static let ar: [String: String] = [
        "title": "المحفظة", "topup": "شحن", "withdraw": "سحب",
        "sub": "دفع ثمن السلع والخدمات · الترويج والخانات", "out_can": "قابل للسحب إلى البطاقة: {n} ₸",
        "held_line": "محجوز {n} ₸ · يُحرَّر بعد {t}", "lock_line": "شحن من البطاقة {n} ₸ — لخدمات Kliko",
        "d_short": "ي", "h_short": "س", "held": "محجوز", "held_why": "فترة الأمان", "held_left": "يُحرَّر بعد",
        "held_note": "المال لك ولن يضيع — يمكنك سحبه عند انتهاء الفترة. وتكون أقصر إذا أكّد المشتري الاستلام.",
        "lock_t": "شحن من البطاقة",
        "lock_note": "ما دامت الصفقة المضمونة متوقفة، يُنفق المال المشحون من البطاقة على خدمات Kliko فقط — ولا يمكن سحبه إلى بيانات أخرى. سنعيد الرصيد غير المستخدم إلى البطاقة نفسها.",
        "lock_sup": "راسل الدعم", "history": "سجل العمليات", "points": "النقاط",
        "site_note": "الشحن والسحب والدفع إلى البطاقة تُفتح في حسابك على الموقع.",
        "loading": "جارٍ التحميل…", "tx_none": "لا توجد عمليات بعد", "tx_generic": "عملية", "tx_deal": "الصفقة",
        "tx_receipt": "الإيصال", "rc_loading": "جارٍ تحميل الإيصال…", "no_title": "بلا عنوان",
        "err_generic": "خطأ", "err_net": "خطأ في الشبكة", "err_no_conn": "لا يوجد اتصال", "retry": "إعادة المحاولة",
        "close": "إغلاق", "cancel": "إلغاء", "ok": "حسنًا", "later": "لاحقًا",
        "tx_topup": "شحن المحفظة", "tx_admin_topup": "شحن من المسؤول", "tx_top": "ترويج TOP",
        "tx_discount": "خصم", "tx_escrow_hold": "الضمان: تجميد المال", "tx_escrow_release": "الضمان: دفعة مقابل البيع",
        "tx_escrow_refund": "الضمان: استرداد للمشتري", "tx_topup_refund": "إعادة الشحن إلى البطاقة",
        "tx_topup_refund_back": "تعذّرت الإعادة إلى البطاقة — المال في الرصيد",
        "tx_escrow_cancel": "الضمان: إلغاء واسترداد", "tx_withdraw": "سحب الأموال",
        "tx_escrow_new": "الضمان: أُنشئت الصفقة", "tx_escrow_delivered": "الضمان: سُلّمت السلعة",
        "tx_escrow_payout": "الضمان: دفعة", "tx_sale": "بيع", "tx_earn": "أرباح",
        "tx_ai_scan": "Kliko AI: تحليل معمّق", "tx_ai_scan_refund": "Kliko AI: استرداد التحليل",
        "tx_buy_ai": "باقة Kliko AI", "tx_admin_deduct": "خصم من المسؤول", "tx_promote": "رفع الإعلان",
        "tx_promote_bulk": "رفع عدة إعلانات", "tx_promote_bulk_refund": "استرداد الترويج",
        "tx_jobs_top": "TOP في قسم «العمل»", "tx_slots": "توسيع الخانات", "tx_combo": "باقة ترويج",
        "tx_pro": "اشتراك PRO", "tx_buy_storefront": "تصميم الواجهة", "tx_escrow_advance": "الضمان: دفعة مقدمة للخدمة",
        "tx_eds_fee": "توقيع العقد بتوقيع eGov", "tx_eds_fee_back": "استرداد رسوم التوقيع",
        "tx_eds_ship": "مندوب ياندكس للصفقة", "tx_eds_ship_back": "استرداد التوصيل",
        "frz_title": "مجمّد الآن", "frz_sub": "خُصمت من الرصيد وتنتظر النتيجة. يمكن تحريرها من هنا.",
        "frz_in_deal": "في صفقة مضمونة", "frz_in_offer": "تأمين العرض", "frz_open": "الصفقة",
        "frz_cancel_deal": "استرداد المال", "frz_unfund": "استرداد المال", "frz_dispute": "نزاع",
        "frz_why_ship": "شُحنت السلعة — يعيد النزاعُ المال لا الإلغاء.",
        "frz_why_meet": "عُرض رمز اللقاء — ربما سُلّمت السلعة بالفعل.",
        "frz_why_stage": "الصفقة مغلقة — المال غير مقفل.", "frz_why_denied": "لا يلغي إلا طرف في الصفقة.",
        "frz_unfund_t": "سحب العرض؟", "frz_unfund_s": "سيُعاد المال كاملًا. وينتهي الاتفاق على السعر.",
        "frz_unfund_ok": "اسحب واسترد", "frz_unfund_done": "سُحب العرض وعاد المال إلى الرصيد",
        "po_ready": "دفعة {n} ₸ جاهزة", "po_sub": "أدخل البطاقة في صفحة البنك{d}.", "po_until": " قبل {d}",
        "po_go": "أدخل البطاقة", "po_opening": "جارٍ الفتح…", "po_unavail": "الرابط غير متاح",
        "po_nonet": "لا يوجد اتصال — حاول مرة أخرى",
        "out_paid_t": "أُرسل المال", "out_paid_s": "يُجري البنك التحويل إلى بطاقتك.",
        "out_fail_t": "تعذّر السحب", "out_fail_s": "عاد المبلغ إلى الرصيد — حاول مرة أخرى.",
        "balance": "الرصيد",
        "topup_title": "شحن المحفظة",
        "topup_sub": "رصيد موحّد: **شراء السلع والخدمات** عبر الصفقة المضمونة، وكذلك الترويج والخانات وPRO",
        "topup_pick": "اختر المبلغ", "topup_custom_ph": "مبلغ آخر", "topup_less": "أقل بـ 1000",
        "topup_more": "أكثر بـ 1000", "topup_limits": "أي مبلغ من 100 ₸ إلى 1 000 000 ₸ في المرة الواحدة",
        "topup_choose_btn": "اختر المبلغ", "topup_btn": "اشحن {n} ₸", "topup_max": "الحد الأقصى 1 000 000 ₸",
        "topup_min": "الحد الأدنى 100 ₸", "topup_processing": "جارٍ المعالجة…", "topup_going": "ننتقل إلى الدفع…",
        "topup_consent": "بالضغط على زر الدفع، تقبل [شروط الدفع والاسترداد]({u}) وتوافق على معالجة البيانات الشخصية لإجراء الدفع، بما في ذلك من قِبل مؤسسة الدفع [Freedom Pay](https://freedompay.kz).",
        "topup_t1": "بلا عمولة", "topup_t2": "إيداع فوري", "topup_t3": "محمي",
        "topup_done": "شُحن الرصيد بمبلغ {n} ₸", "topup_off": "الدفع الإلكتروني غير متاح مؤقتًا",
        "topup_again_q": "شحن المحفظة؟", "gw_title": "الدفع",
        "sub_app": "دفع ثمن السلع والخدمات عبر الصفقة المضمونة",
        "topup_sub_app": "رصيد موحّد **لشراء السلع والخدمات** عبر الصفقة المضمونة",
        "tpm_ok_s_app": "المال في الرصيد — يمكنك دفع الصفقات.",
        "topup_paused_app": "هذه الميزة غير متاحة في التطبيق.",
        "tpm_proc_t": "نتحقق من الدفع…", "tpm_proc_s": "لحظة — نؤكد الدفع ونودعه في المحفظة.",
        "tpm_ok_t": "شُحنت المحفظة", "tpm_ok_s": "المال في الرصيد — يمكنك دفع الصفقات والترويج وPRO.",
        "tpm_ok_btn": "رائع", "tpm_pend_t": "تم قبول الدفع",
        "tpm_pend_s": "إذا تم الدفع فسيتحدّث الرصيد خلال دقيقتين. حدّث الصفحة أو راسل الدعم إذا لم يظهر المال.",
        "tpm_fail_t": "لم يتم الدفع",
        "tpm_fail_s": "لم يكتمل الدفع أو رفضه البنك. لم يُخصم أي مال — يمكنك المحاولة مرة أخرى.",
        "verify_t": "يلزم التوثيق",
        "verify_s": "سحب الأموال متاح للحسابات الموثّقة فقط — فيبقى المال تحت حماية المنصة وتصل الدفعة إلى صاحبها حتمًا.\n\nيمكن شحن الرصيد دون توثيق.",
        "verify_go": "إجراء التوثيق",
        "wd_title": "سحب الأموال", "wd_step_amount": "المبلغ", "wd_step_card": "البطاقة والتحقق",
        "wd_sub": "تُسحب أرباح الصفقات المضمونة **دون عمولة المنصة**. الأموال غير المستخدمة (شحن دون صفقات) — بعمولة {p}%.",
        "wd_available": "متاح للسحب", "wd_amount_label": "مبلغ السحب", "wd_amount_ph": "أو أدخل المبلغ",
        "wd_min": "الحد الأدنى للسحب — {n} ₸", "wd_min_tail": "يُسحب الباقي {n} ₸ كاملًا",
        "wd_all": "الكل", "wd_nothing": "لا يوجد ما يُسحب بعد: المتاح {n} ₸",
        "wd_cap": "لا يزيد عن {n} ₸ في العملية الواحدة. اسحب الباقي في المرة التالية.",
        "wd_over_cap": "أكثر من حد العملية — {n} ₸", "wd_over_avail": "أكثر من المتاح — {n} ₸",
        "wd_bank_fee": "رسوم البنك", "wd_fee_row": "عمولة {p}% (أموال غير مستخدمة)", "wd_fee_pct": "عمولة {p}%",
        "wd_payout": "المبلغ المستلم", "wd_sum_amt": "مبلغ السحب",
        "wd_free_ok": "بلا عمولة — ضمن أرباح المبيعات", "wd_free_split": "بلا عمولة: {a} ₸ · بعمولة: {b} ₸",
        "wd_next": "التالي", "wd_next_sum": "التالي · {n} ₸", "wd_edit_amount": "تغيير", "wd_sum_is": "المبلغ: {n}",
        "wd_method": "طريقة السحب", "wd_card": "بطاقة بنكية", "wd_card_note": "أي بنك في كازاخستان",
        "wd_card_later": "ستُدخل البطاقة في صفحة البنك", "wd_check_t": "تحقق من البيانات",
        "wd_chk_note": "سيُخصم المبلغ من الرصيد الآن. ستُدخل بطاقة الاستلام عبر رابط عندما نؤكد الطلب.",
        "wd_confirm_btn": "كل شيء صحيح، اسحب {n} ₸", "wd_submit": "سحب الأموال", "wd_sending": "جارٍ الإرسال…",
        "wd_auto_t": "السحب التلقائي", "wd_auto_off": "متوقف — اسحب يدويًا", "wd_auto_on": "مفعّل · إلى البطاقة",
        "wd_auto_on_bank": "مفعّل · إلى الحساب",
        "wd_auto_hint": "عند التفعيل تُسحب أرباح المبيعات تلقائيًا إلى الطريقة المرتبطة (عند بلوغ {n} ₸). اختر طريقة أعلاه — وستصبح مرتبطة. البطاقة لا تحتاج إلى بيانات: ستُدخلها عبر رابط عند تأكيد الدفعة.",
        "wd_auto_need": "اختر طريقة السحب أعلاه أولًا", "wd_auto_done_on": "تم تفعيل السحب التلقائي",
        "wd_auto_done_off": "تم إيقاف السحب التلقائي",
        "wd_term1_t": "التأكيد أولًا ثم البطاقة",
        "wd_term1_s": "يُخصم المال من الرصيد فورًا؛ وعند تأكيد الطلب ستُدخل البطاقة عبر رابط",
        "wd_term2_t": "أرباح المبيعات — بلا عمولة", "wd_term2_s": "سحب الشحن غير المستخدم — بعمولة {p}%",
        "wd_term3_t": "سنخبرك عندما يصبح جاهزًا", "wd_term3_s": "يصل عندما يُرسل المال إلى حسابك",
        "wd_need": "حدّد المبلغ وطريقة السحب", "wd_err": "خطأ: {e}", "wd_err_retry": "حاول مرة أخرى",
        "wd_res_t": "تم قبول الطلب", "wd_res_s": "خُصم المبلغ من الرصيد وحُجز للدفعة.",
        "wd_res_amt": "مبلغ السحب", "wd_res_fee": "العمولة", "wd_res_get": "المبلغ المستلم",
        "wd_res_now": "بقي إدخال البطاقة — يُدخل الرقم في صفحة البنك ولا يصل إلينا.",
        "wd_res_when": "التأكيد — {t}.", "wd_term_card": "عادةً خلال يوم عمل", "wd_res_track": "عند تأكيد الطلب سيظهر في المحفظة زر «أدخل البطاقة» — يُدخل الرقم في صفحة البنك.",
        "wd_res_go": "أدخل البطاقة", "wd_res_later": "لاحقًا — سيبقى الرابط في المحفظة", "wd_res_ok": "حسنًا",
        "split_need": "تلزم صفة «متجر»", "split_t": "كن متجرًا",
        "split_s": "السحب إلى الحساب الجاري للمتاجر. يلزم تفعيل الدفعات إلى حساب الشركة (التحقق من البيانات، 1–3 أيام). الانتقال إلى الإعداد؟",
        "split_go": "الحصول على صفة «متجر»",
        "otp_wd_title": "القياس الحيوي للسحب",
        "otp_wd_hint": "أكّد السحب بالقياس الحيوي (الوجه) وeGov — فيبقى مالك محميًا وتصل الدفعة إليك أنت.",
        "otp_passed": "تم التحقق. اضغط «كل شيء صحيح، اسحب» مرة أخرى.",
        "lad_op": "للعملية", "lad_month": "للشهر", "lad_next": "حتى درجة «{l}»: {m}", "lad_deals": "صفقات",
        "lad_turnover": "من التداول", "lad_days": "أيام", "lad_top": "هذه أعلى درجة.", "lad_penalty": "خُفّضت الدرجة",
        "ps_balance": "رصيد النقاط", "ps_cashline": "استرجاعك النقدي {c}% · نقطة = 1 ₸ · يمكن دفع حتى {m}% من الصفقة بالنقاط",
        "ps_next": "حتى مستوى «{l}»: {n} نقطة أخرى", "ps_max": "بلغت أعلى مستوى!",
        "ps_earn_t": "كيف تحصل على النقاط", "ps_buyer_b": "الشراء عبر الضمان",
        "ps_buyer_s": " — {n}% من المبلغ (تزداد مع المستوى)", "ps_seller_b": "البيع عبر الضمان",
        "ps_seller_s": " — {n}% من المبلغ", "ps_spend_t": "كيف تنفقها",
        "ps_spend": "عند دفع الصفقة التالية اختر «تطبيق النقاط» — يُغطّى حتى {n}% من المبلغ بالنقاط تلقائيًا.",
        "ps_levels_t": "مستويات العضو", "lvl_0": "مبتدئ", "lvl_100": "مبتدئ+", "lvl_500": "نشِط",
        "lvl_1000": "خبير مطّلع", "lvl_5000": "خبير", "ps_pts": "{n} نقطة", "ps_pts_tier": "{n} ن · {c}%",
        "ps_log_t": "سجل النقاط", "ps_log_none": "لا نقاط بعد — أكمل صفقتك الأولى عبر الضمان",
        "ps_deal": "← الصفقة",
        "a11y_hide": "إخفاء الرصيد وجهات الاتصال", "a11y_show": "إظهار الرصيد وجهات الاتصال", "a11y_hidden": "الرصيد مخفي",
        "a11y_in": "إيداع", "a11y_out": "خصم", "a11y_bar": "التقدم حتى المستوى التالي", "a11y_reached": "تم بلوغه",
        "a11y_site": "يفتح الموقع"
    ]
}
