import Foundation

/**
 Тексты «Свой ИИ» (ответ ultra-site 08.10.2026: подписи сайта — lang/<язык>.php, ключи oai_* и own_ai_*). Новой копии lang
 у приложения нет, поэтому фразы написаны по смыслу сайта, коротко; ключи — oai_*. Языки: ru, kk, en, ar; прочие — русский.
 Бренды поставщиков (OpenAI, Anthropic, Google — Gemini, OpenRouter) приходят с сервера и не переводятся.
 Ни цен сайта, ни слов об оплате на сайте и пробном периоде здесь нет (покупка в приложении — только App Store).
 */
enum СвойИИText {
    static func т(_ ключ: String) -> String {
        let язык = String((Locale.preferredLanguages.first ?? "ru").prefix(2))
        let словарь: [String: String]
        switch язык {
        case "kk": словарь = kk
        case "en": словарь = en
        case "ar": словарь = ar
        default: словарь = ru
        }
        return словарь[ключ] ?? ru[ключ] ?? ключ
    }

    private static let ru: [String: String] = [
        "oai_title": "Свой ИИ",
        "oai_on_short": "вкл",
        "oai_off_short": "выкл",
        "oai_link": "Свой ИИ — подключить свой ключ",
        "oai_what": "Подключите ключ своего поставщика ИИ — и функции Kliko AI в кабинете пойдут через ваш ИИ, без квоты Kliko AI.",
        "oai_list_t": "Через ваш ИИ пойдут:",
        "oai_f1": "Распознавание фото при подаче и оценка цены по фото",
        "oai_f2": "Подсказки ответов в чатах",
        "oai_f3": "Сборка объявления услуги и оформление текста",
        "oai_f4": "Поиск по фото и проверка кадров при съёмке",
        "oai_f5": "Импорт товаров из таблиц и фото",
        "oai_f6": "Реквизиты компании с фото и текст КП",
        "oai_f7": "Резюме, перевод и консультант",
        "oai_keep": "Ассистент в чате по объявлению и проверка объявлений всегда работают на Kliko AI.",
        "oai_safe": "Ключ хранится на сервере Kliko в зашифрованном виде и в приложении не сохраняется. Ограничения частоты запросов остаются.",
        "oai_prem_t": "Premium «Свой ИИ»",
        "oai_prem_need": "Свой ИИ работает только с действующим Premium.",
        "oai_prem_until": "Действует до %@",
        "oai_prem_left": "Осталось %d дн.",
        "oai_prem_trial": "Пробный период",
        "oai_prem_ended": "Premium закончился — свой ИИ сейчас не используется.",
        "oai_prov_t": "Поставщик",
        "oai_prov_auto": "Определить автоматически",
        "oai_prov_gemini": "Ключ Google Gemini автоматически не определяется — выберите «Google — Gemini» явно.",
        "oai_key_t": "Ключ API",
        "oai_key_ph": "Вставьте ключ",
        "oai_paste": "Вставить",
        "oai_connect": "Подключить",
        "oai_or": "Войти через OpenRouter",
        "oai_or_note": "Откроется OpenRouter. После входа закройте окно — проверим подключение.",
        "oai_conn_t": "Подключение",
        "oai_key_mask": "Ключ",
        "oai_via_or": "через OpenRouter",
        "oai_model_t": "Модель",
        "oai_model_pick": "Выбрать модель",
        "oai_model_need": "Выберите модель — без неё свой ИИ не заработает.",
        "oai_model_saved": "Модель сохранена",
        "oai_test": "Проверить подключение",
        "oai_test_ok": "Подключение работает",
        "oai_use": "Использовать свой ИИ",
        "oai_use_s": "Выключено — функции идут через Kliko AI, ключ остаётся подключённым.",
        "oai_off": "Отключить",
        "oai_off_q": "Отключить свой ИИ?",
        "oai_off_s": "Ключ будет удалён с сервера Kliko. Функции снова пойдут через Kliko AI.",
        "oai_off_done": "Свой ИИ отключён, ключ удалён",
        "oai_connected": "Свой ИИ подключён",
        "oai_use_on": "Свой ИИ включён",
        "oai_use_off": "Свой ИИ выключен — работает Kliko AI",
        "oai_err_t": "Свой ИИ не сработал",
        "oai_fail_t": "Свой ИИ не ответил",
        "oai_settings": "Настройки своего ИИ",
        "oai_disable": "Выключить свой ИИ",
        "oai_later": "Позже",
        "oai_close": "Закрыть",
        "oai_cancel": "Отмена",
        "oai_via": "через ваш ИИ",
        "oai_loading": "Загрузка…",
        "oai_load_fail": "Не удалось загрузить. Проверьте соединение.",
        "oai_retry": "Повторить",
        "oai_unavail": "Раздел сейчас недоступен.",
        "oai_need_login": "Войдите в кабинет, чтобы подключить свой ИИ.",
        "oai_no_conn": "Нет соединения. Попробуйте ещё раз.",
        "oai_fail": "Не удалось — попробуйте ещё раз.",
    ]

    private static let kk: [String: String] = [
        "oai_title": "Өз ЖИ",
        "oai_on_short": "қосулы",
        "oai_off_short": "өшірулі",
        "oai_link": "Өз ЖИ — өз кілтіңізді қосу",
        "oai_what": "Өз ЖИ жеткізушіңіздің кілтін қосыңыз — кабинеттегі Kliko AI функциялары Kliko AI квотасынсыз сіздің ЖИ арқылы жүреді.",
        "oai_list_t": "Сіздің ЖИ арқылы жүретіндер:",
        "oai_f1": "Хабарландыру бергенде фотоны тану және фото бойынша бағалау",
        "oai_f2": "Чаттардағы жауап ұсыныстары",
        "oai_f3": "Қызмет хабарландыруын құрастыру және мәтінді безендіру",
        "oai_f4": "Фото бойынша іздеу және түсіру кезінде кадрды тексеру",
        "oai_f5": "Кестелер мен фотолардан тауар импорты",
        "oai_f6": "Фотодан компания деректемелері және КҰ мәтіні",
        "oai_f7": "Түйіндеме, аударма және кеңесші",
        "oai_keep": "Хабарландыру чатындағы ассистент пен хабарландыруларды тексеру әрқашан Kliko AI-да жұмыс істейді.",
        "oai_safe": "Кілт Kliko серверінде шифрланып сақталады, қосымшада сақталмайды. Сұраныс жиілігінің шектеулері қалады.",
        "oai_prem_t": "Premium «Өз ЖИ»",
        "oai_prem_need": "Өз ЖИ тек әрекеттегі Premium-мен жұмыс істейді.",
        "oai_prem_until": "%@ дейін әрекет етеді",
        "oai_prem_left": "%d күн қалды",
        "oai_prem_trial": "Сынақ кезеңі",
        "oai_prem_ended": "Premium аяқталды — өз ЖИ қазір қолданылмайды.",
        "oai_prov_t": "Жеткізуші",
        "oai_prov_auto": "Автоматты анықтау",
        "oai_prov_gemini": "Google Gemini кілті автоматты анықталмайды — «Google — Gemini» таңдаңыз.",
        "oai_key_t": "API кілті",
        "oai_key_ph": "Кілтті қойыңыз",
        "oai_paste": "Қою",
        "oai_connect": "Қосу",
        "oai_or": "OpenRouter арқылы кіру",
        "oai_or_note": "OpenRouter ашылады. Кіргеннен кейін терезені жабыңыз — қосылымды тексереміз.",
        "oai_conn_t": "Қосылым",
        "oai_key_mask": "Кілт",
        "oai_via_or": "OpenRouter арқылы",
        "oai_model_t": "Модель",
        "oai_model_pick": "Модельді таңдау",
        "oai_model_need": "Модельді таңдаңыз — онсыз өз ЖИ жұмыс істемейді.",
        "oai_model_saved": "Модель сақталды",
        "oai_test": "Қосылымды тексеру",
        "oai_test_ok": "Қосылым жұмыс істеп тұр",
        "oai_use": "Өз ЖИ-ді қолдану",
        "oai_use_s": "Өшірулі — функциялар Kliko AI арқылы жүреді, кілт қосулы қалады.",
        "oai_off": "Ажырату",
        "oai_off_q": "Өз ЖИ-ді ажырату керек пе?",
        "oai_off_s": "Кілт Kliko серверінен жойылады. Функциялар қайтадан Kliko AI арқылы жүреді.",
        "oai_off_done": "Өз ЖИ ажыратылды, кілт жойылды",
        "oai_connected": "Өз ЖИ қосылды",
        "oai_use_on": "Өз ЖИ қосулы",
        "oai_use_off": "Өз ЖИ өшірілді — Kliko AI жұмыс істейді",
        "oai_err_t": "Өз ЖИ істемеді",
        "oai_fail_t": "Өз ЖИ жауап бермеді",
        "oai_settings": "Өз ЖИ баптаулары",
        "oai_disable": "Өз ЖИ-ді өшіру",
        "oai_later": "Кейінірек",
        "oai_close": "Жабу",
        "oai_cancel": "Болдырмау",
        "oai_via": "сіздің ЖИ арқылы",
        "oai_loading": "Жүктелуде…",
        "oai_load_fail": "Жүктеу мүмкін болмады. Байланысты тексеріңіз.",
        "oai_retry": "Қайталау",
        "oai_unavail": "Бөлім қазір қолжетімсіз.",
        "oai_need_login": "Өз ЖИ-ді қосу үшін кабинетке кіріңіз.",
        "oai_no_conn": "Байланыс жоқ. Қайталап көріңіз.",
        "oai_fail": "Мүмкін болмады — қайталап көріңіз.",
    ]

    private static let en: [String: String] = [
        "oai_title": "Own AI",
        "oai_on_short": "on",
        "oai_off_short": "off",
        "oai_link": "Own AI — connect your own key",
        "oai_what": "Connect a key from your AI provider — Kliko AI features in your account will run on your AI, without the Kliko AI quota.",
        "oai_list_t": "Your AI will handle:",
        "oai_f1": "Photo recognition when posting and price estimates from photos",
        "oai_f2": "Reply suggestions in chats",
        "oai_f3": "Building service listings and polishing text",
        "oai_f4": "Photo search and shot checks while shooting",
        "oai_f5": "Importing products from tables and photos",
        "oai_f6": "Company details from a photo and quote text",
        "oai_f7": "Résumé, translation and the consultant",
        "oai_keep": "The assistant in listing chats and listing checks always run on Kliko AI.",
        "oai_safe": "The key is stored encrypted on the Kliko server and is never saved in the app. Request rate limits still apply.",
        "oai_prem_t": "Own AI Premium",
        "oai_prem_need": "Own AI works only with an active Premium.",
        "oai_prem_until": "Active until %@",
        "oai_prem_left": "%d days left",
        "oai_prem_trial": "Trial period",
        "oai_prem_ended": "Premium has ended — your own AI is not used right now.",
        "oai_prov_t": "Provider",
        "oai_prov_auto": "Detect automatically",
        "oai_prov_gemini": "Google Gemini keys aren't detected automatically — choose «Google — Gemini».",
        "oai_key_t": "API key",
        "oai_key_ph": "Paste the key",
        "oai_paste": "Paste",
        "oai_connect": "Connect",
        "oai_or": "Sign in with OpenRouter",
        "oai_or_note": "OpenRouter will open. After signing in, close the window — we'll check the connection.",
        "oai_conn_t": "Connection",
        "oai_key_mask": "Key",
        "oai_via_or": "via OpenRouter",
        "oai_model_t": "Model",
        "oai_model_pick": "Choose model",
        "oai_model_need": "Choose a model — your own AI won't work without it.",
        "oai_model_saved": "Model saved",
        "oai_test": "Test connection",
        "oai_test_ok": "Connection works",
        "oai_use": "Use own AI",
        "oai_use_s": "Off — features run on Kliko AI, the key stays connected.",
        "oai_off": "Disconnect",
        "oai_off_q": "Disconnect own AI?",
        "oai_off_s": "The key will be deleted from the Kliko server. Features will run on Kliko AI again.",
        "oai_off_done": "Own AI disconnected, key deleted",
        "oai_connected": "Own AI connected",
        "oai_use_on": "Own AI is on",
        "oai_use_off": "Own AI is off — Kliko AI is working",
        "oai_err_t": "Own AI failed",
        "oai_fail_t": "Your AI didn't respond",
        "oai_settings": "Own AI settings",
        "oai_disable": "Turn off own AI",
        "oai_later": "Later",
        "oai_close": "Close",
        "oai_cancel": "Cancel",
        "oai_via": "via your AI",
        "oai_loading": "Loading…",
        "oai_load_fail": "Couldn't load. Check your connection.",
        "oai_retry": "Retry",
        "oai_unavail": "This section is unavailable right now.",
        "oai_need_login": "Sign in to your account to connect your own AI.",
        "oai_no_conn": "No connection. Please try again.",
        "oai_fail": "Something went wrong — please try again.",
    ]

    private static let ar: [String: String] = [
        "oai_title": "ذكاؤك الاصطناعي",
        "oai_on_short": "مفعّل",
        "oai_off_short": "متوقف",
        "oai_link": "ذكاؤك الاصطناعي — اربط مفتاحك",
        "oai_what": "اربط مفتاح مزوّد الذكاء الاصطناعي الخاص بك — ستعمل ميزات Kliko AI في حسابك عبر ذكائك الاصطناعي دون حصة Kliko AI.",
        "oai_list_t": "سيتولى ذكاؤك الاصطناعي:",
        "oai_f1": "التعرّف على الصور عند النشر وتقدير السعر من الصور",
        "oai_f2": "اقتراحات الردود في المحادثات",
        "oai_f3": "إنشاء إعلان الخدمة وتنسيق النص",
        "oai_f4": "البحث بالصورة وفحص اللقطات أثناء التصوير",
        "oai_f5": "استيراد المنتجات من الجداول والصور",
        "oai_f6": "بيانات الشركة من صورة ونص العرض التجاري",
        "oai_f7": "السيرة الذاتية والترجمة والمستشار",
        "oai_keep": "المساعد في محادثة الإعلان وفحص الإعلانات يعملان دائمًا على Kliko AI.",
        "oai_safe": "يُحفظ المفتاح مشفّرًا على خادم Kliko ولا يُحفظ في التطبيق. تبقى قيود عدد الطلبات.",
        "oai_prem_t": "Premium «ذكاؤك الاصطناعي»",
        "oai_prem_need": "يعمل ذكاؤك الاصطناعي فقط مع اشتراك Premium ساري.",
        "oai_prem_until": "ساري حتى %@",
        "oai_prem_left": "متبقٍ %d يوم",
        "oai_prem_trial": "فترة تجريبية",
        "oai_prem_ended": "انتهى Premium — ذكاؤك الاصطناعي غير مستخدم الآن.",
        "oai_prov_t": "المزوّد",
        "oai_prov_auto": "تحديد تلقائي",
        "oai_prov_gemini": "لا يُحدَّد مفتاح Google Gemini تلقائيًا — اختر «Google — Gemini».",
        "oai_key_t": "مفتاح API",
        "oai_key_ph": "الصق المفتاح",
        "oai_paste": "لصق",
        "oai_connect": "ربط",
        "oai_or": "الدخول عبر OpenRouter",
        "oai_or_note": "سيُفتح OpenRouter. بعد الدخول أغلق النافذة — وسنتحقق من الاتصال.",
        "oai_conn_t": "الاتصال",
        "oai_key_mask": "المفتاح",
        "oai_via_or": "عبر OpenRouter",
        "oai_model_t": "النموذج",
        "oai_model_pick": "اختيار النموذج",
        "oai_model_need": "اختر نموذجًا — لن يعمل ذكاؤك الاصطناعي بدونه.",
        "oai_model_saved": "تم حفظ النموذج",
        "oai_test": "اختبار الاتصال",
        "oai_test_ok": "الاتصال يعمل",
        "oai_use": "استخدام ذكائك الاصطناعي",
        "oai_use_s": "متوقف — تعمل الميزات على Kliko AI ويبقى المفتاح مربوطًا.",
        "oai_off": "فصل",
        "oai_off_q": "فصل ذكائك الاصطناعي؟",
        "oai_off_s": "سيُحذف المفتاح من خادم Kliko. ستعمل الميزات مجددًا على Kliko AI.",
        "oai_off_done": "تم فصل ذكائك الاصطناعي وحذف المفتاح",
        "oai_connected": "تم ربط ذكائك الاصطناعي",
        "oai_use_on": "ذكاؤك الاصطناعي مفعّل",
        "oai_use_off": "ذكاؤك الاصطناعي متوقف — يعمل Kliko AI",
        "oai_err_t": "تعذّر عمل ذكائك الاصطناعي",
        "oai_fail_t": "لم يستجب ذكاؤك الاصطناعي",
        "oai_settings": "إعدادات ذكائك الاصطناعي",
        "oai_disable": "إيقاف ذكائك الاصطناعي",
        "oai_later": "لاحقًا",
        "oai_close": "إغلاق",
        "oai_cancel": "إلغاء",
        "oai_via": "عبر ذكائك الاصطناعي",
        "oai_loading": "جارٍ التحميل…",
        "oai_load_fail": "تعذّر التحميل. تحقّق من الاتصال.",
        "oai_retry": "إعادة المحاولة",
        "oai_unavail": "هذا القسم غير متاح الآن.",
        "oai_need_login": "سجّل الدخول إلى حسابك لربط ذكائك الاصطناعي.",
        "oai_no_conn": "لا يوجد اتصال. حاول مرة أخرى.",
        "oai_fail": "تعذّر ذلك — حاول مرة أخرى.",
    ]
}
